import {comfortRadius} from './core/autonomy-query';
import {TENDENCIES} from './core/autonomy';
import {drawPrice,queryDraw} from './core/cards';
import {queryClone} from './core/clones';
import {PROFESSION_NAMES,professionOf} from './core/skill-catalog';
import {PERSONAL} from './core/personal';
import type {GameState,Unit,Pos} from './core/types';
import {skillButton as skillHTML,updateSkillButton} from './skill-ui';
import {skillInfo} from './core/skill-catalog';
import {currentSkill} from './core/skills';
import {COMBAT_CONFIG} from './core/combat-config';
import {CardMotion} from './card-motion';
import {queryExplorationExit} from './core/exploration';
import {positionVisible} from './core/visibility';
import {waveProgress} from './core/waves';
export type UIState={initialSetup:boolean;selectedId:string|null;paused:boolean;speed:number;slow:boolean;stage:string;backpack:boolean;debug:boolean;cardId:string|null;item:string|null;notice:string;fps:number;assets:string};
const lifeNames:Record<string,string>={active:'在场',reserve:'待部署',withdrawn:'再部署',downed:'濒死',rescued:'已获救',dead:'死亡',respawning:'重生中',departed:'已离场'};
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export class HUD{
 readonly cardMotion=new CardMotion();
 root:HTMLElement; private phaseKey='';private cardKey='';private selectedKey='';private detailUnit='';
 constructor(host:HTMLElement){
  host.insertAdjacentHTML('beforeend',`<div id="hud">
   <header class="topbar"><div class="brand"><span class="brand-mark">♜</span><div><strong>影 庭</strong><small>灰钟街区 · 战斗原型</small></div></div><div class="mission"><small id="battle-status">准备行动</small><b id="wave">—</b><small id="wave-stage"></small></div><div class="crystal"><small>水晶完整度</small><b id="crystal-hp">12 / 12</b><div class="meter"><i id="crystal-bar"></i></div></div><div class="top-controls"><span id="clock">00:00</span><button data-action="sound" id="sound-btn">音效：开</button><button data-action="speed" id="speed-btn">1×</button><button data-action="pause" id="pause-btn">暂停</button><button data-action="help" title="操作说明" aria-label="操作说明">?</button></div></header>
   <aside class="location"><small>EXPEDITION / 01</small><h1 id="location-name">灰钟街区</h1><p id="mission-text">守住水晶，保留每一位同行者。</p><span class="location-rule"></span></aside>
   <aside id="batch-forecast" aria-label="敌人批次预告" hidden></aside><div id="time-mode" class="time-mode"></div><div id="notice" class="notice" role="status"></div>
   <aside id="unit-detail" class="unit-detail" hidden></aside>
   <section id="personal-controls"><span id="control-status"></span><div class="personal-actions"><button data-action="blink" id="blink-button"><span>瞬影 <kbd>Shift</kbd></span><b id="blink-stock">10 / 10</b><span id="blink-ticks"></span><small id="blink-progress"></small></button><button data-action="collect">影庭收纳 <kbd>Q</kbd><small>指定本体 · 濒死救援</small></button><button data-party="recall">全队召回 <kbd>H</kbd><small>健康本体进入影庭</small></button><button data-party="regroup">全队集结 <kbd>B</kbd><small>健康本体靠近猎人</small></button></div></section><svg id="recall-range" aria-hidden="true"><path/></svg><div id="recall-labels"></div><div id="world-skill"></div><div id="dash-directions" hidden></div>
   <footer class="bottom-dock"><section class="cards-section"><div class="section-label"><span>战术手牌 <small id="card-target"></small></span><span><b id="fragments">0</b> 生命力 <button data-action="draw" id="draw-btn" class="draw-button" title="消耗随身生命力，追加一张背包牌">抽一张 · 10生命力</button><small id="hand-count"></small><button id="sell-zone" type="button" title="拖入手牌预览，松手变卖">变卖 · 拖入手牌</button></span></div><div id="cards" class="cards"></div></section><section class="roster-section"><div class="section-label"><span>同行者 <small>选人 1–4</small></span><button data-action="build" class="text-btn">职业与构筑</button><button data-action="backpack" class="text-btn">行囊 <span id="inventory-count"></span></button></div><div id="roster" class="roster"></div></section></footer>
   <div class="bottom-line"><span id="hint">点击选择 · 拖动快捷移动 · 右键取消</span><span id="carried-gold"></span><button data-action="abandon-battle">放弃本场</button><button data-action="abandon">放弃副本</button><button data-action="debug">验证面板</button></div>
   <aside id="backpack" class="backpack" hidden></aside><aside id="debug-panel" class="debug-panel" hidden></aside>
   <aside id="exploration-status" hidden><small id="exploration-mode"></small><b id="exploration-goal"></b><p id="exploration-events"></p><button id="exploration-exit" data-action="exit-exploration">离开庭院</button><small id="exploration-exit-reason"></small></aside><div id="exploration-exit-confirm" class="dialog-shade" hidden><section class="dialog"><h2>确认放弃濒死同行者</h2><p>他们无法随队离开。逐个确认后才会按各自身份处理死亡；取消不会造成死亡。</p><div id="exploration-abandon-list"></div><button data-action="confirm-exploration-exit" class="primary">确认放弃并离开</button><button data-action="cancel-exploration-exit">取消 · 返回庭院</button></section></div><div id="phase-panel"></div>
   <div id="help" class="dialog-shade" hidden><section class="dialog help-dialog"><small>FIELD MANUAL</small><h2>战场操作</h2><p>点击角色，再点地格：直接移动，无需选择方向。<br>按住战场角色拖到地格，松手：快捷移动。<br>右键取消当前操作；空格暂停；左 Alt 切换 1× / 2×；1–4 选人；WASD 移动；E 当前技能；Shift 猎人瞬影；Q 影庭回收。<br>观察角色、瞄准卡牌或打开行囊时，战斗统一降至 0.1 倍速；结束后恢复之前设置的速度。</p><p>角色栏选择未部署角色，始动结束后点地格部署。<br>点击头像选择本体；头像下方召影按钮：点击后选择落点，或拖到落点；消耗20生命力。<br>疾行卡先选角色，再选择允许的方向。<br>卡牌不限距离；行囊道具只能作用于猎人周围。<br>濒死角色的救援按钮会让猎人自动前往。<br>失败保留损耗；重新进入节点时水晶满血。</p><button data-action="help" class="primary">返回战场</button></section></div>
   <div id="record-dialog" class="dialog-shade" hidden><section class="dialog"><h2>本场操作记录</h2><textarea readonly style="width:100%;height:260px;background:#101719;color:#d8d4c7"></textarea><button data-action="close-record" class="primary">返回战场</button></section></div><div id="error" class="error-banner" hidden></div>
  </div>`);
  this.root=host.querySelector('#hud')!;
  this.el('speed-btn').title='切换默认速度 · 左 Alt';
 }
 private el(id:string){return this.root.querySelector<HTMLElement>('#'+id)!;}
 private text(id:string,text:string){const el=this.el(id);if(el.textContent!==text)el.textContent=text;}
 render(s:GameState,v:UIState){
  const exploring=!!s.exploration&&s.phase==='battle';
  const progress=waveProgress(s),kind=s.node===3?'长塔防':'短塔防';
  const stages={waiting:'等待首批',spawning:'批次抵达',clearing:'清理在场敌人',intermission:'波间整备',complete:'全部波次完成'};
  this.text('battle-status',s.phase==='battle'?`${kind} · ${stages[progress.phase]}`:s.phase==='briefing'?kind+' · 行动准备':s.phase==='result'?'战斗结束':'远征地图');
  this.text('wave',`波次 ${progress.current} / ${progress.total} · 击破 ${s.kills}/${s.totalEnemies}`);
  this.text('wave-stage',progress.phase==='intermission'?`下一波 ${progress.intermission.toFixed(1)}s · 不重置角色状态`:`待出 ${progress.pending} 批 · 在场 ${progress.live}`);
  const forecast=this.el('batch-forecast');forecast.hidden=!progress.previews.length||v.paused&&s.phase!=='battle';
  const forecastKey=progress.previews.map(p=>p.id).join('|');
  if(forecast.dataset.batches!==forecastKey){
   forecast.dataset.batches=forecastKey;
   forecast.innerHTML=progress.previews.map(p=>`<span data-batch="${esc(p.id)}" class="${p.route[0].y<s.height/2?'north':'south'}"><b>第${p.waveNumber}波 · 第${s.waves.find(w=>w.id===p.waveId)!.batches.findIndex(b=>b.id===p.batchId)+1}批</b> ${p.route[0].y<s.height/2?'北路':'南路'} · ${p.count}名 <strong></strong></span>`).join('');
  }
  progress.previews.forEach((p,i)=>{const clock=forecast.children[i]?.querySelector('strong'),text=`${Math.max(0,p.startAt-s.time).toFixed(1)}s`;if(clock&&clock.textContent!==text)clock.textContent=text;});
  this.root.querySelector<HTMLButtonElement>('[data-action="abandon-battle"]')!.hidden=!s.economy.active||s.ruleset==='exploration'||!['briefing','battle'].includes(s.phase);
  this.text('crystal-hp',`${Math.ceil(s.crystalHp)} / ${s.crystalMax}`);this.el('crystal-bar').style.width=`${Math.max(0,s.crystalHp/s.crystalMax)*100}%`;
  this.root.querySelector<HTMLElement>('.crystal')!.hidden=exploring;
  this.el('exploration-status').hidden=!exploring;
  if(exploring){const run=s.exploration!,down=s.units.filter(u=>u.team==='ally'&&!u.cloneOf&&u.life==='downed').map(u=>u.id),check=queryExplorationExit(s,down);
   this.text('battle-status',s.context==='explorationBattle'?'探索 · 交战':'探索 · 非战斗');this.text('wave','雾钟庭院');this.text('wave-stage','WASD 推进视野 · H 召回 · B 集结');forecast.hidden=true;
   this.text('exploration-mode',s.context==='explorationBattle'?'交战中 · 无法离开':'非战斗 · 巡行速度 +25%');
   this.text('exploration-goal',run.memory.objective?'静钟已激活'+(run.memory.cleared?' · 奖励已领取':' · 离开后领取奖励'):'寻找并激活庭院静钟');
   const events=this.el('exploration-events'),key=run.definition.points.filter(p=>positionVisible(s,p.pos)).map(p=>p.id+run.memory.mechanisms.includes(p.id)).join('|');
   if(events.dataset.key!==key){events.dataset.key=key;events.innerHTML=run.definition.points.filter(p=>positionVisible(s,p.pos)).map(p=>'<button data-exploration-point="'+p.id+'" '+(run.memory.mechanisms.includes(p.id)?'disabled':'')+'>'+ (p.kind==='resource'?'搜寻生命力':'激活静钟')+(run.memory.mechanisms.includes(p.id)?' · 已完成':' · 猎人需靠近')+'</button>').join('');}
   (this.el('exploration-exit') as HTMLButtonElement).disabled=!check.ok;this.text('exploration-exit-reason',check.reason||(down.length?'离开前需逐个确认濒死同行者':'猎人与队伍已在出口范围'));
  }
  this.text('clock',`${String(Math.floor(s.time/60)).padStart(2,'0')}:${String(Math.floor(s.time%60)).padStart(2,'0')}`);
  this.text('pause-btn',v.paused?'继续':'暂停');this.text('speed-btn',`${v.speed}×`);
  this.text('time-mode',v.paused?'战术暂停':v.slow?'战术观察 · 0.1×':'');
  this.text('notice',v.notice||s.notice||'');
  const workbench=s.mode==='workbench'&&s.node===1;
  this.text('location-name',workbench?'遗迹双路':(s.mode==='dark'||s.node===3)?'熄灯回廊':s.mode==='hunter'?'影庭试炼':'灰钟街区');
  this.text('mission-text',workbench?'两处侵入口汇合，利用高台与前线守住水晶。':(s.mode==='dark'||s.node===3)?'共享灯火照亮敌人，射程仍由各自武器决定。':s.mode==='hunter'?'猎人周围与据点可部署；受阻后自动续行。':'守住水晶，保留每一位同行者。');
  const brandLocation=this.root.querySelector('.brand small');if(brandLocation)brandLocation.textContent=workbench?'遗迹双路 · 地图工坊验证':'灰钟街区 · 战斗原型';
  if(exploring){this.text('location-name','雾钟庭院');this.text('mission-text','穿过迷雾寻找静钟，激活后回到入口离开。');}
  this.el('backpack').hidden=!v.backpack;this.el('debug-panel').hidden=!v.debug;
  this.root.classList.toggle('not-battle',s.phase!=='battle');this.root.classList.toggle('can-trade',['briefing','nodes'].includes(s.phase));
  const allies=s.units.filter(u=>u.team==='ally'&&!u.cloneOf);
  if(!this.el('roster').children.length){this.el('roster').innerHTML=allies.map((u,i)=>`<div class="unit-slot" style="--unit:${u.color}"><button data-unit="${u.id}" class="unit-card"><div class="portrait"><img src="/assets/portraits/${u.asset}.png" alt=""><small>${esc(u.role==='hunter'?'HUNTER':u.role==='fiorre'?'FIORRE':u.role==='ines'?'INES':u.role==='guard'?'VANGUARD':'AR')}</small></div><b>${esc(u.name)}</b><span id="life-${u.id}"></span><div class="meter hp"><i class="gray-life" id="gray-${u.id}"></i><i id="hp-${u.id}"></i></div><div class="meter posture" title="架势耗尽后再次受压会硬直"><i id="posture-${u.id}"></i></div><div class="meter ready"><i id="ready-${u.id}"></i></div></button><button class="clone-button" data-clone="${u.id}" title="点击后选择落点，或拖到落点" aria-label="召唤复制体，20生命力"><span>◇ 召影</span><small>20</small></button></div>`).join('');}
  for(const u of allies){const card=this.root.querySelector<HTMLElement>(`[data-unit="${u.id}"]`)!;card.classList.toggle('selected',v.selectedId===u.id);card.classList.toggle('lost',u.life==='dead'||u.life==='departed');this.text(`life-${u.id}`,u.life==='downed'?`救援 ${Math.ceil(u.downTimer)}s`:u.life==='respawning'?`重生 ${Math.ceil(u.respawnTimer)}s`:['reserve','withdrawn'].includes(u.life)?(u.ready>0?'始动 '+u.ready.toFixed(1)+'s':'可部署'):u.life==='active'?'在场 · 选定本体':lifeNames[u.life]);card.classList.toggle('low-health',u.life==='active'&&u.hp/u.maxHp<PERSONAL.lowHealth);const clone=this.root.querySelector<HTMLButtonElement>(`[data-clone="${u.id}"]`)!;clone.disabled=!queryClone(s,u.id).ok;this.el(`gray-${u.id}`).style.width=`${Math.min(1,(u.hp+u.grayHp)/u.maxHp)*100}%`;this.el(`posture-${u.id}`).style.width=`${Math.max(0,u.posture/u.maxPosture)*100}%`;card.classList.toggle('staggered',u.stagger>0);card.classList.toggle('broken-posture',u.posture<=0);this.el(`hp-${u.id}`).style.width=`${Math.max(0,u.hp/u.maxHp)*100}%`;this.el(`ready-${u.id}`).style.width=`${(u.ready>0?1-Math.min(1,u.ready/(COMBAT_CONFIG.warmup[u.role as keyof typeof COMBAT_CONFIG.warmup]||1)):1)*100}%`;}
  this.text('fragments',String(s.fragments));this.text('carried-gold','随身金币 '+s.economy.carried.gold);this.text('hand-count',s.cards.length+'/8');this.text('inventory-count',String(s.inventory.heal+s.inventory.weapon+s.inventory.light));
  const order={scene:0,deck:1,exclusive:2};const hand=[...s.cards].sort((a,b)=>order[a.group]-order[b.group]);
  const key=hand.map(c=>c.id+':'+c.group).join('|')+v.cardId;
  const draw=this.el('draw-btn') as HTMLButtonElement;draw.disabled=!queryDraw(s).ok;draw.dataset.price=String(drawPrice(s));draw.textContent='抽一张 · '+drawPrice(s)+'生命力';draw.title=queryDraw(s).reason||'追加一张背包牌；保留已有手牌';draw.style.setProperty('--charge',Math.min(100,s.fragments/drawPrice(s)*100)+'%');
  if(key!==this.cardKey){this.cardKey=key;let last='';this.cardMotion.render(this.el('cards'),hand.map(c=>{const sep=last&&last!==c.group?' separated':'';last=c.group;return `<button data-card="${c.id}" class="tactic-card ${c.group}${sep}${v.cardId===c.id?' chosen':''}" title="${esc(c.description)}"><small>${c.group==='scene'?'临场':c.group==='deck'?'背包':'专属'}</small><span class="card-symbol">${c.kind==='dash'?'➶':c.kind==='cooldown'?'◷':c.kind==='barricade'?'▥':c.kind==='heal'?'✚':'✧'}</span><b>${esc(c.name)}</b></button>`}).join(''));}
  this.text('card-target',v.cardId?'选择目标 · 右键取消':v.item?'道具指向 · 猎人周围':'');
  const u=s.units.find(u=>u.id===v.selectedId);this.detail(u,v,s);this.updateSkills(s,v.selectedId);
  if(v.backpack){const sig=JSON.stringify(s.inventory)+s.quickSlots.join()+v.item;if(this.el('backpack').dataset.sig!==sig){this.el('backpack').dataset.sig=sig;this.el('backpack').innerHTML=`<div class="section-label">行囊 <button data-action="backpack">关闭</button></div><p>拖入快捷栏，或点击「装入」</p><div class="bag-items">${(['heal','weapon','light'] as const).map(k=>`<div draggable="true" data-bag-item="${k}"><b>${k==='heal'?'恢复药剂':k==='weapon'?'备用武器':'提灯'}</b><span>× ${s.inventory[k]}</span><button data-equip="${k}">装入</button></div>`).join('')}</div><div id="quick-drop" class="quick-drop">快捷栏 · 拖到这里${s.quickSlots.map(k=>`<button data-item="${k}" ${s.inventory[k]<=0?'disabled':''}>${k==='heal'?'恢复药剂':k==='weapon'?'备用武器':'提灯'} ×${s.inventory[k]}</button>`).join('')}</div><small>关闭行囊后点目标使用；仅限猎人周围。</small>`;}}
  if(v.debug){
   const debugEl=this.el('debug-panel');if(!debugEl.querySelector('#debug-readings'))debugEl.innerHTML=`<h3>验证面板</h3><p>开发验证 · 局外技能上限</p><button data-unlock-preset="starter">部分解锁上限</button><button data-unlock-preset="expanded">扩展解锁上限</button><p>开发夹具 · 正常庭院自动判断交战</p><button data-context="tower">塔防战斗</button><button data-context="explorationIdle">探索非战斗（测试）</button><button data-context="explorationBattle">探索战斗（测试）</button><button data-action="end-expedition">结束副本（验证培养清空）</button><div id="debug-readings"></div><button data-action="export">查看操作记录</button>`;
   this.el('debug-readings').innerHTML=`<p>${Math.round(v.fps)} FPS · ${esc(v.assets)}</p><p>节点 ${s.node} · 重置机会 ${s.retries}</p><dl>${Object.entries(s.stats).map(([k,n])=>`<div><dt>${esc(k)}</dt><dd>${Number(n).toFixed(Number.isInteger(n)?0:1)}</dd></div>`).join('')}</dl><h4>队友自治</h4><p>${esc(s.exploration?.combatReason||'塔防持续交战')}</p>${s.units.filter(u=>u.team==='ally'&&!u.cloneOf&&u.life==='active').map(u=>`<p>${esc(u.name)} · ${TENDENCIES[u.aiTendency||'default']} · ${esc(u.ai?.phase||u.ai?.intent||'hold')} · 任务 ${esc(u.ai?.task?.kind||'—')}/${esc(u.ai?.targetId||'—')} · 贡献点 ${u.ai?.contributionPoint?u.ai.contributionPoint.x.toFixed(2)+','+u.ai.contributionPoint.y.toFixed(2):'—'} · TTC ${Number.isFinite(u.ai?.ttc)?u.ai!.ttc!.toFixed(2):'—'} / 窗口 ${Number.isFinite(u.ai?.window)?u.ai!.window!.toFixed(2):'∞'} · 响应 ${u.ai?.coverage??0}/${u.ai?.required??0} · Settle ${Math.max(0,(u.ai?.settleUntil||0)-s.time).toFixed(2)} · 锚点 ${u.ai?.anchor?u.ai.anchor.x.toFixed(2)+','+u.ai.anchor.y.toFixed(2):'无'} / 舒适区 ${comfortRadius(s).toFixed(2)} / 距离 ${u.ai?.anchor?Math.hypot(u.pos.x-u.ai.anchor.x,u.pos.y-u.ai.anchor.y).toFixed(2):'—'} · 槽位 ${u.ai?.slot??'—'} · ${esc(u.ai?.rejectReason||'')}</p>`).join('')}<h4>最近事件</h4><p class="events">${s.log.slice(0,6).map(esc).join('<br>')}</p>`;
  }
  if(v.debug)this.el('debug-readings').insertAdjacentHTML('beforeend',s.units.filter(u=>u.team==='ally'&&!u.cloneOf&&u.life==='active').map(u=>`<p>${esc(u.name)} · 破势移动锁 ${u.posture<=0?'是':'否'} · Brace ${u.ai?.phase==='brace'?'是':'否'} · 保持 ${Math.max(0,(u.ai?.braceUntil||0)-s.time).toFixed(2)}s · 上次自治方向 ${u.ai?.lastAutoMoveDirection?`${u.ai.lastAutoMoveDirection.x.toFixed(2)},${u.ai.lastAutoMoveDirection.y.toFixed(2)}`:'—'} · 反向迟滞 ${Math.max(0,1.2-(s.time-(u.ai?.lastAutoMoveAt??-Infinity))).toFixed(2)}s</p>`).join(''));
  const pk=s.phase+'|'+s.result+'|'+s.mode+'|'+s.completed.join()+'|'+s.canStay+'|'+v.initialSetup;
  if(pk!==this.phaseKey){this.phaseKey=pk;const p=this.el('phase-panel');
   if(s.phase==='account')p.innerHTML='';
   else if(s.phase==='briefing')p.innerHTML=`<section class="briefing"><small class="eyebrow">TACTICAL FIELD STUDY / 01</small><h2>${workbench?'遗迹双路<br><em>守住汇流点。</em>':'灰钟之后<br><em>仍有人同行。</em>'}</h2><p>开局先部署，随后敌群逐波涌入。<br>抽取战术牌、布置复制体，在两路汇流处构筑防线。</p>${v.initialSetup?`<div class="mode-picker"><button data-mode="standard" class="${s.mode==='standard'?'active':''}">街区防御</button><button data-mode="hunter" class="${s.mode==='hunter'?'active':''}">猎人范围</button><button data-mode="dark" class="${s.mode==='dark'?'active':''}">黑暗试炼</button><button data-mode="workbench" class="${s.mode==='workbench'?'active':''}">地图工坊验证 · 遗迹双路</button></div>`:`<p>重入节点 · 保留当前生命与装备损耗</p>`}<button data-action="build">战前配置 · 菲奥蕾技能与武器</button><button data-action="start" aria-label="进入战斗" class="primary">进入战斗 <span>→</span></button><small class="brief-note">${s.width} × ${s.height} 地格 · ${s.mode==='workbench'?'0.25米体素 / 1米=1U · ':''}${kind} · ${progress.total}波 · 技能跨战斗重置</small></section>`;
   else if(s.phase==='result')p.innerHTML=`<div class="dialog-shade"><section class="dialog"><small>OPERATION ${s.result==='victory'?'COMPLETE':'FAILED'}</small><h2>${s.result==='victory'?'守住了这一夜':s.endReason==='abandon'?'已放弃本场':'水晶已破碎'}</h2><p>${s.result==='victory'?'战斗结束。未超时的濒死同伴已被带回。':'本次战斗失败，退出节点。角色损耗不会恢复。'}</p><div class="result-numbers"><span>击破 <b>${s.kills}</b></span><span>用时 <b>${Math.floor(s.time)}s</b></span><span>重置机会 <b>${s.retries}</b></span></div><button data-action="continue" class="primary">返回节点地图</button></section></div>`;
   else if(s.phase==='nodes')p.innerHTML=`<div class="dialog-shade"><section class="dialog node-dialog"><small>EXPEDITION / CURRENT STATE</small><h2>同行者的下一站</h2><p>生命、耐久与精神持续保留。重新开战时水晶满血。</p><div class="nodes"><button data-node="1"><span>Ⅰ</span><b>${s.mode==='workbench'?'遗迹双路':'灰钟街区'}</b><small>${s.completed.includes(1)?'已完成 · 可再入':'短塔防 · 3波'}</small></button><button data-action="rest"><span>✧</span><b>街角休息处</b><small>篝火 · 恢复状态与菲奥蕾部署资格</small></button><button data-node="3"><span>Ⅱ</span><b>熄灯回廊</b><small>${s.completed.includes(3)?'已完成 · 可再入':'长塔防 · 12波 · 共享光照'}</small></button>${s.completed.includes(1)?`<button data-node="4"><span>◇</span><b>雾钟庭院</b><small>${s.completed.includes(4)?'目标已完成 · 可再探索':'探索岔路 · 可提前返回'}</small></button>`:''}</div>${s.completed.includes(1)?'<button data-action="safe-exit" class="primary">测试撤离节点 · 安全离开</button>':''}<button data-action="abandon">放弃副本 · 损失随身资源</button><p class="muted">剩余重置机会 ${s.retries} · 自动保留本次远征状态</p></section></div>`;
   else if(s.phase==='ended')p.innerHTML=`<div class="dialog-shade"><section class="dialog"><small>EXPEDITION ENDED</small><h2>远征结束</h2><p>${s.economy.settled==='success'?'剩余资源已按原类型入库。':'全部随身金币与生命力已损失。'}角色损耗保留。</p><button data-action="new" class="primary">开始新一轮原型测试</button></section></div>`;
   else p.innerHTML='';
  }
 }
 private detail(u:Unit|undefined,v:UIState,s:GameState){const el=this.el('unit-detail');el.hidden=!u;if(!u)return;
 const st=currentSkill(u),info=skillInfo(u);const copies=s.units.filter(a=>a.cloneOf===(u.cloneOf||u.id));const key=u.id+u.life+u.weaponIndex+u.cloneOf+info.id+st.stage+JSON.stringify(st.branches)+copies.map(a=>a.id).join('|');if(key!==this.selectedKey){this.selectedKey=key;el.innerHTML=`<small>${u.role==='hunter'?'必备角色 · HUNTER':'同行者'}${u.cloneOf?' · 影复制体':''}</small><h2>${esc(u.name)}</h2><div class="detail-hero"><img class="detail-portrait" src="/assets/portraits/${u.asset}.png" alt="${esc(u.name)}立绘"><div class="detail-skill"><div class="skill-description" data-skill-preview="${u.id}" tabindex="0"><span>${'✧'}</span><b>${info.name}</b><small>${info.description}</small><em>悬停查看范围 · 血条旁释放</em></div></div></div>${u.cloneOf?`<section class="clone-build"><small>出生构筑 · 不随本体升级同步</small><b>来源：${esc(u.cloneIdentity?.sourceName||s.units.find(a=>a.id===u.cloneOf)?.name||u.cloneOf)}</b><span>${PROFESSION_NAMES[professionOf(u)]} · ${info.name} · 进阶 ${st.stage}/${info.stages.length}</span>${info.stages.slice(0,st.stage).map((level,i)=>`<p>进阶 ${i+1}：${esc(level.description)}</p>`).join('')}${info.branches.map(branch=>`<p class="${st.branches[branch.id]?'chosen-branch':''}">${esc(branch.name)} · ${st.branches[branch.id]||0}/${branch.levels.length}${st.branches[branch.id]?'<br>'+esc(branch.levels[st.branches[branch.id]-1].description):' · 未选择'}</p>`).join('')}</section>`:''}<div id="unit-numbers"></div><p id="unit-weapon"></p>${copies.length?`<section class="clone-list"><small>在场影体 ${copies.length} · 点击查看个体</small>${copies.map(c=>`<button data-copy-select="${c.id}" aria-pressed="${c.id===u.id}"><b>影 #${c.cloneIdentity?.serial||c.id.split('-').at(-1)}</b><span>${PROFESSION_NAMES[professionOf(c)]} · ${skillInfo(c).name}</span></button>`).join('')}</section>`:''}<div class="detail-actions">${u.life==='downed'?`<button data-rescue="${u.id}" class="primary">猎人救援</button>`:u.life==='active'?`${!u.cloneOf?`<button data-action="build" data-build-open="${u.id}">职业与构筑 / 换装</button>`:''}${!u.cloneOf&&u.id!=='hunter'?`<button data-extract="${u.id}" data-via="shadow">请求影庭回收</button>`:''}${u.cloneOf?`<button data-destroy-clone="${u.id}" class="destroy-clone">销毁此复制体</button>`:''}`:''}</div><small>${u.cloneOf?'复制体不可移动；Q或下方按钮销毁此影体，不返还资源。':u.role==='hunter'?'WASD 直接移动；Shift 瞬影；Q 指定收纳或救援。':'点击或拖动移动；E 技能；Q 请求影庭回收。'}</small>`;}
 if(this.detailUnit!==u.id){this.detailUnit=u.id;el.scrollTop=0;}
 this.text('unit-numbers',`生命 ${Math.ceil(u.hp)} / ${u.maxHp}　虚血 ${Math.ceil(u.grayHp)}　架势 ${Math.ceil(u.posture)} / ${u.maxPosture}${u.stagger>0?' · 硬直 '+u.stagger.toFixed(1)+'s':u.posture<=0?' · 破势':''}　精神压力 ${Math.round(u.stress)}　${lifeNames[u.life]}`);const w=u.weapons[u.weaponIndex];this.text('unit-weapon',w?`${w.name} · ${w.shadow?'无损耗':`耐久 ${Math.ceil(w.durability)}/${w.maxDurability}`} · 朝向 ${u.facing}${!u.cloneOf?' · 倾向 '+TENDENCIES[u.aiTendency||'default']:''}`:'未装备武器');
 }
 updatePersonal(s:GameState,selectedId:string|null,aim:'blink'|'collect'|null,slow:boolean,project:(p:Pos)=>Pos){
  const h=s.units.find(u=>u.id==='hunter'),u=s.units.find(u=>u.id===selectedId),battle=s.phase==='battle';
  const collectButton=this.root.querySelector<HTMLButtonElement>('[data-action="collect"]')!,copySelected=!!u?.cloneOf;
  if(collectButton.dataset.copy!==String(copySelected)){collectButton.dataset.copy=String(copySelected);collectButton.innerHTML=copySelected?'销毁影体 <kbd>Q</kbd><small>仅此影体 · 不返还资源</small>':'影庭收纳 <kbd>Q</kbd><small>指定本体 · 濒死救援</small>';}

  this.el('personal-controls').hidden=!battle;
  this.text('control-status',aim==='blink'?'瞬影瞄准 · 点击战场':aim==='collect'?'收纳瞄准 · 指定本体':u?(u.life==='active'?(u.cloneOf?'观察复制体':(slow?'观察 · ':'控制 · '))+u.name:'选择 · '+u.name):'默认控制 · 猎人');
  const b=h?.blink,stock=b?.charges||0;this.text('blink-stock',stock+' / '+PERSONAL.blinkCharges);
  const ticks=this.el('blink-ticks');if(!ticks.children.length)ticks.innerHTML=Array.from({length:10},()=>'<i></i>').join('');
  Array.from(ticks.children).forEach((el,i)=>el.classList.toggle('filled',i<stock));
  this.text('blink-progress',stock===10?'储备充足':((PERSONAL.blinkSeconds-(b?.progress||0)).toFixed(3))+'s · 下一层');
  this.el('blink-button').style.setProperty('--refill',((b?.progress||0)/PERSONAL.blinkSeconds*100)+'%');
  (this.el('blink-button') as HTMLButtonElement).disabled=!h||h.life!=='active'||stock<=0||!!selectedId&&selectedId!=='hunter';
  const svg=this.el('recall-range'),show=battle&&h?.life==='active'&&(aim==='collect'||!!u?.recall||u?.id==='hunter');svg.style.display=show?'':'none';svg.setAttribute('viewBox','0 0 '+innerWidth+' '+innerHeight);
  if(show&&h){const points=Array.from({length:65},(_,i)=>project({x:h.pos.x+Math.cos(i*Math.PI/32)*PERSONAL.recallRadius,y:h.pos.y+Math.sin(i*Math.PI/32)*PERSONAL.recallRadius}));svg.querySelector('path')!.setAttribute('d',points.map((p,i)=>(i?'L':'M')+p.x+','+p.y).join(' ')+' Z');}
  const labels=this.el('recall-labels'),targets=battle?s.units.filter(a=>!!a.partyTask||!!a.recall||a.protectedRecall&&a.shadowResident):[];
  const key=targets.map(a=>a.id).join('|');if(labels.dataset.key!==key){labels.dataset.key=key;labels.innerHTML=targets.map(a=>'<div class="recall-label" data-recall-label="'+a.id+'"><span></span><i></i></div>').join('');}
  for(const a of targets){const el=labels.querySelector<HTMLElement>('[data-recall-label="'+a.id+'"]')!;el.hidden=!!a.shadowResident;const p=project(a.pos);el.style.left=p.x+'px';el.style.top=(p.y-95)+'px';el.querySelector('span')!.textContent=a.partyTask?(a.partyTask.elapsed?'集结 '+Math.max(0,PERSONAL.recallSeconds-a.partyTask.elapsed).toFixed(3)+'s':'集结 · 接近猎人'):a.recall?.waitingCross?'跨层后回收':a.recall?.elapsed?'收纳 '+Math.max(0,PERSONAL.recallSeconds-a.recall.elapsed).toFixed(3)+'s':'正在接近猎人';(el.querySelector('i') as HTMLElement).style.width=((a.partyTask?.elapsed||a.recall?.elapsed||0)/PERSONAL.recallSeconds*100)+'%';}
 }
 private updateSkills(s:GameState,selectedId:string|null){const world=document.querySelector<HTMLElement>('#world-skill')!;const u=s.units.find(u=>u.id===selectedId&&u.team==='ally');if(u&&u.life==='active'&&s.phase==='battle'){if(world.dataset.unitId!==u.id+u.skillId){world.dataset.unitId=u.id+u.skillId;world.innerHTML=skillHTML(u,'world-skill-button');}const b=world.querySelector<HTMLButtonElement>('[data-skill]')!;b.dataset.worldSkill='';updateSkillButton(b,u,true);const p=(window as any).prototype.project(u.drawPos||u.pos);world.style.left=(p.x+22)+'px';world.style.top=(p.y-47)+'px';}else{world.replaceChildren();world.dataset.unitId='';}}
 error(message:string){this.el('error').hidden=false;this.text('error',message);}
}
