import type {GameState,CommandResult,Unit} from './types';
export type Balance={gold:number;vitality:number};
export type Economy={account:Balance;carried:Balance;nodeOpen:boolean;active:boolean;serial:number;settled:null|'success'|'failure';draws:number;visit:number;rewards:string[];cardEvents:string[];pending:{key:string;kind:'dash'|'power';group:'scene'|'exclusive';ownerId?:string;node:number}[];audit:{action:string;amount:number;before:Balance;after:Balance;key?:string;expedition:number}[]};
export const ECONOMY={carryMax:80,kill:4,drawBase:10,drawStep:5,handMax:8};
const valid=(n:number)=>Number.isSafeInteger(n)&&n>=0;
const fail=(reason:string):CommandResult=>({ok:false,reason});
export function initEconomy(s:GameState){s.economy={account:{gold:0,vitality:0},carried:{gold:0,vitality:0},nodeOpen:true,active:false,serial:0,settled:null,draws:0,visit:0,rewards:[],cardEvents:[],pending:[],audit:[]};bindBalance(s);}
export function bindBalance(s:GameState){Object.defineProperty(s,'fragments',{configurable:true,enumerable:true,get:()=>s.economy.carried.vitality,set:(v:number)=>{if(valid(v))s.economy.carried.vitality=v;}});}
function audit(s:GameState,action:string,amount:number,before:Balance,key?:string){const e=s.economy;e.audit.push({action,amount,before,after:{...e.carried},key,expedition:e.serial});}
export function exchange(s:GameState,from:'gold'|'vitality',amount:number):CommandResult{const e=s.economy;if(e.active||s.phase!=='account'||!['gold','vitality'].includes(from)||!valid(amount)||amount<=0)return fail('仅可在副本外兑换有效整数');const to=from==='gold'?'vitality':'gold';if(!valid(e.account[from])||e.account[from]<amount||!valid(e.account[to]+amount))return fail('库存不足或金额超限');e.account[from]-=amount;e.account[to]+=amount;return {ok:true};}
export function queryCarry(s:GameState,gold:number,vitality:number):CommandResult{const e=s.economy;if(e.active||s.phase!=='account')return fail('本次携入已经提交');if(!valid(gold)||!valid(vitality)||vitality>ECONOMY.carryMax||gold>e.account.gold||vitality>e.account.vitality)return fail('携入须为库存内整数，生命力最多80');return {ok:true};}
export function commitCarry(s:GameState,gold:number,vitality:number):CommandResult{const r=queryCarry(s,gold,vitality);if(!r.ok)return r;const e=s.economy;e.account.gold-=gold;e.account.vitality-=vitality;e.carried={gold,vitality};e.nodeOpen=true;e.active=true;e.serial++;e.settled=null;e.rewards=[];e.cardEvents=[];e.pending=[];e.draws=0;e.visit=0;audit(s,'carry',vitality,{gold:0,vitality:0});return {ok:true};}
export function canTrade(s:GameState){return s.economy.nodeOpen&&s.economy.active&&s.economy.settled===null&&['briefing','battle','nodes'].includes(s.phase);}
export function canPay(s:GameState,n:number){return canTrade(s)&&valid(n)&&valid(s.fragments)&&s.fragments>=n;}
export function payVitality(s:GameState,n:number,action:string){if(!canPay(s,n))return fail('随身生命力不足或当前不可消费');const before={...s.economy.carried};s.fragments-=n;audit(s,action,n,before);return {ok:true};}
export function credit(s:GameState,n:number,action:string,key?:string){if(!s.economy.active||!valid(n)||!valid(s.fragments+n))return false;const before={...s.economy.carried};s.fragments+=n;audit(s,action,n,before,key);return true;}
export function rewardKill(s:GameState,u:Unit){const key=u.rewardKey||`${s.economy.serial}:node${s.node}:runtime:${u.id}`;if(s.economy.rewards.includes(key))return false;if(!credit(s,ECONOMY.kill,'kill',key))return false;s.economy.rewards.push(key);return true;}
export function settle(s:GameState,result:'success'|'failure'):CommandResult{const e=s.economy;if(!e.active||e.settled)return fail('副本已经结算');const before={...e.carried};if(result==='success'){e.account.gold+=before.gold;e.account.vitality+=before.vitality;}e.carried={gold:0,vitality:0};e.settled=result;e.active=false;s.cards=[];e.pending=[];audit(s,result, before.vitality,before);return {ok:true};}
