import type {ExplorationMemory,ExplorationRun,EnemySense,PartyTask} from './exploration-types';
import type {Economy} from './economy';
export type Pos={x:number;y:number};
export type Direction='north'|'east'|'south'|'west';
export type Life='reserve'|'active'|'downed'|'rescued'|'withdrawn'|'dead'|'respawning'|'departed';
export type Profession='hunter'|'healer'|'cantor'|'guard'|'ranger'|'shieldguard'|'scythe';
export type SkillId='hunt'|'prayer'|'ward'|'bell'|'poison'|'snipe'|'pain'|'sanctuary'|'rain'|'dance'|'reap';
export type SkillKind='timed'|'toggle'|'count'|'auto'|'chargedMode'|'return';
export type ResolvedSkill={id:SkillId;name:string;kind:SkillKind;tier:number;branches:Record<string,number>;cooldown:number;duration:number;range:number;width:number;power:number;heal:number;shieldBase:number;missingHpScale:number;shieldDuration:number;defense:number;defenseDuration:number;regen:number;regenDuration:number;stun:number;slow:number;slowDuration:number;allyHeal:number;attackMultiplier:number;attackPeriodMultiplier:number;poisonPerHit:number;poisonThreshold:number;poisonRadius:number;poisonDamage:number;pulsePeriod:number;pulseAt:number};
export type SkillState={stage:number;branches:Record<string,number>;cd:number;max:number;time:number;pulse:number;enabled:boolean;counter:number;readyAt?:number;targetClocks?:Record<string,number>;run?:SkillRun;snapshot?:ResolvedSkill};
export type SkillCap={stage:number;branches:Record<string,number>};
export type SkillProfile={defaults:Record<string,Partial<Record<Profession,SkillId>>>;unlockCaps:Record<SkillId,SkillCap>;preset:'starter'|'expanded'};
export type Status={origin?:Unit;kind:'attack'|'guard'|'poison'|'defense'|'stun'|'shield'|'regen'|'slow'|'warding'|'resistBreak'|'crack';remaining:number;power:number;source?:string;name?:string;duration?:number};
export type Weapon={attackPeriod?:number;profession?:Profession;name:string;range:number;width:number;remote:boolean;damage:number;durability:number;maxDurability:number;shadow:boolean;damageKind?:'physical'|'arcane';subtype?:'slash'|'pierce'|'impact'|'flame'|'frost'|'shadow';weight?:number;class?:'blade'|'gun'|'focus'};
export type Unit={enemySense?:EnemySense;partyTask?:PartyTask;following?:boolean;rewardKey?:string;cloneIdentity?:{sourceName:string;serial:number};skillLanding?:{origin:Pos;after?:Pos;path?:Pos[]};skillStates?:Record<string,SkillState>;skillId?:SkillId;loadout?:{targetIndex:number;elapsed:number;duration:number};blink?:{charges:number;progress:number;interval:number};direct?:{direction:Pos|null;trail:Pos[];notified?:boolean};recall?:{elapsed:number;waitingCross:boolean;repath:number};shadowResident?:boolean;protectedRecall?:boolean;lowHealthAt?:number;bodyRadius?:number;heading?:number;crossing?:{from:Pos;to:Pos;elapsed:number;switched:boolean};afterCross?:Pos;engagement?:{targetId:string;anchor:Pos};engagementCost?:number;enemyMotion?:'route'|'engaged'|'return';pursuitTargetId?:string;returnPoint?:Pos;navWait?:number;id:string;name:string;team:'ally'|'enemy';role:'hunter'|'fiorre'|'guard'|'ines'|'ranger'|'melee'|'ranged'|'heavy';asset:string;color:string;pos:Pos;drawPos:Pos;life:Life;hp:number;maxHp:number;facing:Direction;defaultFacing:Direction;speed:number;block:number;damage:number;attackPeriod:number;attackTimer:number;skillCd:number;skillMax:number;skillTime:number;skillPulse?:number;sniperMode?:boolean;autoSkill?:boolean;poisonMeter?:number;cloneOf?:string;ready:number;downTimer:number;respawnTimer:number;path:Pos[];destination:Pos|null;transition:number;moveProgress:number;intent:'move'|'extract'|'gate'|'rescue'|null;rescueTarget:string|null;route:Pos[];routeIndex:number;statuses:Status[];weapons:Weapon[];weaponIndex:number;stress:number;stressCd:number;light:number;hitFlash:number;attackFlash:number;reveal:number;attackPending?:{targetId:string;remaining:number;facing:Direction};turnCd?:number;moveFrom?:Pos;dodge?:number;defense?:{subtype:NonNullable<Weapon['subtype']>;flat:number};capacity?:number;compatibleClasses?:NonNullable<Weapon['class']>[];mental?:'steady'|'inspired'|'distressed';mentalTime?:number};
export type Tile=Pos & {layer:number;obstacle:boolean};
export type Card={templateId?:string;sellPrice?:number;node?:number;id:string;kind:'dash'|'cooldown'|'power'|'barricade'|'heal';group:'scene'|'deck'|'exclusive';name:string;description:string;ownerId?:string};
export type Effect={id:number;from:Pos;to:Pos;color:string;remaining:number;kind:'shot'|'heal'|'burst'|'loot'|'blink'|'deploy'|'recall';sourceId?:string;asset?:string;action?:'attack'|'skill';amount?:number};
export type SpawnEntry={id:string;role:'melee'|'ranged'|'heavy';asset:'Dustin'|'Verlaine_bot';hpScale:number;damageScale:number};
export type BatchDefinition={id:string;route:Pos[];offset:number;interval:number;previewSeconds:number;entries:SpawnEntry[]};
export type WaveDefinition={id:string;batches:BatchDefinition[]};
export type WaveRuntime={index:number;phase:'waiting'|'spawning'|'clearing'|'intermission'|'complete';anchor:number;spawned:Record<string,number>;intermissionUntil:number|null};
export type Wave=WaveDefinition;
export type GameState={exploration?:ExplorationRun;explorationMemories?:Record<number,ExplorationMemory>;rescueRestrictions?:Record<string,number>;waveState:WaveRuntime|null;attempt:number;endedAttempt?:number;endReason?:'crystal'|'abandon'|'victory';economy:Economy;skillEffects?:SkillEcho[];combatEvents?:CombatEvent[];profile?:SkillProfile;context?:'tower'|'explorationIdle'|'explorationBattle';ruleset?:'tower'|'exploration';deploymentCells?:Pos[];encounters?:{sourceId:string;targetId:string;party:boolean}[];mode:string;phase:'account'|'briefing'|'battle'|'result'|'nodes'|'ended';result:'victory'|'defeat'|null;tiles:Tile[];width:number;height:number;units:Unit[];time:number;crystalHp:number;crystalMax:number;goal:Pos;gate:Pos;spawns:Pos[];kills:number;totalEnemies:number;spawned:number;spawnTimer:number;wave:number;waves:Wave[];cards:Card[];fragments:number;autoDraw:boolean;inventory:{heal:number;weapon:number;light:number};quickSlots:('heal'|'weapon'|'light')[];barricades:Pos[];barrierHp?:Record<string,number>;lights:{pos:Pos;radius:number;remaining:number}[];effects:Effect[];stats:Record<string,number>;log:string[];notice:string;node:number;completed:number[];retries:number;canStay:boolean;seed:number;nextId:number;reveals?:Record<string,number>};
export type Command=
|{type:'party';kind:'recall'|'regroup'}|{type:'partySelection';id:string|null}|{type:'interactExploration';id:string}|{type:'exitExploration';abandonIds?:string[]}

|{type:'direct';id:string;direction:Pos|null}|{type:'blink';id:string;direction:Pos}|{type:'collect';id:string}|{type:'start'}|{type:'move';id:string;to:Pos;facing?:Direction}|{type:'face';id:string;facing:Direction}
|{type:'deploy';id:string;to:Pos;facing:Direction}|{type:'skill';id:string}|{type:'rescue';id:string}
|{type:'extract';id:string;via:'shadow'|'gate'}|{type:'card';cardId:string;to:Pos;targetId?:string;direction?:Direction}
|{type:'abandonBattle'}|{type:'exchange';from:'gold'|'vitality';amount:number}|{type:'carry';gold:number;vitality:number}|{type:'safeExit'}|{type:'abandon'}|{type:'sellCard';cardId:string}|{type:'enterExplorationNode'}
|{type:'destroyClone';id:string}|{type:'leaveExplorationNode'}|{type:'clone';id:string;to:Pos}|{type:'draw';expectedPrice?:number}|{type:'autoDraw'}|{type:'item';item:'heal'|'weapon'|'light';to:Pos;targetId?:string}
|{type:'equipQuick';item:'heal'|'weapon'|'light'}|{type:'switchWeapon';id:string}|{type:'selectScenario';mode:'standard'|'hunter'|'dark'|'workbench'}
|{type:'configureSkill';id:string;skillId:SkillId}|{type:'upgradeSkill';id:string;kind:'stage'|'branch';branch?:string;expectedLevel:number}|{type:'weapon';id:string;index:number}|{type:'unlockPreset';preset:'starter'|'expanded'}|{type:'setContext';context:'tower'|'explorationIdle'|'explorationBattle'}|{type:'newExpedition'}|{type:'endExpedition'}|{type:'continue'}|{type:'enter';node:number}|{type:'rest'};
export type CommandResult={ok:boolean;reason?:string};
export type UIOverlay={attackPreview?:{center:Pos;radius:number;remote:boolean};hoverValid?:boolean;selectedId:string|null;hover:Pos|null;path:Pos[];range:Pos[];rangeKind?:'attack'|'skill';deployTiles:Pos[];targeting:boolean};
export const DIRS:Direction[]=['north','east','south','west'];

export type CombatEvent={id:number;castId?:number;sourceId:string;targetId:string;skillId?:SkillId;derived:boolean;kind:'hit'|'basic'|'arrow';at:number;power:number};
export type SkillRun={id:number;startedAt?:number;spec:ResolvedSkill;power:number;maxHp:number;weapon:Weapon;origin:Pos;heading:number;elapsed:number;nextSlot:number;fired:number;nextTrace:number;counts:Record<string,number>;inside:Record<string,number>;seen:string[];route?:Pos[];phase?:'out'|'turn'|'back';cursor?:number;virtual?:Pos;outHits?:string[];backHits?:string[];healed?:string[];normalReturn?:boolean};
export type SkillEcho={source?:Unit;id:number;castId:number;sourceId:string;skillId:SkillId;at:number;expires?:number;kind:'painEcho'|'snipeEcho'|'backslash'|'rainTrace'|'scytheTrace'|'seat';center:Pos;heading:number;spec:ResolvedSkill;power:number;maxHp:number;weapon:Weapon;hits:string[];radius?:number;factor?:number};
