import test from 'node:test';
import assert from 'node:assert/strict';
import {EditorDocument} from '../core/document.ts';
import {VoxelSelection} from '../core/voxel-selection.ts';
import {copySelection, planPlacement} from '../core/voxel-clipboard.ts';
import {EditOperationSession} from '../core/edit-operation.ts';
import {creativeConfig} from '../core/creative-build.ts';
import {VoxelPlacementSession} from '../desktop/voxel-placement.ts';

const seed=()=>{const e=new EditorDocument();e.begin();e.put(0,0,0,0,'height');e.put(2,0,0,1,'volume');e.put(0,1,0,2,'volume');e.commit();const s=new VoxelSelection();s.add([e.cells.get('0,0,0'),e.cells.get('2,0,0')]);return {e,s};};
test('clipboard captures only exact cells and stable integer origin',()=>{const {e,s}=seed();const c=copySelection(e,s,'asset-a');assert.equal(c.cells.length,2);assert.deepEqual(c.origin,[0,0,0]);assert.deepEqual(c.cells.map(x=>x.offset),[[0,0,0],[2,0,0]]);assert.equal(c.cells[1].owner,'volume');assert.equal(e.past.length,1);});
test('paste previews without writes, rejects conflicts, and commits as one undo',()=>{const {e,s}=seed(),c=copySelection(e,s,'a');const conflict=planPlacement(e,c,[0,1,0],'paste');assert.equal(conflict.conflicts.length,1);assert.equal(e.cells.size,3);const rejected=new EditOperationSession(e);rejected.begin(creativeConfig(0,'add'));assert.throws(()=>rejected.placement(conflict),/冲突/);rejected.cancel();const p=planPlacement(e,c,[1,2,0],'paste');const op=new EditOperationSession(e);op.begin(creativeConfig(0,'add'));op.apply(op.placement(p));op.commit();assert.equal(e.cells.size,5);assert.equal(e.past.length,2);e.undo();assert.equal(e.cells.size,3);assert.equal(c.cells.length,2);});
test('move permits self-overlap, rejects external collision, and restores on undo',()=>{const {e,s}=seed(),c=copySelection(e,s,'a');const p=planPlacement(e,c,[1,0,0],'move');assert.equal(p.conflicts.length,0);const op=new EditOperationSession(e);op.begin(creativeConfig(0,'add'));op.apply(op.placement(p));op.commit();assert.deepEqual([...e.cells.keys()].sort(),['0,1,0','1,0,0','3,0,0']);e.undo();assert.deepEqual([...e.cells.keys()].sort(),['0,0,0','0,1,0','2,0,0']);assert.equal(planPlacement(e,c,[0,1,0],'move').conflicts.length,1);});
test('move refuses vanished or changed source and paste identical cells is noop',()=>{const {e,s}=seed(),c=copySelection(e,s,'a');const same=planPlacement(e,c,c.origin,'paste');assert.equal(same.noop.length,2);e.begin();e.put(0,0,0,0,'height',true);e.commit();assert.throws(()=>planPlacement(e,c,[4,0,0],'move'),/不存在|变化/);});
test('moving a contiguous pair one cell allows self-overlap and preserves both colors',()=>{const e=new EditorDocument();e.begin();e.put(0,0,0,0,'height');e.put(1,0,0,1,'volume');e.commit();const s=new VoxelSelection();s.add(e.cells.values());const c=copySelection(e,s,'a'),p=planPlacement(e,c,[1,0,0],'move');assert.deepEqual(p.conflicts,[]);const op=new EditOperationSession(e);op.begin(creativeConfig(0,'add'));op.apply(op.placement(p));op.commit();assert.deepEqual([...e.cells.keys()].sort(),['1,0,0','2,0,0']);assert.equal(e.cells.get('1,0,0').color,0);assert.equal(e.cells.get('2,0,0').color,1);});
test('cancel does not alter geometry and clipboard rejects a different module',()=>{const {e,s}=seed(),placement=new VoxelPlacementSession();placement.copy(e,s,'module-a');const before=structuredClone(e.doc);placement.begin('paste',e,s,'module-a');placement.nudge(e,0,1);placement.cancel();assert.deepEqual(e.doc,before);assert.throws(()=>placement.begin('paste',e,s,'module-b'),/其他模块/);});
test('six direction nudges retain whole exact shape and negative grid phase',()=>{const {e,s}=seed();for(const axis of [0,1,2])for(const step of [-1,1]){const placement=new VoxelPlacementSession();placement.begin('move',e,s,'a');const p=placement.nudge(e,axis,step);assert.equal(p.destination.length,2);assert.equal(p.target[axis],step);assert.deepEqual(p.destination.map(c=>[c.x,c.y,c.z][axis]),[step,step+(axis===0?2:0)]);assert.equal(e.cells.size,3);}});
