using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;
namespace Xinghai.MapEditor.Editor {
 public static class WrapperUpgrade {
  static Dictionary<string,PublishedInstance> Instances(GameObject root){var rows=root.GetComponentsInChildren<PublishedInstance>(true);PublishReader.Require(rows.All(i=>PublishReader.Id(i.instanceId))&&rows.Select(i=>i.instanceId).Distinct().Count()==rows.Length,"视觉实例身份重复或无效");return rows.ToDictionary(i=>i.instanceId);}
  static Transform TransformOf(UnityEngine.Object obj){if(obj is GameObject go)return go.transform;if(obj is Component component)return component.transform;return null;}
  static UnityEngine.Object Replacement(UnityEngine.Object obj,GameObject oldRoot,GameObject newRoot,Dictionary<string,PublishedInstance> instances){var transform=TransformOf(obj);if(transform==null||!transform.IsChildOf(oldRoot.transform))return obj;GameObject target;if(transform==oldRoot.transform)target=newRoot;else {var identity=transform.GetComponent<PublishedInstance>();PublishReader.Require(identity!=null&&instances.ContainsKey(identity.instanceId),"用户引用指向未知或已删除的视觉子节点");target=instances[identity.instanceId].gameObject;}if(obj is GameObject)return target;var components=target.GetComponents(obj.GetType());PublishReader.Require(components.Length==1,"视觉组件引用无法唯一重映射");return components[0];}
  static IEnumerable<Component> Owned(GameObject wrapper,GameObject visual)=>wrapper.GetComponentsInChildren<Component>(true).Where(c=>c!=null&&!c.transform.IsChildOf(visual.transform));
  public static UpgradeReport Preview(GameObject wrapper,PublishedScene candidate){var result=new UpgradeReport();try{PublishReader.Require(wrapper!=null&&candidate!=null&&candidate.prefab!=null,"需要包装和新场景接收物");WorkshopBake.AssertReceipt(candidate);var state=wrapper.GetComponent<WrapperState>();PublishReader.Require(state!=null&&state.visualRoot!=null&&state.visualRoot.transform.IsChildOf(wrapper.transform)&&state.visualRoot!=wrapper,"包装缺少 WrapperState 或视觉根");var visual=state.visualRoot.GetComponent<PublishedVisual>();PublishReader.Require(visual!=null&&visual.publishId==state.publishId&&visual.receiptId==state.receiptId,"包装冻结版本身份不匹配");var old=Instances(state.visualRoot);var next=Instances(candidate.prefab);PublishReader.Require(state.overrides!=null&&state.overrides.Select(o=>o.instanceId).Distinct().Count()==state.overrides.Length,"包装覆盖身份重复");var overrides=state.overrides.ToDictionary(o=>o.instanceId);
   foreach(var o in state.overrides){PublishReader.Require(old.ContainsKey(o.instanceId),"覆盖引用未知旧实例："+o.instanceId);PublishReader.Require(next.ContainsKey(o.instanceId),"新版删除了已手调实例："+o.instanceId);PublishReader.Require(old[o.instanceId].assetId==next[o.instanceId].assetId&&old[o.instanceId].anchorM.SequenceEqual(next[o.instanceId].anchorM),"新版改Root或资产与已手调实例冲突："+o.instanceId);PublishReader.Require(o.sourcePositionM!=null&&o.sourcePositionM.Length==3&&o.sourcePositionM.All(v=>!float.IsNaN(v)&&!float.IsInfinity(v)&&Math.Abs(v)<=2048)&&o.rotationDeg%90==0&&Math.Abs((long)o.rotationDeg)<=360000,"包装变换覆盖无效");}
   foreach(var pair in old){var i=pair.Value;var t=i.transform;var position=overrides.TryGetValue(pair.Key,out var o)?o.sourcePositionM:i.sourcePositionM;int rotation=o!=null?o.rotationDeg:i.rotationDeg;PublishReader.Require(Vector3.Distance(t.localPosition,WorkshopCoordinates.Unity(position))<.00001f&&Quaternion.Angle(t.localRotation,Quaternion.Euler(0,-rotation,0))<.001f&&t.localScale==Vector3.one,"未登记或未知的视觉 Transform 覆盖："+pair.Key);}
   PublishReader.Require(state.visualRoot.transform.localPosition==Vector3.zero&&Quaternion.Angle(state.visualRoot.transform.localRotation,Quaternion.identity)<.001f&&state.visualRoot.transform.localScale==Vector3.one,"视觉根存在未支持的包装变换");
   PublishReader.Require(PrefabUtility.GetAddedGameObjects(state.visualRoot).Count==0&&PrefabUtility.GetAddedComponents(state.visualRoot).Count==0&&PrefabUtility.GetRemovedComponents(state.visualRoot).Count==0,"视觉内部存在未支持的新增/删除覆盖");
   var modifications=PrefabUtility.GetPropertyModifications(state.visualRoot)??new PropertyModification[0];foreach(var modification in modifications){if(modification.propertyPath=="m_Name"&&modification.target==PrefabUtility.GetCorrespondingObjectFromSource(state.visualRoot)&&modification.value==state.visualRoot.name)continue;if(modification.propertyPath=="m_Name"&&modification.target is GameObject named&&old.Values.Any(i=>i.name==i.instanceId&&modification.value==i.instanceId&&(PrefabUtility.GetCorrespondingObjectFromSource(i.gameObject)==named||PrefabUtility.GetCorrespondingObjectFromOriginalSource(i.gameObject)==named)))continue;if(modification.target is Transform t){if(modification.propertyPath=="m_RootOrder")continue;var instance=t.GetComponent<PublishedInstance>();if(instance!=null&&overrides.ContainsKey(instance.instanceId)&&(modification.propertyPath.StartsWith("m_LocalPosition.")||modification.propertyPath.StartsWith("m_LocalRotation.")||modification.propertyPath.StartsWith("m_LocalEulerAnglesHint.")))continue;var sourceRoot=PrefabUtility.GetCorrespondingObjectFromSource(state.visualRoot);if(t.gameObject==sourceRoot&&state.visualRoot.transform.localPosition==Vector3.zero&&state.visualRoot.transform.localScale==Vector3.one&&Quaternion.Angle(state.visualRoot.transform.localRotation,Quaternion.identity)<.001f)continue;}throw new Exception("未知的视觉Prefab内部覆盖："+modification.propertyPath+" target="+modification.target.name+" value="+modification.value);}
   foreach(var component in Owned(wrapper,state.visualRoot)){var serialized=new SerializedObject(component);var property=serialized.GetIterator();while(property.Next(true))if(property.propertyType==SerializedPropertyType.ObjectReference&&property.objectReferenceValue!=null)Replacement(property.objectReferenceValue,state.visualRoot,candidate.prefab,next);}
  }catch(Exception e){result.conflicts.Add(e.Message);}return result;}
  public static GameObject CreateCopy(GameObject wrapper,PublishedScene candidate,string destination){var report=Preview(wrapper,candidate);PublishReader.Require(report.canUpgrade,string.Join("\n",report.conflicts));PublishReader.Require(destination!=null&&destination.StartsWith("Assets/",StringComparison.Ordinal)&&destination.EndsWith(".prefab",StringComparison.Ordinal)&&!File.Exists(destination)&&!File.Exists(destination+".meta"),"目标必须是 Assets 内尚不存在的新Prefab");PublishReader.Safe(Path.GetFullPath("Assets"),destination.Substring(7));PublishReader.Require(Directory.Exists(Path.GetDirectoryName(destination)),"目标文件夹不存在");string temporary=destination.Substring(0,destination.Length-7)+"-"+Guid.NewGuid().ToString("N")+".prefab";GameObject clone=null;bool moved=false;try{clone=UnityEngine.Object.Instantiate(wrapper);clone.name=wrapper.name;var state=clone.GetComponent<WrapperState>();var old=state.visualRoot;var fresh=(GameObject)PrefabUtility.InstantiatePrefab(candidate.prefab);fresh.transform.SetParent(old.transform.parent,false);fresh.transform.SetSiblingIndex(old.transform.GetSiblingIndex());var instances=Instances(fresh);foreach(var component in Owned(clone,old)){var serialized=new SerializedObject(component);var property=serialized.GetIterator();while(property.Next(true))if(property.propertyType==SerializedPropertyType.ObjectReference&&property.objectReferenceValue!=null)property.objectReferenceValue=Replacement(property.objectReferenceValue,old,fresh,instances);serialized.ApplyModifiedPropertiesWithoutUndo();}state.visualRoot=fresh;state.publishId=candidate.publishId;state.receiptId=candidate.receiptId;foreach(var o in state.overrides){var t=instances[o.instanceId].transform;t.localPosition=WorkshopCoordinates.Unity(o.sourcePositionM);t.localRotation=Quaternion.Euler(0,-o.rotationDeg,0);}UnityEngine.Object.DestroyImmediate(old);var saved=PrefabUtility.SaveAsPrefabAsset(clone,temporary,out bool success);PublishReader.Require(success&&saved!=null,"包装副本写入失败");PublishReader.Require(!File.Exists(destination)&&!File.Exists(destination+".meta"),"目标已被其他操作创建");string error=AssetDatabase.MoveAsset(temporary,destination);PublishReader.Require(string.IsNullOrEmpty(error),error);moved=true;var result=AssetDatabase.LoadAssetAtPath<GameObject>(destination);PublishReader.Require(result!=null,"包装副本未成功导入");return result;}catch{if(moved)AssetDatabase.DeleteAsset(destination);throw;}finally{if(clone!=null)UnityEngine.Object.DestroyImmediate(clone);if(File.Exists(temporary)||File.Exists(temporary+".meta"))AssetDatabase.DeleteAsset(temporary);}}
 }
}
