import {describe,it,expect} from 'vitest';
import {LabWorld} from '../../src/action-lab/runtime/world';
import {HitEffects,energyReturn} from '../../src/action-lab/runtime/hit-effects';
import {LabResources} from '../../src/action-lab/runtime/resources';
describe('AL01 M2 lifecycle and ownership',()=>{
 it('a rejected immediate repeated dodge spends no extra charge',()=>{const w=new LabWorld();w.enemy.enabled=false;w.aim={x:-1,y:0};expect(w.dodge()).toBe(true);expect(w.dodge()).toBe(false);expect(w.resources.dashCharges).toBe(1);});
 it('dash wall collision does not terminate invulnerability source early',()=>{const w=new LabWorld();w.blue.x=7.74;w.aim={x:1,y:0};w.dodge();w.advance(.05);expect(w.blue.x).toBeLessThanOrEqual(7.75);expect(w.defense.invulnerable(w.simTime)).toBe(true);w.advance(.1);expect(w.defense.invulnerable(w.simTime)).toBe(false);});
 it('insufficient frost cannot start shield and a guard startup hit really damages',()=>{const w=new LabWorld();w.reset(true);w.resources.frost=0;expect(w.shield(true)).toBe(false);expect(w.resources.frost).toBe(0);w.resources.frost=3;w.enemy.cooldown=0;w.advance(.55);w.shield(true);w.advance(.04);expect(w.blue.hp).toBe(95);expect(w.resources.frost).toBe(3);});
 it('zero remaining frost at incoming contact fails even if guard was accepted',()=>{const w=new LabWorld();w.reset(true);w.shield(true);w.resources.frost=0;w.enemy.cooldown=0;w.advance(.7);expect(w.blue.hp).toBe(95);expect(w.log.some(e=>e.result==='frost-insufficient')).toBe(true);});
 it('root cancellation after Attack retains cost and suppresses future child',()=>{const w=new LabWorld();w.enemy.enabled=false;w.prepareActive();w.advance(.2);w.releaseActive();w.advance(.01);expect(w.resources.activeCharge).toBe(0);expect(w.cancelUpper()).toBe(true);w.advance(.7);expect(w.log.some(e=>e.result==='shield-charge'&&e.eventKind==='accepted')).toBe(false);expect(w.resources.activeCharge).toBe(0);});
 it('energy return dedupes target colliders and multiple targets by caster/root/wave; cleanup is symmetric',()=>{const bus=new HitEffects(),a=new LabResources(),b=new LabResources();a.frost=b.frost=0;const returned:number[]=[];const off=energyReturn(bus,1,id=>id==='a'?a:id==='b'?b:undefined,(_,delta)=>returned.push(delta));const h={generation:1,casterId:'a',rootId:1,actionId:2,waveId:3,targetId:'x',kind:'shield-charge',damage:75};bus.publish(h);bus.publish(h);bus.publish({...h,targetId:'y'});expect(a.frost).toBe(2);expect(b.frost).toBe(0);expect(returned).toEqual([2]);bus.publish({...h,casterId:'b'});expect(b.frost).toBe(2);off();bus.publish({...h,waveId:4});expect(a.frost).toBe(2);});
 it('growth does not react to whiffs, basics or old generations',()=>{const bus=new HitEffects(),a=new LabResources();a.frost=0;energyReturn(bus,2,()=>a,()=>{});const h={generation:2,casterId:'a',rootId:1,actionId:2,waveId:3,targetId:'x',kind:'shield-charge',damage:0};bus.publish(h);bus.publish({...h,damage:15,kind:'basic'});bus.publish({...h,damage:75,generation:1});expect(a.frost).toBe(0);});
 it('active and dash cooldowns progress independently while frost recovery waits until released and delayed',()=>{const r=new LabResources();r.spendDodge();r.payActive();r.spendBlock(0);r.advance(2,2,true);expect(r.frost).toBe(2);expect(r.activeCharge).toBe(0);r.advance(.5,2.5,false);expect(r.dashCharges).toBe(2);expect(r.frost).toBeCloseTo(2.4);expect(r.activeCharge).toBe(0);r.advance(5.5,8,false);expect(r.activeCharge).toBe(1);expect(r.mp).toBe(100);});
 it('active preparation carries an explicit bounded invulnerability source, independent of retreat',()=>{const w=new LabWorld();w.resetBuild(true,true);w.enemy.cooldown=0;w.advance(.55);w.prepareActive();w.advance(.5);expect(w.defense.invulnerable(w.simTime)).toBe(true);w.advance(2);expect(w.blue.action).toBeUndefined();expect(w.resources.activeCharge).toBe(1);expect(w.defense.invulnerable(w.simTime)).toBe(false);});
 it('slow simulation scales defense, motion and recovery without consuming them on real time',()=>{const w=new LabWorld();w.enemy.enabled=false;w.aim={x:-1,y:0};w.speed=.25;w.dodge();w.advance(.4);expect(w.simTime).toBeCloseTo(.1);expect(w.defense.invulnerable(w.simTime)).toBe(true);expect(w.resources.dashCooldown).toBeCloseTo(2.4);w.advance(.2);expect(w.defense.invulnerable(w.simTime)).toBe(false);expect(w.motion).toBeUndefined();expect(w.resources.dashCharges).toBe(1);});
 it('actual fatal enemy damage clears guard and cannot leak resources or hazards through reset',()=>{const w=new LabWorld();w.resetBuild(true,true);w.blue.hp=5;w.aim={x:-1,y:0};w.shield(true);w.enemy.cooldown=0;w.advance(.7);expect(w.blue.hp).toBe(0);expect(w.defense.guardHeld).toBe(false);expect(w.motion).toBeUndefined();const generation=w.generation;w.reset();w.advance(.1);expect(w.blue.hp).toBe(100);expect(w.generation).toBe(generation+1);expect(w.hazards).toEqual([]);});
});
