import {describe,it,expect} from 'vitest';
import {LabWorld} from '../../src/action-lab/runtime/world';
const lab=()=>{const w=new LabWorld();w.enemy.enabled=false;return w;};
describe('AL01 M2 attack / defense resource loop',()=>{
 it('accepted dodge spends once, owns motion independently and does not advance basic chain',()=>{const w=lab();w.press();w.release();w.advance(.04);const stage=w.nextStage;w.aim={x:-1,y:0};w.dodge();w.advance(.01);expect(w.resources.dashCharges).toBe(1);expect(w.blue.action?.kind).toBe('dash-strike');expect(w.nextStage).toBe(stage);w.advance(.14);expect(w.defense.invulnerable(w.simTime)).toBe(false);expect(w.log.filter((e)=>e.eventKind==='accepted'&&e.result==='dash-strike')).toHaveLength(1);});
 it('dead dodge rejects without spending or creating a new action',()=>{const w=lab();w.blue.hp=0;w.dodge();expect(w.resources.dashCharges).toBe(2);expect(w.blue.action).toBeUndefined();});
 it('front guard blocks real enemy damage and spends frost only on contact',()=>{const w=new LabWorld();w.reset(true);w.enemy.cooldown=0;w.shield(true);w.advance(.7);expect(w.blue.hp).toBe(100);expect(w.resources.frost).toBe(2);expect(w.log.some((e)=>e.eventKind==='block')).toBe(true);});
 it('back guard fails with actual HP loss and no frost spending',()=>{const w=new LabWorld();w.reset(true);w.enemy.cooldown=0;w.aim={x:-1,y:0};w.shield(true);w.advance(.7);expect(w.blue.hp).toBe(95);expect(w.resources.frost).toBe(3);expect(w.log.some((e)=>e.eventKind==='block-failed')).toBe(true);});
 it('active root cancellation before Attack costs nothing; whiff Attack spends charge without frost return',()=>{const w=lab();w.prepareActive();w.advance(.1);w.cancelUpper();expect(w.resources.activeCharge).toBe(1);w.prepareActive();w.advance(.2);w.releaseActive();w.advance(.3);expect(w.resources.activeCharge).toBe(0);expect(w.resources.activeCooldown).toBeGreaterThan(7);expect(w.resources.frost).toBe(3);expect(w.log.some((e)=>e.eventKind==='active-payment')).toBe(true);});
 it('energy growth restores caster frost once on a real charge contact, independently of payment',()=>{const w=lab();w.reset(true);w.enemy.enabled=false;w.resetBuild(true,true);w.enemy.enabled=false;w.resources.spendBlock(w.simTime);w.resources.spendBlock(w.simTime);w.resources.spendBlock(w.simTime);w.prepareActive();w.advance(.2);w.releaseActive();w.advance(.5);expect(w.enemy.hp).toBe(35);expect(w.resources.frost).toBe(2);expect(w.resources.activeCharge).toBe(0);const payment=w.log.find((e)=>e.eventKind==='active-payment'),refund=w.log.find((e)=>e.eventKind==='frost-return');expect(payment).toBeDefined();expect(refund?.actorId).toBe('blue');expect(refund?.simTime).toBeGreaterThan(payment?.simTime??Infinity);});
 it('pause freezes recovery and removes held guard, prepared casts and invulnerability; reset restores all pools',()=>{const w=lab();w.dodge();w.advance(.02);w.pause(true);const t=w.simTime;w.advance(5);expect(w.simTime).toBe(t);expect(w.defense.invulnerable(w.simTime)).toBe(false);w.reset();expect(w.resources.activeCharge).toBe(1);expect(w.resources.dashCharges).toBe(2);expect(w.resources.frost).toBe(3);});
 it('low frame and fine stepping cross payment and child events once with the same real damage',()=>{const a=lab(),b=lab();for(const w of [a,b]){w.resetBuild(true,true);w.enemy.enabled=false;w.prepareActive();w.advance(.2);w.releaseActive();}a.advance(.7);for(let i=0;i<84;i++)b.advance(1/120);expect(a.resources.activeCharge).toBe(0);expect(a.enemy.hp).toBe(b.enemy.hp);expect(a.log.filter((e)=>e.eventKind==='active-payment')).toHaveLength(1);});
});
