import {XX_PROFILE} from '../core/xx-profile';
import type {Unit,GameState} from '../core/types';
export let xxPortrait='';
let runtimePromise:Promise<any>|undefined;
// An ES module-local vendor binding never writes window.spine, even during concurrent loads.
export function xxRuntime(){return runtimePromise??=(async()=>{const response=await fetch('/__al01-assets/vendor/spine-canvas-4.3.13.js');if(!response.ok)throw new Error('xx missing Spine 4.3.13 runtime');const url=URL.createObjectURL(new Blob([await response.text(),'\nexport default spine;'],{type:'text/javascript'}));try{return (await import(/* @vite-ignore */url)).default;}finally{URL.revokeObjectURL(url);}})();}
export class XXVisual {
 readonly canvas=document.createElement('canvas');ready=false;portrait='';pose='';time=0;names:string[]=[];
 private skeleton:any;private animation:any;private renderer:any;private scale=1;private floor=0;private center=0;private key='';private started=0;
 private constructor(private s:any,readonly data:any){this.canvas.width=this.canvas.height=512;this.skeleton=new s.Skeleton(data);this.animation=new s.AnimationState(new s.AnimationStateData(data));this.renderer=new s.SkeletonRenderer(this.canvas.getContext('2d'));this.renderer.triangleRendering=true;this.names=data.animations.map((a:any)=>a.name);}
 static async load(){const s=await xxRuntime(),base='/__al01-assets/xx/';const [ar,jr]=await Promise.all([fetch(base+'rozeul.atlas'),fetch(base+'rozeul.json')]);if(!ar.ok||!jr.ok)throw new Error('xx missing rozeul.atlas / rozeul.json');const json=await jr.json();if(!json.skeleton.spine.startsWith('4.3.'))throw new Error('xx skeleton requires Spine 4.3');const image=await new Promise<HTMLImageElement>((ok,bad)=>{const i=new Image();i.onload=()=>ok(i);i.onerror=()=>bad(new Error('xx missing rozeul.png'));i.src=base+'rozeul.png';});const atlas=new s.TextureAtlas(await ar.text());for(const page of atlas.pages){if(page.name!=='rozeul.png')throw new Error('xx unknown atlas page '+page.name);page.setTexture(new s.CanvasTexture(image));}const d=new s.SkeletonJson(new s.AtlasAttachmentLoader(atlas)).readSkeletonData(json),v=new XXVisual(s,d);v.sample(XX_PROFILE.animations.idle,0);const offset=new s.Vector2(),size=new s.Vector2();v.skeleton.getBounds(offset,size,[]);v.scale=360/size.y;v.floor=offset.y;v.center=offset.x+size.x/2;v.sample(XX_PROFILE.animations.idle,0);v.portrait=v.canvas.toDataURL();xxPortrait=v.portrait;v.ready=true;return v;}
 sample(pose:string,time:number,facing=1){if(!this.names.includes(pose))throw new Error('xx unknown animation '+pose);if(pose!==this.pose){this.animation.clearTracks();this.animation.setAnimation(0,pose,false);this.pose=pose;}this.time=time;this.skeleton.setupPose();this.animation.getTrack(0).trackTime=time;this.animation.apply(this.skeleton);this.skeleton.updateWorldTransform(this.s.Physics.none);const c=this.canvas.getContext('2d')!;c.setTransform(1,0,0,1,0,0);c.clearRect(0,0,512,512);c.translate(256,450);c.scale(this.scale*(facing<0?-1:1),-this.scale);c.translate(-this.center,-this.floor);this.renderer.draw(this.skeleton);}
 draw(u:Unit,s:GameState,moving:boolean){const x=u.xxCombat,a=x?.action,pose=u.life!=='active'?XX_PROFILE.animations.death:s.time<(x?.hurtUntil??0)?XX_PROFILE.animations.hurt:a?.pose??(moving?XX_PROFILE.animations.move:XX_PROFILE.animations.idle);const key=pose+'/'+(a?.context?.actionId??'');if(this.key!==key){this.started=s.time;this.key=key;}const duration=this.data.findAnimation(pose).duration;this.sample(pose,a?.elapsed??(pose===XX_PROFILE.animations.idle||pose===XX_PROFILE.animations.move?(s.time-this.started)%duration:Math.min(duration,s.time-this.started)),Math.cos(a?.facing??u.heading??0)<0?-1:1);}
 dispose(){this.animation.clearTracks();this.canvas.width=this.canvas.height=0;this.ready=false;}
}
