using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using UnityEngine;
using UnityEditor;
namespace Xinghai.MapEditor.Editor {
 public static class AssetBaker {
  public static PublishedModule Bake(PublishPackage package,ReceiveOptions options){PublishReader.Require(package.manifest.kind=="asset","需要单件发布包");return WorkshopBake.Receive(package,options,false);}
 }
 internal static class WorkshopBake {
  internal static void Folders(string folder,BakeJournal journal){string cursor="Assets/Generated";foreach(string part in folder.Substring(cursor.Length).Split('/').Where(p=>p.Length>0)){cursor+="/"+part;if(!Directory.Exists(cursor)){journal.Watch(cursor);Directory.CreateDirectory(cursor);}}}
  internal static void Write(string path,byte[] bytes,BakeJournal journal){Folders(Path.GetDirectoryName(path).Replace('\\','/'),journal);journal.Watch(path);File.WriteAllBytes(path,bytes);}
  internal static T Store<T>(T obj,string path,BakeJournal journal) where T:UnityEngine.Object {journal.Watch(path);AssetDatabase.CreateAsset(obj,path);return obj;}
  static Material Material(WorkshopColor c){var shader=Shader.Find(c.doubleSided?"Xinghai/Exchange Double Sided"+(c.alphaMode=="BLEND"?" Blend":""):"Standard");PublishReader.Require(shader!=null,"需要 Built-in 材质Shader");var m=new Material(shader){name=c.colorId,color=new Color(c.baseColor_sRGB[0],c.baseColor_sRGB[1],c.baseColor_sRGB[2],c.alpha)};m.SetFloat("_Metallic",c.metallic);m.SetFloat("_Glossiness",1-c.roughness);var emission=new Color(c.emissive[0],c.emissive[1],c.emissive[2])*c.emissiveStrength;m.SetColor("_EmissionColor",emission.gamma);if(emission.maxColorComponent>0)m.EnableKeyword("_EMISSION");if(c.alphaMode=="MASK"){m.SetFloat("_Mode",1);m.SetOverrideTag("RenderType","TransparentCutout");m.EnableKeyword("_ALPHATEST_ON");m.SetFloat("_Cutoff",.5f);m.SetInt("_SrcBlend",1);m.SetInt("_DstBlend",0);m.SetInt("_ZWrite",1);m.renderQueue=2450;}else if(c.alphaMode=="BLEND"){m.SetFloat("_Mode",2);m.SetOverrideTag("RenderType","Transparent");m.EnableKeyword("_ALPHABLEND_ON");m.SetInt("_SrcBlend",5);m.SetInt("_DstBlend",10);m.SetInt("_ZWrite",0);m.renderQueue=3000;}return m;}
  static Mesh Mesh(IEnumerable<Quad> quads,RuntimeVoxel doc){var positions=new List<Vector3>();var normals=new List<Vector3>();var triangles=new List<int>();foreach(var q in quads){int[] axes=Enumerable.Range(0,3).Where(a=>a!=q.axis).ToArray();int start=positions.Count;foreach(var ab in new[]{new[]{q.a,q.b},new[]{q.a+q.w,q.b},new[]{q.a+q.w,q.b+q.h},new[]{q.a,q.b+q.h}}){float[] p={0,0,0},n={0,0,0};p[q.axis]=q.plane;p[axes[0]]=ab[0];p[axes[1]]=ab[1];n[q.axis]=q.sign;positions.Add(WorkshopCoordinates.Unity(p)*doc.voxelSize-WorkshopCoordinates.Unity(doc.anchorM));normals.Add(WorkshopCoordinates.Unity(n));}triangles.AddRange((q.sign==(q.axis==1?-1:1)?new[]{0,2,1,0,3,2}:new[]{0,1,2,0,2,3}).Select(i=>i+start));}var mesh=new Mesh{name=doc.assetId,indexFormat=UnityEngine.Rendering.IndexFormat.UInt32};mesh.SetVertices(positions);mesh.SetNormals(normals);mesh.SetTriangles(triangles,0);mesh.RecalculateBounds();return mesh;}
  static GameObject Native(PublishPackage package,PublishDependency dep,string folder,BakeJournal journal){var doc=PublishReader.Voxel(package.files[dep.unity.runtimePath]);var map=new MapDocument{mapId=doc.assetId,voxelSize=.25f,cells=doc.cells,palette=doc.palette,sideColor=doc.sideColor};var root=new GameObject(dep.assetId);try{foreach(var group in GreedyMesher.Build(map).GroupBy(q=>q.color)){string stem=folder+"/"+dep.assetId+"-"+group.Key;var mesh=Store(Mesh(group,doc),stem+".asset",journal);var material=Store(Material(doc.materialProfile.colors[group.Key]),stem+".mat",journal);var child=new GameObject("Color "+group.Key);child.transform.SetParent(root.transform,false);child.AddComponent<MeshFilter>().sharedMesh=mesh;child.AddComponent<MeshRenderer>().sharedMaterial=material;}string path=folder+"/"+dep.assetId+".prefab";journal.Watch(path);var prefab=PrefabUtility.SaveAsPrefabAsset(root,path,out bool success);PublishReader.Require(success&&prefab!=null,"模块Prefab生成失败");return prefab;}finally{UnityEngine.Object.DestroyImmediate(root);}}
  static GameObject External(PublishPackage package,PublishDependency dep,string folder,BakeJournal journal){string basePath=folder+"/"+dep.assetId;Folders(basePath,journal);var side=PublishReader.Json(package.files[dep.unity.materialsPath]);var mapping=new Dictionary<string,string>();int index=0;foreach(string source in dep.unity.texturePaths){string name="texture-"+(index++)+".png";string relative=source.Substring(Path.GetDirectoryName(dep.unity.materialsPath).Length+1);mapping.Add(relative,name);Write(basePath+"/"+name,package.files[source],journal);AssetDatabase.ImportAsset(basePath+"/"+name,ImportAssetOptions.ForceSynchronousImport);}
   foreach(var color in side["colors"]){string old=(string)color["baseColorTexturePath"];if(old!=null)color["baseColorTexturePath"]=mapping[old];}side["textureDependencies"]=new JArray(mapping.Values);Write(basePath+"/model.xhmaterials.json",System.Text.Encoding.UTF8.GetBytes(side.ToString()),journal);string fbx=basePath+"/model.fbx";Write(fbx,package.files[dep.unity.modelPath],journal);AssetDatabase.ImportAsset(fbx,ImportAssetOptions.ForceSynchronousImport|ImportAssetOptions.ForceUpdate);var imported=AssetDatabase.LoadAssetAtPath<GameObject>(fbx);PublishReader.Require(imported!=null,"FBX导入失败");var root=new GameObject(dep.assetId);try{var child=(GameObject)PrefabUtility.InstantiatePrefab(imported);var rotation=child.transform.localRotation;child.transform.SetParent(root.transform,false);child.transform.localPosition=-WorkshopCoordinates.Unity(dep.anchorM);child.transform.localRotation=Quaternion.Euler(0,180,0)*rotation;string output=basePath+"/Module.prefab";journal.Watch(output);var prefab=PrefabUtility.SaveAsPrefabAsset(root,output,out bool success);PublishReader.Require(success&&prefab!=null,"外部模块Prefab生成失败");return prefab;}finally{UnityEngine.Object.DestroyImmediate(root);}}
  static Dictionary<string,string> Fingerprints(string folder){var result=new Dictionary<string,string>(StringComparer.Ordinal);foreach(string file in Directory.GetFiles(folder,"*",SearchOption.AllDirectories).OrderBy(p=>p,StringComparer.Ordinal)){string relative=file.Substring(folder.Length+1).Replace('\\','/');if(relative!="receipt.json"&&relative!="receipt.json.meta")result.Add(relative,PublishReader.Hash(File.ReadAllBytes(file)));}return result;}
  static void AssertClean(string directory,IEnumerable<string> paths){foreach(string relative in paths.Where(p=>!p.StartsWith("Frozen~/",StringComparison.Ordinal)&&!p.EndsWith(".meta",StringComparison.Ordinal))){string path=directory+"/"+relative;foreach(var obj in AssetDatabase.LoadAllAssetsAtPath(path)){if(obj==null)continue;PublishReader.Require(!EditorUtility.IsDirty(obj),"生成物存在未保存的手改："+path);if(obj is GameObject root)foreach(var component in root.GetComponentsInChildren<Component>(true))PublishReader.Require(component!=null&&!EditorUtility.IsDirty(component)&&!EditorUtility.IsDirty(component.gameObject),"生成Prefab存在未保存的手改："+path);}var importer=AssetImporter.GetAtPath(path);PublishReader.Require(importer==null||!EditorUtility.IsDirty(importer),"生成物导入配置存在未保存的手改："+path);}}
  internal static void AssertReceipt(PublishedModule received){PublishReader.Require(received!=null&&received.prefab!=null&&AssetDatabase.GetAssetPath(received.prefab)==received.directory+"/Scene.prefab","候选必须是正式场景接收物");string report=received.directory+"/receipt.json";var json=PublishReader.Json(File.ReadAllBytes(report));var expected=json["files"].ToObject<Dictionary<string,string>>();var actual=Fingerprints(received.directory);AssertClean(received.directory,actual.Keys);PublishReader.Require(expected.Count==actual.Count&&expected.All(p=>actual.TryGetValue(p.Key,out var value)&&p.Value==value),"候选生成物已修改或缺失");}
  internal static PublishedModule Receive(PublishPackage package,ReceiveOptions options,bool scene){BakeJournal.Recover();PublishReader.Require(options!=null&&PublishReader.Id(options.receiptId)&&PublishReader.Id(package.manifest.publishId),"接收身份无效");var m=package.manifest;PublishReader.Require(PublishReader.Hash(System.Text.Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(m)))==package.manifestCanonicalHash,"冻结manifest被修改");string directory="Assets/Generated/Workshop/"+m.publishId+"/"+options.receiptId;PublishReader.Safe(Path.GetFullPath("Assets/Generated"),"Workshop/"+m.publishId+"/"+options.receiptId+"/receipt.json");string report=directory+"/receipt.json",prefabPath=directory+(scene?"/Scene.prefab":"/Module.prefab");foreach(var f in m.payloadFiles.Concat(m.outputFiles))PublishReader.Require(package.files.TryGetValue(f.path,out var bytes)&&bytes.LongLength==f.byteLength&&PublishReader.Hash(bytes)==f.sha256,"冻结内存负载被修改");
   if(File.Exists(report)){var previous=PublishReader.Json(File.ReadAllBytes(report));PublishReader.Require((string)previous["manifestHash"]==package.manifestHash,"接收身份已经绑定另一冻结包，请新建接收副本");var expected=previous["files"].ToObject<Dictionary<string,string>>();var actual=Fingerprints(directory);AssertClean(directory,actual.Keys);PublishReader.Require(expected.Count==actual.Count&&expected.All(p=>actual.TryGetValue(p.Key,out var value)&&value==p.Value),"生成物已手改或缺失，请新建接收副本");var prefab=AssetDatabase.LoadAssetAtPath<GameObject>(prefabPath);PublishReader.Require(prefab!=null,"生成Prefab缺失");return Result(scene,m,options,directory,prefab,(string)previous["outputFingerprint"]);}
   PublishReader.Require(!Directory.Exists(directory)||Directory.GetFileSystemEntries(directory).Length==0,"未登记生成物目录冲突，请新建接收副本");using(var journal=new BakeJournal()){Folders(directory,journal);string frozen=directory+"/Frozen~";foreach(var pair in package.files)Write(frozen+"/"+pair.Key,pair.Value,journal);Write(frozen+"/manifest.json",System.Text.Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(m)),journal);string assetsFolder=directory+"/Assets";Folders(assetsFolder,journal);AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);var modules=new Dictionary<string,GameObject>();var textures=new Dictionary<string,Texture2D>();foreach(var dep in m.dependencies){if(dep.kind=="voxel")modules.Add(dep.assetId,Native(package,dep,assetsFolder,journal));else if(dep.kind=="external")modules.Add(dep.assetId,External(package,dep,assetsFolder,journal));else {string png=assetsFolder+"/"+dep.assetId+".png";Write(png,package.files[dep.unity.imagePath],journal);AssetDatabase.ImportAsset(png,ImportAssetOptions.ForceSynchronousImport);var texture=AssetDatabase.LoadAssetAtPath<Texture2D>(png);PublishReader.Require(texture!=null,"PNG导入失败");textures.Add(dep.assetId,texture);}}
    var root=scene?SceneBaker.Build(package,modules,textures,assetsFolder,journal):(GameObject)PrefabUtility.InstantiatePrefab(modules[m.targetId]);try{root.name=m.targetId;var identity=root.AddComponent<PublishedVisual>();identity.publishId=m.publishId;identity.receiptId=options.receiptId;identity.manifestHash=package.manifestHash;journal.Watch(prefabPath);var prefab=PrefabUtility.SaveAsPrefabAsset(root,prefabPath,out bool success);PublishReader.Require(success&&prefab!=null,"发布Prefab生成失败");AssetDatabase.SaveAssets();AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);var fingerprint=Fingerprints(directory);string hash=PublishReader.Hash(System.Text.Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(fingerprint)));Write(report,System.Text.Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(new{schema="xinghai-workshop-receipt-1",manifestHash=package.manifestHash,outputFingerprint=hash,files=fingerprint},Formatting.Indented)),journal);journal.Commit();return Result(scene,m,options,directory,prefab,hash);}finally{UnityEngine.Object.DestroyImmediate(root);}}
  }
  static PublishedModule Result(bool scene,PublishManifest m,ReceiveOptions options,string directory,GameObject prefab,string hash){PublishedModule result=scene?new PublishedScene():new PublishedModule();result.publishId=m.publishId;result.receiptId=options.receiptId;result.directory=directory;result.prefab=prefab;result.outputFingerprint=hash;return result;}
 }
}
