using System;
using System.IO;
using System.Linq;
using Newtonsoft.Json.Linq;
using UnityEngine;
using UnityEditor;
using UnityEditor.SceneManagement;
namespace Xinghai.MapEditor.Editor {
 public static class WorkshopWorkflowProof {
  public static void Run(){GameObject wrapper=null;try{EditorSceneManager.NewScene(NewSceneSetup.EmptyScene);var info=JObject.Parse(File.ReadAllText("../workshop-task9/workflow-ui-result.json"));string id=(string)info["floorAssetId"],receipt=(string)info["sceneId"];var a=SceneBaker.Bake(PublishReader.Read("../workshop-task9/workflow-project/releases/workflow-a/manifest.json"),new ReceiveOptions{receiptId=receipt});var b=SceneBaker.Bake(PublishReader.Read("../workshop-task9/workflow-project/releases/workflow-b/manifest.json"),new ReceiveOptions{receiptId=receipt});WorkshopPublishProof.Check(a.prefab.GetComponentsInChildren<PublishedInstance>().Length==10&&b.prefab.GetComponentsInChildren<PublishedInstance>().Length==10,"Workflow instances lost");string guid=AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(a.prefab));var again=SceneBaker.Bake(PublishReader.Read("../workshop-task9/workflow-project/releases/workflow-a/manifest.json"),new ReceiveOptions{receiptId=receipt});WorkshopPublishProof.Check(AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(again.prefab))==guid,"Same workflow receipt GUID changed");
   wrapper=new GameObject("墓室 · 用户包装");var state=wrapper.AddComponent<WrapperState>();state.publishId=a.publishId;state.receiptId=a.receiptId;state.visualRoot=(GameObject)PrefabUtility.InstantiatePrefab(a.prefab);state.visualRoot.transform.SetParent(wrapper.transform,false);var old=state.visualRoot.GetComponentsInChildren<PublishedInstance>().First(i=>i.assetId==id);float[] position=(float[])old.sourcePositionM.Clone();position[0]+=.25f;state.overrides=new[]{new InstanceOverride{instanceId=old.instanceId,sourcePositionM=position,rotationDeg=90}};old.transform.localPosition=WorkshopCoordinates.Unity(position);old.transform.localRotation=Quaternion.Euler(0,-90,0);var own=new GameObject("手工碰撞与脚本");own.transform.SetParent(wrapper.transform,false);own.AddComponent<BoxCollider>();own.AddComponent<WorkshopUserMarker>().target=old.gameObject;
   string folder="Assets/WorkshopWorkflowProof";Directory.CreateDirectory(folder);AssetDatabase.Refresh();string original=folder+"/A-"+receipt+".prefab",destination=folder+"/B-"+receipt+".prefab";PrefabUtility.SaveAsPrefabAsset(wrapper,original);byte[] before=File.ReadAllBytes(original);var preview=WrapperUpgrade.Preview(wrapper,b);WorkshopPublishProof.Check(preview.canUpgrade,string.Join(";",preview.conflicts));var copy=WrapperUpgrade.CreateCopy(wrapper,b,destination);var moved=copy.GetComponentInChildren<WorkshopUserMarker>().target.GetComponent<PublishedInstance>();WorkshopPublishProof.Check(moved.instanceId==old.instanceId&&moved.transform.localPosition==WorkshopCoordinates.Unity(position)&&Quaternion.Angle(moved.transform.localRotation,Quaternion.Euler(0,-90,0))<.001f,"Workflow wrapper override/reference lost");WorkshopPublishProof.Check(copy.GetComponentsInChildren<BoxCollider>().Length==1&&before.SequenceEqual(File.ReadAllBytes(original)),"Workflow manual objects/original changed");
   wrapper.SetActive(false);var visual=(GameObject)PrefabUtility.InstantiatePrefab(b.prefab);var light=new GameObject("Proof light").AddComponent<Light>();light.type=LightType.Directional;light.transform.rotation=Quaternion.Euler(45,35,0);RenderSettings.ambientLight=new Color(.6f,.6f,.6f);var camera=new GameObject("Proof camera").AddComponent<Camera>();camera.orthographic=true;camera.orthographicSize=2.5f;camera.backgroundColor=new Color(.05f,.07f,.09f);camera.clearFlags=CameraClearFlags.SolidColor;camera.transform.position=new Vector3(4,5,-5);camera.transform.LookAt(new Vector3(0,.5f,0));var target=new RenderTexture(1440,900,24);camera.targetTexture=target;camera.Render();RenderTexture.active=target;var png=new Texture2D(1440,900,TextureFormat.RGB24,false);png.ReadPixels(new Rect(0,0,1440,900),0,0);png.Apply();File.WriteAllBytes("../workshop-task9/unity-tomb.png",png.EncodeToPNG());RenderTexture.active=null;camera.targetTexture=null;target.Release();UnityEngine.Object.DestroyImmediate(target);UnityEngine.Object.DestroyImmediate(png);
   File.WriteAllText("../workshop-task9/unity-workflow-proof.json",new JObject{["passed"]=true,["instances"]=10,["moduleGuid"]=guid,["receiptId"]=receipt,["wrapperOriginal"]=original,["wrapperCopy"]=destination,["sourcePublishA"]=a.directory,["sourcePublishB"]=b.directory,["version"]=Application.unityVersion}.ToString());Debug.Log("XH_WORKSHOP_WORKFLOW_PASS");EditorApplication.Exit(0);
  }catch(Exception e){Debug.LogException(e);EditorApplication.Exit(1);}finally{if(wrapper!=null)UnityEngine.Object.DestroyImmediate(wrapper);}}
 }
}
