import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
test('pause stops queued accepted-action sounds before the next visual frame',async({page})=>{
 await page.addInitScript(()=>{const native=requestAnimationFrame;const start=AudioBufferSourceNode.prototype.start;const probe={freeze:false,pending:[] as FrameRequestCallback[],starts:0};(window as any).__m3Audio=probe;window.requestAnimationFrame=cb=>native(t=>{if(probe.freeze)probe.pending.push(cb);else cb(t);});AudioBufferSourceNode.prototype.start=function(...args:any[]){probe.starts++;return start.apply(this,args as [number?,number?,number?]);};});
 await page.goto('/action-lab.html');await expect(page.locator('#readiness')).toHaveText('原资源就绪');await page.evaluate(()=>{(window as any).__m3Audio.freeze=true;});await page.waitForTimeout(50);await page.keyboard.press('Space');await page.waitForTimeout(50);await page.getByRole('button',{name:'暂停',exact:true}).click();
 const starts=await page.evaluate(()=>{const p=(window as any).__m3Audio;const before=p.starts;p.freeze=false;p.pending.splice(0).forEach((cb:FrameRequestCallback)=>cb(performance.now()));return p.starts-before;});expect(starts).toBe(0);await expect(page.locator('#input-state')).toHaveText('暂停');
 const count=await page.evaluate(()=>(window as any).__m3Audio.starts);await page.getByRole('button',{name:'继续',exact:true}).click();await page.waitForTimeout(100);expect(await page.evaluate(()=>(window as any).__m3Audio.starts)).toBe(count);await page.getByRole('button',{name:'重置',exact:true}).click();const box=(await page.locator('#arena').boundingBox())!;await page.mouse.click(box.x+box.width*.7,box.y+box.height*.5);await expect.poll(()=>page.evaluate(()=>(window as any).__m3Audio.starts)).toBeGreaterThan(count);
});

test('normal combined actions retain ownership through victory, blur and repeated resets',async({page})=>{
 test.setTimeout(30000);await page.goto('/action-lab.html');await expect(page.locator('#readiness')).toHaveText('原资源就绪');await page.selectOption('#build','energy');const b=(await page.locator('#arena').boundingBox())!;
 await page.mouse.move(b.x+b.width*.7,b.y+b.height*.5);await page.mouse.click(b.x+b.width*.7,b.y+b.height*.5);await page.waitForTimeout(60);await page.keyboard.press('Space');await expect(page.locator('#dash-resource')).toContainText('1 / 2');await page.waitForTimeout(400);
 await page.mouse.move(b.x+b.width*.1,b.y+b.height*.5);await page.mouse.down({button:'right'});await expect(page.locator('#feedback')).toContainText('格挡成功',{timeout:8000});await page.mouse.up({button:'right'});await page.keyboard.down('KeyQ');await page.waitForTimeout(200);await page.keyboard.up('KeyQ');await expect(page.locator('#feedback')).toContainText('霜寒回复',{timeout:5000});
 await page.waitForTimeout(700);await page.mouse.move(b.x+b.width*.8,b.y+b.height*.5);await page.mouse.down();await expect(page.locator('#enemy-hp')).toHaveText('0 / 110',{timeout:5000});await page.mouse.up();
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'导出本轮事件 JSON'}).click();await(await pending).saveAs('../work/AL-01/M3/combined-round.json');await page.screenshot({path:'../work/AL-01/M3/combined-victory.png'});
 const round=JSON.parse(await readFile('../work/AL-01/M3/combined-round.json','utf-8'));const payment=round.events.find((e:any)=>e.eventKind==='active-payment');const refund=round.events.find((e:any)=>e.eventKind==='frost-return');expect(payment.resourceDelta).toBe(-1);expect(refund.actorId).toBe('blue');expect(refund.parentActionId).toBe(payment.actionInstanceId);expect(refund.rootActionId).toBe(payment.rootActionId);expect(refund.simTime).toBeGreaterThan(payment.simTime);expect(round.events.filter((e:any)=>e.eventKind==='frost-return')).toHaveLength(1);expect(round.events.some((e:any)=>e.eventKind==='death'&&e.actorId==='zombie')).toBe(true);
 for(let i=0;i<3;i++){await page.getByRole('button',{name:'重置',exact:true}).click();await expect(page.locator('#blue-hp')).toHaveText('100 / 100');await expect(page.locator('#dash-resource')).toContainText('2 / 2');await expect(page.locator('#active-resource')).toContainText('1 / 1');}
 await page.keyboard.down('KeyQ');await expect(page.locator('#combo')).toContainText('准备');await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await page.keyboard.up('KeyQ');await expect(page.locator('#input-state')).toHaveText('暂停');await expect(page.locator('#active-resource')).toContainText('1 / 1');await page.getByRole('button',{name:'继续',exact:true}).click();await page.waitForTimeout(400);await expect(page.locator('#combo')).not.toContainText('准备');await expect(page.locator('#active-resource')).toContainText('1 / 1');
});
