import {test,expect,type Page} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
const snap=(p:Page)=>p.evaluate(()=>(window as any).AL03Snapshot());
async function start(page:Page,mode='melee'){await page.goto('/action-lab.html');await expect(page.locator('#readiness')).toHaveText('原资源就绪');await page.locator('#player').selectOption('cannoneer');await expect(page.locator('#player-readiness')).toContainText('原魔弹射手骨架就绪');if(mode!=='melee')await page.locator('#encounter').selectOption(mode);}
async function pointer(page:Page,x:number,y=0){const b=(await page.locator('#arena').boundingBox())!,scale=Math.min(b.width/16,b.height/9);await page.mouse.move(b.x+b.width/2+x*scale,b.y+b.height/2-y*scale);}
async function record(page:Page,name:string){await mkdir('../work/AL-04/browser',{recursive:true});await writeFile(`../work/AL-04/browser/${name}.json`,JSON.stringify(await snap(page),null,2));await page.screenshot({path:`../work/AL-04/browser/${name}.png`});}
test('AL04 A native selection, actual Basic contact and distinct resource HUD',async({page})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await start(page);await expect(page.locator('#blue-hp')).toHaveText('40 / 40');await expect(page.locator('#yellow-unit')).toBeVisible();await page.locator('#close').click();await pointer(page,3);await page.mouse.down();await page.waitForTimeout(130);await page.mouse.up();await expect(page.locator('#enemy-hp')).not.toHaveText('110 / 110');expect((await snap(page)).events.some((e:any)=>e.eventKind==='damage'&&e.actorId==='yellow')).toBe(true);expect(errors).toEqual([]);await record(page,'A-basic');});
test('AL04 B real held three-stage sequence, whiff and Reset',async({page})=>{await start(page);await page.locator('#close').click();await pointer(page,3);await page.mouse.down();await page.waitForFunction(()=>new Set((window as any).AL03Snapshot().events.filter((e:any)=>e.eventKind==='attack-event').map((e:any)=>e.executedSkillId)).size>=3);await page.mouse.up();await record(page,'B-held');await page.locator('#reset').click();await pointer(page,-6);await page.mouse.down();await page.mouse.up();await page.waitForTimeout(200);expect((await snap(page)).enemies[0].hp).toBe(110);});
test('AL04 C RMB shots spend ammo at Hit and independently reload',async({page})=>{await start(page);await pointer(page,4);await page.mouse.down({button:'right'});await page.waitForFunction(()=>(window as any).AL03Snapshot().events.filter((e:any)=>e.eventKind==='resource-payment').length>=4);await page.mouse.up({button:'right'});await page.waitForFunction(()=>(window as any).AL03Snapshot().events.some((e:any)=>e.eventKind==='reload-complete'));const s=await snap(page);expect(s.events.filter((e:any)=>e.eventKind==='resource-payment').length).toBe(4);expect(s.resources[0].value).toBe('4 / 4');expect(s.events.some((e:any)=>e.eventKind==='block')).toBe(false);await record(page,'C-ammo');});
test('AL04 D mobility is a nonattacking roll with separate cooldown',async({page})=>{await start(page);await page.locator('#speed').selectOption('.25');await pointer(page,-5);await page.keyboard.press('Space');await page.waitForTimeout(300);const s=await snap(page);expect(s.blue.x).toBeLessThan(-2);expect(s.events.some((e:any)=>e.eventKind==='dodge'&&e.actorId==='yellow')).toBe(true);expect(s.events.some((e:any)=>e.eventKind==='attack-event')).toBe(false);await record(page,'D-roll');});
test('AL04 E Q native rocket follows transport and lands a causal explosion',async({page})=>{await start(page);await pointer(page,1);await page.keyboard.press('KeyQ');await page.waitForFunction(()=>(window as any).AL03Snapshot().projectiles.some((p:any)=>p.ownerId==='yellow'));await record(page,'E-flight');await page.waitForFunction(()=>(window as any).AL03Snapshot().events.some((e:any)=>e.eventKind==='explosion-created'&&e.actorId==='yellow'));const s=await snap(page),boom=s.events.find((e:any)=>e.eventKind==='explosion-created'&&e.actorId==='yellow');expect(s.blue.x).toBeGreaterThan(-2);expect(boom.executedSkillId).toBe('火箭弹射爆炸');expect(boom.parentActionId).not.toBeNull();expect(boom.rootActionId).not.toBe(boom.actionInstanceId);await record(page,'E-land');});
test('AL04 F cancel and safe character selection retire active transport and held input',async({page})=>{await start(page);await page.locator('#speed').selectOption('.25');await pointer(page,2);await page.keyboard.press('KeyQ');await page.waitForFunction(()=>(window as any).AL03Snapshot().projectiles.some((p:any)=>p.ownerId==='yellow'));await page.keyboard.press('Escape');await page.waitForTimeout(1800);let s=await snap(page);expect(s.events.some((e:any)=>e.eventKind==='explosion-created'&&e.actorId==='yellow')).toBe(false);expect(s.projectiles.filter((p:any)=>p.ownerId==='yellow')).toEqual([]);const g=s.generation;await page.locator('#player').selectOption('isdara');s=await snap(page);expect(s.generation).toBe(g+1);expect(s.playerId).toBe('blue');await expect(page.locator('#blue-hp')).toHaveText('100 / 100');await expect(page.locator('#build')).toBeEnabled();await record(page,'F-return');});
test('AL04 G ranged explosion really hurts and can kill the new character',async({page})=>{test.setTimeout(65000);await start(page,'ranged');await expect(page.locator('#blue-hp')).not.toHaveText('40 / 40',{timeout:6000});await expect(page.locator('#outcome')).toContainText('倒下',{timeout:55000});expect((await snap(page)).events.some((e:any)=>e.eventKind==='death'&&e.actorId==='yellow')).toBe(true);await record(page,'G-death');});
test('AL04 H missing new asset disables only that character and old version remains playable',async({page})=>{await page.route('**/__al01-assets/yellow/unit.json',r=>r.fulfill({status:404,body:'missing'}));await page.goto('/action-lab.html');await expect(page.locator('#readiness')).toHaveText('原资源就绪');await page.locator('#player').selectOption('cannoneer');await expect(page.locator('#player-readiness')).toContainText('小蓝仍可玩');expect((await snap(page)).playerId).toBe('blue');await page.locator('#close').click();await pointer(page,3);await page.mouse.down();await page.waitForTimeout(200);await page.mouse.up();await expect(page.locator('#enemy-hp')).not.toHaveText('110 / 110');});
test('AL04 mixed normal Q, aimed shot and Basic resolve two distinct enemy identities',async({page})=>{await start(page,'mixed');await page.locator('#close').click();await pointer(page,1.3);await page.keyboard.press('KeyQ');await page.waitForFunction(()=>(window as any).AL03Snapshot().events.some((e:any)=>e.eventKind==='explosion-created'&&e.actorId==='yellow'));await page.waitForTimeout(100);let s=await snap(page),r=s.enemies.find((e:any)=>e.id==='ranged-1');await pointer(page,r.x,r.y);await page.mouse.down({button:'right'});await page.waitForTimeout(550);await page.mouse.up({button:'right'});s=await snap(page);const z=s.enemies.find((e:any)=>e.id==='zombie');await pointer(page,z.x,z.y);await page.mouse.down();await page.waitForFunction(()=>(window as any).AL03Snapshot().enemies.every((e:any)=>e.hp===0));await page.mouse.up();s=await snap(page);expect(new Set(s.events.filter((e:any)=>e.eventKind==='damage'&&e.actorId==='yellow').map((e:any)=>e.targetId))).toEqual(new Set(['zombie','ranged-1']));await record(page,'mixed-victory');});
test('AL04 ranged mobility has a real invulnerable explosion contact',async({page})=>{await start(page,'ranged');await page.locator('#speed').selectOption('.25');await page.waitForFunction(()=>(window as any).AL03Snapshot().projectiles.length===3);const s=await snap(page),p=s.projectiles[0];await pointer(page,p.landing.x,p.landing.y);await page.waitForFunction(()=>{const s=(window as any).AL03Snapshot();return s.projectiles.length&&s.projectiles[0].expiresAt-s.simTime<.018;});await page.keyboard.press('Space');await page.waitForFunction(()=>(window as any).AL03Snapshot().events.some((e:any)=>e.eventKind==='explosion-created'));expect((await snap(page)).events.some((e:any)=>e.eventKind==='evade'&&e.actorId==='yellow'&&e.projectileId)).toBe(true);await record(page,'ranged-roll-contact');});
test('AL04 ordinary WASD avoids the admitted ranged landing without a defense action',async({page})=>{await start(page,'ranged');await page.waitForFunction(()=>(window as any).AL03Snapshot().projectiles.length===3);await page.keyboard.down('KeyW');await page.waitForTimeout(600);await page.keyboard.up('KeyW');await page.waitForFunction(()=>(window as any).AL03Snapshot().events.some((e:any)=>e.eventKind==='explosion-created'));expect((await snap(page)).blue.hp).toBe(40);expect((await snap(page)).events.some((e:any)=>e.eventKind==='dodge')).toBe(false);await record(page,'ranged-walk');});
