import {beforeEach,vi} from 'vitest';
import * as definitions from '../src/core/basic-definition';
const currentResolver=definitions.resolveBasicDefinition;
// Frozen AR02/AR03 contract regression explicitly exercises the retained legacy definition.
beforeEach(()=>{vi.spyOn(definitions,'resolveBasicDefinition').mockImplementation(u=>{const d=currentResolver(u);return d.id==='hunter-basic-v1'?definitions.BASIC_DEFINITIONS['legacy-main-basic']:d;});});
import {test,expect} from 'vitest';
import {existsSync} from 'node:fs';
import {setup} from './ar03-fixture';
import {command,step} from '../src/core/engine';
import {requestBasic} from '../src/core/basic-chain';
import {combatTraceSnapshot} from '../src/core/combat-identity';
import {resolveHit} from '../src/core/engine';
import {startBasicAction} from '../src/core/basic-runtime';
import {BASIC_DEFINITIONS,nextBasicStage} from '../src/core/basic-definition';
const start=()=>{const a=setup('loop',742);expect(command(a.s,{type:'basic',id:a.h.id,aim:a.e.pos,requestId:1}).ok).toBe(true);return a;};
test('accepted party Basic owns a single runtime and one AR02 identity',()=>{const {s,h}=start();expect(h.basicAction).toBeDefined();expect(h.basicAction?.combatContext).toBe(h.attackPending?.combatContext);expect(combatTraceSnapshot(s).filter(r=>r.type==='action-started'&&r.context?.actorId===h.id)).toHaveLength(1);});
test('legacy contract profiles share one immutable two-stage definition; custom definitions permit topology without duplicating legacy',async()=>{
 expect(existsSync(new URL('../src/core/basic-definition.ts',import.meta.url))).toBe(true);
 const {resolveBasicDefinition,BASIC_DEFINITIONS,BASIC_DEFINITION_IDS}=await import('../src/core/basic-definition');const {h}=setup('loop',19);
 for(const profession of ['hunter','guard','shieldguard','healer','cantor','ranger','scythe'] as const){h.weapons[0].profession=profession;expect(resolveBasicDefinition(h)).toBe(BASIC_DEFINITIONS['legacy-main-basic']);}
 expect(new Set(Object.values(BASIC_DEFINITION_IDS))).toEqual(new Set(['legacy-main-basic','hunter-basic-v1']));expect(Object.isFrozen(resolveBasicDefinition(h))).toBe(true);expect(resolveBasicDefinition(h).stages).toHaveLength(2);
});
test('runtime has cached distinct move-ready and attack-ready; finish waits for shared legacy recovery',()=>{const {s,h}=start();for(let i=0;i<6;i++)step(s,.05);expect(h.basicAction).toBeDefined();expect(h.basicAction?.released).toBe(true);expect(h.basicAction?.moveReady).toBe(true);expect(h.basicAction?.attackReady).toBe(false);expect(h.attackPending).toBeUndefined();const before=s.stats.basicStagesStarted;expect(command(s,{type:'basic',id:h.id,aim:{x:16,y:10},requestId:2}).ok).toBe(false);expect(s.stats.basicStagesStarted).toBe(before);for(let i=0;i<12;i++)step(s,.05);expect(h.basicAction).toBeUndefined();expect(combatTraceSnapshot(s).filter(r=>r.type==='action-finished'&&r.context?.kind==='basic'&&r.context.actorId===h.id)).toHaveLength(1);});
test.each(['move','direct','blink'] as const)('%s cancels accepted windup once without release or recovery refund',kind=>{const {s,h}=start();const timer=h.attackTimer;const result=kind==='move'?command(s,{type:'move',id:h.id,to:{x:15,y:12}}):command(s,{type:kind,id:h.id,direction:{x:0,y:1}});expect(result.ok).toBe(true);expect(h.basicAction).toBeUndefined();expect(h.attackTimer).toBe(timer);expect(combatTraceSnapshot(s).filter(r=>r.type==='action-cancelled'&&r.context?.kind==='basic')).toHaveLength(1);expect(combatTraceSnapshot(s).filter(r=>r.type==='attack-released')).toHaveLength(0);});
test('control switch preserves runtime and requester; companion and order requests use the same shape',()=>{const {s,h,p,e}=start();const runtime=h.basicAction;expect(runtime).toBeDefined();command(s,{type:'controlBody',id:p.id});expect(h.basicAction).toBe(runtime);for(let i=0;i<6;i++)step(s,.05);expect(combatTraceSnapshot(s).some(r=>r.type==='attack-released'&&r.context?.actorId===h.id&&r.context.requestSource==='player-input')).toBe(true);for(const source of ['companion-ai','order-auto'] as const){const a=setup('ai',19);expect(requestBasic(a.s,a.h,a.e.pos,123,source).ok).toBe(true);expect(a.h.basicAction?.requestSource).toBe(source);expect(a.h.basicAction?.definitionId).toBe('legacy-main-basic');}});
test('buffer has no runtime identity until true consumption and next stage remains cyclic',()=>{const {s,h,e}=start();for(let i=0;i<14;i++)step(s,.05);const first=h.basicAction;expect(first).toBeDefined();expect(command(s,{type:'basic',id:h.id,aim:e.pos,requestId:2}).ok).toBe(true);expect(h.basicAction).toBe(first);for(let i=0;i<4;i++)step(s,.05);expect(h.basicAction?.stageIndex).toBe(1);expect(h.basicAction?.combatContext?.actionId).not.toBe(first?.combatContext?.actionId);});
test('compatibility pending is not a second countdown: altered mirror cannot fire early',()=>{const {s,h}=start();expect(h.basicAction).toBeDefined();h.attackPending!.remaining=-1;step(s,.05);expect(h.basicAction?.released).toBe(false);expect(h.attackPending?.remaining).toBeCloseTo(.2);expect(combatTraceSnapshot(s).some(r=>r.type==='attack-released'&&r.context?.actorId===h.id)).toBe(false);});
test('whiff emits one attack opportunity and presentation, never a synthetic outcome',()=>{const a=setup('whiff',742);command(a.s,{type:'basic',id:a.h.id,aim:{x:15,y:9},requestId:1});expect(a.h.basicAction).toBeDefined();for(let i=0;i<8;i++)step(a.s,.05);expect(a.h.basicRelease).toBeDefined();const rows=combatTraceSnapshot(a.s).filter(r=>r.context?.actorId===a.h.id);expect(rows.filter(r=>r.type==='attack-released')).toHaveLength(1);expect(rows.filter(r=>r.type==='hit-outcome')).toHaveLength(0);});
test('Tower and enemy Basic remain legacy without a runtime',()=>{const a=setup('loop',19);a.s.exploration!.definition.kind='legacy' as any;expect(a.h.basicAction).toBeUndefined();a.h.attackTimer=0;for(let i=0;i<8;i++)step(a.s,.05);expect(a.h.basicAction).toBeUndefined();expect(a.e.basicAction).toBeUndefined();});

test('definition supports single, three and four stage topology without another executor',()=>{
 const legacy=BASIC_DEFINITIONS['legacy-main-basic'];
 for(const count of [1,3,4]){const definition={...legacy,id:'test-'+count,stages:Array.from({length:count},(_,i)=>({...legacy.stages[0],id:'s'+i}))};
  expect(nextBasicStage(definition,count-1,true)).toBe(0);expect(nextBasicStage(definition,1,false)).toBe(0);
  const a=setup('loop',19);const runtime=startBasicAction(a.s,a.h,definition,count-1,{id:2,source:'player-input',aim:a.e.pos,targetId:a.e.id,expiresAt:1},.8);
  expect(runtime.stageIndex).toBe(count-1);expect(runtime.definitionId).toBe(definition.id);for(let i=0;i<6;i++)step(a.s,.05);
  expect(combatTraceSnapshot(a.s).filter(r=>r.type==='attack-released'&&r.context?.actorId===a.h.id)).toHaveLength(1);
 }
});
test('accepted target and facing remain cached; departed target makes a real whiff',()=>{const {s,h,e,f}=start();const a=h.basicAction!;const target=a.targetId,facing=a.acceptedFacing;e.pos={x:30,y:10};f.pos={x:16,y:10};for(let i=0;i<6;i++)step(s,.05);expect(a.targetId).toBe(target);expect(a.acceptedFacing).toBe(facing);expect(combatTraceSnapshot(s).filter(r=>r.type==='hit-outcome'&&r.context?.actorId===h.id)).toHaveLength(0);});
test('real posture break cancels exactly once; later steps cannot release the cancelled action',()=>{const {s,h,e}=start();const actionId=h.basicAction!.combatContext!.actionId;h.posture=1;h.dodge=0;resolveHit(s,h,e.weapons[0],1,e,{postureDamage:999});expect(h.basicAction).toBeDefined();resolveHit(s,h,e.weapons[0],1,e,{postureDamage:999});expect(h.basicAction).toBeUndefined();for(let i=0;i<7;i++)step(s,.05);const rows=combatTraceSnapshot(s).filter(r=>r.context?.actionId===actionId);expect(rows.filter(r=>r.type==='action-cancelled')).toHaveLength(1);expect(rows.filter(r=>r.type==='attack-released')).toHaveLength(0);});
test('end expedition disposes released runtime and records only one terminal lifecycle',()=>{const {s,h}=start();const actionId=h.basicAction!.combatContext!.actionId;for(let i=0;i<6;i++)step(s,.05);expect(h.basicAction?.released).toBe(true);expect(command(s,{type:'endExpedition'}).ok).toBe(true);expect(h.basicAction).toBeUndefined();expect(combatTraceSnapshot(s).filter(r=>r.context?.actionId===actionId&&['action-finished','action-cancelled'].includes(r.type))).toHaveLength(1);});
test('buffer consumption closes the previous action once before creating the next identity',()=>{const {s,h,e}=start();const id=h.basicAction!.combatContext!.actionId;for(let i=0;i<14;i++)step(s,.05);command(s,{type:'basic',id:h.id,aim:e.pos,requestId:2});for(let i=0;i<4;i++)step(s,.05);expect(h.basicAction!.combatContext!.actionId).not.toBe(id);expect(combatTraceSnapshot(s).filter(r=>r.context?.actionId===id&&r.type==='action-finished')).toHaveLength(1);});
