import {test,expect} from 'vitest';
import {setup} from './ar03-fixture';
import {command,step,resolveHit} from '../src/core/engine';
import {pauseHunter,hunterInput} from '../src/core/hunter-combat';
const fixture=()=>{const a=setup('loop',742);a.s.units=a.s.units.filter(u=>u.team==='ally'||u.id===a.e.id);a.e.ready=999;a.e.pos={x:35,y:20};a.h.basicProfileId='hunter-v2';return a;};
const run=(s:any,n:number,speed=1)=>{for(let i=0;i<n;i++)step(s,.01*speed,.01);};
const input=(a:ReturnType<typeof fixture>,kind:any,held=true)=>command(a.s,{type:'hunterInput',id:a.h.id,kind,held,aim:{x:a.h.pos.x+8,y:a.h.pos.y}});
test('AttackReady and MoveReady are distinct; early WASD waits then cancels exactly once',()=>{const a=fixture();input(a,'basic');input(a,'basic',false);command(a.s,{type:'direct',id:a.h.id,direction:{x:0,y:1}});run(a.s,21);expect(a.h.basicAction?.attackReady).toBe(true);expect(a.h.basicAction?.moveReady).toBe(false);expect(a.h.pos.y).toBe(10);run(a.s,4);expect(a.h.pos.y).toBeGreaterThan(10);expect(a.h.basicAction).toBeUndefined();expect(a.h.hunterCombat?.trace.filter(e=>e.kind==='Cancel')).toHaveLength(1);});
test('dodge retains held and accepts next Basic at its Break rather than animation Finish',()=>{const a=fixture();input(a,'basic');run(a.s,5);input(a,'dodge');run(a.s,22);expect(a.h.basicAction).toBeDefined();expect(a.h.basicAction?.stageIndex).toBe(1);});
test('real edge expires while slow action is still locked; released held cannot resurrect it',()=>{const a=fixture();input(a,'basic');input(a,'basic',false);run(a.s,5);input(a,'basic');input(a,'basic',false);run(a.s,30,.1);run(a.s,24);expect(a.h.hunterCombat?.trace.filter(e=>e.kind==='accepted'&&e.stage!==undefined)).toHaveLength(1);});
test('combo expires in real time after actual Finish, independent of slow simulation',()=>{const a=fixture();input(a,'basic');input(a,'basic',false);run(a.s,75);run(a.s,65,.1);input(a,'basic');expect(a.h.basicAction?.stageIndex).toBe(0);});
test('guard rear contact and startup fail without consuming frost; qualified duplicate cannot pay twice',()=>{const a=fixture();input(a,'guard');const hp=a.h.hp;a.e.pos={x:a.h.pos.x+1,y:a.h.pos.y};resolveHit(a.s,a.h,a.e.weapons[0],8,a.e,{eventId:1,postureDamage:0});expect(a.h.hp).toBeLessThan(hp);expect(a.h.hunterCombat?.frost).toBe(3);run(a.s,45);expect(input(a,'guard').ok).toBe(true);run(a.s,9);a.e.pos={x:a.h.pos.x+1,y:a.h.pos.y};resolveHit(a.s,a.h,a.e.weapons[0],8,a.e,{eventId:2,postureDamage:0});resolveHit(a.s,a.h,a.e.weapons[0],8,a.e,{eventId:2,postureDamage:0});expect(a.h.hunterCombat?.frost).toBe(2);});
test('cancel or pause before active Attack removes motion/invulnerability without paying',()=>{for(const mode of ['cancel','pause']){const a=fixture();input(a,'active');run(a.s,5);if(mode==='pause')pauseHunter(a.s);else input(a,'cancel');expect(a.h.hunterCombat?.activeCharge).toBe(1);expect(a.h.hunterCombat?.motion).toBeUndefined();expect(a.h.hunterCombat?.invulnerableUntil).toBe(0);run(a.s,60);expect(a.h.hunterCombat?.special).toBeUndefined();}});
test('control switch retains accepted active identity/payment/CD; key release can finish offhand',()=>{const a=fixture();input(a,'active');run(a.s,20);const root=a.h.hunterCombat?.special?.context;command(a.s,{type:'controlBody',id:a.p.id});expect(input(a,'active',false).ok).toBe(true);run(a.s,20);const child=a.h.hunterCombat?.special?.context;expect(child?.actorId).toBe(a.h.id);expect(child?.parentActionId).toBe(root?.actionId);expect(child?.rootActionId).toBe(root?.rootActionId);expect(a.h.hunterCombat?.activeCharge).toBe(0);expect(a.h.hunterCombat?.activeCooldown).toBeGreaterThan(7);});
test('offhand AI uses same four-stage runtime and cannot auto start guard or active',()=>{const a=fixture();a.e.pos={x:a.h.pos.x+1,y:a.h.pos.y};a.e.ready=0;a.s.context='explorationBattle';a.e.encounterRoom=1;a.s.exploration!.definition.encounters=[{room:1,name:'AR05 active combat fixture',tier:'strong',enemyIds:[a.e.id],center:{...a.e.pos},tacticalRadius:6.5}];command(a.s,{type:'controlBody',id:a.p.id});run(a.s,120);const rows=a.h.hunterCombat?.trace.filter(e=>e.kind==='accepted'&&e.stage!==undefined)??[];expect(rows.slice(0,4).map(e=>e.stage)).toEqual([0,1,2,3]);expect(a.h.hunterCombat?.special).toBeUndefined();});
test('old Hunter abilities and slots reject, Tower remains legacy',()=>{const a=fixture();for(const c of [{type:'skill',id:a.h.id},{type:'blink',id:a.h.id,direction:{x:1,y:0}},{type:'evade',id:a.h.id,direction:{x:1,y:0}}] as any[])expect(command(a.s,c).ok).toBe(false);expect(hunterInput({...a.s,journey:'tower'},a.h,'basic').ok).toBe(false);});
test('invulnerability has a negative AR02 outcome and no damage; death/reset remove pending effects',()=>{const a=fixture();input(a,'dodge');const hp=a.h.hp;expect(resolveHit(a.s,a.h,a.e.weapons[0],12,a.e,{eventId:42})).toBe(false);expect(a.h.hp).toBe(hp);expect(a.s.combatIdentity?.trace.at(-1)?.type).toBe('hit-outcome');a.h.life='downed';run(a.s,1);expect(a.h.hunterCombat?.hazards).toHaveLength(0);expect(a.h.basicAction).toBeUndefined();});

test('incoming qualified HP damage applies the frozen enemy-contact real hitstop',()=>{const a=fixture();resolveHit(a.s,a.h,a.e.weapons[0],8,a.e,{eventId:81,postureDamage:0});expect(a.s.combatHitstop?.scale).toBe(.5);expect(a.s.combatHitstop?.until).toBeCloseTo((a.s.realTime??a.s.time)+.2);});
