import {mkdirSync,writeFileSync} from 'node:fs';
import {test,expect,type Page} from '@playwright/test';
test.setTimeout(60000);
const errors=new WeakMap<Page,string[]>();test.beforeEach(({page})=>{const list:string[]=[];errors.set(page,list);page.on('pageerror',e=>list.push(e.message));});test.afterEach(({page})=>expect(errors.get(page)).toEqual([]));
async function begin(page:Page){await page.goto('/');await page.locator('[data-journey="exploration"]').click();await page.locator('[data-companion="ranger"]').click();await page.locator('[data-action="carry"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.unitVisuals.get('hunter')?.reference?.ready)).toBe(true);await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').ready)).toBe(0);}
const direct=(page:Page)=>page.evaluate(()=>(window as any).prototype.state.controlledBodyId);
const stages=(page:Page)=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').hunterCombat?.trace.filter((r:any)=>r.kind==='accepted'&&r.stage!==undefined).length??0);
async function blind(page:Page){return page.evaluate(()=>{const p=(window as any).prototype,r=document.querySelector('#scene')!.getBoundingClientRect();for(let y=250;y<r.bottom-200;y+=40)for(let x=350;x<r.right-250;x+=40)if(document.elementFromPoint(x,y)?.closest('#scene')&&!p.scene.pick(x,y).tile)return {x,y};throw Error('no unpicked scene pixel');});}
test('Z alone switches two bodies; obsolete keys and readonly avatar never change identity',async({page})=>{
 await begin(page);await page.keyboard.press('z');expect(await direct(page)).toBe('ranger');await page.keyboard.down('z');await page.keyboard.down('z');expect(await direct(page)).toBe('hunter');await page.keyboard.up('z');
 for(const key of ['c','1','2']){await page.keyboard.press(key);expect(await direct(page)).toBe('hunter');}
 await page.locator('[data-unit="ranger"]').click();expect(await direct(page)).toBe('hunter');
});
test('unpicked dark scene pixel starts Hunter Basic without revealing terrain',async({page})=>{
 await begin(page);const q=await blind(page);const pure=await page.evaluate(q=>{const p=(window as any).prototype,h=p.state.units.find((u:any)=>u.id==="hunter"),before=JSON.stringify(p.state);const aim=p.scene.combatAimAt(q.x,q.y,h.pos);return {aim,unchanged:before===JSON.stringify(p.state)};},q);expect(pure.unchanged).toBe(true);expect(Number.isFinite(pure.aim.x)).toBe(true);await page.mouse.move(q.x,q.y);await page.mouse.down();await expect.poll(()=>stages(page)).toBeGreaterThan(0);await page.mouse.up();mkdirSync('../work/AR-05/F02',{recursive:true});await page.screenshot({path:'../work/AR-05/F02/黑暗指向与Z提示.png'});writeFileSync('../work/AR-05/F02/aim-readonly.json',JSON.stringify({pixel:q,query:pure},null,2));
});
test('Z while LMB held isolates release from new actor and pause blocks switching',async({page})=>{
 await begin(page);const q=await blind(page);await page.mouse.move(q.x,q.y);await page.mouse.down();await expect.poll(()=>stages(page)).toBeGreaterThan(0);await page.keyboard.press('z');expect(await direct(page)).toBe('ranger');const n=await stages(page);await page.mouse.up();await page.waitForTimeout(800);expect(await stages(page)).toBe(n);expect(await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').basicAction)).toBeUndefined();await page.keyboard.press('Space');await page.keyboard.press('z');expect(await direct(page)).toBe('ranger');
});
test('F and G own dark LMB, while RMB guard and prepared E follow dark direction',async({page})=>{
 await begin(page);const q=await blind(page);await page.keyboard.press('f');await page.mouse.click(q.x,q.y);expect(await stages(page)).toBe(0);expect(await page.evaluate(()=>(window as any).prototype.state.explorationControl.aim?.kind)).toBe('path');await page.keyboard.press('Escape');await page.mouse.move(q.x,q.y);await page.keyboard.down('g');await page.mouse.click(q.x,q.y);expect(await stages(page)).toBe(0);await page.keyboard.press('z');expect(await direct(page)).toBe('ranger');await page.keyboard.up('g');await page.keyboard.press('z');await page.mouse.down({button:'right'});await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').hunterCombat?.special?.kind)).toBe('guard');await page.mouse.up({button:'right'});
});

test('W+D transfer, invalid body, modal and text input keep one control authority',async({page})=>{
 await begin(page);await page.keyboard.down('w');await page.keyboard.down('d');await page.keyboard.press('z');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').direct?.direction.x)).toBeGreaterThan(0);await page.keyboard.up('w');await page.keyboard.up('d');await expect.poll(()=>page.evaluate(()=>!!(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').direct)).toBe(false);
 await page.locator('[data-action="backpack"]').first().click();await page.keyboard.press('z');expect(await direct(page)).toBe('ranger');await page.keyboard.press('Escape');
 await page.evaluate(()=>{const input=document.createElement('input');input.id='f02-text';input.style.cssText='position:fixed;top:100px;left:400px;z-index:100';document.body.append(input);input.focus();});await page.keyboard.press('z');expect(await direct(page)).toBe('ranger');await page.evaluate(()=>document.querySelector('#f02-text')!.remove());
 await page.evaluate(()=>{(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').shadowResident=true;});await page.keyboard.press('z');expect(await direct(page)).toBe('ranger');
});

test('friend, obstacle and actor center admit attacks; avatar inspection cannot clear held',async({page})=>{
 await begin(page);
 const q=await page.evaluate(()=>{const p=(window as any).prototype,s=p.state,h=s.units.find((u:any)=>u.id==='hunter'),r=s.units.find((u:any)=>u.id==='ranger');r.pos=r.drawPos={x:h.pos.x+1,y:h.pos.y};return p.project(r.pos);});await page.waitForTimeout(150);const hp=await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').hp);await page.mouse.move(q.x,q.y);await page.mouse.down();await expect.poll(()=>stages(page)).toBeGreaterThan(0);await page.mouse.up();expect(await direct(page)).toBe('hunter');expect(await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').hp)).toBe(hp);
 const center=await page.evaluate(()=>{const p=(window as any).prototype,h=p.state.units.find((u:any)=>u.id==='hunter');return p.project(h.pos);});await page.mouse.move(center.x,center.y);const n=await stages(page);await page.mouse.down();await expect.poll(()=>stages(page)).toBeGreaterThan(n);await page.locator('[data-unit="ranger"]').dispatchEvent('click');expect(await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').hunterCombat.held)).toBe(true);await page.mouse.up();
 const wall=await page.evaluate(()=>{const p=(window as any).prototype,h=p.state.units.find((u:any)=>u.id==='hunter'),pos={x:Math.round(h.pos.x-1),y:Math.round(h.pos.y)};p.state.tiles.find((t:any)=>t.x===pos.x&&t.y===pos.y).obstacle=true;return p.project(pos);});await page.mouse.move(wall.x,wall.y);const m=await stages(page);await page.mouse.down();await expect.poll(()=>stages(page)).toBeGreaterThan(m);await page.mouse.up();
 expect(await page.evaluate(()=>{const h=(window as any).prototype.state.units.find((u:any)=>u.id==='hunter');return Number.isFinite(h.hunterCombat.aim.x)&&Number.isFinite(h.basicAction?.angle??h.heading);})).toBe(true);
});

test('partner tap attacks dark direction; cancellation and blur never retain Hunter held',async({page})=>{
 await begin(page);await page.keyboard.press('z');const q=await blind(page);await page.mouse.click(q.x,q.y);await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').alCombat?.lastInput??0)).toBeGreaterThan(0);
 await page.keyboard.press('z');await page.mouse.down();await expect.poll(()=>stages(page)).toBeGreaterThan(0);await page.evaluate(()=>document.querySelector('#scene')!.dispatchEvent(new PointerEvent('pointercancel',{bubbles:true,pointerId:1})));expect(await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').hunterCombat.held)).toBe(false);await page.mouse.up();await page.mouse.down();await page.evaluate(()=>window.dispatchEvent(new Event('blur')));expect(await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').hunterCombat.held)).toBe(false);await page.mouse.up();
});

test('prepared E updates direction in darkness and releases only its original owner after Z',async({page})=>{
 await begin(page);const q=await blind(page);await page.mouse.move(q.x,q.y);await page.keyboard.down('e');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').hunterCombat.special?.kind)).toBe('prepare');const target={x:q.x+100,y:q.y+80};await page.evaluate(()=>window.addEventListener('pointermove',e=>{const p=(window as any).prototype,h=p.state.units.find((u:any)=>u.id==='hunter');(window as any).f02Expected=p.scene.combatAimAt(e.clientX,e.clientY,h.pos);},{capture:true,once:true}));await page.mouse.move(target.x,target.y);const a=await page.evaluate(()=>{const p=(window as any).prototype,h=p.state.units.find((u:any)=>u.id==='hunter');return {got:h.hunterCombat.aim,want:(window as any).f02Expected};});expect(a.got.x).toBeCloseTo(a.want.x,1);expect(a.got.y).toBeCloseTo(a.want.y,1);await page.keyboard.press('z');await page.keyboard.up('e');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').hunterCombat.activeCharge)).toBe(0);expect(await direct(page)).toBe('ranger');expect(await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').hunterCombat)).toBeUndefined();
});

test('Tower numeric selection and unit avatar remain legacy controls',async({page})=>{
 await page.goto('/');await page.locator('[data-action="carry"]').click();await page.locator('[data-action="start"]').click();await page.locator('[data-action="pause"]').click();await page.evaluate(()=>{const s=(window as any).prototype.state;s.units=s.units.filter((u:any)=>u.team==='ally');for(const u of s.units){u.life='active';u.ready=0;u.shadowResident=false;}});await page.keyboard.press('Space');for(const key of ['1','2','3','4']){await page.keyboard.press(key);expect(await page.evaluate(()=>(window as any).prototype.interaction.selectedId)).toBe(await page.evaluate(n=>(window as any).prototype.state.units[Number(n)-1].id,key));}await page.locator('[data-unit="hunter"]').click();expect(await page.evaluate(()=>(window as any).prototype.interaction.selectedId)).toBe('hunter');
});


test('releasing captured LMB must not release the independently held RMB guard',async({page})=>{
 await begin(page);const q=await blind(page);await page.mouse.move(q.x,q.y);await page.mouse.down({button:'right'});await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').hunterCombat.special?.kind)).toBe('guard');await page.mouse.down();await page.mouse.up();await page.waitForTimeout(100);expect(await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').hunterCombat.special?.kind)).toBe('guard');await page.mouse.up({button:'right'});await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').hunterCombat.special?.kind)).not.toBe('guard');
});


test('visible resource interaction keeps priority over the new free-direction Basic',async({page})=>{
 await begin(page);await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.terrain.userData.loaded),{timeout:45000}).toBe(true);
 const point=await page.evaluate(()=>{const p=(window as any).prototype,s=p.state,h=s.units.find((u:any)=>u.id==='hunter');s.units=s.units.filter((u:any)=>u.team==='ally');s.context='explorationIdle';s.exploration.lastActivity=s.time-10;const pos={x:Math.round(h.pos.x)+1,y:Math.round(h.pos.y)};s.tiles.find((t:any)=>t.x===pos.x&&t.y===pos.y).obstacle=false;const event={id:'f02-visible-resource',pos,kind:'resource',reward:10};s.exploration.definition.points.push(event);return {id:event.id,pos};});await page.waitForTimeout(200);
 const q=await page.evaluate(pos=>{const p=(window as any).prototype,q=p.project(pos);return {...q,pick:p.scene.pick(q.x,q.y),onScene:!!document.elementFromPoint(q.x,q.y)?.closest('#scene')};},point.pos);expect(q.onScene).toBe(true);expect(q.pick.tile).not.toBeNull();expect(q.pick.unitId).toBeNull();expect(Math.hypot(q.pick.tile.x-point.pos.x,q.pick.tile.y-point.pos.y)).toBeLessThan(.6);await page.mouse.click(q.x,q.y);await expect.poll(()=>page.evaluate(id=>(window as any).prototype.state.exploration.memory.mechanisms.includes(id),point.id)).toBe(true);expect(await stages(page)).toBe(0);
});
