import {isPartyBody} from '../src/core/exploration-party';
import {test,expect} from 'vitest';
import {createGame,command,step} from '../src/core/engine';
import {resolveBasicDefinition} from '../src/core/basic-definition';
export function fixture(){const s=createGame();command(s,{type:'selectJourney',journey:'exploration'});command(s,{type:'selectExplorationCompanion',id:'ranger'});command(s,{type:'carry',gold:0,vitality:0});s.tiles.forEach(t=>{t.obstacle=false;t.layer=0;});s.units=s.units.filter(u=>u.team==='ally');const u=s.units.find(u=>u.id==='ranger')!;u.ready=0;u.pos={x:15,y:10};u.drawPos={...u.pos};command(s,{type:'controlBody',id:u.id});return {s,u};}
test('AR06 real Al uses three-stage definition; Tower and Hunter stay isolated',()=>{const {s,u}=fixture();expect(u.name).toBe('阿尔');expect(resolveBasicDefinition(u).id).toBe('al-basic-v1');expect(resolveBasicDefinition(u).stages).toHaveLength(3);expect(s.units.filter(u=>isPartyBody(s,u))).toHaveLength(2);expect(s.units.find(u=>u.id==='hunter')!.basicProfileId).toBe('hunter-v2');const tower=createGame();expect(tower.units.find(u=>u.id==='ranger')?.basicProfileId).not.toBe('al-basic-v1');});
test('AR06 held native three-stage events keep own timing and resource identity',()=>{const {s,u}=fixture();expect(command(s,{type:'alInput',id:u.id,kind:'basic',held:true,aim:{x:25,y:10}} as any).ok).toBe(true);for(let i=0;i<90;i++)step(s,.01);const trace=(u as any).alCombat.trace;expect(trace.filter((r:any)=>r.kind==='accepted'&&r.stage!==undefined).slice(0,4).map((r:any)=>r.stage)).toEqual([0,1,2,0]);expect(u.hunterCombat).toBeUndefined();});

test('Al roll uses independent cooldown and no Hunter slash; shot pays at Hit and reloads',()=>{const {s,u}=fixture();expect(command(s,{type:'alInput',id:u.id,kind:'roll',direction:{x:1,y:0}}).ok).toBe(true);const x=u.pos.x;for(let i=0;i<20;i++)step(s,.01);expect(u.pos.x-x).toBeCloseTo(2.4,2);expect(u.alCombat!.rollCd).toBeGreaterThan(.7);expect(u.alCombat!.entities).toHaveLength(0);for(let i=0;i<20;i++)step(s,.01);expect(command(s,{type:'alInput',id:u.id,kind:'shot',aim:{x:30,y:10}}).ok).toBe(true);expect(u.alCombat!.ammo).toBe(4);step(s,.04);expect(u.alCombat!.ammo).toBe(3);expect(u.alCombat!.entities[0].kind).toBe('bullet');});
test('Al rocket captures destination, pays on Hit and lands one child; old skills reject',()=>{const {s,u}=fixture();expect(command(s,{type:'skill',id:u.id,slot:0}).ok).toBe(false);expect(command(s,{type:'alInput',id:u.id,kind:'rocket',aim:{x:19,y:10}}).ok).toBe(true);step(s,.09);expect(u.alCombat!.rocketCd).toBe(0);step(s,.02);expect(u.alCombat!.rocketCd).toBeGreaterThan(5.9);for(let i=0;i<34;i++)step(s,.01);expect(u.pos.x).toBeCloseTo(19,2);expect(u.alCombat!.trace.filter(e=>e.kind==='land')).toHaveLength(1);});
test('Al released bullet survives actor switch, pays once and cannot cross wall',()=>{for(const wall of [false,true]){const {s,u}=fixture();const enemy=structuredClone(u);enemy.id='al-target';enemy.team='enemy';enemy.basicProfileId=undefined;enemy.alCombat=undefined;enemy.hp=enemy.maxHp=20000;enemy.posture=enemy.maxPosture=2000;enemy.pos={x:18,y:10};enemy.drawPos={...enemy.pos};enemy.ready=999;s.units.push(enemy);if(wall)s.tiles.find(t=>t.x===17&&t.y===10)!.obstacle=true;command(s,{type:'alInput',id:u.id,kind:'shot',aim:enemy.pos});step(s,.04);command(s,{type:'alInput',id:u.id,kind:'shot',held:false});command(s,{type:'controlBody',id:'hunter'});for(let i=0;i<30;i++)step(s,.01);expect(u.alCombat!.ammo).toBe(3);expect(enemy.hp<20000).toBe(!wall);expect(u.alCombat!.trace.filter(e=>e.kind==='ammo-payment')).toHaveLength(1);}});
test('Al move gate, rocket cancel before payment and death cleanup are independent',()=>{const {s,u}=fixture();command(s,{type:'alInput',id:u.id,kind:'basic',held:false});command(s,{type:'basic',id:u.id,aim:{x:25,y:10},requestId:100});command(s,{type:'direct',id:u.id,direction:{x:0,y:1}});step(s,.15);expect(u.basicAction?.moveReady).toBe(false);expect(u.pos.y).toBe(10);step(s,.07);expect(u.basicAction).toBeUndefined();command(s,{type:'direct',id:u.id,direction:null});command(s,{type:'alInput',id:u.id,kind:'rocket',aim:{x:19,y:10}});step(s,.04);command(s,{type:'alInput',id:u.id,kind:'cancel'});expect(u.alCombat!.rocketCd).toBe(0);expect(u.alCombat!.special).toBeUndefined();u.life='downed';step(s,.01);expect(u.alCombat!.entities).toHaveLength(0);});
test.each([.1,1,2])('Al ammo/reload uses simulation clock at scale %s without a second payment',scale=>{const {s,u}=fixture();command(s,{type:'alInput',id:u.id,kind:'shot',aim:{x:30,y:10}});command(s,{type:'alInput',id:u.id,kind:'shot',held:false});for(let i=0;i<Math.ceil(.6/scale/.01);i++)step(s,.01*scale,.01);command(s,{type:'alInput',id:u.id,kind:'shot',held:false});expect(u.alCombat!.ammo).toBe(3);for(let i=0;i<Math.ceil(4/scale/.01);i++)step(s,.01*scale,.01);expect(u.alCombat!.ammo).toBe(4);expect(u.alCombat!.trace.filter(e=>e.kind==='ammo-payment')).toHaveLength(1);expect(u.alCombat!.trace.filter(e=>e.kind==='reload-complete')).toHaveLength(1);});
test('Al invalid direct Basic aim rejects without corrupting future animation',()=>{const {s,u}=fixture();expect(command(s,{type:'basic',id:u.id,aim:{x:NaN,y:10},requestId:10}).ok).toBe(false);expect(u.basicAction).toBeUndefined();expect(command(s,{type:'basic',id:u.id,aim:{x:20,y:10},requestId:11}).ok).toBe(true);});
import {restoreSkillAtCampfire} from '../src/core/campfire';
test('Al empty legacy slots remain safe at a real campfire restore',()=>{const {u}=fixture();expect(()=>restoreSkillAtCampfire(u)).not.toThrow();expect(u.skillSlots).toEqual([null,null,null]);});
import {resolveHit} from '../src/core/engine';
import {pauseAl} from '../src/core/al-combat';
test('Al roll invulnerability expires after the approved window; pause clears pending rocket',()=>{const {s,u}=fixture();const enemy=structuredClone(u);enemy.id='damage-source';enemy.team='enemy';enemy.basicProfileId=undefined;enemy.pos={x:18,y:10};command(s,{type:'alInput',id:u.id,kind:'roll',direction:{x:1,y:0}});step(s,.05);const hp=u.hp;resolveHit(s,u,enemy.weapons[0],100,enemy);expect(u.hp).toBe(hp);step(s,.1);resolveHit(s,u,enemy.weapons[0],100,enemy);expect(u.hp).toBeLessThan(hp);step(s,.3);command(s,{type:'alInput',id:u.id,kind:'rocket',aim:{x:20,y:10}});pauseAl(s);expect(u.alCombat!.special).toBeUndefined();expect(u.alCombat!.shotHeld).toBe(false);});
test('Al rocket child has its own identity and real terrain blocks transport',()=>{const {s,u}=fixture();s.tiles.find(t=>t.x===17&&t.y===10)!.obstacle=true;command(s,{type:'alInput',id:u.id,kind:'rocket',aim:{x:20,y:10}});step(s,.45);expect(u.pos.x).toBeLessThan(17);const rows=s.combatIdentity!.trace.filter(r=>r.type==='action-started'&&r.context?.actorId==='ranger');const child=rows.find(r=>r.context?.executedAbilityId==='火箭弹射爆炸')!.context!,root=rows.find(r=>r.context?.executedAbilityId==='火箭弹射')!.context!;expect(child.actionId).not.toBe(root.actionId);expect(child.parentActionId).toBe(root.actionId);expect(child.rootActionId).toBe(root.actionId);});
import {setup as battleSetup} from './ar03-fixture';
test('Al offhand uses native three-stage Basic without spending ammo or rocket',()=>{const {s,h,p,e}=battleSetup('loop',742);h.basicProfileId='hunter-v2';p.basicProfileId='al-basic-v1';s.units=[h,p,e];s.controlledBodyId=h.id;h.pos={x:14,y:10};p.pos={x:15,y:10};e.pos={x:16.2,y:10};for(const u of [h,p,e]){u.drawPos={...u.pos};u.ready=0;u.path=[];u.direct=undefined;}p.skillSlots=[null,null,null];p.attackTimer=0;e.ready=999;e.hp=e.maxHp=100000;e.reveal=999;e.encounterRoom=1;e.pursuitTargetId=h.id;s.context='explorationBattle';s.exploration!.definition.encounters=[{room:1,name:'AR06 AI',tier:'strong',enemyIds:[e.id],center:{...p.pos},tacticalRadius:6.5}];for(let i=0;i<600;i++)step(s,.01);const a=p.alCombat!;expect(a.trace.filter(r=>r.kind==='accepted'&&r.stage!==undefined).slice(0,3).map(r=>r.stage)).toEqual([0,1,2]);expect(a.ammo).toBe(4);expect(a.rocketCd).toBe(0);});
test('Al Basic emits one release sound per committed Hit',()=>{const {s,u}=fixture();command(s,{type:'alInput',id:u.id,kind:'basic',aim:{x:30,y:10}});command(s,{type:'alInput',id:u.id,kind:'basic',held:false});step(s,.08);expect(u.alCombat!.trace.filter(e=>e.cue==='release')).toHaveLength(1);});
