import {test,expect} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
test.setTimeout(90000);
test.use({video:'on'});
test('xx native preview, module isolation, held four stages and two-body Z in main exploration',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/xx-preview.html');await expect.poll(()=>page.evaluate(()=>!!(window as any).xxPreview?.visual.ready)).toBe(true);const metadata=await page.evaluate(()=>{const v=(window as any).xxPreview.visual;return {version:v.data.version,names:v.names,events:v.data.animations.map((a:any)=>({name:a.name,duration:a.duration,events:a.timelines.flatMap((t:any)=>t.events??[]).map((e:any)=>({time:e.time,name:e.data.name}))}))};});expect(metadata.version).toBe('4.3.26');expect(metadata.names).toContain('atk4');mkdirSync('../work/AR-07-X01',{recursive:true});writeFileSync('../work/AR-07-X01/native-runtime-audit.json',JSON.stringify(metadata,null,2));
 await page.goto('/?xx=1');await page.locator('[data-companion="ranger"]').click();await page.locator('[data-action="carry"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.unitVisuals.get('hunter')?.reference?.ready)).toBe(true);await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').ready)).toBe(0);const box=(await page.locator('#scene').boundingBox())!;await page.mouse.move(box.x+box.width*.58,box.y+box.height*.5);await page.mouse.down();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').xxCombat.trace.filter((e:any)=>e.name==='accepted').length),{timeout:15000}).toBeGreaterThan(3);await page.mouse.up();await page.screenshot({path:'../work/AR-07-X01/main-xx-al.png'});await page.keyboard.press('z');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.controlledBodyId)).toBe('ranger');await page.keyboard.press('z');expect(await page.evaluate(()=>(window as any).prototype.state.controlledBodyId)).toBe('hunter');await expect(page.locator('#control-status')).toContainText('xx（实验）');const data=await page.evaluate(()=>{const p=(window as any).prototype;return {party:p.state.units.filter((u:any)=>u.team==='ally'&&!u.cloneOf&&u.life==='active').map((u:any)=>({id:u.id,name:u.name,profile:u.basicProfileId})),trace:p.state.units.find((u:any)=>u.id==='hunter').xxCombat.trace,namespaceHasLegacyBinary:!!(window as any).spine.SkeletonBinary,reference:p.scene.unitVisuals.get('hunter').reference.pose};});expect(data.party).toHaveLength(2);expect(data.namespaceHasLegacyBinary).toBe(true);expect(data.trace.filter((e:any)=>e.name==='accepted').slice(0,4).map((e:any)=>e.stage)).toEqual([0,1,2,3]);await page.waitForTimeout(1600);const walk=await page.evaluate(async()=>{const p=(window as any).prototype,h=p.state.units.find((u:any)=>u.id==='hunter'),{canStop,segmentClear}=await import('/src/core/spatial.ts' as any);for(const [key,x,y] of [['d',1,0],['a',-1,0],['s',0,1],['w',0,-1]] as const){const goal={x:h.pos.x+x,y:h.pos.y+y};if(canStop(p.state,goal,h)&&segmentClear(p.state,h.pos,goal))return {key,start:{...h.pos}};}throw new Error('no walkable direction at current actor');});await page.keyboard.down(walk.key);await page.waitForTimeout(1100);await page.keyboard.up(walk.key);const moved=await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').pos);expect(Math.hypot(moved.x-walk.start.x,moved.y-walk.start.y)).toBeGreaterThan(.1);await page.screenshot({path:'../work/AR-07-X01/main-move.png'});await page.waitForTimeout(300);await page.screenshot({path:'../work/AR-07-X01/main-pair.png'});
 await page.mouse.down();await page.keyboard.press('Space');const pausedTime=await page.evaluate(()=>(window as any).prototype.state.time);await page.waitForTimeout(300);expect(await page.evaluate(()=>(window as any).prototype.state.time)).toBe(pausedTime);expect(await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').xxCombat.held)).toBe(false);await page.mouse.up();await page.keyboard.press('Space');await page.mouse.down();await page.evaluate(()=>window.dispatchEvent(new Event('blur')));expect(await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').xxCombat.held)).toBe(false);await page.mouse.up();
 const interrupted=await page.evaluate(async()=>{const p=(window as any).prototype,engine=await import('/src/core/engine.ts'),h=p.state.units.find((u:any)=>u.id==='hunter');engine.command(p.state,{type:'xxInput',id:h.id,held:true,aim:{x:h.pos.x+1,y:h.pos.y}});const e=structuredClone(h);e.id='fixture-enemy';e.team='enemy';e.basicProfileId=undefined;e.xxCombat=undefined;e.pos={x:h.pos.x+1,y:h.pos.y};const hp=h.hp;engine.resolveHit(p.state,h,e.weapons[0],10,e);return {lost:h.hp<hp,actionGone:!h.xxCombat.action,hurtUntil:h.xxCombat.hurtUntil,time:p.state.time};});expect(interrupted.lost).toBe(true);expect(interrupted.actionGone).toBe(true);await page.waitForTimeout(80);await page.screenshot({path:'../work/AR-07-X01/main-hurt.png'});
 await page.waitForTimeout(600);const wall=await page.evaluate(()=>{const p=(window as any).prototype,h=p.state.units.find((u:any)=>u.id==='hunter'),tiles=p.state.tiles;const free=tiles.find((t:any)=>!t.obstacle&&t.layer===0&&tiles.some((w:any)=>w.x===t.x+1&&w.y===t.y&&w.obstacle));if(!free)throw new Error('no real map wall fixture');h.pos={x:free.x,y:free.y};h.drawPos={...h.pos};h.direct=undefined;h.path=[];return {x:free.x,y:free.y};});await page.keyboard.down('d');await page.waitForTimeout(700);await page.keyboard.up('d');const end=await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').pos);expect(end.x).toBeLessThan(wall.x+1);await page.screenshot({path:'../work/AR-07-X01/main-wall.png'});
  const disposal=await page.evaluate(()=>{const p=(window as any).prototype,v=p.scene.unitVisuals.get('hunter').reference;p.scene.dispose();return {width:v.canvas.width,ready:v.ready};});expect(disposal).toEqual({width:0,ready:false});
 writeFileSync('../work/AR-07-X01/main-evidence.json',JSON.stringify(data,null,2));expect(errors).toEqual([]);
});
