import {test,expect} from 'vitest';
import {createGame,command,step} from '../src/core/engine';
import {isPartyBody} from '../src/core/exploration-party';
import {xxState,requestXX,advanceXX,cancelXX} from '../src/core/xx-combat';
import {resolveHit} from '../src/core/engine';
import {XX_PROFILE} from '../src/core/xx-profile';
function fixture(){const s=createGame();command(s,{type:'selectJourney',journey:'exploration'});command(s,{type:'selectExplorationCompanion',id:'ranger'});expect(command(s,{type:'xxExperiment',enabled:true} as any).ok).toBe(true);command(s,{type:'carry',gold:0,vitality:0});s.tiles.forEach(t=>{t.obstacle=false;t.layer=0;});s.units=s.units.filter(u=>u.team==='ally');const u=s.units.find(u=>u.id==='hunter')!;u.pos={x:15,y:10};u.ready=0;return {s,u};}
test('xx substitutes hunter, keeps two party bodies and cannot mutate a running party',()=>{const {s,u}=fixture();expect(u.name).toBe('xx');expect(u.basicProfileId).toBe('xx-experiment');expect(s.units.filter(u=>isPartyBody(s,u))).toHaveLength(2);expect(s.units.find(u=>u.id==='ranger')!.basicProfileId).toBe('al-basic-v1');expect(command(s,{type:'xxExperiment',enabled:false} as any).ok).toBe(false);});
test('single click waits for original hit_start then closes at hit_end, one damage per target',()=>{const {s,u}=fixture();const enemy=structuredClone(u);enemy.id='target';enemy.team='enemy';enemy.life='active';enemy.pos={x:16,y:10};requestXX(s,u,enemy.pos,1);const hits:number[]=[];advanceXX(s,u,.08,[enemy],()=>{hits.push(15);return true;});expect(hits).toEqual([]);advanceXX(s,u,.004,[enemy],()=>{hits.push(15);return true;});advanceXX(s,u,.184,[enemy],()=>{hits.push(15);return true;});expect(hits).toEqual([15]);expect(xxState(u).trace.map(e=>e.name)).toContain('hit_end');expect(xxState(u).action!.attackReady).toBe(false);});
test('held input cycles four own stages; release and switch do not create extra actors',()=>{const {s,u}=fixture();command(s,{type:'xxInput',id:u.id,held:true,aim:{x:20,y:10}} as any);for(let i=0;i<250;i++)step(s,.01);expect(xxState(u).trace.filter(e=>e.name==='accepted').slice(0,4).map(e=>e.stage)).toEqual([0,1,2,3]);command(s,{type:'clearBasicInputs'});expect(xxState(u).held).toBe(false);command(s,{type:'controlBody',id:'ranger'});expect(s.controlledBodyId).toBe('ranger');});
test('cancel before hit_start never releases damage and hurt blocks a new input',()=>{const {s,u}=fixture();requestXX(s,u,{x:20,y:10},1);cancelXX(s,u,'hurt');expect(xxState(u).action).toBeUndefined();const hits:number[]=[];advanceXX(s,u,.3,[],()=>{hits.push(1);return true;});expect(hits).toEqual([]);});
test.each([false,true])('real authority respects encounter identity and wall=%s',wall=>{const {s,u}=fixture();const e=structuredClone(u);e.id='enemy';e.team='enemy';e.basicProfileId=undefined;e.xxCombat=undefined;e.hp=e.maxHp=1000;e.ready=999;e.pos={x:16,y:10};e.drawPos={...e.pos};e.encounterRoom=s.exploration!.definition.encounters![0].room;e.pursuitTargetId=u.id;s.units.push(e);const tile=s.tiles.find(t=>t.x===16&&t.y===10)!;tile.obstacle=wall;command(s,{type:'xxInput',id:u.id,held:true,aim:e.pos});command(s,{type:'xxInput',id:u.id,held:false});for(let i=0;i<20;i++)step(s,.01);expect(e.hp<1000).toBe(!wall);if(!wall)expect(xxState(u).trace.filter(e=>e.name==='contact')).toHaveLength(1);});
test('multiple windows and same-frame reopening share action damage identity',()=>{const {s,u}=fixture();requestXX(s,u,{x:20,y:10},1);xxState(u).action!.windows=[{start:0,end:.1},{start:.1,end:.2}];const e=structuredClone(u);e.id='target';e.team='enemy';e.pos={x:16,y:10};const hits:number[]=[];for(let i=0;i<25;i++)advanceXX(s,u,.01,[e],()=>{hits.push(1);return true;});expect(hits).toEqual([1]);expect(xxState(u).trace.filter(e=>e.name==='hit_start')).toHaveLength(2);});
test('real WASD waits for independent move gate, then cancels recovery without extra Release',()=>{const {s,u}=fixture();command(s,{type:'xxInput',id:u.id,held:true,aim:{x:20,y:10}});command(s,{type:'xxInput',id:u.id,held:false});command(s,{type:'direct',id:u.id,direction:{x:1,y:0}});const start=u.pos.x;step(s,.3);expect(u.pos.x).toBe(start);step(s,.12);expect(u.pos.x).toBeGreaterThan(start);expect(xxState(u).action).toBeUndefined();expect(xxState(u).trace.filter(e=>e.name==='hit_start')).toHaveLength(1);});
test('main damage authority interrupts xx once; no borrowed Hunter state or guard',()=>{const {s,u}=fixture();command(s,{type:'xxInput',id:u.id,aim:{x:20,y:10}});const enemy=structuredClone(u);enemy.id='source';enemy.team='enemy';enemy.basicProfileId=undefined;enemy.pos={x:16,y:10};const hp=u.hp;resolveHit(s,u,enemy.weapons[0],100,enemy);expect(u.hp).toBeLessThan(hp);expect(xxState(u).action).toBeUndefined();expect(xxState(u).hurtUntil).toBe(.5);expect(u.hunterCombat).toBeUndefined();expect(requestXX(s,u,{x:20,y:10},99).ok).toBe(false);});
test.each([.1,1,2])('xx source timeline under %sx simulation speed releases at own time',speed=>{const {s,u}=fixture();command(s,{type:'xxInput',id:u.id,aim:{x:25,y:10}});command(s,{type:'xxInput',id:u.id,held:false});for(let i=0;i<Math.ceil(.08/(.01*speed));i++)step(s,.01*speed,.01);step(s,.04*speed,.04);expect(xxState(u).trace.filter(e=>e.name==='hit_start')).toHaveLength(1);expect(xxState(u).trace.find(e=>e.name==='hit_start')!.time).toBe(.08333333);});
test('unselected and Tower entry preserve frozen Hunter profile; no persistent xx selection',()=>{const s=createGame();expect(command(s,{type:'xxExperiment',enabled:true}).ok).toBe(false);command(s,{type:'selectJourney',journey:'exploration'});command(s,{type:'selectExplorationCompanion',id:'ranger'});command(s,{type:'xxExperiment',enabled:true});command(s,{type:'xxExperiment',enabled:false});command(s,{type:'carry',gold:0,vitality:0});expect(s.units.find(u=>u.id==='hunter')!.basicProfileId).toBe('hunter-v2');expect(XX_PROFILE.stages.map(d=>d.damage)).toEqual([15,15,20,35]);});

test('unengaged unknown enemy is absent from tactical targets; empty swing cannot discover it',()=>{const {s,u}=fixture();const e=structuredClone(u);e.id='unknown';e.team='enemy';e.xxCombat=undefined;e.basicProfileId=undefined;e.encounterRoom='unknown-room';e.pos={x:27,y:10};e.ready=999;e.hp=1000;s.units.push(e);command(s,{type:'xxInput',id:u.id,held:true,aim:e.pos});command(s,{type:'xxInput',id:u.id,held:false});for(let i=0;i<50;i++)step(s,.01);expect(e.hp).toBe(1000);expect(xxState(u).trace.some(e=>e.name==='contact')).toBe(false);});
test('Z handoff retains accepted action; released companion may start only ordinary xx basic',()=>{const {s,u}=fixture();requestXX(s,u,{x:20,y:10},1);const action=xxState(u).action;command(s,{type:'controlBody',id:'ranger'});expect(xxState(u).action).toBe(action);expect(u.ai?.handoffPending).toBe(true);expect(requestXX(s,u,{x:20,y:10},99).ok).toBe(false);expect(requestXX(s,u,{x:20,y:10},99,'companion-ai').ok).toBe(true);cancelXX(s,u,'test');expect(requestXX(s,u,{x:20,y:10},100,'companion-ai').ok).toBe(true);expect(xxState(u).action?.pose).toBe('atk2');expect(u.skillSlots).toEqual([null,null,null]);});

test('main AI after Z uses xx ordinary action against an engaged encounter',()=>{const {s,u}=fixture();const e=structuredClone(u);const al=s.units.find(u=>u.id==='ranger')!;al.pos={x:15,y:12};al.drawPos={...al.pos};e.id='enemy-ai';e.team='enemy';e.basicProfileId=undefined;e.xxCombat=undefined;e.hp=e.maxHp=1000;e.ready=999;e.pos={x:16,y:10};e.drawPos={...e.pos};e.encounterRoom=s.exploration!.definition.encounters![0].room;e.pursuitTargetId=u.id;s.units.push(e);requestXX(s,u,e.pos,1);command(s,{type:'controlBody',id:'ranger'});for(let i=0;i<150;i++)step(s,.01);expect(xxState(u).trace.filter(e=>e.name==='accepted').length).toBeGreaterThan(1);expect(e.hp).toBeLessThan(1000);expect(u.hunterCombat).toBeUndefined();expect(s.units.filter(u=>isPartyBody(s,u))).toHaveLength(2);});
