import {expect,it} from 'vitest';
import {createGame,command,step} from '../src/core/engine';
function setup(role='melee') {const s=createGame();command(s,{type:'selectJourney',journey:'exploration'});command(s,{type:'selectExplorationCompanion',id:'ines'});command(s,{type:'carry',gold:0,vitality:0});s.tiles.forEach(t=>{t.obstacle=false;t.layer=0;});const h=s.units[0],p=s.units.find(u=>u.id==='ines')!,e=s.units.find(u=>u.team==='enemy')!;s.units=[h,p,e];h.pos={x:10,y:10};p.pos={x:10.1,y:10.3};e.pos={x:9,y:10};e.role=role as any;e.ready=0;e.path=[];e.enemySense!.home={...e.pos};e.pursuitTargetId=h.id;e.enemyMotion='engaged';h.attackTimer=p.attackTimer=100;return {s,h,p,e};}
it('intent follows a target until lock then keeps a frozen geometry',async()=>{const {startIntent,tickIntent}=await import('../src/core/attack-intent');const {s,h,e}=setup();startIntent(s,e,h);expect(e.attackIntent?.phase).toBe('tracking');const old=e.attackIntent!.area;s.time=.1;h.pos={x:9,y:11};tickIntent(s,e,.1);expect(e.attackIntent!.area).not.toEqual(old);s.time=.35;tickIntent(s,e,.25);expect(e.attackIntent!.phase).toBe('locked');const locked=JSON.stringify(e.attackIntent!.area);h.pos={x:8,y:10};s.controlledBodyId='ines';s.time=.5;tickIntent(s,e,.15);expect(JSON.stringify(e.attackIntent!.area)).toBe(locked);});
for(const reason of ['dead','stun','return','noTarget'])it('intent cancels for '+reason,async()=>{const {startIntent,tickIntent}=await import('../src/core/attack-intent');const {s,h,e}=setup();startIntent(s,e,h);if(reason==='dead')e.life='dead';if(reason==='stun')e.statuses.push({kind:'stun',remaining:1,power:0});if(reason==='return')e.enemyMotion='return';if(reason==='noTarget')e.pursuitTargetId=undefined;s.time=.9;expect(tickIntent(s,e,.9)).toBeNull();expect(e.attackIntent).toBeUndefined();});
it('same enemy cannot start overlapping intents or refund its cycle',async()=>{const {startIntent}=await import('../src/core/attack-intent');const {s,h,e}=setup('heavy');e.attackPeriod=.1;expect(startIntent(s,e,h)).toBe(true);const a=e.attackIntent;expect(e.attackTimer).toBeCloseTo(1);expect(startIntent(s,e,h)).toBe(false);expect(e.attackIntent).toBe(a);});
for(const [role,total,lock] of [['melee',.55,.35],['ranged',.75,.45],['heavy',.9,.55]] as const)it(role+' uses the expected lock and resolve and stops moving',()=>{const {s,h,e}=setup(role);if(role==='ranged'){e.weapons[0].range=4;e.weapons[0].remote=true;}step(s,.05);expect(e.attackIntent).toBeDefined();expect(e.attackIntent!.resolveAt-e.attackIntent!.startedAt).toBeCloseTo(total);expect(e.attackIntent!.lockAt-e.attackIntent!.startedAt).toBeCloseTo(lock);const pos={...e.pos};h.pos={x:10,y:10.3};step(s,.2);expect(e.pos).toEqual(pos);});
it('heavy resolves against both originals inside and excludes bodies outside and enemies',()=>{const {s,h,p,e}=setup('heavy');const hp=[h.hp,p.hp,e.hp];step(s,.05);step(s,1);expect(h.hp).toBeLessThan(hp[0]);expect(p.hp).toBeLessThan(hp[1]);expect(s.stats.telegraphHits).toBe(2);expect(e.hp).toBe(hp[2]);expect(e.attackIntent).toBeUndefined();});
it('moving outside locked area is a complete position avoid without hit events',()=>{const {s,h,p,e}=setup();p.life='withdrawn';step(s,.05);step(s,.35);const hp=h.hp,posture=h.posture;h.pos={x:9,y:12};step(s,.2);expect(h.hp).toBe(hp);expect(h.posture).toBe(posture);expect(s.stats.telegraphPositionAvoids).toBe(1);expect(s.stats.telegraphHits||0).toBe(0);});
it('active evade, early evade and normal hit retain distinct outcomes',()=>{const {s,h,p,e}=setup('heavy');h.life='withdrawn';p.pos={x:9.8,y:10};s.controlledBodyId='ines';step(s,.05);step(s,.83);expect(command(s,{type:'evade',id:'ines',direction:{x:1,y:0}}).ok).toBe(true);const hp=p.hp,posture=p.posture;step(s,.07);expect(p.hp).toBe(hp);expect(p.posture).toBe(posture);expect(s.stats.activeEvades).toBe(1);expect(s.stats.telegraphPositionAvoids||0).toBe(0);});
it('an early evade window expires before the area hit',()=>{const {s,h,p,e}=setup('heavy');h.life='withdrawn';p.pos={x:9.7,y:10};s.controlledBodyId='ines';step(s,.05);step(s,.7);expect(command(s,{type:'evade',id:'ines',direction:{x:0,y:1}}).ok).toBe(true);const hp=p.hp;step(s,.2);expect(p.hp).toBeLessThan(hp);expect(s.stats.activeEvades||0).toBe(0);});
it('ranged line hits the inside original but a side step completely avoids it',()=>{const {s,h,p,e}=setup('ranged');e.weapons[0].range=4;e.weapons[0].remote=true;p.pos={x:11,y:10};step(s,.05);step(s,.45);h.pos={x:10,y:11};const hp=h.hp,other=p.hp;step(s,.3);expect(h.hp).toBe(hp);expect(p.hp).toBeLessThan(other);expect(s.stats.telegraphHits).toBe(1);expect(s.stats.telegraphPositionAvoids).toBe(1);});
it('hunter blink escapes a locked sector without receiving an evade window',()=>{const {s,h,p}=setup();p.life='withdrawn';step(s,.05);step(s,.35);expect(command(s,{type:'blink',id:'hunter',direction:{x:0,y:1}}).ok).toBe(true);const hp=h.hp;step(s,.2);expect(h.hp).toBe(hp);expect(s.stats.telegraphPositionAvoids).toBe(1);expect(s.stats.activeEvades||0).toBe(0);});
it('death during windup leaves no active intent at the next step',()=>{const {s,e}=setup();step(s,.05);e.life='dead';step(s,.05);expect(e.attackIntent).toBeUndefined();});
it('single source cadence includes windup rather than adding a second period',()=>{const {s,h,p,e}=setup();p.life='withdrawn';h.maxHp=h.hp=10000;const starts:number[]=[];for(let i=0;i<60;i++){const prior=s.stats.telegraphsStarted||0;step(s,.05);if((s.stats.telegraphsStarted||0)>prior)starts.push(s.time);}expect(starts.length).toBeGreaterThan(2);expect(starts[1]-starts[0]).toBeCloseTo(1.1);});

it('heavy can begin at its template reach rather than the old one-unit weapon reach',()=>{const {s,h,p,e}=setup('heavy');p.life='withdrawn';h.pos={x:10.25,y:10};step(s,.05);expect(e.attackIntent).toBeDefined();});
it('debug shows current bodies in the area and hides unknown source intents',async()=>{const {standaloneSummary}=await import('../src/core/standalone-summary');const {s,h,p,e}=setup('heavy');step(s,.05);expect(standaloneSummary(s)!.telegraphs[0]).toMatchObject({source:e.id,inside:2});e.pos={x:50,y:50};expect(standaloneSummary(s)!.telegraphs).toEqual([]);});
it('start immediately commits battle engagement and finite tracking respects turn speed',async()=>{const {startIntent,tickIntent}=await import('../src/core/attack-intent');const {s,h,e}=setup();s.context='explorationIdle';startIntent(s,e,h);expect(s.context).toBe('explorationBattle');const heading=e.attackIntent!.heading;h.pos={x:8,y:10};s.time=.1;tickIntent(s,e,.1);expect(Math.abs(e.attackIntent!.heading-heading)).toBeLessThanOrEqual(Math.PI*.1+1e-7);});
for(const reason of ['stage','ruleset'])it('intent clears after '+reason+' invalidation',async()=>{const {startIntent,tickIntent}=await import('../src/core/attack-intent');const {s,h,e}=setup();startIntent(s,e,h);if(reason==='stage')s.phase='ended';if(reason==='ruleset')s.exploration=undefined;expect(tickIntent(s,e,.1)).toBeNull();expect(e.attackIntent).toBeUndefined();});
it('area hits never include a clone, withdrawn companion or unavailable body',async()=>{const {intentTargets}=await import('../src/core/attack-intent');const {s,h,p,e}=setup('heavy');const clone={...structuredClone(p),id:'test-clone',cloneOf:p.id};s.units.push(clone);step(s,.05);expect(intentTargets(s,e.attackIntent!).map(u=>u.id)).toEqual([h.id,p.id]);p.life='withdrawn';h.ready=1;expect(intentTargets(s,e.attackIntent!)).toEqual([]);});
it('resolved enemy attack consumes weapon durability once and shares one cast across both bodies',()=>{const {s,h,p,e}=setup('heavy');const durability=e.weapons[0].durability;step(s,.05);step(s,.9);expect(e.weapons[0].durability).toBe(durability-1);const events=s.combatEvents!.filter(v=>v.sourceId===e.id);expect(events).toHaveLength(2);expect(events[0].castId).toBe(events[1].castId);});
it('attack snapshot retains the existing mental and attack status multipliers',async()=>{const {startIntent}=await import('../src/core/attack-intent');const {s,h,e}=setup();e.mental='inspired';e.mentalTime=1;e.statuses.push({kind:'attack',remaining:1,power:.2});startIntent(s,e,h);expect(e.attackIntent!.damage).toBeCloseTo(e.weapons[0].damage*1.25*1.2);});
