import {expect,it} from 'vitest';
import {createGame} from '../src/core/engine';
const area=()=>import('../src/core/attack-area');
it('circle body grazing and epsilon do not reduce hit detection to centre points',async()=>{const {intersectsArea}=await area();const a={kind:'circle',center:{x:0,y:0},radius:1} as const;expect(intersectsArea(a,{x:1.18,y:0},.18)).toBe(true);expect(intersectsArea(a,{x:1.181,y:0},.18)).toBe(false);});
it('sector front, back, corner grazing and arc edge use the body circle',async()=>{const {intersectsArea}=await area();const a={kind:'sector',origin:{x:0,y:0},heading:0,range:1,arc:Math.PI/2} as const;for(const [p,r,want] of [[{x:.8,y:0},0,true],[{x:-.3,y:0},.18,false],[{x:.6,y:.75},.18,true],[{x:.6,y:.9},.18,false],[{x:1.1,y:0},.18,true]] as const)expect(intersectsArea(a,p,r)).toBe(want);});
it('capsule includes both rounded caps and rejects body entirely outside',async()=>{const {intersectsArea}=await area();const a={kind:'capsule',from:{x:0,y:0},to:{x:4,y:0},radius:.225} as const;expect(intersectsArea(a,{x:2,y:.4},.18)).toBe(true);expect(intersectsArea(a,{x:2,y:.406},.18)).toBe(false);expect(intersectsArea(a,{x:4.4,y:0},.18)).toBe(true);});
it('wall blocks sectors and truncates a ranged line before targets behind it',async()=>{const {areaHits,clipCapsule}=await area();const s=createGame();s.tiles.forEach(t=>{t.obstacle=false;t.layer=0;});s.tiles.find(t=>t.x===3&&t.y===3)!.obstacle=true;const u=s.units[0];u.pos={x:4,y:3};const a={kind:'sector',origin:{x:1,y:3},heading:0,range:4,arc:Math.PI/2} as const;expect(areaHits(s,a,u)).toBe(false);const c=clipCapsule(s,{kind:'capsule',from:{x:1,y:3},to:{x:5,y:3},radius:.225});expect(c.to.x).toBeLessThanOrEqual(2.5);expect(areaHits(s,c,u)).toBe(false);});

it('core drawing footprint cannot extend beyond an intervening wall',async()=>{const {areaFootprint}=await area();const s=createGame();s.tiles.forEach(t=>{t.obstacle=false;t.layer=0;});for(const t of s.tiles)if(t.x===3)t.obstacle=true;const vertices=areaFootprint(s,{kind:'sector',origin:{x:1,y:3},heading:0,range:4,arc:Math.PI/2});expect(vertices.length).toBeGreaterThan(3);expect(Math.max(...vertices.map(p=>p.x))).toBeLessThanOrEqual(2.5+1e-5);});
it('barricade obstructs the area and visible footprint together',async()=>{const {areaHits,areaFootprint}=await area();const s=createGame();s.tiles.forEach(t=>{t.obstacle=false;t.layer=0;});s.barricades=[{x:3,y:3}];const a={kind:'sector',origin:{x:1,y:3},heading:0,range:4,arc:Math.PI/2} as const,u=s.units[0];u.pos={x:4,y:3};expect(areaHits(s,a,u)).toBe(false);expect(Math.max(...areaFootprint(s,a).filter(p=>Math.abs(p.y-3)<.01).map(p=>p.x))).toBeLessThanOrEqual(2.5+1e-5);});
