import {test,expect} from 'vitest';
import {createGame,command,step,resolveHit} from '../src/core/engine';
import {canStop,enemyContact,distance} from '../src/core/spatial';
import {movementSpeed} from '../src/core/movement-speed';
import type {GameState,Unit} from '../src/core/types';

function explore(){const s=createGame();command(s,{type:'carry',gold:0,vitality:0});s.completed.push(1);s.phase='nodes';command(s,{type:'enter',node:4});return s;}
function arena(){const s=createGame();command(s,{type:'carry',gold:0,vitality:0});s.phase='battle';s.waveState=null;s.waves=[];s.totalEnemies=999;s.width=14;s.height=10;s.tiles=Array.from({length:140},(_,i)=>({x:i%14,y:Math.floor(i/14),layer:0,obstacle:false}));for(const u of s.units){u.life='reserve';u.ready=0;u.path=[];u.destination=null;}return s;}
function place(u:Unit,x:number,y:number){u.life='active';u.ready=0;u.pos={x,y};u.drawPos={...u.pos};}
function enemy(s:GameState,x:number,y:number){const e={...structuredClone(s.units[0]),id:'test-enemy',team:'enemy' as const,role:'melee' as const,cloneOf:undefined,life:'active' as const,pos:{x,y},drawPos:{x,y},speed:0,block:0,attackTimer:100,route:[],path:[],destination:null,enemyMotion:'route' as const};e.weapons=[{...e.weapons[0],remote:false,range:1,damage:0}];s.units.push(e);return e;}

// Catches retaining the idle multiplier or tying enemy movement to player speed.
test('player direct movement has the same 1.70 base in tower and exploration',()=>{for(const s of [arena(),explore()]){const h=s.units[0];place(h,3,16);if(!s.exploration)place(h,3,4);s.units=s.units.filter(u=>u.team==='ally');const x=h.pos.x;expect(command(s,{type:'direct',id:h.id,direction:{x:1,y:0}}).ok).toBe(true);step(s,.2);expect(h.pos.x-x).toBeCloseTo(.34,5);}});
test('enemy base is independent and direct movement preserves slow modifiers',()=>{const s=explore(),h=s.units[0],e=s.units.find(u=>u.team==='enemy')!;expect(e.speed).toBeCloseTo(1.275);h.statuses=[{kind:'slow',power:.5,remaining:5}];expect(movementSpeed(s,h,true)).toBeCloseTo(.85);h.speed=2;expect(e.speed).toBeCloseTo(1.275);});
test('exploration bodies may share an endpoint while tower bodies and copies retain spacing',()=>{for(const s of [explore(),arena()]){const h=s.units[0],g=s.units.find(u=>u.id==='ines')!;place(h,3,s.exploration?16:4);place(g,4,h.pos.y);expect(canStop(s,h.pos,g)).toBe(!!s.exploration);if(s.exploration){const copy={...structuredClone(h),id:'copy',cloneOf:'hunter',pos:{x:5,y:16}};s.units.push(copy);expect(canStop(s,copy.pos,g)).toBe(false);s.tiles.find(t=>t.x===6&&t.y===16)!.obstacle=true;expect(canStop(s,{x:6,y:16},g)).toBe(false);const e=s.units.find(u=>u.team==='enemy')!;e.pos={x:7,y:16};expect(enemyContact(s,e.pos)).toBe(true);expect(canStop(s,e.pos,g)).toBe(false);}}});

// Catches pursuit/damage-level first entry and attacks from uncommanded companions.
test('enemy detection and pursuit alone leave the party idle until attack windup is submitted',()=>{const s=explore(),h=s.units[0],e=s.units.find(u=>u.team==='enemy')!;place(h,8,15);command(s,{type:'partySelection',id:h.id});e.pos={x:10,y:15};e.enemySense!.home={...e.pos};h.weapons.forEach(w=>w.range=.1);step(s,.05);expect(e.pursuitTargetId).toBe(h.id);expect(s.context).toBe('explorationIdle');e.pos={x:8.8,y:15};e.path=[];e.attackTimer=0;step(s,.05);expect(e.attackPending).toBeDefined();expect(s.context).toBe('explorationBattle');expect((h as any).ai?.anchor).toEqual(h.pos);});
test('hunter attack windup snapshots body positions and stops following before damage',()=>{const s=explore(),h=s.units[0],g=s.units.find(u=>u.id==='ines')!,e=s.units.find(u=>u.team==='enemy')!;place(h,8,15);place(g,7,15);g.following=true;g.path=[{x:8,y:16}];g.destination={x:8,y:16};e.pos={x:11,y:15};e.enemySense!.home={...e.pos};e.attackTimer=100;e.speed=0;const hp=e.hp;step(s,.05);expect(h.attackPending).toBeDefined();expect(s.context).toBe('explorationBattle');expect(e.hp).toBe(hp);expect(g.following).toBe(false);expect((g as any).ai?.anchor).toEqual(g.pos);});
test('idle companions neither fire basics nor start automatic rain even at point blank',()=>{const s=explore(),r=s.units.find(u=>u.id==='ranger')!,e=s.units.find(u=>u.team==='enemy')!;place(r,8,15);command(s,{type:'partySelection',id:r.id});command(s,{type:'configureSkill',id:r.id,skillId:'rain'});r.skillCd=0;e.pos={x:9,y:15};e.life='active';e.enemySense=undefined;e.speed=0;e.attackTimer=100;step(s,1);expect(s.context).toBe('explorationIdle');expect(s.stats.rainArrows||0).toBe(0);expect(r.attackPending).toBeUndefined();expect(s.combatEvents||[]).toHaveLength(0);});
test('copy and ambient damage never start combat; body delayed damage only renews an already active battle',()=>{const s=explore(),h=s.units[0],e=s.units.find(u=>u.team==='enemy')!,copy={...structuredClone(h),id:'copy',cloneOf:h.id};resolveHit(s,e,h.weapons[0],1,copy);resolveHit(s,e,h.weapons[0],1);resolveHit(s,e,h.weapons[0],1,h,{derived:true});expect(s.context).toBe('explorationIdle');command(s,{type:'skill',id:h.id});h.skillCd=0;expect(command(s,{type:'skill',id:h.id}).ok).toBe(true);expect(s.context).toBe('explorationBattle');s.time=2;resolveHit(s,e,h.weapons[0],1,h,{derived:true});expect(s.exploration!.lastActivity).toBe(2);});

// Catches AI taking explicit orders, widening the radius, or drifting the anchor.
test('melee micro-movement enters range, keeps its anchor and returns after targets disappear',()=>{const s=arena(),g=s.units.find(u=>u.id==='ines')!;place(g,3,4);const e=enemy(s,4.9,4);step(s,.5);expect(g.pos.x).toBeGreaterThan(3.1);expect((g as any).ai.anchor).toEqual({x:3,y:4});expect(distance(g.pos,(g as any).ai.anchor)).toBeLessThanOrEqual(1);e.life='dead';step(s,2);expect(distance(g.pos,{x:3,y:4})).toBeLessThan(.1);});
test('selection and explicit paths immediately preempt autonomous movement in tower without UI dependence',()=>{const s=arena(),g=s.units.find(u=>u.id==='ines')!;place(g,3,4);enemy(s,4.9,4);step(s,.1);expect(g.path.length).toBeGreaterThan(0);const stopped={...g.pos};command(s,{type:'partySelection',id:g.id});expect(g.path).toHaveLength(0);step(s,.5);expect(g.pos).toEqual(stopped);command(s,{type:'partySelection',id:null});const p={x:2,y:4};expect(command(s,{type:'move',id:g.id,to:p}).ok).toBe(true);step(s,.4);expect(g.destination).toEqual(p);step(s,1);expect((g as any).ai.anchor).toEqual(p);});
test('held direct motion updates anchors after actual accumulated 0.75 travel and AI never overwrites it',()=>{const s=arena(),h=s.units[0];place(h,3,4);enemy(s,8,4);command(s,{type:'partySelection',id:h.id});command(s,{type:'direct',id:h.id,direction:{x:1,y:0}});step(s,.5);expect(h.direct?.direction).toEqual({x:1,y:0});expect((h as any).ai.anchor.x).toBeGreaterThan(3.7);command(s,{type:'direct',id:h.id,direction:null});expect(h.direct).toBeUndefined();});
test('tendency is configurable only during preparation and never spends currency or enlarges radius',()=>{const s=arena(),g=s.units.find(u=>u.id==='ines')!;s.phase='briefing';const money=s.fragments;expect(command(s,{type:'configureTendency',id:g.id,tendency:'preserve'} as any).ok).toBe(true);expect((g as any).aiTendency).toBe('preserve');expect(s.fragments).toBe(money);expect(command(s,{type:'configureTendency',id:g.id,tendency:'bad'} as any).ok).toBe(false);s.phase='battle';expect(command(s,{type:'configureTendency',id:g.id,tendency:'aggressive'} as any).ok).toBe(false);});
