import {test,expect} from 'vitest';
import {createGame,command,step,resolveHit} from '../src/core/engine';
import {advanceAutonomy,aiState,initializeAnchor,activityRadius} from '../src/core/autonomy';
import {attackCommit,updatePartyCombat} from '../src/core/exploration';
import {canStop,distance,clearShot,inWeaponRange} from '../src/core/spatial';
import {movementSpeed} from '../src/core/movement-speed';
import {currentSkill} from '../src/core/progression';
import type {GameState,Unit} from '../src/core/types';
function arena(){const s=createGame();command(s,{type:'carry',gold:0,vitality:0});s.phase='battle';s.waveState=null;s.waves=[];s.totalEnemies=999;s.width=14;s.height=10;s.tiles=Array.from({length:140},(_,i)=>({x:i%14,y:Math.floor(i/14),layer:0,obstacle:false}));for(const u of s.units){u.life='reserve';u.ready=0;}return s;}
function place(u:Unit,x:number,y:number){u.life='active';u.ready=0;u.pos={x,y};u.drawPos={...u.pos};}
function enemy(s:GameState,x:number,y:number){const e={...structuredClone(s.units[0]),id:'foe',team:'enemy' as const,role:'melee' as const,life:'active' as const,pos:{x,y},drawPos:{x,y},speed:0,attackTimer:100,route:[],path:[],destination:null};e.weapons=[{...e.weapons[0],remote:false,range:1,damage:0}];s.units.push(e);return e;}
function explore(){const s=createGame();command(s,{type:'carry',gold:0,vitality:0});s.completed.push(1);s.phase='nodes';command(s,{type:'enter',node:4});return s;}

test('preserve posture moves away from known attack danger only inside the same fixed radius',()=>{const s=arena(),g=s.units.find(u=>u.id==='ines')!;place(g,4,4);g.aiTendency='preserve';g.posture=1;const e=enemy(s,4.8,4);e.attackPending={targetId:g.id,remaining:1,facing:'west'};initializeAnchor(s,g);advanceAutonomy(s,.05);expect(g.destination).not.toBeNull();expect(distance(g.destination!,e.pos)).toBeGreaterThan(distance(g.pos,e.pos));expect(distance(g.destination!,g.ai!.anchor!)).toBeLessThanOrEqual(1.000001);});
test('remote ally finds a local clear firing point around light obstruction and never follows a distant target',()=>{const s=arena(),r=s.units.find(u=>u.id==='ranger')!;place(r,3,4);r.weapons[0].range=4;const e=enemy(s,6,4);s.tiles.find(t=>t.x===4&&t.y===4)!.obstacle=true;expect(clearShot(s,r.pos,e.pos)).toBe(false);initializeAnchor(s,r);advanceAutonomy(s,.05);expect(r.destination).not.toBeNull();expect(inWeaponRange(s,{...r,pos:r.destination!},e.pos,r.weapons[0])).toBe(true);expect(distance(r.destination!,{x:3,y:4})).toBeLessThanOrEqual(1);});
test('support tendency moves to cover a hurt ally without casting a manual skill or spending resources',()=>{const s=arena(),f=s.units.find(u=>u.id==='fiorre')!,g=s.units.find(u=>u.id==='ines')!;s.phase='briefing';command(s,{type:'weapon',id:f.id,index:0});s.phase='battle';place(f,3,4);place(g,6.5,4);g.hp=80;f.aiTendency='rescue';command(s,{type:'partySelection',id:g.id});initializeAnchor(s,f);f.ai!.commandUntil=0;currentSkill(f).cd=0;f.skillCd=0;const money=s.fragments;advanceAutonomy(s,.05);expect(f.destination).not.toBeNull();expect(distance(f.destination!,g.pos)).toBeLessThanOrEqual(3);expect(currentSkill(f).time).toBe(0);expect(s.fragments).toBe(money);});
test('AI never changes anchor, crosses layers or jitters its destination at every frame',()=>{const s=arena(),g=s.units.find(u=>u.id==='ines')!;place(g,3,4);enemy(s,4.9,4);initializeAnchor(s,g);advanceAutonomy(s,.01);const p={...g.destination!};for(let n=0;n<20;n++){s.time+=.01;advanceAutonomy(s,.01);expect(g.destination).toEqual(p);}expect(g.ai!.anchor).toEqual({x:3,y:4});expect(g.path.every(p=>distance(p,g.ai!.anchor!)<=1)).toBe(true);});
test('rejected command preserves AI intent; accepted weapon switch and recall preempt it',()=>{const s=arena(),g=s.units.find(u=>u.id==='ines')!;place(g,3,4);enemy(s,4.9,4);initializeAnchor(s,g);advanceAutonomy(s,.05);const p={...g.destination!};expect(command(s,{type:'move',id:g.id,to:{x:-1,y:4}}).ok).toBe(false);expect(g.destination).toEqual(p);expect(command(s,{type:'weapon',id:g.id,index:1}).ok).toBe(true);expect(g.path).toHaveLength(0);advanceAutonomy(s,1);expect(g.destination).toBeNull();});
test('calm clears battle anchors and preserves player path, economy and copy lifecycle',()=>{const s=explore(),h=s.units[0],g=s.units.find(u=>u.id==='ines')!;place(g,4,16);attackCommit(s,h);expect(g.ai!.anchor).toEqual(g.pos);const price=s.economy.draws;command(s,{type:'move',id:g.id,to:{x:5,y:16}});s.time=3;updatePartyCombat(s);expect(s.context).toBe('explorationIdle');expect(g.ai?.anchor).toBeUndefined();expect(g.destination).toEqual({x:5,y:16});expect(s.economy.draws).toBe(price);});
test('idle follow assigns separate soft slots and catchup applies only while actually following',()=>{const s=explore(),h=s.units[0],g=s.units.find(u=>u.id==='ines')!,r=s.units.find(u=>u.id==='ranger')!;place(h,6,16);place(g,2,16);place(r,2,17);s.units=s.units.filter(u=>u.team==='ally');step(s,.05);expect(g.following).toBe(true);expect(r.following).toBe(true);expect(distance(g.destination!,r.destination!)).toBeGreaterThan(.4);expect(movementSpeed(s,g)).toBeCloseTo(1.955);command(s,{type:'direct',id:g.id,direction:{x:1,y:0}});expect(g.following).toBe(false);expect(movementSpeed(s,g)).toBeCloseTo(1.7);});
test('selecting a crossing follower leaves its physical transition intact',()=>{const s=explore(),g=s.units.find(u=>u.id==='ines')!;place(g,4,16);g.following=true;g.crossing={from:{x:4,y:16},to:{x:4,y:17},elapsed:.2,switched:false};const crossing=g.crossing;command(s,{type:'partySelection',id:g.id});expect(g.crossing).toBe(crossing);});
test('commit precedes dodge and shield, copies and healing never create anchors',()=>{const s=explore(),h=s.units[0],e=s.units.find(u=>u.team==='enemy')!,copy={...structuredClone(h),id:'copy',cloneOf:h.id};attackCommit(s,copy,e);expect(s.context).toBe('explorationIdle');e.pos={x:3,y:16};e.drawPos={...e.pos};e.enemySense!.home={...e.pos};h.dodge=1;h.statuses=[{kind:'shield',power:100,remaining:5}];attackCommit(s,e,h);resolveHit(s,h,e.weapons[0],20,e);expect(s.context).toBe('explorationBattle');expect(h.ai!.anchor).toEqual(h.pos);expect(h.hp).toBe(h.maxHp);});
test('soft formation keeps lawful placements through a small leader reversal and selected body ownership',()=>{const s=explore(),h=s.units[0],g=s.units.find(u=>u.id==='ines')!;s.units=s.units.filter(u=>u.team==='ally');place(h,5,16);place(g,3.7,16.7);step(s,.4);const before={...g.pos};h.heading=Math.PI;h.pos.x-=.15;step(s,.05);expect(distance(g.pos,before)).toBeLessThan(.1);expect(canStop(s,g.pos,g)).toBe(true);command(s,{type:'partySelection',id:g.id});const stopped={...g.pos};h.pos.x+=2;step(s,.5);expect(g.pos).toEqual(stopped);});
test('an explicit skill toggle cancels an AI path immediately rather than adopting it as a player path',()=>{const s=arena(),r=s.units.find(u=>u.id==='ranger')!;place(r,3,4);r.weapons[0].range=1;enemy(s,4.9,4);initializeAnchor(s,r);advanceAutonomy(s,.05);expect(r.path.length).toBeGreaterThan(0);expect(command(s,{type:'skill',id:r.id}).ok).toBe(true);expect(r.path).toHaveLength(0);expect(r.ai!.intent).toBe('player');});
test('player dash relocates the anchor and does not return to a stale AI position',()=>{const s=arena(),h=s.units[0];place(h,3,4);initializeAnchor(s,h);const c=s.cards.find(c=>c.kind==='dash')!;expect(command(s,{type:'card',cardId:c.id,to:h.pos,targetId:h.id,direction:'east'}).ok).toBe(true);step(s,1);expect(h.pos).toEqual({x:4,y:4});expect(h.ai!.anchor).toEqual({x:4,y:4});});
test('manual exploration companion speed uses its own slow modifier while follow pace is independent',()=>{const s=explore(),g=s.units.find(u=>u.id==='ines')!;place(g,4,16);g.statuses=[{kind:'slow',power:.5,remaining:5}];command(s,{type:'direct',id:g.id,direction:{x:1,y:0}});const x=g.pos.x;step(s,.2);expect(g.pos.x-x).toBeCloseTo(.17);});
test('position-addressed dash also commits its new anchor without needing a target id',()=>{const s=arena(),h=s.units[0];place(h,3,4);initializeAnchor(s,h);const c=s.cards.find(c=>c.kind==='dash')!;expect(command(s,{type:'card',cardId:c.id,to:h.pos,direction:'east'}).ok).toBe(true);step(s,1);expect(h.pos).toEqual({x:4,y:4});});
test('completed group regroup establishes the new commanded position as the combat anchor',()=>{const s=arena(),h=s.units[0],g=s.units.find(u=>u.id==='ines')!;place(h,4,4);place(g,2.05,4);initializeAnchor(s,g);command(s,{type:'partySelection',id:h.id});expect(command(s,{type:'party',kind:'regroup'}).ok).toBe(true);step(s,1.05);expect(g.partyTask).toBeUndefined();expect(g.ai!.anchor).toEqual(g.pos);});
