import {test,expect} from 'vitest';
import {createGame,command,step} from '../src/core/engine';
import {distance} from '../src/core/spatial';
import type {GameState,Unit} from '../src/core/types';
import {mkdirSync,writeFileSync} from 'node:fs';

function arena(){const s=createGame();command(s,{type:'carry',gold:0,vitality:0});s.phase='battle';s.waveState=null;s.waves=[];s.totalEnemies=999;s.width=14;s.height=10;s.tiles=Array.from({length:140},(_,i)=>({x:i%14,y:Math.floor(i/14),layer:0,obstacle:false}));for(const u of s.units){u.life='reserve';u.ready=0;u.path=[];u.destination=null;}return s;}
function place(u:Unit,x:number,y:number,range=1){u.life='active';u.ready=0;u.pos={x,y};u.drawPos={...u.pos};u.weapons[u.weaponIndex].range=range;u.attackTimer=100;}
function enemy(s:GameState,x:number,y:number,id='target'){const e={...structuredClone(s.units[0]),id,team:'enemy' as const,role:'melee' as const,cloneOf:undefined,life:'active' as const,pos:{x,y},drawPos:{x,y},speed:0,block:0,attackTimer:100,route:[],path:[],destination:null,enemyMotion:'route' as const,ai:undefined};e.weapons=[{...e.weapons[0],remote:false,range:1,damage:0}];s.units.push(e);return e;}
function body(s:GameState){const g=s.units.find(u=>u.id==='ines')!;place(g,4,4);return g;}
const trace=(s:GameState,u:Unit,seconds:number)=>{const points=[];for(let t=0;t<seconds-1e-7;t+=.05){step(s,.05);points.push({...u.pos});}return points;};
function saveTrace(name:string,data:unknown){mkdirSync('../记录/验证/T-016',{recursive:true});writeFileSync('../记录/验证/T-016/'+name+'.json',JSON.stringify({fixture:'isolated flat arena; not normal-play evidence',data},null,2));}

// Missing target validation lets the old path finish and immediately reverses it.
test('Case A: target death stops the old approach now and observes before returning',()=>{const s=arena(),g=body(s),e=enemy(s,4,2.1);const approach=trace(s,g,.3);expect(g.pos.y).toBeLessThan(3.8);const stopped={...g.pos};e.life='dead';step(s,.05);expect(g.path).toEqual([]);expect(g.pos).toEqual(stopped);expect(g.ai?.phase).toBe('settle');const points=trace(s,g,.7);expect(points.every(p=>distance(p,stopped)<1e-6)).toBe(true);saveTrace('case-a',{approach,stopped,observe:points,phase:g.ai?.phase});});
// Coverage controls movement only: a second unit should not chase a covered small enemy.
test('Case B: a backliner does not walk toward a normal target already covered at the front',()=>{const s=arena(),back=body(s),front=s.units[0];place(front,5.2,3.4);enemy(s,5.9,4);const points=trace(s,back,.2);expect(back.pos).toEqual({x:4,y:4});expect(back.path).toEqual([]);saveTrace('case-b',{points,reason:back.ai?.rejectReason});});
// Proximity scoring alone can start a path although no point can ever land a hit.
test('Case C: getting closer without a legal attack point never drives movement',()=>{const s=arena(),g=body(s);enemy(s,6.3,4);const points=trace(s,g,.7);expect(g.pos).toEqual({x:4,y:4});expect(g.path).toEqual([]);saveTrace('case-c',{points,reason:g.ai?.rejectReason});});

test('a heavy target accepts a second mobile responder',()=>{const s=arena(),back=body(s),front=s.units[0];place(front,5.2,3.4);const e=enemy(s,5.9,4);e.role='heavy';step(s,.2);expect(back.pos.x).toBeGreaterThan(4.1);expect(back.ai?.targetId).toBe(e.id);});
test('a directly attacked body may respond despite existing ordinary coverage',()=>{const s=arena(),back=body(s),front=s.units[0];place(front,5.2,3.4);const e=enemy(s,5.9,4);e.attackPending={targetId:back.id,remaining:5,facing:'west'};step(s,.1);expect(back.pos.x).toBeGreaterThan(4);});
test('a route target that leaves before travel plus windup is not chased',()=>{const s=arena(),g=body(s),e=enemy(s,5.9,4);e.speed=20;e.route=[{x:5.9,y:4},{x:12,y:4}];e.routeIndex=1;step(s,.05);expect(g.pos).toEqual({x:4,y:4});expect(g.path).toEqual([]);});
test('settle accepts a new reachable task directly without a trip via the anchor',()=>{const s=arena(),g=body(s),e=enemy(s,4,2.1);step(s,.3);e.life='dead';step(s,.05);const y=g.pos.y;const next=enemy(s,4,5.7,'next');step(s,.1);expect(g.ai?.targetId).toBe(next.id);expect(g.ai?.phase).toBe('approach');expect(g.pos.y).toBeGreaterThan(y);expect(g.destination?.y).toBeGreaterThan(4.5);});
test('return finishes upon entering the comfort zone instead of snapping to the anchor',()=>{const s=arena(),g=body(s);g.ai={anchor:{x:4,y:4},intent:'hold',phase:'hold',nextDecision:0,movedAt:-10,commandUntil:0,directTravel:0};g.pos={x:4.9,y:4};g.drawPos={...g.pos};step(s,2);expect(distance(g.pos,{x:4,y:4})).toBeLessThanOrEqual(.35);expect(distance(g.pos,{x:4,y:4})).toBeGreaterThan(.1);expect(g.path).toEqual([]);});
test('new work interrupts a return path at its current position',()=>{const s=arena(),g=body(s);g.ai={anchor:{x:4,y:4},intent:'hold',phase:'hold',nextDecision:0,movedAt:-10,commandUntil:0,directTravel:0};g.pos={x:4.9,y:4};g.drawPos={...g.pos};step(s,.1);expect(g.ai?.phase).toBe('return');const x=g.pos.x,e=enemy(s,5.9,4);step(s,.05);expect(g.ai?.targetId).toBe(e.id);expect(g.pos.x).toBeGreaterThan(x);});
test('a player command clears the committed target and leaves the player path intact',()=>{const s=arena(),g=body(s);enemy(s,5.9,4);step(s,.1);expect(command(s,{type:'move',id:g.id,to:{x:3,y:4}}).ok).toBe(true);expect(g.ai?.phase).toBe('player');expect(g.ai?.task).toBeUndefined();step(s,.2);expect(g.destination).toEqual({x:3,y:4});});
test('support movement requires a usable installed support skill and a real coverage improvement',()=>{for(const cooldown of [0,10]){const s=arena(),g=body(s),f=s.units.find(u=>u.id==='fiorre')!;s.phase='briefing';expect(command(s,{type:'weapon',id:f.id,index:0}).ok).toBe(true);s.phase='battle';s.time=1;place(g,8,4);g.hp=100;place(f,4,4);f.ai=undefined;f.skillStates!.prayer.cd=cooldown;f.skillCd=cooldown;step(s,.2);if(cooldown===0){expect(f.pos.x).toBeGreaterThan(4);expect(f.ai?.task?.kind).toBe('support');}else expect(f.pos).toEqual({x:4,y:4});expect(f.skillTime).toBe(0);}});
test('equal new opportunities do not replace a valid committed target',()=>{const s=arena(),g=body(s),first=enemy(s,5.9,4,'first');step(s,.1);enemy(s,4,2.1,'other');step(s,.2);expect(g.ai?.targetId).toBe(first.id);expect(g.ai?.task?.startedAt).toBeLessThan(.2);});
test('a target that becomes impossible clears an in-flight autonomous path immediately',()=>{const s=arena(),g=body(s),e=enemy(s,5.9,4);step(s,.1);e.pos={x:10,y:4};const p={...g.pos};step(s,.05);expect(g.path).toEqual([]);expect(g.pos).toEqual(p);expect(g.ai?.phase).toBe('settle');});
test('normal stationary focus fire remains possible when movement coverage is saturated',()=>{const s=arena(),g=body(s),h=s.units[0];place(h,5.1,3.5);place(g,5.1,4.5);const e=enemy(s,5.8,4);g.attackTimer=h.attackTimer=0;const hp=e.hp;step(s,.5);expect(e.hp).toBeLessThan(hp);expect(s.combatEvents?.some(a=>a.sourceId===g.id)).toBe(true);expect(s.combatEvents?.some(a=>a.sourceId===h.id)).toBe(true);});
test('a successful task hit is recorded before later response coverage can release its commitment',()=>{const s=arena(),g=body(s),e=enemy(s,5.9,4);g.attackTimer=0;step(s,1.4);expect(g.ai?.task?.contributed).toBe(true);expect(e.hp).toBeLessThan(e.maxHp);});
test('rescue tendency without an actual equipped support effect does not create a fake support task',()=>{const s=arena(),g=body(s),h=s.units[0];g.aiTendency='rescue';place(h,6.2,4);h.hp=20;step(s,.5);expect(g.pos).toEqual({x:4,y:4});expect(g.ai?.task).toBeUndefined();});
test('a committed path and its contribution point never leave the fixed activity radius',()=>{const s=arena(),g=body(s);enemy(s,5.9,4);for(let i=0;i<20;i++){step(s,.05);expect(distance(g.pos,{x:4,y:4})).toBeLessThanOrEqual(1.000001);for(const p of g.path)expect(distance(p,{x:4,y:4})).toBeLessThanOrEqual(1.000001);}expect(g.ai?.anchor).toEqual({x:4,y:4});});
test('comfort zone holds an idle body without a precision return',()=>{const s=arena(),g=body(s);g.ai={anchor:{x:4,y:4},intent:'hold',phase:'hold',nextDecision:0,movedAt:-10,commandUntil:0,directTravel:0};g.pos={x:4.3,y:4};g.drawPos={...g.pos};step(s,2);expect(g.pos).toEqual({x:4.3,y:4});expect(g.path).toEqual([]);});
test('a staggered enemy remains an attackable contribution target',()=>{const s=arena(),g=body(s),e=enemy(s,5.9,4);e.stagger=1;step(s,.1);expect(g.pos.x).toBeGreaterThan(4);expect(g.ai?.targetId).toBe(e.id);});
test('critical reachable support can preempt an ordinary attack commitment',()=>{const s=arena(),f=s.units.find(u=>u.id==='fiorre')!,h=s.units[0];s.phase='briefing';command(s,{type:'weapon',id:f.id,index:0});s.phase='battle';s.time=1;place(f,4,4);f.ai=undefined;f.skillStates!.prayer.cd=0;f.skillCd=0;place(h,8,4);enemy(s,5.9,4);step(s,.1);expect(f.ai?.task?.kind).toBe('attack');h.hp=20;step(s,.05);expect(f.ai?.task?.kind).toBe('support');expect(f.ai?.targetId).toBe(h.id);expect(f.skillTime).toBe(0);});
test('normal attack selection honors a reachable committed target ahead of an ordinary closer target',()=>{const s=arena(),g=body(s),first=enemy(s,5.9,4,'first');g.block=0;step(s,.7);enemy(s,g.pos.x,g.pos.y+.7,'closer');g.attackTimer=0;step(s,.05);expect(g.attackPending?.targetId).toBe(first.id);});
test('an already attackable new target holds an outside-comfort body instead of triggering idle return',()=>{const s=arena(),g=body(s);g.ai={anchor:{x:4,y:4},intent:'hold',phase:'hold',nextDecision:0,movedAt:-10,commandUntil:0,directTravel:0};g.pos={x:4.8,y:4};g.drawPos={...g.pos};enemy(s,5.5,4);step(s,.1);expect(g.pos).toEqual({x:4.8,y:4});expect(g.ai?.phase).toBe('engage');expect(g.path).toEqual([]);});
