import {test,expect,type Page} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {route} from './enbal01-browser-helpers';
const out=fileURLToPath(new URL('../../work/CB-02-20261010/browser',import.meta.url));mkdirSync(out,{recursive:true});
test.setTimeout(180000);
async function enter(page:Page,preset='high-pressure-v1'){
 await page.setViewportSize({width:1920,height:1080});await page.goto('/?enemyPressure='+preset+'&v=cb02');await page.locator('[data-companion=ranger]').click();await page.locator('[data-action=carry]').click();await expect.poll(()=>page.evaluate(()=>['hunter','ranger'].every(id=>(window as any).prototype?.scene.unitVisuals.get(id)?.reference?.ready)),{timeout:40000}).toBe(true);
 await expect(page.locator('#hero-cluster .duo-stamina span')).toContainText('100/100');
 const empty=await page.evaluate(()=>{const p=(window as any).prototype,h=p.state.units.find((u:any)=>u.id==='hunter');return p.project({x:h.pos.x+2,y:h.pos.y-1});});await page.mouse.move(empty.x,empty.y);
}
async function facts(page:Page){return page.evaluate(()=>{const p=(window as any).prototype,s=p.state;return {time:s.time,scale:p.effectiveTimeScale,phase:s.phase,control:s.controlledBodyId,world:s.world?.id,visit:s.world?.visit,used:s.exploration?.memory.mechanisms,notice:s.notice,log:s.log,units:s.units.filter((u:any)=>u.team==='ally'&&!u.cloneOf).map((u:any)=>({id:u.id,pos:u.pos,life:u.life,ready:u.ready,crossing:u.crossing,landing:u.skillLanding,hp:u.hp,maxHp:u.maxHp,stamina:u.stamina,guard:u.hunterCombat?.special?.kind,ammo:u.alCombat?.ammo,hunter:u.hunterCombat?.trace,al:u.alCombat?.trace})),combat:s.combatIdentity?.trace,posture:s.postureRuntime?.trace};});}
async function save(page:Page,label:string){const f=await facts(page);writeFileSync(out+'/'+label+'.json',JSON.stringify(f,null,2));await page.screenshot({path:out+'/'+label+'.png'});return f;}
async function aim(page:Page,id:string){const p=await page.evaluate(id=>(window as any).prototype.project((window as any).prototype.state.units.find((u:any)=>u.id===id).pos),id);await page.mouse.move(p.x,p.y);}
async function keys(page:Page,held:Set<string>,next:string[]){for(const k of [...held])if(!next.includes(k)){await page.keyboard.up(k);held.delete(k);}for(const k of next)if(!held.has(k)){await page.keyboard.down(k);held.add(k);}}
async function walk(page:Page,to:{x:number;y:number},stopOnContact=false){
 const path=await route(page,to);expect(path.length).toBeGreaterThan(0);let i=0;const held=new Set<string>();
 try{for(let n=0;n<1300;n++){
  const d=await page.evaluate(()=>{const s=(window as any).prototype.state,h=s.units.find((u:any)=>u.id==='hunter');return {pos:h.pos,life:h.life,contact:s.combatIdentity.trace.find((r:any)=>r.type==='hit-outcome'&&r.context?.kind==='enemy'&&r.outcome?.hpLost>0&&r.outcome.targetId==='hunter')};});
  if(stopOnContact&&d.contact)return d.contact;if(Math.hypot(d.pos.x-to.x,d.pos.y-to.y)<.6)return;expect(d.life).toBe('active');while(i<path.length&&Math.hypot(path[i].x-d.pos.x,path[i].y-d.pos.y)<.25)i++;const goal=path[i]??to,dx=goal.x-d.pos.x,dy=goal.y-d.pos.y;await keys(page,held,[...(Math.abs(dx)>.12?[dx>0?'d':'a']:[]),...(Math.abs(dy)>.12?[dy>0?'s':'w']:[])]);await page.waitForTimeout(40);
 }}finally{await keys(page,held,[]);}throw Error('natural keyboard route deadline');
}
test('Hunter actual Accept drain/refusal/recovery, free input and 1280 original HUD click shield',async({page})=>{
 await enter(page);await page.keyboard.press('Space');await save(page,'01-full-1920');await page.keyboard.press('Space');await page.mouse.down();
 await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').stamina.current),{timeout:65000,intervals:[80]}).toBeLessThan(10);
 await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.notice),{timeout:10000}).toContain('体力不足');await page.mouse.up();await page.keyboard.press('Space');const drained=await save(page,'02-drained-1920');expect(drained.units.find((u:any)=>u.id==='hunter')!.stamina.nextAcceptedId).toBeGreaterThan(6);
 const paused=drained.time;await page.waitForTimeout(500);expect((await facts(page)).time).toBe(paused);await page.keyboard.press('Space');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').stamina.current),{timeout:25000}).toBeGreaterThan(50);
 await page.setViewportSize({width:1280,height:720});await page.keyboard.press('Space');const before=await facts(page);const boxes=await page.locator('.duo-stamina').evaluateAll(es=>es.map(e=>{const b=e.getBoundingClientRect(),fill=e.querySelector('i')!.getBoundingClientRect();return {x:b.x,y:b.y,w:b.width,h:b.height,fill:fill.width,text:e.textContent,hit:document.elementFromPoint(b.x+b.width/2,b.y+b.height/2)?.closest('.duo-stamina')!=null};}));expect(boxes).toHaveLength(2);for(const b of boxes){expect(b.x+b.w).toBeLessThanOrEqual(1280);expect(b.y+b.h).toBeLessThanOrEqual(720);expect(b.fill).toBeLessThanOrEqual(b.w);expect(b.hit).toBe(true);}
 await page.keyboard.press('Space');const count=(await facts(page)).units[0].stamina.nextAcceptedId;await page.locator('#hero-cluster .duo-stamina').click();await page.waitForTimeout(150);expect((await facts(page)).units[0].stamina.nextAcceptedId).toBe(count);await page.keyboard.press('Space');await save(page,'03-hud-1280');writeFileSync(out+'/hud-boxes.json',JSON.stringify({before,boxes},null,2));
});
test('Z real handoff Al actual four-shot ammo loop, own roll/E and source identity',async({page})=>{
 await enter(page);await page.mouse.down();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').stamina.current)).toBeLessThan(85);await page.mouse.up();const hunterBefore=(await facts(page)).units.find((u:any)=>u.id==='hunter')!.stamina.nextAcceptedId;
 await page.keyboard.press('z');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.controlledBodyId)).toBe('ranger');await expect(page.locator('#companion-cluster .duo-face img')).toHaveAttribute('src','/assets/ui/portraits/al-user.png');await page.mouse.down({button:'right'});
 await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').alCombat.trace.filter((r:any)=>r.kind==='ammo-payment').length),{timeout:25000,intervals:[30]}).toBe(4);await page.mouse.up({button:'right'});await page.keyboard.press('Space');const four=await save(page,'04-Al-four-shots-Z');const al=four.units.find((u:any)=>u.id==='ranger')!;expect(al.ammo).toBe(0);expect(al.stamina.nextAcceptedId).toBe(5);expect(four.units.find((u:any)=>u.id==='hunter')!.stamina.nextAcceptedId).toBe(hunterBefore);
 await page.keyboard.press('Space');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').alCombat.ammo)).toBe(4);await page.keyboard.press('Shift');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').stamina.nextAcceptedId)).toBe(6);await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').stamina.current),{timeout:15000}).toBeGreaterThan(50);await page.keyboard.press('e');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').alCombat.trace.some((r:any)=>r.kind==='land'))).toBe(true);await page.keyboard.press('Space');const active=await save(page,'05-Al-roll-rocket');expect(active.units.find((u:any)=>u.id==='ranger')!.stamina.nextAcceptedId).toBe(7);
});
test('Hunter held shield drains to zero, safely closes, frozen pause and release permits reenter',async({page})=>{
 await enter(page);await page.mouse.down({button:'right'});await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').stamina.guardExhausted),{timeout:90000,intervals:[40]}).toBe(true);const empty=await save(page,'06-guard-exhausted');const h=empty.units.find((u:any)=>u.id==='hunter')!;expect(h.guard).toBeUndefined();expect(h.stamina.current).toBeLessThan(8);
 await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').stamina.current),{timeout:12000}).toBeGreaterThan(20);const recovering=await facts(page);expect(recovering.units.find((u:any)=>u.id==='hunter')!.guard).toBeUndefined();expect(recovering.units.find((u:any)=>u.id==='hunter')!.stamina.nextAcceptedId).toBe(2);
 await page.mouse.up({button:'right'});await page.mouse.down({button:'right'});await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').hunterCombat.special?.kind)).toBe('guard');await page.mouse.up({button:'right'});await page.keyboard.press('Space');const frozen=await facts(page);await page.waitForTimeout(600);expect((await facts(page)).units[0].stamina.current).toBe(frozen.units[0].stamina.current);
});
test('baseline and high natural enemy contacts keep old HP authority while stamina and shield are real',async({page})=>{
 for(const preset of ['baseline','high-pressure-v1']){
  await enter(page,preset);await page.keyboard.press('AltLeft');const center=await page.evaluate(()=>{const s=(window as any).prototype.state,h=s.units.find((u:any)=>u.id==='hunter');return s.exploration.definition.encounters.filter((e:any)=>e.tier==='small').sort((a:any,b:any)=>Math.hypot(a.center.x-h.pos.x,a.center.y-h.pos.y)-Math.hypot(b.center.x-h.pos.x,b.center.y-h.pos.y))[0].center;});await walk(page,center,true);
  await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.combatIdentity.trace.find((r:any)=>r.type==='hit-outcome'&&r.context?.kind==='enemy'&&r.outcome?.hpLost>0&&r.outcome.targetId==='hunter')),{timeout:35000}).toBeTruthy();await page.keyboard.press('Space');const d=await save(page,'07-contact-'+preset),hit=d.combat.find((r:any)=>r.type==='hit-outcome'&&r.context?.kind==='enemy'&&r.outcome?.hpLost>0&&r.outcome.targetId==='hunter').outcome;expect(hit.rawPower).toBe(preset==='baseline'?5:123);expect(hit.hpLost).toBeCloseTo(preset==='baseline'?2:120);expect(hit.rawPosture).toBe(preset==='baseline'?15:54);
  await page.keyboard.press('Space');const enemy=await page.evaluate(()=>{const s=(window as any).prototype.state,h=s.units.find((u:any)=>u.id==='hunter');return s.units.filter((u:any)=>u.enemyV2&&u.life==='active').sort((a:any,b:any)=>Math.hypot(a.pos.x-h.pos.x,a.pos.y-h.pos.y)-Math.hypot(b.pos.x-h.pos.x,b.pos.y-h.pos.y))[0].id;});await expect.poll(()=>page.evaluate(()=>{const s=(window as any).prototype.state,h=s.units.find((u:any)=>u.id==='hunter');return s.time>=h.hunterCombat.hurtUntil;})).toBe(true);await aim(page,enemy);await page.mouse.down({button:'right'});
  await expect.poll(async()=>{await aim(page,enemy);return page.evaluate(()=>(window as any).prototype.state.combatIdentity.trace.some((r:any)=>r.type==='hit-outcome'&&r.context?.kind==='enemy'&&r.outcome.targetId==='hunter'&&r.outcome.hpLost===0&&r.outcome.postureApplied>0));},{timeout:45000,intervals:[80]}).toBe(true);await page.mouse.up({button:'right'});await page.keyboard.press('Space');await save(page,'08-guard-contact-'+preset);
 }
});
test('natural unused campfire restores stamina once; repeated button disabled with same world identity',async({page})=>{
 await enter(page,'baseline');await page.mouse.down();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').stamina.current)).toBeLessThan(85);await page.mouse.up();await page.keyboard.press('AltLeft');const p=await page.evaluate(()=>{const s=(window as any).prototype.state,h=s.units.find((u:any)=>u.id==='hunter');return s.exploration.definition.points.filter((p:any)=>p.kind==='campfire').sort((a:any,b:any)=>Math.hypot(a.pos.x-h.pos.x,a.pos.y-h.pos.y)-Math.hypot(b.pos.x-h.pos.x,b.pos.y-h.pos.y))[0];});await walk(page,p.pos);
 // Open the actual event UI first, then spend at the physical site. Capture only after pause;
 // a slow WebGL screenshot must not let idle recovery masquerade as campfire restoration.
 await expect.poll(()=>page.evaluate(()=>{const s=(window as any).prototype.state,h=s.units.find((u:any)=>u.id==='hunter');return s.context==='explorationIdle'&&h.ready<=0&&!h.basicAction&&!h.hunterCombat.special&&!h.crossing&&!h.skillLanding;}),{timeout:10000}).toBe(true);
 await page.locator('#exploration-objective summary').click();const button=page.locator(`[data-exploration-point="${p.id}"]`);await expect(button).toBeEnabled();const free=await page.evaluate(()=>{const p=(window as any).prototype,h=p.state.units.find((u:any)=>u.id==='hunter');return p.project({x:h.pos.x+2,y:h.pos.y-1});});await page.mouse.move(free.x,free.y);await page.mouse.down({button:'right'});await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').hunterCombat.special?.kind)).toBe('guard');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').stamina.current),{timeout:15000}).toBeLessThan(70);
 const before=await facts(page);expect(before.units.find((u:any)=>u.id==='hunter')!.stamina.current).toBeLessThan(70);writeFileSync(out+'/09-before-campfire.json',JSON.stringify(before,null,2));await page.mouse.up({button:'right'});await button.click();await page.keyboard.press('Space');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.exploration.memory.mechanisms)).toContain(p.id);await expect(button).toBeDisabled();const d=await save(page,'09-campfire');expect(d.units.find((u:any)=>u.id==='hunter')!.stamina.current).toBe(100);expect(d.used.filter((id:string)=>id===p.id)).toHaveLength(1);expect(d.world).toBe(before.world);
});
