import {test,expect} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
const dir='../work/R1-CL01A/cl-browser';mkdirSync(dir,{recursive:true});test.setTimeout(120000);
async function enter(page:any){await page.goto('/');await page.locator('[data-companion=ranger]').click();await page.locator('[data-action=carry]').click();await expect.poll(()=>page.evaluate(()=>['hunter','ranger'].every(id=>(window as any).prototype.scene.unitVisuals.get(id)?.reference?.ready)),{timeout:30000}).toBe(true);}
for(const [width,height] of [[1440,900],[1280,720]])test(`official start and real dual HUD at ${width}`,async({page})=>{
 await page.setViewportSize({width,height});await page.goto('/');await expect(page.getByRole('button',{name:'开始探索',exact:true})).toBeVisible();await expect(page.locator('[data-journey=tower],#selected-panel,#cards,#hand-drawer,[data-clone]')).toHaveCount(0);await page.screenshot({path:dir+`/entry-${width}.png`});
 await page.locator('[data-companion=ranger]').click();await page.locator('[data-action=carry]').click();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.unitVisuals.get('ranger')?.reference?.ready),{timeout:30000}).toBe(true);
 await expect(page.locator('#duo-status [data-body]')).toHaveCount(2);await expect(page.locator('#action-strip')).toContainText('方向格挡');await page.keyboard.press('z');await expect(page.locator('#action-strip')).toContainText('四发射击');await expect(page.locator('[data-body=ranger]')).toHaveClass(/controlled/);await page.screenshot({path:dir+`/battle-${width}.png`});
 const p=await page.evaluate(()=>{const p=(window as any).prototype,u=p.state.units.find((u:any)=>u.id==='ranger');return p.project({x:u.pos.x+1,y:u.pos.y});});await page.mouse.move(p.x,p.y);await page.mouse.down({button:'right'});await page.waitForTimeout(1200);await page.mouse.up({button:'right'});await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').alCombat.trace.some((r:any)=>r.kind==='ammo-payment'))).toBe(true);
 await page.keyboard.press('f');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.explorationControl?.aim?.kind)).toBe('path');await page.keyboard.press('Escape');await page.keyboard.down('g');await expect(page.locator('#tactic-wheel')).toBeVisible();await page.keyboard.press('Escape');await page.keyboard.up('g');
 const history=await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').alCombat.trace);writeFileSync(dir+`/actual-${width}.json`,JSON.stringify(history,null,2));
});
test('retired held keys and help/pause releases do not recall or reopen old UI',async({page})=>{
 await enter(page);await page.keyboard.press('Space');const before=await page.evaluate(()=>{const s=(window as any).prototype.state;return JSON.stringify({fragments:s.fragments,cards:s.cards,party:s.units.filter((u:any)=>u.team==='ally').map((u:any)=>({id:u.id,life:u.life,resident:u.shadowResident}))});});
 for(const k of ['q','h','b','Tab','c','v']){await page.keyboard.down(k);await page.waitForTimeout(70);await page.keyboard.up(k);}expect(await page.evaluate(()=>{const s=(window as any).prototype.state;return JSON.stringify({fragments:s.fragments,cards:s.cards,party:s.units.filter((u:any)=>u.team==='ally').map((u:any)=>({id:u.id,life:u.life,resident:u.shadowResident}))});})).toBe(before);await expect(page.locator('#hand-drawer,[data-clone],#selected-panel')).toHaveCount(0);
 await page.keyboard.press('Space');const p=await page.evaluate(()=>{const p=(window as any).prototype,u=p.state.units.find((u:any)=>u.id==='hunter');return p.project({x:u.pos.x+1,y:u.pos.y});});await page.mouse.move(p.x,p.y);await page.mouse.down();await page.waitForTimeout(300);await page.keyboard.press('Space');await page.mouse.up();await page.locator('[data-action=help]').first().click();await expect(page.locator('#help')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('#help')).toBeHidden();expect(await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').hunterCombat.held)).toBe(false);
 await page.locator('[data-action=abandon]').click();await page.locator('[data-action=cancel-economic]').click();await expect(page.locator('#economy-confirm')).toBeHidden();await page.locator('[data-action=abandon]').click();await page.locator('[data-action=confirm-economic]').click();await page.locator('[data-action=new]').click();await expect(page.locator('[data-action=carry]')).toBeVisible();await expect(page.locator('[data-journey=tower]')).toHaveCount(0);
});
test('explicit legacy and EN01 developer routes remain isolated',async({page})=>{await page.goto('/?legacy=1');await expect(page.locator('[data-journey=tower]')).toBeVisible();await expect(page.locator('#developer-route')).toContainText('历史');await page.goto('/?en01=1');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.some((u:any)=>!!u.enemyV2)),{timeout:30000}).toBe(true);});
