import {historicalTower} from './wave-fixtures';
import {createGame} from '../src/core/engine';
import {it,expect} from 'vitest';
import {command,step} from '../src/core/engine';
import {currentSkill} from '../src/core/progression';
import {writeFileSync} from 'node:fs';
it('A25 original map uses only initial balance and real kill income for old/new copies',()=>{
 const s=createGame(),log:any[]=[];const trace=(action:string)=>log.push({action,time:s.time,kills:s.kills,balance:s.fragments,hp:s.crystalHp,phase:s.phase});
 const act=(c:Parameters<typeof command>[1])=>{const r=command(s,c);expect(r.ok,r.reason).toBe(true);trace(c.type);};
 s.economy.account={gold:25,vitality:60};act({type:'carry',gold:5,vitality:40});expect(s.economy.account).toEqual({gold:20,vitality:20});expect(s.fragments).toBe(40);act({type:'weapon',id:'fiorre',index:0});act({type:'upgradeSkill',id:'ines',kind:'stage',expectedLevel:0});historicalTower(s);act({type:'start'});step(s,10.1);
 act({type:'deploy',id:'ranger',to:{x:3,y:4},facing:'east'});act({type:'deploy',id:'fiorre',to:{x:4,y:4},facing:'east'});act({type:'deploy',id:'ines',to:{x:2,y:6},facing:'east'});act({type:'move',id:'hunter',to:{x:3,y:5}});act({type:'skill',id:'ranger'});
 const advance=(predicate:()=>boolean)=>{for(let n=0;n<8000&&!predicate()&&s.phase==='battle';n++){for(const u of s.units.filter(u=>u.team==='ally'&&u.life==='active')){const st=currentSkill(u);if((u.skillId==='pain'&&st.counter>0||['hunt','prayer'].includes(u.skillId!)&&st.cd===0&&st.time===0)&&!u.path.length)command(s,{type:'skill',id:u.id});}step(s,.1);}trace('advance');if(!predicate())writeFileSync('../记录/验证/T-012/economy-failure.json',JSON.stringify({log,units:s.units},null,2));expect(predicate(),JSON.stringify(log)).toBe(true);};
 advance(()=>s.fragments>=20);act({type:'clone',id:'ines',to:{x:3,y:6}});const old=s.units.at(-1)!;expect(currentSkill(old).stage).toBe(1);
 advance(()=>s.fragments>=12);act({type:'upgradeSkill',id:'ines',kind:'branch',branch:'A',expectedLevel:0});expect(currentSkill(old).branches.A).toBeUndefined();
 advance(()=>s.fragments>=20);act({type:'clone',id:'ines',to:{x:2,y:5}});const fresh=s.units.at(-1)!;expect(currentSkill(fresh).branches.A).toBe(1);expect(s.units).toContain(old);
 act({type:'extract',id:'ranger',via:'shadow'});advance(()=>s.units.find(u=>u.id==='ranger')!.life==='withdrawn');act({type:'move',id:'hunter',to:{x:6,y:2}});advance(()=>currentSkill(old).counter>0||currentSkill(fresh).counter>0);const caster=currentSkill(old).counter>0?old:fresh;act({type:'skill',id:caster.id});act({type:'destroyClone',id:old.id});expect(s.units).toContain(fresh);
 act({type:'move',id:'hunter',to:{x:3,y:5}});act({type:'extract',id:'ines',via:'shadow'});advance(()=>s.fragments>=10);act({type:'draw',expectedPrice:10});const sold=s.cards.find(c=>c.group==='deck')!;act({type:'sellCard',cardId:sold.id});advance(()=>s.phase==='result');expect(s.units.some(u=>u.cloneOf)).toBe(false);expect(s.fragments).toBe(40+s.kills*4-24-20-12-20-10+2);expect(s.result).toBe('victory');const carried=s.fragments,terminal={result:s.result,kills:s.kills};act({type:'continue'});expect(s.economy.account).toEqual({gold:20,vitality:20});act({type:'safeExit'});expect(s.economy.account).toEqual({gold:25,vitality:20+carried});expect(s.fragments).toBe(0);expect(command(s,{type:'safeExit'}).ok).toBe(false);const hp=s.units[0].hp,durability=s.units[0].weapons[0].durability;act({type:'newExpedition'});act({type:'carry',gold:0,vitality:10});expect(s.units[0].hp).toBe(hp);expect(s.units[0].weapons[0].durability).toBe(durability);expect(s.fragments).toBe(10);writeFileSync('../记录/验证/T-012/normal-economy.json',JSON.stringify({...terminal,log,initial:40,carried,account:s.economy.account},null,2));
});
