import {describe,it,expect} from 'vitest';
import {arena,foe} from './rework-fixtures';
import {command,cloneTiles,step,resolveHit} from '../src/core/engine';
import {currentSkill} from '../src/core/progression';
import type {Command} from '../src/core/types';
function setup(){const s=arena(),h=s.units[0];h.life='active';h.pos={x:5,y:5};return {s,h};}
function summon(){const {s,h}=setup();expect(command(s,{type:'clone',id:h.id,to:{x:6,y:5}}).ok).toBe(true);return {s,h,c:s.units.at(-1)!};}
describe('R4 summon transaction',()=>{
 it('uses candidate footprint at map boundary without excluding its parent',()=>{const {s,h}=setup();h.bodyRadius=.7;const before=s.fragments,next=s.nextId;expect(cloneTiles(s,h.id)).not.toContainEqual({x:0,y:5});expect(command(s,{type:'clone',id:h.id,to:{x:0,y:5}}).ok).toBe(false);expect(command(s,{type:'clone',id:h.id,to:h.pos}).ok).toBe(false);expect(s.fragments).toBe(before);expect(s.nextId).toBe(next);});
 it('preview stops offering points when funds/source become unavailable',()=>{const {s,h}=setup();expect(cloneTiles(s,h.id).length).toBeGreaterThan(0);s.fragments=19;expect(cloneTiles(s,h.id)).toEqual([]);h.life='withdrawn';s.fragments=100;expect(command(s,{type:'clone',id:h.id,to:{x:6,y:5}}).ok).toBe(false);expect(s.fragments).toBe(100);});
 it('names instances stably and clears transient presentation without resetting mental policy',()=>{const {s,h}=setup();h.weapons[0].durability=17;h.hp=1;h.hitFlash=1;h.attackFlash=1;h.reveal=2;h.stress=42;h.path=[{x:9,y:5}];h.loadout={targetIndex:1,elapsed:.2,duration:.8};h.statuses=[{kind:'attack',power:2,remaining:10}];currentSkill(h).time=4;command(s,{type:'clone',id:h.id,to:{x:6,y:5}});const c=s.units.at(-1)!;expect(c.name).not.toBe(h.name+'·影');expect(c.hp).toBe(c.maxHp);expect(c.weapons[0].durability).toBe(17);expect(c.weaponIndex).toBe(0);expect(c.stress).toBe(42);expect([c.hitFlash,c.attackFlash,c.reveal]).toEqual([0,0,0]);expect(c.path).toEqual([]);expect(c.loadout).toBeUndefined();expect(c.statuses).toEqual([]);expect(c.skillTime).toBe(0);c.skillCd=3;expect(h.skillCd).not.toBe(3);});
});
describe('R4 lifetime',()=>{
 it('single destruction releases engagements immediately, clears owned cards and is idempotent',()=>{const {s,h,c}=summon(),e=foe(s,7,5);e.engagement={targetId:c.id,anchor:{x:7,y:5}};e.pursuitTargetId=c.id;e.route=[{x:9,y:5}];e.routeIndex=0;e.attackPending={targetId:c.id,remaining:.2,facing:'west'};s.cards.push({id:'bound',kind:'power',group:'exclusive',name:'bound',description:'',ownerId:c.id});const before=s.fragments;expect(command(s,{type:'destroyClone',id:c.id} as Command).ok).toBe(true);expect(s.units).toContain(h);expect(s.units).not.toContain(c);expect(e.engagement).toBeUndefined();expect(e.enemyMotion).toBe('return');expect(e.attackPending).toBeUndefined();expect(s.cards.some(x=>x.ownerId===c.id)).toBe(false);command(s,{type:'destroyClone',id:c.id} as Command);expect(s.fragments).toBe(before);});
 it('death removes body immediately without waiting another simulation tick',()=>{const {s,c}=summon(),e=foe(s);resolveHit(s,c,e.weapons[0],99999,e);expect(c.life).toBe('dead');expect(s.units).not.toContain(c);});
 it('end expedition removes clones and their owner card bindings',()=>{const {s,c}=summon();s.cards.push({id:'bound',kind:'power',group:'exclusive',name:'',description:'',ownerId:c.id});command(s,{type:'endExpedition'});expect(s.units.some(u=>u.cloneOf)).toBe(false);expect(s.cards.some(x=>x.ownerId===c.id)).toBe(false);});
 it('exploration combat context preserves clones; explicit node exit clears them and effects',()=>{const {s,c}=summon();s.ruleset='exploration';command(s,{type:'setContext',context:'explorationBattle'});step(s,.1);command(s,{type:'setContext',context:'explorationIdle'});expect(s.units).toContain(c);expect(command(s,{type:'leaveExplorationNode'} as Command).ok).toBe(true);expect(s.units).not.toContain(c);expect(s.skillEffects||[]).toEqual([]);});
});

it('exploration node exit terminates original maintained casts as well as copy effects',()=>{const {s,h}=setup();const u=s.units[2];u.life='active';u.pos={x:6,y:5};u.skillId='sanctuary';currentSkill(u).cd=0;s.ruleset='exploration';expect(command(s,{type:'skill',id:u.id}).ok).toBe(true);expect(currentSkill(u).run).toBeDefined();command(s,{type:'leaveExplorationNode'});expect(currentSkill(u).run).toBeUndefined();expect(u.skillTime).toBe(0);expect(h.direct).toBeUndefined();});
for(const life of ['withdrawn','downed','dead','respawning'] as const)it('parent '+life+' preserves existing copy but forbids new summon',()=>{const {s,h,c}=summon();h.life=life;const count=s.units.length,balance=s.fragments;expect(command(s,{type:'clone',id:h.id,to:{x:8,y:5}}).ok).toBe(false);expect(s.units.length).toBe(count);expect(s.units).toContain(c);expect(s.fragments).toBe(balance);});
it('birth strips crossing, recall, direct, landing and all running skill state without shared references',()=>{const {s,h}=setup();h.crossing={from:{x:5,y:5},to:{x:5,y:6},elapsed:.3,switched:false};h.afterCross={x:7,y:6};h.direct={direction:{x:1,y:0},trail:[{x:5,y:5}]};h.recall={elapsed:.1,waitingCross:true,repath:0};h.skillLanding={origin:{x:5,y:5},after:{x:9,y:5}};h.rescueTarget='somebody';h.attackPending={targetId:'enemy',remaining:.2,facing:'east'};currentSkill(h).counter=7;command(s,{type:'clone',id:h.id,to:{x:6,y:5}});const c=s.units.at(-1)!;for(const field of ['crossing','afterCross','direct','recall','skillLanding','attackPending'] as const)expect(c[field]).toBeUndefined();expect(c.rescueTarget).toBeNull();expect(c.skillCd).toBe(18);expect(currentSkill(c).counter).toBe(0);expect(c.weapons[0]).not.toBe(h.weapons[0]);expect(c.skillStates).not.toBe(h.skillStates);expect(c.defense).not.toBe(h.defense);});
it('copy core rejects movement, rescue, blink, collection, loadout, build, skill selection and dash without charging',()=>{const {s,c}=summon(),balance=s.fragments;const dash=s.cards.find(x=>x.kind==='dash')!;const cmds:Command[]=[{type:'move',id:c.id,to:{x:8,y:5}},{type:'direct',id:c.id,direction:{x:1,y:0}},{type:'blink',id:c.id,direction:{x:1,y:0}},{type:'collect',id:c.id},{type:'rescue',id:c.id},{type:'weapon',id:c.id,index:1},{type:'upgradeSkill',id:c.id,kind:'stage',expectedLevel:0},{type:'configureSkill',id:c.id,skillId:'hunt'},{type:'card',cardId:dash.id,to:c.pos,targetId:c.id,direction:'east'}];for(const cmd of cmds)expect(command(s,cmd).ok,cmd.type).toBe(false);expect(s.fragments).toBe(balance);expect(s.cards).toContain(dash);expect(c.shadowResident).toBe(false);});
