import {describe,it,expect} from 'vitest';
import {arena,foe} from './rework-fixtures';
import {command,step,resolveHit,createGame,createLegacyGuard} from '../src/core/engine';
import {currentSkill,resetNodeSkills} from '../src/core/progression';
import {resolveSkill} from '../src/core/skill-catalog';
import type {SkillId,Unit} from '../src/core/types';
function pair(id:SkillId){const s=arena(),index=['pain','sanctuary'].includes(id)?2:['snipe','rain'].includes(id)?3:id==='hunt'?0:1,u=s.units[index];u.life='active';u.pos={x:5,y:5};u.drawPos={...u.pos};u.weaponIndex=['prayer','ward'].includes(id)?0:id==='bell'?2:u.weaponIndex;u.skillId=id;currentSkill(u).stage=1;currentSkill(u).branches={};command(s,{type:'clone',id:u.id,to:{x:5,y:6}});const a=s.units.at(-1)!;command(s,{type:'clone',id:u.id,to:{x:4,y:5}});const b=s.units.at(-1)!;return {s,u,a,b};}
for(const id of ['pain','sanctuary','snipe','rain','dance','reap','prayer','ward','bell','hunt'] as SkillId[])describe(id+' clone independence',()=>{
 it('isolates weapon wear, snapshot stages, counters and clock mirrors across original and two copies',()=>{const {s,u,a,b}=pair(id);const parent=structuredClone(currentSkill(u)),before=b.weapons[0].durability;currentSkill(u).stage=2;currentSkill(a).counter=7;a.skillCd=3;a.weapons[0].durability=11;a.hp=1;expect(currentSkill(b).counter).toBe(0);expect(currentSkill(a).stage).toBe(1);expect(currentSkill(b).stage).toBe(1);expect(b.weapons[0].durability).toBe(before);expect(b.hp).toBe(b.maxHp);expect(u.skillCd).toBe(parent.cd);u.life='withdrawn';step(s,.1);expect(s.units).toContain(a);expect(s.units).toContain(b);expect(command(s,{type:'clone',id:u.id,to:{x:8,y:5}}).ok).toBe(false);});
});
it('multiple rain windows retain different clocks and do not consume basic weapon endurance',()=>{const {s,u,a,b}=pair('rain');u.life='withdrawn';foe(s,6,6);a.attackTimer=b.attackTimer=0;a.skillCd=0;b.skillCd=.2;const wear=[a.weapons[0].durability,b.weapons[0].durability];step(s,.1);expect(currentSkill(a).run!.fired).toBeGreaterThan(0);expect(currentSkill(b).run).toBeUndefined();step(s,.2);expect(currentSkill(a).run!.fired).toBeGreaterThan(currentSkill(b).run!.fired);expect(currentSkill(a).run).not.toBe(currentSkill(b).run);expect([a.weapons[0].durability,b.weapons[0].durability]).toEqual(wear);});
it('pain counters count actual direct hits per individual and launched echo survives single destroy',()=>{const {s,u,a,b}=pair('pain'),e=foe(s,6,6);resolveHit(s,a,e.weapons[0],20,e);expect(currentSkill(a).counter).toBe(1);expect(currentSkill(b).counter).toBe(0);u.hp=10;expect(command(s,{type:'skill',id:a.id}).ok).toBe(true);const hp=u.hp;command(s,{type:'destroyClone',id:a.id});step(s,.75);expect(u.hp).toBeGreaterThan(hp);expect(s.units).toContain(b);});
it('two sanctuary sources use strongest reduction rather than summed reduction and destroy settles field',()=>{const {s,u,a,b}=pair('sanctuary'),e=foe(s,5.5,5.5);a.skillCd=b.skillCd=0;currentSkill(a).stage=2;currentSkill(a).branches={B:2};command(s,{type:'skill',id:a.id});command(s,{type:'skill',id:b.id});step(s,6);expect(e.statuses.filter(st=>st.kind==='resistBreak').length).toBe(2);expect(Math.max(...e.statuses.filter(st=>st.kind==='resistBreak').map(st=>st.power))).toBeCloseTo(.7);command(s,{type:'destroyClone',id:a.id});expect(currentSkill(a).run).toBeUndefined();expect(e.statuses.find(st=>st.source==='field:'+a.id)?.power).toBe(.25);expect(currentSkill(b).run).toBeDefined();expect(u.skillTime).toBe(0);});
it('sniper and dance modes remain independent when parent switches modes or advances its build',()=>{for(const id of ['snipe','dance'] as const){const {s,u,a,b}=pair(id);currentSkill(a).enabled=true;currentSkill(b).enabled=false;currentSkill(u).enabled=false;currentSkill(u).stage=2;expect(currentSkill(a).enabled).toBe(true);expect(currentSkill(a).stage).toBe(1);command(s,{type:'skill',id:a.id});expect(currentSkill(a).enabled).toBe(false);expect(currentSkill(b).enabled).toBe(false);}});
it('two return scythes move virtual bodies independently and destroy removes only maintained seat',()=>{const {s,u,a,b}=pair('reap');u.life='withdrawn';foe(s,6,6);foe(s,5,5);currentSkill(a).counter=currentSkill(b).counter=5;currentSkill(a).branches={C:1};const positions=[{...a.pos},{...b.pos}];step(s,.1);expect(currentSkill(a).run).toBeDefined();expect(currentSkill(b).run).toBeDefined();expect(currentSkill(a).run!.outHits).not.toBe(currentSkill(b).run!.outHits);expect([a.pos,b.pos]).toEqual(positions);command(s,{type:'destroyClone',id:a.id});expect(s.skillEffects!.some(e=>e.sourceId===a.id&&e.kind==='seat')).toBe(false);expect(currentSkill(b).run).toBeDefined();});
it('healing and cooldown cards target one copy and not other clocks or buffs',()=>{const {s,u,a,b}=pair('prayer');u.life='withdrawn';a.hp=b.hp=1;a.skillCd=0;command(s,{type:'skill',id:a.id});step(s,1.1);expect(a.hp).toBeGreaterThan(1);expect(b.hp).toBeGreaterThan(1);const cool=s.cards.find(c=>c.kind==='cooldown')!;a.skillTime=0;a.skillCd=10;b.skillCd=10;command(s,{type:'card',cardId:cool.id,to:a.pos,targetId:a.id});expect(a.skillCd).toBe(0);expect(b.skillCd).toBe(10);const power=s.cards.find(c=>c.kind==='power')!;command(s,{type:'card',cardId:power.id,to:a.pos,targetId:a.id});expect(a.statuses.some(st=>st.kind==='attack')).toBe(true);expect(b.statuses.some(st=>st.kind==='attack')).toBe(false);});
it('clone shadow weapon fallback is independent and legacy guard poison remains shared per enemy',()=>{const s=arena(),u=createLegacyGuard({x:5,y:5});u.life='active';u.ready=0;u.attackTimer=0;s.units.push(u);command(s,{type:'clone',id:u.id,to:{x:5,y:6}});const a=s.units.at(-1)!;a.attackTimer=0;a.weapons[0].durability=1;foe(s,6,5.5);step(s,.4);expect(a.weaponIndex).toBe(1);expect(u.weaponIndex).toBe(0);expect(currentSkill(a).enabled).toBe(true);expect(s.units.find(e=>e.team==='enemy')!.poisonMeter).toBeGreaterThan(0);});
it('exploration does not pursue or retaliate on copies but environmental damage still kills',()=>{const {s,u,a,b}=pair('pain');s.ruleset='exploration';u.life='withdrawn';const e=foe(s,5,6);e.attackTimer=0;e.hp=10;step(s,.4);expect(e.engagement).toBeUndefined();expect(e.pursuitTargetId).toBeUndefined();expect(s.encounters?.some(x=>x.party)).toBeFalsy();resolveHit(s,b,e.weapons[0],99999);expect(s.units).not.toContain(b);expect(s.units).toContain(a);});
