import {expect,it} from 'vitest';
import {createGame,command,resolveHit,step} from '../src/core/engine';
import {movementSpeed} from '../src/core/movement-speed';
import {followParty} from '../src/core/party';
import {enterExploration,updateExplorationEnemy} from '../src/core/exploration';
import {inCombatDomain,pathSafeFromInactiveEncounters} from '../src/core/encounter-domain';
import {startIntent,tickIntent} from '../src/core/attack-intent';
import {visibleHazards,advanceCompanionCombat} from '../src/core/companion-combat';
import {ensureControlledBody} from '../src/core/direct-control';
import {simulationDelta} from '../src/interaction';
import {advanceTacticalFocus,focusTimeScale} from '../src/core/tactical-focus';
function fixture(){
 const s=createGame();command(s,{type:'selectJourney',journey:'exploration'});command(s,{type:'selectExplorationCompanion',id:'ranger'});command(s,{type:'carry',gold:0,vitality:0});
 s.tiles.forEach(t=>{t.obstacle=false;t.layer=0;});const h=s.units[0],p=s.units.find(u=>u.id==='ranger')!,e=s.units.find(u=>u.role==='heavy')!;s.units=[h,p,e];
 for(const u of s.units){u.pos={x:10,y:10};u.drawPos={...u.pos};u.path=[];u.destination=null;u.weapons.forEach(w=>w.weight=0);u.dodge=0;u.defense=undefined;u.ready=0;u.attackTimer=100;u.ai=undefined;u.statuses=[];}
 h.pos={x:15,y:10};p.pos={x:10,y:10};e.pos={x:14,y:10};e.enemySense!.home={x:14,y:10};p.life='active';e.enemyMotion='engaged';e.pursuitTargetId=h.id;e.encounterRoom=1;e.encounterId='fixture';e.enemyCombat!.armed=true;e.enemyCombat!.abilityReadyAt=100;
 s.context='explorationBattle';s.exploration!.lastActivity=0;s.exploration!.definition.encounters=[{room:1,center:{x:14,y:10},tacticalRadius:6.5,name:'fixture',tier:'normal',enemyIds:['fixture']}];return {s,h,p,e};
}
it.each([[2,1],[3,1.2],[4,1.45],[6,1.7]])('idle follower closes %sU with the approved relative speed', (d,m)=>{const {s,h,p}=fixture();s.context='explorationIdle';h.pos={x:20,y:10};p.pos={x:20-d,y:10};p.following=true;expect(movementSpeed(s,p)).toBeCloseTo(2.4*m);});
it('far follower heads toward the leader and resumes formation after catching up',()=>{const {s,h,p}=fixture();s.context='explorationIdle';h.pos={x:25,y:10};followParty(s,.1);expect(p.destination!.x).toBeGreaterThan(23);expect(p.ai!.catchingUp).toBe(true);p.pos={x:23,y:10};s.time=.2;followParty(s,.1);expect(p.ai!.catchingUp).toBe(false);});
it('engaged chaser continues beyond the old home radius and detects target out to pursuit range',()=>{const {s,h,e}=fixture();h.pos={x:25,y:10};e.pos={x:23,y:10};updateExplorationEnemy(s,e);expect(e.pursuitTargetId).toBe(h.id);expect(e.enemySense!.lostAt).toBeUndefined();});
it('chaser pursues lastSeen through a 4.5 second search before returning',()=>{const {s,h,p,e}=fixture();p.life='withdrawn';e.enemySense!.home={x:12,y:10};h.pos={x:16,y:10};updateExplorationEnemy(s,e);s.tiles.find(t=>t.x===15&&t.y===10)!.obstacle=true;updateExplorationEnemy(s,e);s.time=2;updateExplorationEnemy(s,e);expect(e.pursuitTargetId).toBe(h.id);expect(e.enemySense!.lastSeen).toEqual({x:16,y:10});s.time=4.6;updateExplorationEnemy(s,e);expect(e.enemyMotion).toBe('return');});
it('18U escape and territorial home boundary release pursuit',()=>{const {s,h,p,e}=fixture();p.life='withdrawn';h.pos={x:35,y:10};updateExplorationEnemy(s,e);expect(e.pursuitTargetId).toBeUndefined();h.pos={x:25,y:10};e.pos={x:23,y:10};e.pursuitTargetId=h.id;e.enemySense!.pursuitPolicy='territorial';updateExplorationEnemy(s,e);expect(e.pursuitTargetId).toBeUndefined();});
it('active chase extends combat domain beyond the old room while inactive detection still rejects paths',()=>{const {s,h,e}=fixture();h.pos={x:28,y:10};e.pos={x:27,y:10};expect(inCombatDomain(s,{x:28,y:11})).toBe(true);expect(pathSafeFromInactiveEncounters(s,[{x:27,y:10},{x:28,y:11}])).toBe(true);const other=structuredClone(e);other.id='inactive';other.encounterRoom=2;other.pursuitTargetId=undefined;other.enemyMotion='route';other.pos={x:31,y:10};s.units.push(other);expect(pathSafeFromInactiveEncounters(s,[{x:27,y:10},{x:28,y:11}])).toBe(false);});
it.each([['melee',.22,.10],['ranged',.30,.14],['heavy',.36,.18]] as const)('%s Basic locks and releases quickly without AI emergency hazard', (role,total,lock)=>{const {s,h,e}=fixture();e.role=role;h.pos={x:15,y:10};expect(startIntent(s,e,h)).toBe(true);expect(visibleHazards(s)).toEqual([]);s.time=lock;tickIntent(s,e,lock);expect(e.attackIntent!.phase).toBe('locked');s.time=total;expect(tickIntent(s,e,total-lock)?.kind).toBe('basic');});
it('repeated Basic areas do not consume companion Evade',()=>{const {s,p,e}=fixture();p.pos={x:15,y:10};e.pursuitTargetId=p.id;startIntent(s,e,p);advanceCompanionCombat(s);s.time=.2;advanceCompanionCombat(s);expect(p.evasion!.charges).toBe(2);expect(p.companionCombat!.hazardKey).toBeUndefined();});
it('low-threat Ability accepts imminent hit while dangerous Broken threat spends real mobility',()=>{const {s,p,e}=fixture();p.pos={x:15,y:10};p.aiTendency='aggressive';startIntent(s,e,p,'heavy-ground-slam');e.attackIntent!.damage=1;e.attackIntent!.postureDamage=1;advanceCompanionCombat(s);s.time=1;advanceCompanionCombat(s);expect(p.evasion!.charges).toBe(2);e.attackIntent!.postureDamage=100;p.posture=5;s.time=1.01;advanceCompanionCombat(s);expect(p.evasion!.charges).toBe(1);});
it('damage feedback shows actual HP loss after shield and aggregates only same cast',()=>{const {s,h,e}=fixture();e.directionalProfileId='neutral';e.statuses=[{kind:'shield',power:17,remaining:10}];const hp=e.hp;resolveHit(s,e,h.weapons[0],37,h,{castId:44,postureDamage:0});expect(e.hp).toBe(hp-20);expect(s.damageFloats!.map(f=>f.amount)).toEqual([20]);s.time=.05;resolveHit(s,e,h.weapons[0],10,h,{castId:44,postureDamage:0});expect(s.damageFloats!.map(f=>f.amount)).toEqual([30]);resolveHit(s,e,h.weapons[0],5,h,{castId:45,postureDamage:0});expect(s.damageFloats!.map(f=>f.amount)).toEqual([30,5]);});
it('zero HP loss emits no ordinary damage float',()=>{const {s,h,e}=fixture();e.statuses=[{kind:'shield',power:100,remaining:10}];resolveHit(s,e,h.weapons[0],10,h,{postureDamage:0});expect(s.damageFloats||[]).toEqual([]);});
it('new command focus starts window; repeat does not restart and programmatic handoff never creates it',()=>{const {s,h,p}=fixture();command(s,{type:'commandFocus',id:p.id});expect(s.tacticalFocus?.elapsed).toBe(0);s.tacticalFocus!.elapsed=.5;command(s,{type:'commandFocus',id:p.id});expect(s.tacticalFocus!.elapsed).toBe(.5);command(s,{type:'promoteCommandFocus'});expect(s.controlledBodyId).toBe(p.id);expect(s.tacticalFocus).toBeUndefined();p.life='downed';ensureControlledBody(s);expect(s.controlledBodyId).toBe(h.id);expect(s.tacticalFocus).toBeUndefined();});
it('takeover clears focus even when the actual movement is refused',()=>{const {s,p}=fixture();command(s,{type:'commandFocus',id:p.id});p.posture=0;command(s,{type:'promoteCommandFocus'});expect(command(s,{type:'direct',id:p.id,direction:{x:1,y:0}}).ok).toBe(false);expect(s.tacticalFocus).toBeUndefined();expect(s.controlledBodyId).toBe(p.id);p.posture=90;expect(command(s,{type:'direct',id:p.id,direction:{x:1,y:0}}).ok).toBe(true);});
it('explicit numerical time scale composes slow sources without speeding them up',()=>{expect(simulationDelta(.05,false,false,.2)).toBeCloseTo(.01);expect(simulationDelta(.05,false,false,.1)).toBeCloseTo(.005);expect(simulationDelta(.05,true,false,.2)).toBe(0);});
it('focus expires after real time independently of simulation and freezes while hidden',()=>{const {s,p}=fixture();command(s,{type:'commandFocus',id:p.id});expect(focusTimeScale(s)).toBeCloseTo(.2);step(s,.1);expect(focusTimeScale(s)).toBeCloseTo(.2);advanceTacticalFocus(s,.75);expect(focusTimeScale(s)).toBeCloseTo(.6);advanceTacticalFocus(s,5,true);expect(focusTimeScale(s)).toBeCloseTo(.6);advanceTacticalFocus(s,.75);expect(s.tacticalFocus).toBeUndefined();});
it.each(['melee','heavy'] as const)('%s approach uses deterministic probe or speed burst before Basic',role=>{const {s,h,p,e}=fixture();p.life='withdrawn';e.role=role;e.pos={x:12.5,y:10};h.pos={x:15,y:10};e.attackTimer=0;e.enemyCombat!.reactionReadyAt=100;step(s,.05);expect(e.enemyCombat!.approach).toBeDefined();const a=structuredClone(e.enemyCombat!.approach);const second=fixture();second.p.life='withdrawn';second.e.role=role;second.e.id=e.id;second.e.pos={x:12.5,y:10};second.h.pos={x:15,y:10};second.e.attackTimer=0;second.e.enemyCombat!.reactionReadyAt=100;step(second.s,.05);expect(second.e.enemyCombat!.approach).toEqual(a);});

it('leaving Standalone and starting a fresh exploration clears focus and damage feedback',()=>{const {s,h,p,e}=fixture();resolveHit(s,e,h.weapons[0],5,h,{postureDamage:0});command(s,{type:'controlBody',id:p.id});s.ruleset='tower';s.exploration=undefined;ensureControlledBody(s);expect(s.tacticalFocus).toBeUndefined();enterExploration(s,(id,name,role,pos,team)=>({...structuredClone(h),id,name,role,pos,team}));expect(s.damageFloats).toEqual([]);expect(s.tacticalFocus).toBeUndefined();});

it('Burst immediately resumes closing after Probe even with a pending path refresh clock',()=>{const {s,h,p,e}=fixture();p.life='withdrawn';e.pos={x:12.5,y:10};e.enemySense!.home={...e.pos};h.pos={x:15,y:10};e.attackTimer=0;e.navWait=.3;e.enemyCombat!.approach={phase:'probe',until:.05,burstSeconds:.3,speed:1.6,side:1,serial:0};const before=h.pos.x-e.pos.x;step(s,.1);expect(e.enemyCombat!.approach?.phase).toBe('burst');expect(h.pos.x-e.pos.x).toBeLessThan(before);});
it('a committed Reaction revokes the unfinished approach phase',async()=>{const {scheduleEnemyReaction}=await import('../src/core/enemy-combat');const {s,h,e}=fixture();e.enemyCombat!.approach={phase:'probe',until:1,burstSeconds:.3,speed:1.6,side:1,serial:0};expect(scheduleEnemyReaction(s,e,h)).toBe(true);expect(e.enemyCombat!.approach).toBeUndefined();});
