import {expect,test} from 'vitest';
import {createGame,command,step,resolveHit} from '../src/core/engine';
import {tickSpecial} from '../src/core/skill-execution';
import type {Command,GameState} from '../src/core/types';
import * as control from '../src/core/exploration-control';
import {advanceCompanionCombat} from '../src/core/companion-combat';
import {followParty} from '../src/core/party';
import {startIntent} from '../src/core/attack-intent';
import {evadeAI} from '../src/core/evasion';
import {skillState} from '../src/core/progression';
function fixture(){
 const s=createGame();command(s,{type:'selectJourney',journey:'exploration'});command(s,{type:'selectExplorationCompanion',id:'ranger'});command(s,{type:'carry',gold:0,vitality:0});
 s.tiles.forEach(t=>{t.obstacle=false;t.layer=0;});const h=s.units[0],p=s.units.find(u=>u.id==='ranger')!,e=s.units.find(u=>u.role==='heavy')!;
 s.units=[h,p,e];h.pos={x:15,y:10};p.pos={x:10,y:10};e.pos={x:14,y:10};for(const u of s.units){u.drawPos={...u.pos};u.path=[];u.destination=null;u.ready=0;u.attackTimer=100;u.hp=u.maxHp=10000;u.weapons.forEach(w=>w.weight=0);}
 e.enemyMotion='engaged';e.pursuitTargetId=h.id;e.enemySense!.home={...e.pos};e.encounterRoom=1;e.encounterId='fixture';e.enemyCombat!.abilityReadyAt=100;e.enemyCombat!.armed=true;
 s.context='explorationBattle';s.exploration!.definition.encounters=[{room:1,name:'fixture',tier:'strong',enemyIds:['fixture'],center:{x:13,y:10},tacticalRadius:6.5}];command(s,{type:'commandFocus',id:p.id});return {s,h,p,e};
}
const begin=(s:GameState,kind='path')=>command(s,{type:'beginCommandAim',kind} as Command);
const cancel=(s:GameState)=>command(s,{type:'cancelCommandAim'} as Command);
const reserved=(s:GameState,u:GameState['units'][number])=>control.commandReserved(s,u);
const ready=(s:GameState,u:GameState['units'][number])=>control.commandReservationReady(s,u);
test.each(['path','skill','mobility'])('official %s Aim records actor/time and yields only that actor',kind=>{const {s,h,p}=fixture();s.time=3;expect(begin(s,kind).ok).toBe(true);expect(s.explorationControl?.aim).toEqual({kind,actorId:p.id,source:'command',startedAt:3});expect(control.inputAuthority(s)).toBe('aim');expect(reserved(s,p)).toBe(true);expect(reserved(s,h)).toBe(false);expect(ready(s,p)).toBe(true);});
test('no focus, invalid kind and Legacy reject without changes',()=>{const {s}=fixture();command(s,{type:'commandFocus',id:null});const before=structuredClone(s);expect(begin(s).ok).toBe(false);expect(s).toEqual(before);command(s,{type:'commandFocus',id:'ranger'});expect(begin(s,'invalid').ok).toBe(false);const legacy=createGame();expect(begin(legacy).ok).toBe(false);expect(cancel(legacy).ok).toBe(false);});
test.each(['move','recall','party','rescue','loadout'])('existing player %s rejects Aim without modification',kind=>{const {s,p}=fixture();if(kind==='move'){p.ai={command:'move'} as any;p.path=[{x:11,y:10}];p.destination={x:11,y:10};}if(kind==='recall')p.recall={} as any;if(kind==='party')p.partyTask={} as any;if(kind==='rescue')p.rescueTarget='hunter';if(kind==='loadout')p.loadout={} as any;const before=structuredClone(s);expect(begin(s).ok).toBe(false);expect(s).toEqual(before);});
test('AI locomotion is withdrawn, not snapshotted or restored after cancel',()=>{const {s,p}=fixture();advanceCompanionCombat(s);expect(p.path.length).toBeGreaterThan(0);const old=p.path;expect(begin(s).ok).toBe(true);expect(p.path).toEqual([]);expect(p.destination).toBeNull();expect(p.companionCombat?.moving).toBe(false);advanceCompanionCombat(s);expect(p.companionCombat?.rejectReason).toBe('command-reserved');expect(p.path).toEqual([]);const focus=s.tacticalFocus;cancel(s);expect(s.tacticalFocus).toBe(focus);expect(s.explorationControl?.commandFocusId).toBe(p.id);expect(p.path).toEqual([]);advanceCompanionCombat(s);expect(p.path.length).toBeGreaterThan(0);expect(p.path).not.toBe(old);});
test('follow stops during Aim and replans toward current leader after cancellation',()=>{const {s,h,p}=fixture();s.context='explorationIdle';s.units=[h,p];followParty(s,.1);expect(p.following).toBe(true);const old=p.destination;begin(s);expect(p.following).toBe(false);h.pos={x:18,y:13};s.time+=1;followParty(s,.1);expect(p.path).toEqual([]);cancel(s);followParty(s,.1);expect(p.following).toBe(true);expect(p.destination).not.toEqual(old);});
test('pending Basic resolves normally once; new Basic is blocked until cancellation',()=>{const {s,p,e}=fixture();p.pos={x:15,y:10};p.facing='west';p.heading=Math.PI;p.attackPending={targetId:e.id,remaining:.1,facing:'west'};p.attackTimer=0;e.statuses=[{kind:'stun',power:0,remaining:100}];begin(s);expect(ready(s,p)).toBe(false);const hp=e.hp;step(s,.2);expect(e.hp).toBeLessThan(hp);const after=e.hp;expect(p.attackPending).toBeUndefined();expect(ready(s,p)).toBe(true);step(s,.6);expect(e.hp).toBe(after);expect(p.attackPending).toBeUndefined();cancel(s);step(s,3);expect(e.hp).toBeLessThan(after);});
test.each(['walking','evade','blink'])('reserved body does not start hazard %s and still takes real damage',kind=>{const {s,h,p,e}=fixture();const u=kind==='blink'?h:p;if(u===h){command(s,{type:'controlBody',id:p.id});command(s,{type:'commandFocus',id:h.id});}u.pos={x:kind==='walking'?15.5:15,y:10};startIntent(s,e,u,'heavy-ground-slam');begin(s);advanceCompanionCombat(s);s.time=kind==='walking'?.19:.95;const evade=u.evasion?.charges,blink=u.blink?.charges,hp=u.hp;advanceCompanionCombat(s);expect(u.path).toEqual([]);expect(u.evasion?.charges).toBe(evade);expect(u.blink?.charges).toBe(blink);step(s,1.2);expect(u.hp).toBeLessThan(hp);});
test('committed real Evade finishes while reserved; resources recharge independently',()=>{const {s,p}=fixture();expect(evadeAI(s,p,{x:1,y:0}).ok).toBe(true);const action=p.evasion!.action;begin(s);expect(p.evasion!.action).toBe(action);expect(ready(s,p)).toBe(false);step(s,.3);expect(p.evasion!.action).toBeUndefined();expect(p.pos.x).toBeCloseTo(11.2);expect(ready(s,p)).toBe(true);step(s,3);expect(p.evasion!.charges).toBe(2);});
test.each(['attack','skill','evade','forced','crossing','landing','stagger','stun','warmup'])('Ready is derived from committed %s, never stored',kind=>{const {s,p}=fixture();if(kind==='attack')p.attackPending={} as any;if(kind==='skill')skillState(p,'reap').run={} as any;if(kind==='evade')p.evasion!.action={} as any;if(kind==='forced')p.forcedMotion={} as any;if(kind==='crossing'){p.crossing={from:{...p.pos},to:{x:11,y:10},elapsed:0,switched:false};p.path=[{x:11,y:10}];p.companionCombat={moving:true} as any;}if(kind==='landing')p.skillLanding={origin:{...p.pos},path:[{x:11,y:10}]};if(kind==='stagger')p.stagger=1;if(kind==='stun')p.statuses=[{kind:'stun',power:0,remaining:1}];if(kind==='warmup')p.ready=1;const path=p.path;expect(begin(s).ok).toBe(true);expect(ready(s,p)).toBe(false);if(kind==='crossing')expect(p.path).toEqual(path);expect((s.explorationControl?.aim as any).ready).toBeUndefined();p.attackPending=undefined;p.skillStates={};p.evasion!.action=undefined;p.forcedMotion=undefined;p.crossing=undefined;p.skillLanding=undefined;p.stagger=0;p.statuses=[];p.ready=0;expect(ready(s,p)).toBe(true);});
test('background modes and cooldown keep running; new Rain is blocked, existing Rain completes',()=>{const {s,h,p,e}=fixture();p.skillSlots=['rain','snipe','poison'];for(const id of ['rain','snipe','poison'] as const){const st=skillState(p,id);st.cd=id==='rain'?0:1;st.enabled=id!=='rain';}begin(s);e.statuses=[{kind:'stun',power:0,remaining:100}];step(s,.5);expect(skillState(p,'rain').run).toBeUndefined();expect(skillState(p,'snipe').enabled).toBe(true);expect(skillState(p,'poison').enabled).toBe(true);expect(skillState(p,'snipe').cd).toBeCloseTo(.5);cancel(s);s.units=[h,p];step(s,.02);expect(skillState(p,'rain').run).toBeDefined();begin(s);const run=skillState(p,'rain').run;step(s,.1);expect(skillState(p,'rain').run).toBe(run);expect(run!.elapsed).toBeGreaterThan(0);step(s,6);expect(skillState(p,'rain').run).toBeUndefined();});
test('expired stun and background Dance do not falsely own Ready',()=>{const {s,p}=fixture();p.skillSlots=['dance','snipe','poison'];skillState(p,'dance').enabled=true;p.statuses=[{kind:'stun',power:0,remaining:0}];begin(s);expect(ready(s,p)).toBe(true);step(s,.1);expect(skillState(p,'dance').enabled).toBe(true);});
test('atomic crossing settles at its endpoint without resuming withdrawn AI waypoints',()=>{const {s,h,p}=fixture();s.units=[h,p];p.crossing={from:{...p.pos},to:{x:11,y:10},elapsed:0,switched:false};p.path=[{x:11,y:10},{x:12,y:10}];p.destination={x:12,y:10};p.afterCross={x:13,y:10};p.following=true;const cross=p.crossing;begin(s);expect(p.crossing).toBe(cross);expect(p.path).toEqual([{x:11,y:10}]);step(s,1);expect(p.crossing).toBeUndefined();expect(p.pos).toEqual({x:11,y:10});expect(p.path).toEqual([]);expect(ready(s,p)).toBe(true);});
test('new automatic Reap waits; committed Reap completes and retains its hit lifecycle',()=>{const {s,h,p,e}=fixture();p.role='fiorre';p.id='fiorre';s.explorationCompanionId=p.id;p.weapons[0]={...p.weapons[0],profession:'scythe',remote:false,range:1.5};p.skillSlots=['dance','reap',null];p.skillId='dance';command(s,{type:'commandFocus',id:p.id});p.pos={x:12,y:10};e.pos={x:13,y:10};h.pos={x:16,y:12};e.statuses=[{kind:'stun',power:0,remaining:100}];const st=skillState(p,'reap');st.counter=5;begin(s,'skill');step(s,.1);expect(st.counter).toBe(5);expect(st.run).toBeUndefined();cancel(s);p.path=[];p.destination=null;p.companionCombat=undefined;tickSpecial(s,p,.02,{hit:resolveHit},'reap');expect(st.run).toBeDefined();const run=st.run,hp=e.hp;begin(s,'skill');expect(ready(s,p)).toBe(false);step(s,2);expect(st.run).toBeUndefined();expect(run!.elapsed).toBeGreaterThan(0);expect(e.hp).toBeLessThan(hp);expect(ready(s,p)).toBe(true);});
test('repeated same Aim keeps its timestamp, kind change does not restart TacticalFocus',()=>{const {s}=fixture();begin(s);const aim=s.explorationControl!.aim,focus=s.tacticalFocus;s.time=2;begin(s);expect(s.explorationControl!.aim).toBe(aim);begin(s,'skill');expect(s.explorationControl!.aim).toEqual({kind:'skill',actorId:'ranger',source:'command',startedAt:2});expect(s.tacticalFocus).toBe(focus);});
test('permission and Ready queries are pure; clone and Legacy bodies never acquire reservation',()=>{const {s,p}=fixture();const copy={...structuredClone(p),id:'copy',cloneOf:p.id};s.units.push(copy);const before=structuredClone(s);expect(control.queryBeginCommandAim(s,'path').ok).toBe(true);expect(control.commandReservationReady(s,p)).toBe(false);expect(control.autonomousBodyStartAllowed(s,p)).toBe(true);expect(s).toEqual(before);begin(s);const during=structuredClone(s);expect(control.commandReservationReady(s,p)).toBe(true);expect(control.autonomousBodyStartAllowed(s,p)).toBe(false);expect(control.commandReserved(s,copy)).toBe(false);expect(control.autonomousBodyStartAllowed(s,copy)).toBe(true);expect(s).toEqual(during);s.exploration!.definition.kind=undefined;expect(control.commandReserved(s,p)).toBe(false);expect(control.autonomousBodyStartAllowed(s,p)).toBe(true);});
test.each(['clear','switch','promote','downed','shadow','party','phase'])('%s invalidates Aim without passing reservation to replacement',kind=>{const {s,p}=fixture();begin(s);if(kind==='clear')command(s,{type:'commandFocus',id:null});if(kind==='switch')command(s,{type:'commandFocus',id:'hunter'});if(kind==='promote')command(s,{type:'promoteCommandFocus'});if(kind==='downed')p.life='downed';if(kind==='shadow')p.shadowResident=true;if(kind==='party')s.explorationCompanionId='ines';if(kind==='phase')s.phase='ended';control.ensureExplorationControl(s);expect(s.explorationControl?.aim).toBeUndefined();expect(reserved(s,p)).toBe(false);});
test('stale Aim cannot capture authority; cancel preserves current state and no-op cancels are safe',()=>{const {s,h,p}=fixture();begin(s);s.explorationControl!.aim!.actorId=h.id;expect(control.inputAuthority(s)).toBe('direct');control.ensureExplorationControl(s);expect(s.explorationControl!.aim).toBeUndefined();begin(s);const before=structuredClone(s);expect(cancel(s).ok).toBe(true);before.explorationControl!.aim=undefined;expect(s).toEqual(before);expect(cancel(s).ok).toBe(true);expect(ready(s,p)).toBe(false);});
