import {legacyEnemy,hazard} from './legacy-enemy-fixture';
import {vi} from 'vitest';
// AR06: retain these historical weapon/skill contracts on the Legacy branch.
vi.mock('../src/core/al-state',async importActual=>({...await importActual<object>(),isAlV2:()=>false}));
import {expect,it} from 'vitest';
import {createGame,command,step} from '../src/core/engine';
import {activeEncounters,inCombatDomain,pathSafeFromInactiveEncounters} from '../src/core/encounter-domain';
import {advanceCompanionCombat,rangeBand,visibleHazards,TACTICAL_WEIGHTS,tacticalTargets} from '../src/core/companion-combat';
import {startIntent} from '../src/core/attack-intent';
import {hitDirection} from '../src/core/directionality';
import {queryEvade} from '../src/core/evasion';
import {planReapPath} from '../src/core/reap-path';
export function combatFixture(){
 const s=createGame();command(s,{type:'selectJourney',journey:'exploration'});command(s,{type:'selectExplorationCompanion',id:'ranger'});command(s,{type:'carry',gold:0,vitality:0});
 s.tiles.forEach(t=>{t.obstacle=false;t.layer=0;});const h=s.units[0],p=s.units.find(u=>u.id==='ranger')!,e=legacyEnemy(s);
 s.units=[h,p,e];h.pos={x:15,y:10};p.pos={x:10,y:10};e.pos={x:14,y:10};for(const u of s.units){u.drawPos={...u.pos};u.path=[];u.destination=null;u.ready=0;u.attackTimer=100;u.weapons.forEach(w=>w.weight=0);u.hp=u.maxHp=10000;}
 p.life='active';e.enemyMotion='engaged';e.pursuitTargetId=h.id;e.enemySense!.home={...e.pos};e.encounterRoom=1;e.encounterId='fixture';
 s.context='explorationBattle';s.exploration!.lastActivity=0;s.exploration!.definition.encounters=[{room:1,name:'active',tier:'strong',enemyIds:['fixture'],center:{x:13,y:10},tacticalRadius:6.5}];return {s,h,p,e};
}
it('generated encounters retain center/radius and runtime identity, never parse display names',()=>{const {s,e}=combatFixture();expect(e.encounterRoom).toBe(1);expect(activeEncounters(s).map(a=>a.room)).toEqual([1]);expect(inCombatDomain(s,{x:17,y:10})).toBe(true);e.enemyMotion='return';e.pursuitTargetId=undefined;expect(activeEncounters(s)).toEqual([]);});
it('multiple engaged groups form a union and reject paths through inactive perception zones',()=>{const {s,e}=combatFixture();const next={...e,id:'opaque',encounterRoom:2,encounterId:'other',pos:{x:22,y:10},enemyMotion:'route' as const,pursuitTargetId:undefined,enemySense:{home:{x:22,y:10},patrol:[],cursor:0}};s.units.push(next);s.exploration!.definition.encounters!.push({room:2,name:'other',tier:'normal',enemyIds:['other'],center:{x:22,y:10},tacticalRadius:6.5});expect(pathSafeFromInactiveEncounters(s,[{x:18,y:10},{x:22,y:10}])).toBe(false);next.pursuitTargetId='hunter';next.enemyMotion='engaged';expect(activeEncounters(s)).toHaveLength(2);expect(inCombatDomain(s,{x:25,y:10})).toBe(true);});
it('off-control body ignores obsolete anchor and direct actor never receives autonomous movement',()=>{const {s,h,p}=combatFixture();p.ai={anchor:{x:1,y:1},intent:'hold',nextDecision:0,movedAt:0,commandUntil:0,directTravel:0};advanceCompanionCombat(s);expect(p.companionCombat?.targetId).toBe(s.units[2].id);expect(p.path.length).toBeGreaterThan(0);expect(h.path).toEqual([]);expect(h.companionCombat).toBeUndefined();});
it('real Telegraph is observed before response, and foreground remains owned',()=>{const {s,p,e}=combatFixture();p.pos={x:14.8,y:10};s.controlledBodyId='hunter';hazard(s,e,p);advanceCompanionCombat(s);expect(visibleHazards(s)).toHaveLength(1);expect(p.companionCombat?.hazardSeenAt).toBe(0);expect(p.companionCombat?.intent).not.toBe('evade');s.time=.19;advanceCompanionCombat(s);expect(p.companionCombat?.intent).toBe('evade');});
it('regroup can leave domain following the player, with hysteresis',()=>{const {s,h,p}=combatFixture();h.pos={x:22,y:10};advanceCompanionCombat(s);expect(p.companionCombat?.intent).toBe('regroup');expect(p.path.at(-1)!.x).toBeGreaterThan(19.5);});
it('profession range bands follow equipped weapon rather than legacy radius',()=>{const {p}=combatFixture();const [a,b]=rangeBand(p);expect(a).toBeCloseTo(p.weapons[p.weaponIndex].range*.6);expect(b).toBeCloseTo(p.weapons[p.weaponIndex].range*.85);});
it('engine invokes AI2 and can move farther than two units without a return anchor',()=>{const {s,h,p,e}=combatFixture();h.pos={x:16,y:10};p.pos={x:10,y:10};p.ai=undefined;e.statuses=[{kind:'stun',remaining:100,power:0}];e.postureDelay=100;const from={...p.pos};step(s,2);expect(Math.hypot(p.pos.x-from.x,p.pos.y-from.y)).toBeGreaterThan(2);expect(p.companionCombat).toBeDefined();});
it('AI companion uses real charge only when walking is too late',()=>{const {s,p,e}=combatFixture();p.pos={x:15,y:10};hazard(s,e,p);advanceCompanionCombat(s);expect(p.path).toEqual([]);s.time=.9;const charges=p.evasion!.charges;advanceCompanionCombat(s);expect(p.companionCombat?.mobilityEscape).toBe('evade');expect(p.evasion!.charges).toBe(charges-1);expect(p.evasion!.action).toBeDefined();});
it('walking escape preserves evade charges',()=>{const {s,p,e}=combatFixture();p.pos={x:15.5,y:10};hazard(s,e,p);advanceCompanionCombat(s);s.time=.19;const charges=p.evasion!.charges;advanceCompanionCombat(s);expect(p.companionCombat?.mobilityEscape).toBe('walk');expect(p.evasion!.charges).toBe(charges);});
it('off-control Hunter consumes real Blink, without foreground cancellation',()=>{const {s,h,p,e}=combatFixture();s.controlledBodyId=p.id;h.pos={x:15,y:10};hazard(s,e,h);advanceCompanionCombat(s);s.time=.95;const charges=h.blink!.charges;advanceCompanionCombat(s);expect(h.companionCombat?.mobilityEscape).toBe('blink');expect(h.blink!.charges).toBe(charges-1);});
it('no resource permits actual damage instead of granting an invulnerability shortcut',()=>{const {s,p,e}=combatFixture();p.pos={x:15,y:10};p.evasion!.charges=0;p.evasion!.progress=0;p.attackTimer=100;hazard(s,e,p);advanceCompanionCombat(s);s.time=.95;advanceCompanionCombat(s);expect(p.companionCombat?.mobilityEscape).toBe('unavailable');const hp=p.hp;step(s,.21);expect(p.hp).toBeLessThan(hp);});
it('foreground cast owns the body even during imminent hazard',()=>{const {s,h,p,e}=combatFixture();s.controlledBodyId=p.id;h.pos={x:15,y:10};h.skillStates!.hunt={stage:0,branches:{},cd:1,max:1,time:1,pulse:0,enabled:false,counter:0};hazard(s,e,h);advanceCompanionCombat(s);s.time=.95;advanceCompanionCombat(s);expect(h.blink!.charges).toBe(10);expect(h.skillStates!.hunt.time).toBe(1);});
it('C handoff revokes AI locomotion immediately and leaves explicit mouse destination owned',()=>{const {s,h,p}=combatFixture();advanceCompanionCombat(s);expect(p.path.length).toBeGreaterThan(0);command(s,{type:'controlBody',id:p.id} as any);expect(p.path).toEqual([]);command(s,{type:'move',id:p.id,to:{x:11,y:9}});command(s,{type:'controlBody',id:h.id} as any);const path=structuredClone(p.path);advanceCompanionCombat(s);expect(p.path).toEqual(path);});
it('runtime generation copies all explicit encounter identities',()=>{const s=createGame();command(s,{type:'selectJourney',journey:'exploration'});command(s,{type:'carry',gold:0,vitality:0});for(const e of s.units.filter(u=>u.team==='enemy')){expect(e.encounterRoom).toBeTypeOf('number');expect(s.exploration!.definition.encounters!.some(a=>a.room===e.encounterRoom&&a.enemyIds.includes(e.encounterId!))).toBe(true);}});
it('hidden unengaged telegraphs and inactive targets are unavailable to AI',()=>{const {s,p,e}=combatFixture();p.pos={x:15,y:10};hazard(s,e,p);e.pos={x:40,y:40};e.pursuitTargetId=undefined;e.attackIntent!.targetId='not-party';e.enemyMotion='route';expect(visibleHazards(s)).toEqual([]);expect(tacticalTargets(s)).toEqual([]);});
it('legacy Tower and courtyard remain isolated from AI2 domains',()=>{const {s,p}=combatFixture();s.exploration!.definition.kind=undefined;expect(activeEncounters(s)).toEqual([]);advanceCompanionCombat(s);expect(p.companionCombat).toBeUndefined();s.exploration=undefined;expect(activeEncounters(s)).toEqual([]);});
it('Ranger prefers a safe heavy side/back point without circling once established',()=>{const {s,h,p,e}=combatFixture();h.pos={x:14,y:12};p.pos={x:16.5,y:10};e.heading=0;advanceCompanionCombat(s);expect(hitDirection(e,p.companionCombat!.point!)).not.toBe('front');const point=structuredClone(p.companionCombat!.point);s.time=.1;advanceCompanionCombat(s);expect(p.companionCombat!.point).toEqual(point);p.pos={...point!};p.path=[];p.destination=null;s.time=.4;advanceCompanionCombat(s);expect(p.path).toEqual([]);});
it('Shieldguard crosses old radius to peel the DirectActor instead of anchor bracing',()=>{const {s,h,p,e}=combatFixture();p.id='ines';p.role='ines';p.weapons=[{...p.weapons[0],profession:'shieldguard',remote:false,range:1.4}];s.explorationCompanionId=p.id;h.pos={x:15.5,y:10};p.pos={x:10,y:10};advanceCompanionCombat(s);expect(p.companionCombat?.intent).toBe('peel');expect(p.companionCombat?.rangeBand).toEqual([.75,1.2]);expect(p.companionCombat?.point!.x).toBeGreaterThan(12);expect(p.ai?.braceUntil).toBeUndefined();});
it('hazard preempts movement commitment and multi-hazard escape is safe for every live area',()=>{const {s,p,e}=combatFixture();advanceCompanionCombat(s);p.pos={x:15.5,y:10};p.path=[];hazard(s,e,p);const second={...structuredClone(e),id:'second',pos:{x:14,y:12}};s.units.push(second);second.attackIntent!.sourceId=second.id;second.attackIntent!.area={kind:'circle',center:{x:15.5,y:11},radius:1};s.time=.05;advanceCompanionCombat(s);s.time=.25;advanceCompanionCombat(s);expect(p.companionCombat?.intent).toBe('evade');const point=p.companionCombat!.point!;expect(Math.hypot(point.x-14,point.y-10)).toBeGreaterThan(1.93);expect(Math.hypot(point.x-15.5,point.y-11)).toBeGreaterThan(1.18);});
it('forced motion clears old task and resumes from new location',()=>{const {s,p}=combatFixture();advanceCompanionCombat(s);p.forcedMotion={direction:{x:1,y:0},remaining:.4,speed:8,layer:0,wallPin:false,wallPinStagger:1};advanceCompanionCombat(s);expect(p.path).toEqual([]);p.forcedMotion=undefined;p.pos={x:12,y:11};s.time=.4;advanceCompanionCombat(s);expect(p.companionCombat?.point).toBeDefined();});
it('player evade query still rejects off-control resources; tendency weights are distinct',()=>{const {s,p}=combatFixture();expect(queryEvade(s,p).ok).toBe(false);expect(queryEvade(s,p,true).ok).toBe(true);expect(TACTICAL_WEIGHTS.avoid.risk).toBeGreaterThan(TACTICAL_WEIGHTS.default.risk);expect(TACTICAL_WEIGHTS.preserve.risk).toBeGreaterThan(TACTICAL_WEIGHTS.default.risk);expect(TACTICAL_WEIGHTS.rescue.peel).toBeGreaterThan(TACTICAL_WEIGHTS.default.peel);expect(TACTICAL_WEIGHTS.aggressive.flank).toBeGreaterThan(TACTICAL_WEIGHTS.default.flank);});
it('automatic Reap does not reach an inactive encounter through a safe-looking endpoint',()=>{const {s,p,e}=combatFixture();p.companionCombat={intent:'hold',encounterRooms:[1],nextDecision:0};const inactive={...structuredClone(e),id:'inactive',pos:{x:12,y:10},encounterRoom:2,enemyMotion:'route' as const,pursuitTargetId:undefined};s.units.push(inactive);expect(planReapPath(s,p)).toBeUndefined();});
it('movement command finishes before free AI resumes, and noncombat clears AI2 into follow',()=>{const {s,h,p}=combatFixture();command(s,{type:'controlBody',id:p.id});command(s,{type:'move',id:p.id,to:{x:11,y:9}});command(s,{type:'controlBody',id:h.id});s.units[2].statuses=[{kind:'stun',remaining:10,power:0}];step(s,.3);expect(p.ai?.command).toBe('move');step(s,1.2);expect(p.ai?.command).toBeUndefined();expect(p.companionCombat?.targetId).toBeDefined();s.context='explorationIdle';advanceCompanionCombat(s);expect(p.companionCombat).toBeUndefined();});
it('party regroup temporarily owns an AI2 body and free combat resumes after its channel',()=>{
 const {s,h,p,e}=combatFixture();h.pos={x:16,y:10};p.pos={x:15,y:11.5};e.statuses=[{kind:'stun',remaining:100,power:0}];
 advanceCompanionCombat(s);expect(command(s,{type:'party',kind:'regroup'}).ok).toBe(true);step(s,.4);
 expect(p.partyTask?.kind).toBe('regroup');expect(p.partyTask!.elapsed).toBeGreaterThan(.3);expect(p.companionCombat?.moving).not.toBe(true);
 step(s,1);expect(p.partyTask).toBeUndefined();expect(p.life).toBe('active');expect(p.companionCombat?.targetId).toBe(e.id);
});
it('party recall supersedes AI2 and withdrawal cannot resume its old tactical path',()=>{
 const {s,h,p,e}=combatFixture();h.pos={x:16,y:10};p.pos={x:15,y:11.5};e.statuses=[{kind:'stun',remaining:100,power:0}];
 advanceCompanionCombat(s);expect(command(s,{type:'party',kind:'recall'}).ok).toBe(true);step(s,.4);expect(p.recall).toBeDefined();expect(p.companionCombat?.moving).not.toBe(true);
 step(s,1);expect(p.life).toBe('withdrawn');expect(p.path).toEqual([]);expect(p.companionCombat).toBeUndefined();
});
