// AR05: this frozen historical suite verifies the retained pre-Blue branch.

vi.mock('../src/core/hunter-state',async importActual=>({...await importActual<object>(),isHunterV2:()=>false}));
import {vi,expect,it} from 'vitest';
import {createGame,command,resolveHit,step} from '../src/core/engine';
import {captureRecallProtection} from '../src/core/personal';
function fixture(){const s=createGame();command(s,{type:'selectJourney',journey:'exploration'});command(s,{type:'selectExplorationCompanion',id:'ranger'});command(s,{type:'carry',gold:0,vitality:0});s.tiles.forEach(t=>{t.obstacle=false;t.layer=0;});const h=s.units[0],p=s.units.find(u=>u.id==='ranger')!,e=s.units.find(u=>u.team==='enemy')!;s.units=[h,p,e];for(const u of s.units){u.ready=0;u.attackTimer=100;u.dodge=0;u.defense=undefined;u.path=[];u.directionalProfileId='neutral';}h.pos={x:10,y:10};p.pos={x:10,y:10.5};e.pos={x:11,y:10};return {s,h,p,e};}
it('poison feedback aggregates actual shielded HP loss from the same status source',()=>{const {s,h,e}=fixture();e.statuses=[{kind:'poison',power:20,remaining:1,origin:h},{kind:'shield',power:1,remaining:1},{kind:'stun',power:0,remaining:1}];const hp=e.hp;step(s,.05);expect(s.damageFloats||[]).toHaveLength(0);step(s,.05);step(s,.05);expect(hp-e.hp).toBeCloseTo(2);expect(s.damageFloats).toHaveLength(1);expect(s.damageFloats![0]).toMatchObject({targetId:e.id,sourceId:h.id,amount:2});});
it('lethal protected recall displays the actual HP delta after the one-HP rescue',()=>{const {s,h,p,e}=fixture();p.hp=10;p.recall={elapsed:0,waitingCross:false,repath:0};captureRecallProtection(s);resolveHit(s,p,e.weapons[0],100,e,{postureDamage:0});expect(p.life).toBe('rescued');expect(p.hp).toBe(1);expect(s.damageFloats![0].amount).toBe(9);});
it('real takeover clears focus before skill, mouse movement and actual mobility',()=>{const {s,h,p}=fixture();s.context='explorationBattle';command(s,{type:'controlBody',id:p.id});expect(s.tacticalFocus).toBeUndefined();command(s,{type:'promoteCommandFocus'});expect(command(s,{type:'skill',id:p.id,slot:0}).ok).toBe(true);expect(s.tacticalFocus).toBeUndefined();expect(command(s,{type:'move',id:p.id,to:{x:10,y:12}}).ok).toBe(true);command(s,{type:'controlBody',id:h.id});command(s,{type:'promoteCommandFocus'});expect(command(s,{type:'blink',id:h.id,direction:{x:0,y:1}}).ok).toBe(true);expect(s.tacticalFocus).toBeUndefined();command(s,{type:'controlBody',id:p.id});command(s,{type:'promoteCommandFocus'});expect(command(s,{type:'evade',id:p.id,direction:{x:0,y:1}}).ok).toBe(true);expect(s.tacticalFocus).toBeUndefined();});
