import {expect,test} from 'vitest';
import {createGame,command,step,canHit,cloneTiles} from '../src/core/engine';
import {positionVisible} from '../src/core/visibility';
import {updateExplorationEnemy,queryExplorationExit} from '../src/core/exploration';
import {participants} from '../src/core/engagement';
import {useCampfire} from '../src/core/campfire';
import {weightProfile} from '../src/core/combat-config';
import {terrainFits,segmentClear,distance} from '../src/core/spatial';
import {standaloneSummary} from '../src/core/standalone-summary';
import {queryClone} from '../src/core/clones';
import {movementSpeed} from '../src/core/movement-speed';
import {standaloneDefinition} from '../src/core/standalone-exploration';
import type {Command} from '../src/core/types';
function choose(s:ReturnType<typeof createGame>,id:string){return command(s,{type:'selectExplorationCompanion',id} as Command);}
function begin(id='ines'){const s=createGame();command(s,{type:'selectJourney',journey:'exploration',seed:18});choose(s,id);expect(command(s,{type:'carry',gold:0,vitality:0}).ok).toBe(true);return s;}
test('explicit companion choice is required before any carry transaction',()=>{const s=createGame();command(s,{type:'selectJourney',journey:'exploration'});const before=JSON.stringify(s.economy);expect(command(s,{type:'carry',gold:0,vitality:0}).ok).toBe(false);expect(JSON.stringify(s.economy)).toBe(before);});
test.each(['fiorre','ines','ranger'])('only hunter and selected %s enter',id=>{const s=begin(id);expect(s.units.filter(u=>u.team==='ally'&&u.life==='active').map(u=>u.id)).toEqual(['hunter',id]);const h=s.units[0],a=s.units.find(u=>u.id===id)!;expect(Math.hypot(h.pos.x-a.pos.x,h.pos.y-a.pos.y)).toBeGreaterThan(.5);expect(Math.hypot(h.pos.x-a.pos.x,h.pos.y-a.pos.y)).toBeLessThanOrEqual(1.01);for(const u of s.units.filter(u=>u.team==='ally'&&u.id!==id&&u.id!=='hunter')){expect(command(s,{type:'deploy',id:u.id,to:h.pos}).ok).toBe(false);expect(command(s,{type:'partySelection',id:u.id}).ok).toBe(false);}expect(choose(s,'ranger').ok).toBe(false);});
test.each(['hunter','missing','clone-1'])('invalid companion %s rejected',id=>{const s=createGame();command(s,{type:'selectJourney',journey:'exploration'});expect(choose(s,id).ok).toBe(false);});
test('standalone movement and enemy durability are isolated from tower',()=>{const s=begin(),h=s.units[0],e=s.units.find(u=>u.team==='enemy')!;expect(movementSpeed(s,h)).toBeCloseTo(2.4);expect(movementSpeed(s,e)).toBeCloseTo(1.9);for(const a of s.units.filter(u=>u.team==='enemy')){expect(a.maxHp).toBe(a.role==='heavy'?270:170);expect(a.damage).toBe(6);}const tower=createGame();expect(command(tower,{type:'carry',gold:0,vitality:0}).ok).toBe(true);expect(movementSpeed(tower,tower.units[0])).toBeCloseTo(1.7);});
test('encounters have safe rooms, small groups and a bounded seeded budget',()=>{const d=standaloneDefinition(18),groups=(d as any).encounters;expect(groups).toBeDefined();expect(groups.some((g:any)=>g.tier==='safe')).toBe(true);expect(groups.some((g:any)=>g.tier==='small')).toBe(true);expect(groups.some((g:any)=>g.tier==='strong')).toBe(true);expect(d.enemies.length).toBeGreaterThanOrEqual(40);expect(d.enemies.length).toBeLessThanOrEqual(48);expect(d).toEqual(standaloneDefinition(18));expect(d.enemies).not.toEqual(standaloneDefinition(19).enemies);});
test('predeparture change replaces the choice, and new expedition clears it',()=>{const s=createGame();command(s,{type:'selectJourney',journey:'exploration'});expect(choose(s,'fiorre').ok).toBe(true);expect(choose(s,'ranger').ok).toBe(true);expect(s.explorationCompanionId).toBe('ranger');expect(command(s,{type:'carry',gold:0,vitality:0}).ok).toBe(true);expect(s.units.filter(u=>u.team==='ally'&&u.life==='active').map(u=>u.id)).toEqual(['hunter','ranger']);command(s,{type:'abandon'});expect(command(s,{type:'newExpedition'}).ok).toBe(true);expect(s.explorationCompanionId).toBeUndefined();});
test('excluded original cannot provide vision, be targeted, or tick local AI even with stale active state',()=>{const s=begin(),u=s.units.find(u=>u.id==='ranger')!,e=s.units.find(u=>u.team==='enemy')!;u.life='active';u.ready=0;u.pos={...e.pos};expect(positionVisible(s,u.pos)).toBe(false);expect(participants(s,e)).not.toContain(u);expect(canHit(s,e,u)).toBe(false);updateExplorationEnemy(s,e);expect(e.pursuitTargetId).not.toBe(u.id);const before={...u.pos};step(s,.2);expect(u.pos).toEqual(before);expect(u.ai).toBeUndefined();});
test('campfire only restores party originals, never excluded originals or clones',()=>{const s=begin();s.units=s.units.filter(u=>u.team==='ally');for(const u of s.units){u.hp=5;u.stress=65;}s.fragments=40;const h=s.units[0],point=cloneTiles(s,h.id)[0];expect(command(s,{type:'clone',id:h.id,to:point}).ok).toBe(true);const c=s.units.find(u=>u.cloneOf)!;c.hp=5;expect(useCampfire(s,s.exploration!.definition.points[0]).ok).toBe(true);for(const u of s.units)expect(u.hp).toBe(['hunter','ines'].includes(u.id)?5+u.maxHp*.5:5);expect(standaloneSummary(s)?.campfiresUsed).toBe(1);});
test.each(['recall','regroup'] as const)('party %s and exit only consider the selected originals',kind=>{const s=begin(),h=s.units[0],chosen=s.units.find(u=>u.id==='ines')!,excluded=s.units.find(u=>u.id==='ranger')!;s.units=s.units.filter(u=>u.team==='ally');excluded.life='active';excluded.pos={x:38,y:10};const before=structuredClone(excluded);expect(command(s,{type:'party',kind}).ok).toBe(true);expect(excluded).toEqual(before);expect(kind==='recall'?chosen.life==='withdrawn':distance(chosen.pos,h.pos)<2).toBe(true);h.pos={...s.goal};chosen.life='withdrawn';excluded.life='downed';expect(queryExplorationExit(s).ok).toBe(true);expect(queryExplorationExit(s,[excluded.id]).ok).toBe(false);expect(command(s,{type:'exitExploration'}).ok).toBe(true);expect(command(s,{type:'exitExploration'}).ok).toBe(false);expect(standaloneSummary(s)?.outcome).toBe('victory');});
test('clones are allowed for current party, cannot move, and never become original targets',()=>{const s=begin();s.fragments=40;const h=s.units[0],e=s.units.find(u=>u.team==='enemy')!,to=cloneTiles(s,h.id)[0];expect(queryClone(s,h.id,to).ok).toBe(true);expect(command(s,{type:'clone',id:h.id,to}).ok).toBe(true);const c=s.units.find(u=>u.cloneOf)!;expect(command(s,{type:'move',id:c.id,to:h.pos}).ok).toBe(false);expect(participants(s,e)).not.toContain(c);expect(queryClone(s,'fiorre').ok).toBe(false);expect(choose(s,c.id).ok).toBe(false);});
test('speed modifiers and follower catchup remain multiplicative',()=>{const s=begin(),h=s.units[0],a=s.units.find(u=>u.id==='ines')!;h.capacity=.01;expect(movementSpeed(s,h)).toBeCloseTo(2.4*weightProfile(h).move);h.statuses.push({kind:'slow',power:.25,remaining:10});expect(movementSpeed(s,h)).toBeCloseTo(2.4*weightProfile(h).move*.75);a.following=true;a.pos={x:h.pos.x+3,y:h.pos.y};expect(movementSpeed(s,a)).toBeCloseTo(movementSpeed(s,h)*1.2);h.capacity=100;h.statuses=[];h.posture=0;const p={...h.pos};expect(command(s,{type:'move',id:h.id,to:{x:p.x+1,y:p.y}}).ok).toBe(false);step(s,.2);expect(h.pos).toEqual(p);});
test('real movement uses standalone speed in idle and combat',()=>{for(const context of ['explorationIdle','explorationBattle'] as const){const s=begin(),h=s.units[0];s.units=s.units.filter(u=>u.id===h.id);s.context=context;command(s,{type:'partySelection',id:h.id});expect(command(s,{type:'move',id:h.id,to:{x:h.pos.x+2,y:h.pos.y}}).ok).toBe(true);const p={...h.pos};step(s,.5);expect(distance(p,h.pos)).toBeCloseTo(1.2,1);}});
test('legacy courtyard keeps original roster, speeds and HP',()=>{const s=createGame();command(s,{type:'carry',gold:0,vitality:0});s.phase='nodes';s.completed.push(1);expect(command(s,{type:'enter',node:4}).ok).toBe(true);s.units.find(u=>u.id==='ines')!.ready=0;expect(s.exploration?.definition.kind).toBeUndefined();expect(movementSpeed(s,s.units[0])).toBeCloseTo(1.7);const e=s.units.find(u=>u.team==='enemy')!;expect(movementSpeed(s,e)).toBeCloseTo(1.275);expect(e.maxHp).toBe(78);expect(command(s,{type:'deploy',id:'ines',to:{x:3,y:16}}).ok).toBe(true);});
test.each([0,1,2,18,19,99,2026,4294967295])('seed %i generates legal groups, safe routes and unscaled posture',seed=>{const d=standaloneDefinition(seed),s=begin();s.tiles=d.tiles;s.units=[];expect(d.enemies.length).toBeGreaterThanOrEqual(40);expect(d.enemies.length).toBeLessThanOrEqual(48);expect(terrainFits(s,d.exit)).toBe(true);for(const g of d.encounters!){const units=d.enemies.filter(e=>g.enemyIds.includes(e.id));expect(units.length).toBe(g.tier==='safe'?0:g.tier==='small'?3:4);if(g.tier==='strong')expect(units.some(e=>e.role==='heavy')||units.filter(e=>e.role==='ranged').length>=2).toBe(true);}for(const e of d.enemies){expect(terrainFits(s,e.pos)).toBe(true);for(const p of [e.pos,...e.patrol||[]])for(const safe of [d.entry,d.exit,...d.points.map(p=>p.pos)])expect(distance(p,safe)).toBeGreaterThanOrEqual(6);if(e.role==='heavy')expect(e.patrol).toEqual([]);if(e.patrol?.length)expect(segmentClear(s,e.patrol[0],e.patrol[1])).toBe(true);}const run=begin();for(const u of run.units.filter(u=>u.team==='enemy'))expect(u.maxPosture).toBe(u.role==='heavy'?150:u.role==='ranged'?60:90);});
