// AR05: this frozen historical suite verifies the retained pre-Blue branch.

vi.mock('../src/core/hunter-state',async importActual=>({...await importActual<object>(),isHunterV2:()=>false}));
import {vi,expect,test} from 'vitest';
import {createGame,command,step} from '../src/core/engine';
import type {Command,GameState} from '../src/core/types';
import {attackCommit,updatePartyCombat} from '../src/core/exploration';
import {followParty} from '../src/core/party';
import {controlledBody,ensureControlledBody} from '../src/core/direct-control';
import {movementSpeed} from '../src/core/movement-speed';
import {controlFocus} from '../src/view/control-focus';
import {distance} from '../src/core/spatial';
const control=(s:GameState,id:string)=>command(s,{type:'controlBody',id} as Command);
const id=(s:GameState)=>(s as GameState&{controlledBodyId?:string|null}).controlledBodyId;
function begin(){const s=createGame();command(s,{type:'selectJourney',journey:'exploration'});command(s,{type:'selectExplorationCompanion',id:'ines'});command(s,{type:'carry',gold:0,vitality:0});s.units=s.units.filter(u=>u.team==='ally');return s;}
test('standalone begins with hunter control, switches two originals and keeps observation separate',()=>{const s=begin();expect(id(s)).toBe('hunter');expect(control(s,'ines').ok).toBe(true);expect(id(s)).toBe('ines');command(s,{type:'partySelection',id:'hunter'});expect(id(s)).toBe('ines');expect(control(s,'hunter').ok).toBe(true);expect(id(s)).toBe('hunter');});
test('control rejects excluded originals and clones without changing current actor',()=>{const s=begin(),copy={...structuredClone(s.units[0]),id:'copy',cloneOf:'hunter'};s.units.push(copy);for(const name of ['fiorre','ranger','copy','missing']){expect(control(s,name).ok).toBe(false);expect(id(s)).toBe('hunter');}});
test.each(['downed','dead','rescued','withdrawn','respawning','departed'] as const)('cannot switch into %s',life=>{const s=begin(),a=s.units.find(u=>u.id==='ines')!;a.life=life;expect(control(s,a.id).ok).toBe(false);expect(id(s)).toBe('hunter');});
test('broken and staggered actor can be controlled without unlocking movement',()=>{const s=begin(),a=s.units.find(u=>u.id==='ines')!;a.posture=0;a.stagger=.5;expect(control(s,a.id).ok).toBe(true);expect(command(s,{type:'direct',id:a.id,direction:{x:1,y:0}}).ok).toBe(false);expect(id(s)).toBe(a.id);});
test('incoming autonomous path stops without discarding attack or loadout',()=>{const s=begin(),a=s.units.find(u=>u.id==='ines')!;a.ai={intent:'approach',phase:'approach',moving:true,nextDecision:0,movedAt:0,commandUntil:0,directTravel:0,task:{kind:'attack',targetId:'enemy',point:{...a.pos},startedAt:0} as any};a.path=[{x:a.pos.x+1,y:a.pos.y}];a.destination={...a.path[0]};a.attackPending={targetId:'enemy',remaining:.2,facing:'east'};a.loadout={targetIndex:0,elapsed:.2,duration:1};const pending=a.attackPending,loadout=a.loadout;expect(control(s,a.id).ok).toBe(true);expect(a.path).toEqual([]);expect(a.destination).toBeNull();expect(a.ai.task).toBeUndefined();expect(a.ai.phase).toBe('player');expect(a.attackPending).toBe(pending);expect(a.loadout).toBe(loadout);});
test('outgoing direct stops and anchors at actual position while mouse command keeps going',()=>{const s=begin(),h=s.units[0];s.context='explorationBattle';command(s,{type:'direct',id:h.id,direction:{x:1,y:0}});step(s,.1);const position={...h.pos};expect(control(s,'ines').ok).toBe(true);expect(h.direct).toBeUndefined();expect(h.ai?.anchor).toEqual(position);control(s,h.id);const target={x:h.pos.x+1,y:h.pos.y};expect(command(s,{type:'move',id:h.id,to:target}).ok).toBe(true);const path=structuredClone(h.path);control(s,'ines');expect(h.path).toEqual(path);step(s,.6);expect(h.pos.x).toBeCloseTo(target.x,1);expect(h.ai?.anchor?.x).toBeCloseTo(target.x,1);});
test('loss of control falls back, revival does not steal it, both unavailable means null',()=>{const s=begin(),h=s.units[0],a=s.units.find(u=>u.id==='ines')!;control(s,a.id);a.life='downed';step(s,.05);expect(id(s)).toBe(h.id);a.life='active';step(s,.05);expect(id(s)).toBe(h.id);h.life='respawning';h.respawnTimer=10;step(s,.05);expect(id(s)).toBe(a.id);h.life='active';step(s,.05);expect(id(s)).toBe(a.id);a.life='withdrawn';h.life='respawning';step(s,.05);expect(id(s)).toBeNull();});
test('switch does not refresh combat resources or pending lifecycle and refuses other modes',()=>{const s=begin(),a=s.units.find(u=>u.id==='ines')!;a.hp=70;a.grayHp=10;a.posture=20;a.postureDelay=3;a.stagger=.2;a.skillCd=4;a.skillTime=1;a.attackTimer=.7;a.stress=12;const before=structuredClone(a);for(let i=0;i<20;i++){control(s,a.id);control(s,'hunter');}for(const k of ['hp','grayHp','posture','postureDelay','stagger','skillCd','skillTime','attackTimer','stress','weapons'] as const)expect(a[k]).toEqual(before[k]);const tower=createGame();expect(control(tower,'hunter').ok).toBe(false);command(s,{type:'abandon'});expect(id(s)).toBeNull();});
test('partner leads without teleporting, hunter follows with catchup, combat transitions keep control',()=>{const s=begin(),h=s.units[0],a=s.units.find(u=>u.id==='ines')!;a.pos={x:h.pos.x+3,y:h.pos.y};a.drawPos={...a.pos};const hp={...h.pos},ap={...a.pos};control(s,a.id);expect(h.pos).toEqual(hp);expect(a.pos).toEqual(ap);followParty(s,.1);expect(h.following).toBe(true);expect(a.following).toBe(false);expect(movementSpeed(s,h)).toBeCloseTo(2.4*1.2);step(s,.25);expect(distance(h.pos,a.pos)).toBeLessThan(3);const enemy={...structuredClone(h),id:'threat',team:'enemy' as const};s.units.push(enemy);attackCommit(s,enemy,a);expect(s.context).toBe('explorationBattle');expect(id(s)).toBe(a.id);expect(h.ai?.anchor).toEqual(h.pos);s.time+=4;updatePartyCombat(s);expect(s.context).toBe('explorationIdle');expect(id(s)).toBe(a.id);});
test('shadow recall hands control to hunter immediately and redeploy never steals it',()=>{const s=begin(),a=s.units.find(u=>u.id==='ines')!;control(s,a.id);expect(command(s,{type:'party',kind:'recall'}).ok).toBe(true);expect(a.shadowResident).toBe(true);expect(id(s)).toBe('hunter');a.life='active';a.shadowResident=false;ensureControlledBody(s);expect(id(s)).toBe('hunter');a.shadowResident=true;expect(control(s,a.id).ok).toBe(false);});
test('handoff preserves crossing, skill landing and active SkillRun by identity',()=>{const s=begin(),a=s.units.find(u=>u.id==='ines')!;a.crossing={from:{...a.pos},to:{x:a.pos.x+1,y:a.pos.y},elapsed:.1,switched:false};a.skillLanding={origin:{...a.pos},path:[{...a.pos}]};const skill=a.skillStates![a.skillId!]!;skill.run={spec:{id:a.skillId},elapsed:.1} as any;const crossing=a.crossing,landing=a.skillLanding,run=skill.run;control(s,a.id);control(s,'hunter');expect(a.crossing).toBe(crossing);expect(a.skillLanding).toBe(landing);expect(skill.run).toBe(run);});
test('mouse command ending in crossing updates final anchor before AI takes over',()=>{const s=begin(),h=s.units[0];s.context='explorationBattle';const to={x:h.pos.x+1,y:h.pos.y};command(s,{type:'move',id:h.id,to});control(s,'ines');h.pos={...to};h.path=[];h.destination=null;h.crossing=undefined;ensureControlledBody(s);expect(h.ai?.anchor).toEqual(to);expect(h.ai?.command).toBeUndefined();});
test('leaving combat preserves submitted mouse ownership until its destination',()=>{const s=begin(),h=s.units[0];s.context='explorationBattle';const to={x:h.pos.x+2,y:h.pos.y};command(s,{type:'move',id:h.id,to});control(s,'ines');s.time=4;updatePartyCombat(s);expect(h.ai?.command).toBe('move');step(s,1);expect(h.ai?.anchor?.x).toBeCloseTo(to.x,1);});
test('camera focuses primary with 35 percent bounded help, excluding shadows and clones',()=>{const s=begin(),h=s.units[0],a=s.units.find(u=>u.id==='ines')!;h.pos=h.drawPos={x:0,y:0};a.pos=a.drawPos={x:4,y:0};expect(controlFocus(s)).toEqual({x:1.4,y:0});control(s,a.id);expect(controlFocus(s)?.x).toBeCloseTo(2.6);h.pos=h.drawPos={x:-100,y:0};expect(controlFocus(s)).toEqual({x:1,y:0});h.life='respawning';expect(controlFocus(s)).toEqual({x:4,y:0});a.life='dead';expect(controlFocus(s)).toBeNull();expect(controlledBody(s)).toBeNull();});
test.each(['return','follow'] as const)('incoming %s revokes ordinary AI travel',phase=>{const s=begin(),a=s.units.find(u=>u.id==='ines')!;a.path=[{x:a.pos.x+1,y:a.pos.y}];a.destination={...a.path[0]};a.following=phase==='follow';a.ai={intent:phase,phase:phase==='return'?'return':'hold',moving:phase==='return',nextDecision:0,movedAt:0,commandUntil:0,directTravel:0};control(s,a.id);expect(a.path).toEqual([]);expect(a.following).toBe(false);expect(a.ai.moving).toBe(false);});
test('hunter under AI finishes an attack after switching without changing enemy aggro',()=>{const s=begin(),h=s.units[0],a=s.units.find(u=>u.id==='ines')!;s.context='explorationBattle';const e={...structuredClone(h),id:'target',name:'target',team:'enemy' as const,role:'melee' as const,pos:{x:h.pos.x+.5,y:h.pos.y},hp:1000,maxHp:1000,attackTimer:10,engagement:{targetId:h.id,anchor:{...h.pos}},pursuitTargetId:h.id};s.units.push(e);h.attackPending={targetId:e.id,remaining:.02,facing:'east'};h.attackTimer=.8;const aggro=structuredClone(e.engagement);control(s,a.id);expect(e.engagement).toEqual(aggro);expect(e.pursuitTargetId).toBe(h.id);expect(h.attackPending).toBeDefined();step(s,.05);expect(e.hp).toBeLessThan(1000);expect(h.attackTimer).toBeGreaterThan(.5);expect(id(s)).toBe(a.id);});
test('old courtyard remains hunter-led and ignores DirectActor command',()=>{const s=createGame();command(s,{type:'carry',gold:0,vitality:0});s.phase='nodes';s.completed=[1];command(s,{type:'enter',node:4});const h=s.units[0],a=s.units.find(u=>u.id==='ines')!;a.life='active';a.ready=0;a.pos={x:h.pos.x+3,y:h.pos.y};expect(control(s,a.id).ok).toBe(false);followParty(s,.1);expect(h.following).toBe(false);expect(a.following).toBe(true);expect(movementSpeed(s,h)).toBeCloseTo(1.7);});
