import {it,expect} from 'vitest';
import {createGame,command,step,resolveHit} from '../src/core/engine';
const setup=()=>{const s=createGame();command(s,{type:'carry',gold:0,vitality:0});return s;};
it('full hand rejects draws without RNG or quote and retains event for later delivery',()=>{const s=setup();s.fragments=500;for(let i=0;i<7;i++)expect(command(s,{type:'draw'}).ok).toBe(true);const seed=s.seed,b=s.fragments;expect(command(s,{type:'draw'}).ok).toBe(false);expect(s.seed).toBe(seed);expect(s.fragments).toBe(b);s.economy.pending.push({key:'test-event',kind:'power',group:'exclusive',ownerId:'hunter',node:1});const id=s.cards.find(c=>c.group==='deck')!.id;expect(command(s,{type:'sellCard',cardId:id}).ok).toBe(true);expect(s.cards).toHaveLength(8);expect(s.cards.some(c=>c.ownerId==='hunter')).toBe(true);});
it('same preset reward stays consumed across retry regardless of nextId while kills still count',()=>{const s=setup();command(s,{type:'start'});step(s,18.05);const e=s.units.find(u=>u.team==='enemy')!;e.dodge=0;resolveHit(s,e,e.weapons[0],99999);expect(s.fragments).toBe(4);s.crystalHp=0;step(s,.05);command(s,{type:'continue'});command(s,{type:'enter',node:1});s.nextId+=200;command(s,{type:'start'});step(s,18.05);const again=s.units.find(u=>u.team==='enemy')!;again.dodge=0;resolveHit(s,again,again.weapons[0],99999);expect(s.fragments).toBe(4);expect(s.kills).toBe(1);expect(again.id).not.toBe(e.id);expect(s.cards.some(c=>c.group==='scene')).toBe(false);});
it('exploration combat changes preserve price and leaving invalidates trade until new visit',()=>{const s=setup();s.ruleset='exploration';s.fragments=100;command(s,{type:'draw'});command(s,{type:'setContext',context:'explorationIdle'});expect(s.economy.draws).toBe(1);command(s,{type:'leaveExplorationNode'});expect(command(s,{type:'draw'}).ok).toBe(false);command(s,{type:'enterExplorationNode'} as any);expect(s.economy.draws).toBe(0);expect(command(s,{type:'draw'}).ok).toBe(true);});
it('zero carry real original map earns first kill without a paid asset',()=>{const s=setup();command(s,{type:'start'});for(let n=0;n<1500&&!s.kills;n++)step(s,.1);expect(s.kills).toBeGreaterThan(0);expect(s.fragments).toBeGreaterThanOrEqual(4);expect(s.units.some(u=>u.cloneOf)).toBe(false);});

it('node three victory settles success once and does not convert life to gold',()=>{const s=createGame();s.economy.account={gold:30,vitality:50};command(s,{type:'carry',gold:7,vitality:40});s.phase='nodes';s.completed=[1,2];expect(command(s,{type:'enter',node:3}).ok).toBe(true);expect(command(s,{type:'draw'}).ok).toBe(true);expect(command(s,{type:'start'}).ok).toBe(true);s.waves=[];s.totalEnemies=0;step(s,.05);expect(s.result).toBe('victory');expect(s.economy.settled).toBe('success');expect(s.economy.account).toEqual({gold:30,vitality:40});expect(s.cards).toHaveLength(0);expect(command(s,{type:'abandon'}).ok).toBe(false);expect(command(s,{type:'safeExit'}).ok).toBe(false);expect(s.economy.account).toEqual({gold:30,vitality:40});});
