import {it,expect} from 'vitest';
import {createGame,command,step} from '../src/core/engine';
import {eventCard,makeCard,salePrice} from '../src/core/cards';
const setup=()=>{const s=createGame();s.economy.account={gold:100000,vitality:80};command(s,{type:'carry',gold:100000,vitality:80});return s;};
it('gold never substitutes for life and stale cultivation/clone quotes cannot pay twice',()=>{const s=setup();s.fragments=24;expect(command(s,{type:'upgradeSkill',id:'ines',kind:'stage',expectedLevel:0}).ok).toBe(true);expect(s.fragments).toBe(0);const count=s.units.length;for(const c of [{type:'upgradeSkill',id:'ines',kind:'stage',expectedLevel:0},{type:'clone',id:'hunter',to:{x:3,y:4}},{type:'draw'}] as const)expect(command(s,c).ok).toBe(false);expect(s.fragments).toBe(0);expect(s.economy.carried.gold).toBe(100000);expect(s.units.length).toBe(count);});
it('sale, use and owner destruction compete for only the same instance',()=>{const s=setup();command(s,{type:'start'});const c=makeCard(s,'power');s.cards.push(c);expect(command(s,{type:'sellCard',cardId:c.id}).ok).toBe(true);expect(command(s,{type:'card',cardId:c.id,targetId:'hunter',to:s.units[0].pos}).ok).toBe(false);const used=makeCard(s,'power');s.cards.push(used);expect(command(s,{type:'card',cardId:used.id,targetId:'hunter',to:s.units[0].pos}).ok).toBe(true);expect(command(s,{type:'sellCard',cardId:used.id}).ok).toBe(false);expect(command(s,{type:'clone',id:'hunter',to:{x:3,y:4}}).ok).toBe(true);const clone=s.units.at(-1)!;s.cards=Array.from({length:8},()=>makeCard(s,'heal'));eventCard(s,'clone-test','power','exclusive',clone.id);expect(s.economy.pending).toHaveLength(1);expect(command(s,{type:'destroyClone',id:clone.id}).ok).toBe(true);expect(s.economy.pending).toHaveLength(0);expect(s.cards).toHaveLength(8);});
it('all sources have independent instances and fixed configured integer sale prices',()=>{const s=setup();s.cards=[];for(const group of ['scene','deck','exclusive'] as const){const c=makeCard(s,'power',group);s.cards.push(c);expect(salePrice(c)).toBe(group==='deck'?2:1);const before=s.fragments;expect(command(s,{type:'sellCard',cardId:c.id}).ok).toBe(true);expect(s.fragments).toBe(before+(group==='deck'?2:1));expect(command(s,{type:'sellCard',cardId:c.id}).ok).toBe(false);}const c=makeCard(s,'heal');c.sellPrice=3;s.cards.push(c);expect(command(s,{type:'sellCard',cardId:c.id}).ok).toBe(true);const again=makeCard(s,'heal');expect(again.templateId).toBe(c.templateId);expect(again.id).not.toBe(c.id);});
it('automatic requests and insufficient draws never change RNG or hand',()=>{const s=setup();s.autoDraw=true;command(s,{type:'start'});s.waves=[];s.totalEnemies=999;step(s,.2);expect(s.fragments).toBe(80);const seed=s.seed,cards=s.cards.map(c=>c.id);s.fragments=9;expect(command(s,{type:'draw'}).ok).toBe(false);expect(s.seed).toBe(seed);expect(s.cards.map(c=>c.id)).toEqual(cards);expect(s.economy.draws).toBe(0);});

it('dead body drops owned cards and pending events without affecting other sources',()=>{const s=setup();s.cards=Array.from({length:8},()=>makeCard(s,'heal'));s.cards[0]=makeCard(s,'power','exclusive','ines');eventCard(s,'dead-owner','power','exclusive','ines');s.units.find(u=>u.id==='ines')!.life='dead';command(s,{type:'start'});s.waves=[];s.totalEnemies=999;step(s,.05);expect(s.cards.some(c=>c.ownerId==='ines')).toBe(false);expect(s.economy.pending.some(c=>c.ownerId==='ines')).toBe(false);expect(s.cards).toHaveLength(7);});
