import {test,expect} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
const dir='../work/EN-02/browser';mkdirSync(dir,{recursive:true});
test.setTimeout(60000);
async function rally(page:any){await page.keyboard.press('h');}
const snap=(page:any)=>page.evaluate(()=>{const p=(window as any).prototype;return {time:p.state.time,units:p.state.units.map((u:any)=>({id:u.id,pos:u.pos,hp:u.hp,life:u.life,v2:u.enemyV2})),assets:[...p.scene.unitVisuals.values()].map((a:any)=>({id:a.unit.id,ready:a.reference?.ready,profile:a.referenceProfile,pose:a.reference?.pose,failed:a.loadFailed})),entities:p.state.enemyRuntime};});
test('EN02 natural original model, movement, attack and real guard',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?enemies=v2');await expect(page.locator('[data-v2=reset]')).toBeVisible();await rally(page);
 await expect.poll(()=>page.evaluate(()=>(window as any).prototype?.scene.unitVisuals.get('v2-zombie')?.reference?.ready),{timeout:30000}).toBe(true);
 const start=await snap(page);writeFileSync(dir+'/start.json',JSON.stringify(start,null,2));await page.screenshot({path:dir+'/moving.png'});
 await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.enemyV2).enemyV2.trace.some((r:any)=>r.event==='attack')),{timeout:25000}).toBe(true);
 const p=await page.evaluate(()=>{const p=(window as any).prototype;return p.project(p.state.units.find((u:any)=>u.enemyV2).pos);});await page.mouse.move(p.x,p.y);await page.mouse.down({button:'right'});
 await expect.poll(async()=>{const f=await page.evaluate(()=>{const p=(window as any).prototype,e=p.state.units.find((u:any)=>u.enemyV2);return {p:p.project(e.pos),block:e.enemyV2.trace.some((r:any)=>r.defense==='block'),guard:p.state.units.find((u:any)=>u.id==='hunter').hunterCombat?.special?.kind==='guard'};});await page.mouse.move(f.p.x,f.p.y);if(!f.guard){await page.mouse.up({button:'right'});await page.mouse.down({button:'right'});}return f.block;},{timeout:25000,intervals:[150]}).toBe(true);await page.mouse.up({button:'right'});
 const end=await snap(page);expect(end.units.find((u:any)=>u.v2).pos).not.toEqual(start.units.find((u:any)=>u.v2).pos);expect(errors).toEqual([]);writeFileSync(dir+'/natural.json',JSON.stringify({method:'ordinary page, real RMB; no state writes',start,end},null,2));await page.screenshot({path:dir+'/guard.png'});
});
test('EN02 real LMB hurt/death and safe reset reload',async({page})=>{
 await page.goto('/?enemies=v2');await expect(page.locator('[data-v2=reset]')).toBeVisible();await rally(page);await expect.poll(()=>page.evaluate(()=>(window as any).prototype?.scene.unitVisuals.get('v2-zombie')?.reference?.ready),{timeout:30000}).toBe(true);
 await expect.poll(()=>page.evaluate(()=>{const s=(window as any).prototype.state,h=s.units.find((u:any)=>u.id==='hunter'),e=s.units.find((u:any)=>u.enemyV2);return Math.hypot(h.pos.x-e.pos.x,h.pos.y-e.pos.y);}),{timeout:20000}).toBeLessThan(1.7);
 const p=await page.evaluate(()=>{const p=(window as any).prototype;return p.project(p.state.units.find((u:any)=>u.enemyV2).pos);});await page.mouse.move(p.x,p.y);await page.mouse.down();await expect.poll(async()=>{const f=await page.evaluate(()=>{const p=(window as any).prototype,s=p.state,e=s.units.find((u:any)=>u.enemyV2),h=s.units.find((u:any)=>u.id==='hunter');return {life:e.life,d:Math.hypot(e.pos.x-h.pos.x,e.pos.y-h.pos.y),x:e.pos.x-h.pos.x,y:e.pos.y-h.pos.y,p:p.project(e.pos)};});await page.mouse.move(f.p.x,f.p.y);await page.mouse.up();await page.mouse.down();for(const k of ['w','a','s','d'])await page.keyboard.up(k);if(f.d>1.7)await page.keyboard.down(Math.abs(f.y)>Math.abs(f.x)?f.y<0?'w':'s':f.x<0?'a':'d');return f.life;},{timeout:45000,intervals:[150]}).toBe('dead');for(const k of ['w','a','s','d'])await page.keyboard.up(k);await page.mouse.up();await page.screenshot({path:dir+'/death.png'});writeFileSync(dir+'/death.json',JSON.stringify(await snap(page),null,2));await page.locator('[data-v2="reset"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.enemyV2).life)).toBe('active');
});
test('EN02 absent original asset is visible failure and freezes the named encounter',async({page})=>{await page.route('**/__al01-assets/zombie/unit.json',r=>r.fulfill({status:404,body:'missing'}));await page.goto('/?enemies=v2');await expect(page.locator('body')).toContainText('Enemy assets unavailable');const time=await page.evaluate(()=>(window as any).prototype.state.time);await page.waitForTimeout(300);expect(await page.evaluate(()=>(window as any).prototype.state.time)).toBe(time);expect(await page.evaluate(()=>(window as any).prototype.scene.unitVisuals.get('v2-zombie').spine)).toBeUndefined();});
