import {test,expect} from 'vitest';
import {setup} from './en01-fixture';
import {ARCHER,registerEnemy} from '../src/core/enemy-profiles';
import {requestEnemyAction,advanceEnemyAction} from '../src/core/enemy-action';
import {commitEnemyRelease,advanceEnemyEntities,enemyWorld,interruptEnemyV2,enemyDefenseOrigin} from '../src/core/enemy-attack-entity';
import {tickEnemyDecision} from '../src/core/enemy-decision';
import {configureCombatTrace,resetCombatTrace} from '../src/core/combat-identity';
import {createEnemyPlaytest} from '../src/core/enemy-playtest';
function fire(trace=true){const x=setup(),{s,e,h}=x;e.pos={x:15,y:10};e.drawPos={...e.pos};registerEnemy(s,e,ARCHER);e.enemyV2!.readyAt=0;configureCombatTrace(s,trace);expect(requestEnemyAction(s,e,ARCHER,h).ok).toBe(true);s.time=.6333;advanceEnemyAction(s,e).forEach(r=>commitEnemyRelease(s,r));return x;}
const noop=()=>({accepted:true,hpLost:3});
test('source profile uses original ranged model, exact Hit, two children and three committed transports',()=>{const {s,e}=fire();const entities=enemyWorld(s).entities;expect(e.enemyVisualProfileId).toBe('ranged');expect(entities).toHaveLength(3);expect(entities.map(p=>p.spawnAt)).toEqual([.6333,.6333,.7333]);expect(new Set(entities.map(p=>p.context.parentActionId)).size).toBe(2);expect(new Set(entities.map(p=>p.context.actionId)).size).toBe(3);expect(new Set(entities.map(p=>p.context.rootActionId)).size).toBe(1);expect(entities.every(p=>p.context.actorId===e.id)).toBe(true);});
test('pre-Hit interruption yields zero; post-Hit death retains late third and all land after body finish',()=>{const {s,e}=setup();e.pos={x:15,y:10};registerEnemy(s,e,ARCHER);e.enemyV2!.readyAt=0;requestEnemyAction(s,e,ARCHER,s.units.find(u=>u.id==='hunter'));interruptEnemyV2(s,e);s.time=1;expect(advanceEnemyAction(s,e)).toHaveLength(0);expect(enemyWorld(s).entities).toHaveLength(0);const b=fire();b.e.life='dead';interruptEnemyV2(b.s,b.e,'death');b.s.time=.7;advanceEnemyEntities(b.s,noop);expect(enemyWorld(b.s).entities.filter(p=>p.born)).toHaveLength(2);b.s.time=.7333;advanceEnemyEntities(b.s,noop);expect(enemyWorld(b.s).entities.filter(p=>p.born)).toHaveLength(3);b.s.time=2;advanceEnemyEntities(b.s,noop);expect(b.e.enemyV2!.trace.filter(p=>p.kind==='land')).toHaveLength(3);expect(enemyWorld(b.s).entities).toHaveLength(0);});
test('transport never deals HP; three independently deduplicated explosions can each hit two bodies',()=>{const {s,e,h,al}=fire();let hits=0;s.time=1;advanceEnemyEntities(s,()=>{hits++;return noop();});expect(hits).toBe(0);for(const p of enemyWorld(s).entities)p.to={...h.pos};s.time=1.5533;advanceEnemyEntities(s,()=>{hits++;return noop();});expect(hits).toBe(4);s.time=1.56;advanceEnemyEntities(s,()=>{hits++;return noop();});expect(hits).toBe(4);s.time=1.6533;advanceEnemyEntities(s,()=>{hits++;return noop();});expect(hits).toBe(6);expect(e.enemyV2!.trace.filter(x=>x.kind==='contact').map(x=>x.targetId)).toContain(al.id);});
test('moving away cannot drag cached landings; new generation clears future danger',()=>{const {s,h}=fire();const ends=enemyWorld(s).entities.map(p=>({...p.to}));h.pos={x:20,y:20};s.time=1;advanceEnemyEntities(s,noop);expect(enemyWorld(s).entities.map(p=>p.to)).toEqual(ends);resetCombatTrace(s);expect(enemyWorld(s).entities).toEqual([]);});
test('wall destroys swept transport rather than hitting behind obstacle',()=>{const {s,e}=fire();s.tiles.find(t=>t.x===13&&t.y===10)!.obstacle=true;for(const p of enemyWorld(s).entities)p.to={x:10,y:10};s.time=2;let hit=0;advanceEnemyEntities(s,()=>{hit++;return noop();});expect(hit).toBe(0);expect(enemyWorld(s).entities).toHaveLength(0);expect(e.enemyV2!.trace.filter(r=>r.kind==='blocked')).toHaveLength(3);});
test('trace off keeps deterministic samples and all identity relations',()=>{const a=fire(),b=fire(false);expect(enemyWorld(a.s).entities).toEqual(enemyWorld(b.s).entities);});
test('coincident explosion guard origin uses inverse incoming trajectory, never current dead caster position',()=>{const {s,h}=fire();const p=enemyWorld(s).entities[0];p.pos={...h.pos};p.heading=Math.PI;expect(enemyDefenseOrigin(p,h)).toEqual({x:h.pos.x+1,y:h.pos.y});});
test('ranged retreats under comfort range, ordinary movement stops during native attack',()=>{const {s,e}=fire();e.enemyV2!.action=undefined;e.pos={x:12,y:10};e.enemyV2!.brain!.home={...e.pos};tickEnemyDecision(s,e,.1);expect(e.enemyV2!.brain!.decision).toBe('retreat');expect(e.pos.x).toBeGreaterThan(12);const p={...e.pos};e.enemyV2!.action={context:{...enemyWorld(s).entities[0].context},targetId:'hunter',point:{x:10,y:10},origin:p,facing:Math.PI,cursor:0,attackReady:false,moveReady:false};tickEnemyDecision(s,e,.1);expect(e.pos).toEqual(p);});
test('explicit mixed entry has only two original named V2 enemies and untouched main-map source',()=>{const s=createEnemyPlaytest(0,'mix');const enemies=s.units.filter(u=>u.team==='enemy');expect(enemies.map(e=>e.enemyVisualProfileId).sort()).toEqual(['ranged','zombie']);expect(enemies.every(e=>!e.enemyCombat&&!e.attackIntent)).toBe(true);expect(s.totalEnemies).toBe(2);});

test('closest visible isolated island is not selected over the farther reachable party body',()=>{const {s,e,h,al}=setup();e.pos={x:11,y:10};h.pos={x:12,y:11};al.pos={x:8,y:10};for(const [x,y] of [[11,11],[12,10],[13,10],[13,11],[11,12],[12,12],[13,12]])s.tiles.find(t=>t.x===x&&t.y===y)!.obstacle=true;registerEnemy(s,e,ARCHER);expect(tickEnemyDecision(s,e,.01)?.id).toBe(al.id);});

test('a visible target that becomes unreachable is dropped at the next bounded sense refresh',()=>{const {s,e,h,al}=setup();e.pos={x:11,y:10};h.pos={x:12,y:11};al.pos={x:8,y:10};registerEnemy(s,e,ARCHER);expect(tickEnemyDecision(s,e,0)?.id).toBe(h.id);for(const [x,y] of [[11,11],[12,10],[13,10],[13,11],[11,12],[12,12],[13,12]])s.tiles.find(t=>t.x===x&&t.y===y)!.obstacle=true;s.time=.25;expect(tickEnemyDecision(s,e,0)?.id).toBe(al.id);});

import {step,command} from '../src/core/engine';
/** Controlled geometry fixtures; these are not natural keyboard/mouse evidence. */
function landingFixture(trace=true){const x=fire(trace);for(const p of enemyWorld(x.s).entities)p.to={...x.h.pos};x.e.enemyV2!.brain=undefined;return x;}
test('main resolveHit owns multi-wave HP, trace off preserves HP RNG and runtime identities',()=>{const run=(trace:boolean)=>{const {s,h,al,e}=landingFixture(trace),hp=[h.hp,al.hp];step(s,1.1);expect(h.hp).toBeLessThan(hp[0]);expect(al.hp).toBeLessThan(hp[1]);return {hp:[h.hp,al.hp],seed:s.seed,contacts:e.enemyV2!.trace.filter(r=>r.kind==='contact'),entities:s.enemyRuntime!.entities.map(p=>[p.id,p.context.actionId,p.attack.attackEventId])};};expect(run(false)).toEqual(run(true));});
test('explosion center direction guards the front but not the rear using main Hunter defense',()=>{for(const front of [true,false]){const {s,h,al,e}=landingFixture();al.pos={x:20,y:20};for(const p of enemyWorld(s).entities){p.to={x:h.pos.x+(front?.3:-.3),y:h.pos.y};p.heading=Math.PI;}command(s,{type:'hunterInput',id:h.id,kind:'guard',held:true,aim:{x:h.pos.x+5,y:h.pos.y}});const hp=h.hp;step(s,1.1);if(front){expect(h.hp).toBe(hp);expect(e.enemyV2!.trace.some(r=>r.defense==='block')).toBe(true);}else{expect(h.hp).toBeLessThan(hp);expect(e.enemyV2!.trace.some(r=>r.defense==='block')).toBe(false);}}});
test('main Al roll immunity rejects an actual explosion contact without HP loss',()=>{const {s,h,al,e}=landingFixture();h.pos={x:20,y:20};for(const p of enemyWorld(s).entities)p.to={...al.pos};s.time=1.5;command(s,{type:'controlBody',id:al.id});command(s,{type:'alInput',id:al.id,kind:'roll',direction:{x:0,y:1}});const hp=al.hp;step(s,.06);expect(al.hp).toBe(hp);expect(e.enemyV2!.trace.some(r=>r.targetId===al.id&&r.defense==='invulnerable')).toBe(true);});
