import {test,expect} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
const dir='../work/EN-03/browser';mkdirSync(dir,{recursive:true});test.setTimeout(90000);
async function read(page:any){return page.evaluate(()=>{const p=(window as any).prototype,s=p.state;return {time:s.time,controlled:s.controlledBodyId,generation:s.combatIdentity.generation,units:s.units.filter((u:any)=>u.enemyV2||['hunter','ranger'].includes(u.id)).map((u:any)=>({id:u.id,hp:u.hp,life:u.life,pos:u.pos,heading:u.heading,shadow:u.shadowResident,v2:u.enemyV2,al:u.alCombat,hunter:u.hunterCombat})),entities:s.enemyRuntime?.entities??[],views:[...p.scene.unitVisuals.values()].map((a:any)=>({id:a.unit.id,profile:a.referenceProfile,ready:a.reference?.ready,pose:a.reference?.pose,failed:a.loadFailed})),combat:s.combatIdentity.trace};});}
async function save(page:any,name:string){const s=await read(page);writeFileSync(dir+'/'+name+'.json',JSON.stringify({method:'ordinary keyboard/mouse; state and scene read only',...s},null,2));await page.screenshot({path:dir+'/'+name+'.png'});return s;}
async function ready(page:any,mode:string){await page.goto('/?enemies=v2&mode='+mode);await expect(page.locator('[data-v2=reset]')).toBeVisible();await expect.poll(()=>page.evaluate(()=>{const p=(window as any).prototype;return p?.state.units.filter((u:any)=>u.enemyVisualProfileId).every((u:any)=>p.scene.unitVisuals.get(u.id)?.reference?.ready);}),{timeout:35000}).toBe(true);}
test('EN03 real original archer, three committed flights, no flight damage and natural whiff',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await ready(page,'ranged');await page.keyboard.press('h');
 await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.enemyRuntime?.entities.length??0),{timeout:30000,intervals:[50]}).toBe(3);
 const flight=await save(page,'flight');const enemy=flight.units.find((u:any)=>u.v2);expect(enemy.v2.profile.visual).toBe('ranged');expect(enemy.v2.trace.filter((r:any)=>r.kind==='contact')).toHaveLength(0);expect(new Set(flight.entities.map((e:any)=>e.context.parentActionId)).size).toBe(2);
 await page.keyboard.down('d');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.enemyV2).enemyV2.trace.filter((r:any)=>r.kind==='land').length),{timeout:15000,intervals:[50]}).toBe(3);await page.keyboard.up('d');const end=await save(page,'landing');expect(end.units.find((u:any)=>u.id==='hunter').pos).not.toEqual(flight.units.find((u:any)=>u.id==='hunter').pos);expect(end.units.find((u:any)=>u.v2).v2.trace.filter((r:any)=>r.kind==='contact')).toHaveLength(0);expect(errors).toEqual([]);
});
test('EN03-MIX both original bodies, real Z RMB Shift, shared clock and repeated mode resets',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await ready(page,'mix');const initial=await save(page,'mix-start');expect(initial.units.filter((u:any)=>u.v2)).toHaveLength(2);
 let targeted=false;for(let attempt=0;attempt<8;attempt++){const focus=await page.evaluate(async()=>{const p=(window as any).prototype,{focusTargetLegal}=await import('/src/core/party-tactics.ts' as any),q=p.project(p.state.units.find((u:any)=>u.id==='v2-ranged').pos);const points=[];for(let dy=-85;dy<=45;dy+=5)for(let dx=-45;dx<=45;dx+=5){const x=q.x+dx,y=q.y+dy;if(document.elementFromPoint(x,y)?.closest('#scene')&&p.scene.pick(x,y).unitId==='v2-ranged')points.push({x,y});}if(!points.length)throw Error('Archer needs a hoverable main scene position');return {...points[Math.floor(points.length/2)],legal:focusTargetLegal(p.state,'v2-ranged'),context:p.state.context};});writeFileSync(dir+'/focus-attempt.json',JSON.stringify(focus));await page.mouse.move(focus.x,focus.y);await page.keyboard.down('g');await expect(page.locator('#tactic-wheel')).toBeVisible();targeted=await page.evaluate(()=>(window as any).prototype.wheel.targetId==='v2-ranged');if(targeted)break;await page.keyboard.press('Escape');await page.keyboard.up('g');}expect(targeted).toBe(true);const box=(await page.locator('#tactic-wheel').boundingBox())!;await page.mouse.move(box.x+box.width-25,box.y+box.height/2);await page.keyboard.up('g');

 const p=await page.evaluate(()=>{const p=(window as any).prototype;return p.project(p.state.units.find((u:any)=>u.id==='v2-zombie').pos);});await page.mouse.move(p.x,p.y);await page.mouse.down({button:'right'});
 await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='v2-zombie').enemyV2.trace.some((r:any)=>r.event==='attack')),{timeout:30000}).toBe(true);await page.mouse.up({button:'right'});await page.keyboard.press('z');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.controlledBodyId)).toBe('ranger');
 const target=await page.evaluate(()=>{const p=(window as any).prototype;return p.project(p.state.units.find((u:any)=>u.id==='v2-ranged').pos);});await page.mouse.move(target.x,target.y);await page.mouse.down({button:'right'});await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').alCombat?.trace.some((e:any)=>e.kind==='ammo-payment')),{timeout:15000}).toBe(true);await page.mouse.up({button:'right'});await page.keyboard.press('Shift');await page.keyboard.down('d');await page.waitForTimeout(350);await page.keyboard.up('d');await save(page,'mix-controls');
 await page.keyboard.press('Space');const frozen=(await read(page)).time;await page.waitForTimeout(250);expect((await read(page)).time).toBe(frozen);await page.keyboard.press('Space');await page.mouse.move(720,400);await page.keyboard.down('g');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.effectiveTimeScale)).toBe(.1);await page.keyboard.up('g');await page.keyboard.press('Alt');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.effectiveTimeScale)).toBe(2);
 const generation=(await read(page)).generation;for(const mode of ['zombie','ranged','mix','zombie','ranged','mix'])await page.locator('[data-v2='+mode+']').click();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.combatIdentity.generation)).toBe(generation+6);await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.unitVisuals.size)).toBe(initial.views.length);await save(page,'mix-reset');expect(errors).toEqual([]);
});

test('EN03 natural Hunter damage then post-Hit kill retains three independent landings',async({page})=>{
 await ready(page,'ranged');await page.keyboard.press('h');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.time)).toBeGreaterThan(0);
 const aim=async()=>{const p=await page.evaluate(()=>{const p=(window as any).prototype;return p.project(p.state.units.find((u:any)=>u.id==='v2-ranged').pos);});await page.mouse.move(p.x,p.y);};
 await aim();await page.keyboard.down('e');await page.waitForTimeout(230);await page.keyboard.up('e');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='v2-ranged').hp),{timeout:15000}).toBeLessThan(110);await save(page,'pre-damaged');
 // Follow through ordinary WASD while withholding attacks until the actual root Hit.
 await expect.poll(async()=>{const f=await page.evaluate(()=>{const s=(window as any).prototype.state,h=s.units.find((u:any)=>u.id==='hunter'),e=s.units.find((u:any)=>u.id==='v2-ranged');return {released:e.enemyV2.trace.some((r:any)=>r.event==='attack'),x:e.pos.x-h.pos.x,y:e.pos.y-h.pos.y,d:Math.hypot(e.pos.x-h.pos.x,e.pos.y-h.pos.y)};});for(const k of ['w','a','s','d'])await page.keyboard.up(k);if(f.d>1.4)await page.keyboard.down(Math.abs(f.y)>Math.abs(f.x)?f.y<0?'w':'s':f.x<0?'a':'d');return f.released;},{timeout:25000,intervals:[75]}).toBe(true);
 for(const k of ['w','a','s','d'])await page.keyboard.up(k);const committed=await read(page);expect(committed.entities.length).toBe(3);await aim();await page.mouse.down();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='v2-ranged').life),{timeout:20000,intervals:[50]}).toBe('dead');await page.mouse.up();const death=await save(page,'post-hit-death');expect(death.entities.some((e:any)=>e.kind==='transport')).toBe(true);
 await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='v2-ranged').enemyV2.trace.filter((r:any)=>r.kind==='land').length),{timeout:15000,intervals:[50]}).toBe(3);await save(page,'dead-caster-landings');
});

test('EN03-MIX real Hunter shield contact with companion recalled through H',async({page})=>{
 await ready(page,'mix');await page.keyboard.press('h');
 await expect.poll(async()=>{const f=await page.evaluate(()=>{const p=(window as any).prototype,e=p.state.units.find((u:any)=>u.id==='v2-zombie');return {p:p.project(e.pos),block:e.enemyV2.trace.some((r:any)=>r.defense==='block'),guard:p.state.units.find((u:any)=>u.id==='hunter').hunterCombat?.special?.kind==='guard'};});await page.mouse.move(f.p.x,f.p.y);if(!f.guard){await page.mouse.up({button:'right'});await page.mouse.down({button:'right'});}return f.block;},{timeout:30000,intervals:[150]}).toBe(true);
 await page.mouse.up({button:'right'});await save(page,'mix-real-guard');
});
