import {test,expect} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
const dir='../work/EN-04/browser';mkdirSync(dir,{recursive:true});test.setTimeout(90000);
async function ready(page:any){await page.goto('/?enemies=v2&mode=zombie');await expect(page.locator('#en01-panel')).toContainText('架势：归零立即受控');await expect.poll(()=>page.evaluate(()=>{const p=(window as any).prototype;return p?.state.units.filter((u:any)=>u.enemyVisualProfileId).every((u:any)=>p.scene.unitVisuals.get(u.id)?.reference?.ready);}),{timeout:35000}).toBe(true);}
test('EN04 natural Hunter attacks control a living original zombie on the same zero contact',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await ready(page);await page.keyboard.press('h');
 await expect.poll(async()=>{const q=await page.evaluate(()=>{const p=(window as any).prototype,h=p.state.units.find((u:any)=>u.id==='hunter'),e=p.state.units.find((u:any)=>u.enemyV2);return {q:p.project(e.pos),d:Math.hypot(h.pos.x-e.pos.x,h.pos.y-e.pos.y),dx:e.pos.x-h.pos.x,dy:e.pos.y-h.pos.y};});for(const k of ['w','a','s','d'])await page.keyboard.up(k);if(q.d>1.4)await page.keyboard.down(Math.abs(q.dy)>Math.abs(q.dx)?q.dy<0?'w':'s':q.dx<0?'a':'d');await page.mouse.move(q.q.x,q.q.y);return q.d;},{timeout:20000,intervals:[100]}).toBeLessThan(1.5);
 for(const k of ['w','a','s','d'])await page.keyboard.up(k);await page.mouse.down();
 await expect.poll(async()=>{const q=await page.evaluate(()=>{const p=(window as any).prototype,e=p.state.units.find((u:any)=>u.enemyV2);return {q:p.project(e.pos),broken:p.state.postureRuntime.trace.find((r:any)=>r.kind==='PostureBroken'&&r.targetId===e.id)};});await page.mouse.move(q.q.x,q.q.y);return !!q.broken;},{timeout:30000,intervals:[100]}).toBe(true);await page.mouse.up();
 const result=await page.evaluate(()=>{const p=(window as any).prototype,s=p.state;return {time:s.time,posture:s.postureRuntime,units:s.units.map((u:any)=>({id:u.id,life:u.life,hp:u.hp,posture:u.posture,control:u.postureControl,v2:u.enemyV2,shadow:u.shadowResident})),combat:s.combatIdentity.trace};});writeFileSync(dir+'/natural-zero.json',JSON.stringify({method:'real WASD/LMB; H recall makes this a single-controlled-Hunter case, not duo acceptance',...result},null,2));await page.screenshot({path:dir+'/natural-zero.png'});expect(errors).toEqual([]);
 const zero=result.posture.trace.find((r:any)=>r.kind==='PostureBroken');expect(zero.before).toBeGreaterThan(0);expect(zero.after).toBe(0);const controlled=result.units.find((u:any)=>u.id===zero.targetId);expect(controlled.life).toBe('active');expect(controlled.control.until-controlled.control.startedAt).toBeCloseTo(.6);expect(controlled.v2.action).toBeUndefined();
});
