import {test,expect} from 'vitest';
import {createEnemyPlaytest} from '../src/core/enemy-playtest';
import {command,step,resolveHit} from '../src/core/engine';
import {isPartyBody} from '../src/core/exploration-party';
import {visibleHazards,tacticalRisk} from '../src/core/companion-combat';
import {requestEnemyAction,advanceEnemyAction} from '../src/core/enemy-action';
import {commitEnemyRelease,enemyWorld} from '../src/core/enemy-attack-entity';
import {ARCHER,ZOMBIE} from '../src/core/enemy-profiles';
import {positionVisible} from '../src/core/visibility';
function duo(){const s=createEnemyPlaytest(0,'mix'),h=s.units.find(u=>u.id==='hunter')!,al=s.units.find(u=>u.id==='ranger')!,z=s.units.find(u=>u.id==='v2-zombie')!,r=s.units.find(u=>u.id==='v2-ranged')!;for(const e of [z,r]){e.enemyV2!.readyAt=100;e.enemyV2!.brain=undefined;}return {s,h,al,z,r};}
test('native known zombie preparation contributes actual hazard risk to offhand footwork',()=>{const x=duo();x.z.pos={x:x.h.pos.x+1,y:x.h.pos.y};x.z.heading=Math.PI;x.z.enemyV2!.readyAt=0;expect(requestEnemyAction(x.s,x.z,ZOMBIE,x.h).ok).toBe(true);expect(visibleHazards(x.s).some(a=>a.sourceId===x.z.id)).toBe(true);expect(tacticalRisk(x.s,x.al,x.h.pos)).toBeGreaterThan(5);});
test('three committed landing risks include unborn third and survive caster death',()=>{const x=duo();x.r.enemyV2!.readyAt=0;x.r.heading=Math.atan2(x.h.pos.y-x.r.pos.y,x.h.pos.x-x.r.pos.x);expect(requestEnemyAction(x.s,x.r,ARCHER,x.h).ok).toBe(true);x.s.time=.634;advanceEnemyAction(x.s,x.r).forEach(r=>commitEnemyRelease(x.s,r));x.r.life='dead';expect(visibleHazards(x.s).filter(h=>h.sourceId===x.r.id)).toHaveLength(3);expect(new Set(visibleHazards(x.s).map((h:any)=>h.observationKey)).size).toBe(3);});
test('V2 risk observations never disclose a landing outside player visibility',()=>{const x=duo();x.r.enemyV2!.readyAt=0;x.r.heading=Math.PI;expect(requestEnemyAction(x.s,x.r,ARCHER,x.h).ok).toBe(true);x.s.time=.634;advanceEnemyAction(x.s,x.r).forEach(r=>commitEnemyRelease(x.s,r));for(const e of enemyWorld(x.s).entities)e.to={x:30,y:30};expect(positionVisible(x.s,{x:30,y:30})).toBe(false);expect(visibleHazards(x.s).filter(h=>h.sourceId===x.r.id)).toHaveLength(0);});
test('committed landing threat uses its own geometry after the caster body leaves the world',()=>{const x=duo();x.r.enemyV2!.readyAt=0;expect(requestEnemyAction(x.s,x.r,ARCHER,x.h).ok).toBe(true);x.s.time=.634;advanceEnemyAction(x.s,x.r).forEach(r=>commitEnemyRelease(x.s,r));for(const e of enemyWorld(x.s).entities)e.to={...x.h.pos};x.s.units=x.s.units.filter(u=>u!==x.r);expect(tacticalRisk(x.s,x.al,x.h.pos)).toBeGreaterThan(5);});
test('one body control does not reset the other actual ammo; illegal controlled actor cannot cast',()=>{const x=duo();command(x.s,{type:'controlBody',id:x.al.id});command(x.s,{type:'alInput',id:x.al.id,kind:'shot',held:true,aim:x.z.pos});step(x.s,.04);command(x.s,{type:'alInput',id:x.al.id,kind:'shot',held:false});const ammo=x.al.alCombat!.ammo;x.h.posture=1;resolveHit(x.s,x.h,{...x.z.weapons[0],damage:1,postureDamage:15},1,x.z,{hitOrigin:x.z.pos});expect(x.h.stagger).toBeGreaterThan(0);expect(x.al.alCombat!.ammo).toBe(ammo);expect(command(x.s,{type:'hunterInput',id:x.h.id,kind:'active',aim:x.z.pos}).ok).toBe(false);expect(x.s.units.filter(u=>isPartyBody(x.s,u)&&!u.shadowResident)).toHaveLength(2);});
test('real tactics refuse unknown focus without charging resources and keep two body identity',()=>{const x=duo();const hp=x.h.hp,mp=x.h.hunterCombat?.mp,ammo=x.al.alCombat?.ammo;expect(command(x.s,{type:'partyTactic',issuerId:x.h.id,recipientId:x.al.id,kind:'focus',targetId:'hidden-next-group',requestId:1,expectedControlRevision:x.s.controlRevision??0}).ok).toBe(false);expect([x.h.hp,x.h.hunterCombat?.mp,x.al.alCombat?.ammo]).toEqual([hp,mp,ammo]);for(const kind of ['cautious','rally','free'] as const)expect(command(x.s,{type:'partyTactic',issuerId:x.h.id,recipientId:x.al.id,kind,requestId:2+['cautious','rally','free'].indexOf(kind),expectedControlRevision:x.s.controlRevision??0}).ok).toBe(true);});
test('new group offhand autonomy cannot start manual special ammo rocket or shield skill',()=>{const s=createEnemyPlaytest(0,'four');for(let i=0;i<100;i++)step(s,.05);const al=s.units.find(u=>u.id==='ranger')!;expect(al.alCombat?.trace.some(r=>r.kind==='ammo-payment'||r.kind==='rocket-payment')).toBe(false);expect(al.alCombat?.rocketCd??0).toBe(0);expect(s.units.filter(u=>isPartyBody(s,u))).toHaveLength(2);});
