import {test,expect} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
const dir='../work/EN-06/performance';mkdirSync(dir,{recursive:true});test.setTimeout(600000);
test('same Edge software WebGL 1/2/3/4/5 enemies: 30s static and 60s natural scripted combat',async({page,browser})=>{
 const errors:string[]=[],failures:string[]=[],rows:any[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failures.push(r.status()+' '+r.url());});page.on('requestfailed',r=>failures.push(r.url()+' '+r.failure()?.errorText));
 const sample=()=>page.evaluate(()=>{const p=(window as any).prototype,s=p.state,gl=p.scene.renderer.getContext(),debug=gl.getExtension('WEBGL_debug_renderer_info'),views=[...p.scene.unitVisuals.values()].filter((v:any)=>v.reference?.ready);return {wall:performance.now(),time:s.time,generation:s.combatIdentity.generation,phase:s.phase,scale:p.effectiveTimeScale,memory:{...p.scene.renderer.info.memory},render:{...p.scene.renderer.info.render},references:views.map((v:any)=>({id:v.unit.id,w:v.reference.canvas.width,h:v.reference.canvas.height,pose:v.reference.pose,ready:v.reference.ready})),entities:s.enemyRuntime?.entities.length??0,preparing:s.units.filter((u:any)=>u.enemyV2?.action).length,trace:s.combatIdentity.trace.length,postureTrace:s.postureRuntime.trace.length,liveEnemies:s.units.filter((u:any)=>u.enemyV2&&u.life==='active').length,activeParty:s.units.filter((u:any)=>['hunter','ranger'].includes(u.id)&&u.life==='active'&&!u.shadowResident).length,gl:debug?gl.getParameter(debug.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),dpr:devicePixelRatio,width:innerWidth,height:innerHeight,heap:(performance as any).memory?.usedJSHeapSize,frames:(window as any).__en06Frames?.splice(0)??[]};});
 for(const mode of ['zombie','mix','three','four','five']){
  await page.goto('/?enemies=v2&mode='+mode);await expect.poll(()=>page.evaluate(()=>(window as any).prototype?.state.time??0),{timeout:35000}).toBeGreaterThan(0);await page.keyboard.press('Space');
  await page.evaluate(()=>{const w=window as any;w.__en06Frames=[];let last=performance.now();function observe(now:number){if(w.__en06Frames.length<20000)w.__en06Frames.push(now-last);last=now;requestAnimationFrame(observe);}requestAnimationFrame(observe);});
  const row:any={mode,method:'natural UI/keyboard/mouse scripted; 30/60 wall seconds; no HP/position/clock injection',static:[],combat:[],resets:0};const start=Date.now();
  while(Date.now()-start<30000){await page.waitForTimeout(2000);row.static.push(await sample());}
  await page.keyboard.press('Space');await page.keyboard.press('z');await page.mouse.move(850,400);await page.mouse.down({button:'right'});const combatAt=Date.now();let tick=0;
  while(Date.now()-combatAt<60000){const q=await page.evaluate(()=>{const p=(window as any).prototype,s=p.state,u=s.units.find((u:any)=>u.id===s.controlledBodyId),e=s.units.filter((u:any)=>u.enemyV2&&u.life==='active').sort((a:any,b:any)=>Math.hypot(a.pos.x-u.pos.x,a.pos.y-u.pos.y)-Math.hypot(b.pos.x-u.pos.x,b.pos.y-u.pos.y))[0];return {point:e?p.project(e.pos):null,party:s.units.filter((u:any)=>['hunter','ranger'].includes(u.id)&&u.life==='active'&&!u.shadowResident).length};});if(q.point)await page.mouse.move(q.point.x,q.point.y);if(!q.party||!q.point){await page.mouse.up({button:'right'});await page.locator('[data-v2=reset]').click();row.resets++;await page.keyboard.press('z');await page.mouse.down({button:'right'});}if(tick++%5===3){await page.keyboard.down('s');await page.keyboard.press('Shift');await page.waitForTimeout(300);await page.keyboard.up('s');}await page.waitForTimeout(1700);row.combat.push(await sample());}
  await page.mouse.up({button:'right'});rows.push(row);writeFileSync(dir+'/samples.json',JSON.stringify({browser:browser.version(),date:new Date().toISOString(),errors,failures,rows},null,2));await page.screenshot({path:dir+'/'+mode+'-end.png'});console.log(mode+' measured 30s static / 60s combat; references '+row.combat.at(-1).references.length);
 }
 expect(errors).toEqual([]);expect(failures).toEqual([]);expect(rows.every(r=>[...r.static,...r.combat].every((q:any)=>q.trace<=512&&q.postureTrace<=512))).toBe(true);
});
