import {test,expect} from '@playwright/test';
test.setTimeout(60000);
test('ordinary exploration keeps current Blue41 and Yellow38 with natural Hunter four-stage input',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.locator('[data-journey="exploration"]').click();await page.locator('[data-companion="ranger"]').click();await page.locator('[data-action="carry"]').click();await expect.poll(()=>page.evaluate(()=>['hunter','ranger'].every(id=>(window as any).prototype.scene.unitVisuals.get(id)?.reference?.ready)),{timeout:25000}).toBe(true);
 const q=await page.evaluate(()=>{const p=(window as any).prototype,h=p.state.units.find((u:any)=>u.id==='hunter');return p.project({x:h.pos.x+1,y:h.pos.y});});await page.mouse.move(q.x,q.y);await page.mouse.down();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').hunterCombat.trace.filter((r:any)=>r.kind==='accepted'&&r.stage!==undefined).slice(0,4).map((r:any)=>r.stage)),{timeout:20000}).toEqual([0,1,2,3]);await page.mouse.up();expect(await page.evaluate(()=>!!(window as any).prototype.state.postureRuntime)).toBe(false);expect(errors).toEqual([]);
 });
test('ordinary Al still pays four native shots and reloads independently',async({page})=>{
 await page.goto('/');await page.locator('[data-journey="exploration"]').click();await page.locator('[data-companion="ranger"]').click();await page.locator('[data-action="carry"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').ready),{timeout:15000}).toBe(0);await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.unitVisuals.get('ranger')?.reference?.ready)).toBe(true);await page.keyboard.press('z');const q=await page.evaluate(()=>{const p=(window as any).prototype,h=p.state.units.find((u:any)=>u.id==='ranger');return p.project({x:h.pos.x+1,y:h.pos.y});});await page.mouse.move(q.x,q.y);await page.mouse.down({button:'right'});await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').alCombat.trace.filter((r:any)=>r.kind==='ammo-payment').length),{timeout:15000}).toBe(4);await page.mouse.up({button:'right'});await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').alCombat.ammo),{timeout:15000}).toBe(4);await expect(page.locator('#control-status')).toContainText('弹夹');
 });
