import {test,expect} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
const dir='../work/EN-06/browser';mkdirSync(dir,{recursive:true});test.setTimeout(150000);
async function ready(page:any,mode:string){await page.goto('/?enemies=v2&mode='+mode);await expect.poll(()=>page.evaluate(()=>(window as any).prototype?.state.time??0),{timeout:35000}).toBeGreaterThan(0);}
async function snap(page:any,name:string){const r=await page.evaluate(()=>{const p=(window as any).prototype,s=p.state;return {time:s.time,generation:s.combatIdentity.generation,controlled:s.controlledBodyId,tactics:s.partyTactics,units:s.units.filter((u:any)=>u.enemyV2||['hunter','ranger'].includes(u.id)).map((u:any)=>({id:u.id,life:u.life,hp:u.hp,pos:u.pos,posture:u.posture,shadow:u.shadowResident,v2:u.enemyV2,hunter:u.hunterCombat,al:u.alCombat,ai:u.companionCombat})),entities:s.enemyRuntime?.entities,combat:s.combatIdentity.trace,posture:s.postureRuntime.trace};});writeFileSync(dir+'/'+name+'.json',JSON.stringify({method:'natural keyboard/mouse, state read only; no H recall or position/HP injection',...r},null,2));await page.screenshot({path:dir+'/'+name+'.png'});return r;}
async function aim(page:any,id:string){const q=await page.evaluate((id:string)=>{const p=(window as any).prototype;return p.project(p.state.units.find((u:any)=>u.id===id).pos);},id);await page.mouse.move(q.x,q.y);}
async function focus(page:any){const q=await page.evaluate(()=>{const p=(window as any).prototype,e=p.state.units.find((u:any)=>u.id==='v2-ranged'),q=p.project(e.pos);for(let dy=-70;dy<=35;dy+=5)for(let dx=-40;dx<=40;dx+=5){const x=q.x+dx,y=q.y+dy;if(document.elementFromPoint(x,y)?.closest('#scene')&&p.scene.pick(x,y).unitId===e.id)return {x,y};}throw Error('visible original archer has no scene hover');});await page.mouse.move(q.x,q.y);await page.keyboard.down('g');await expect(page.locator('#tactic-wheel')).toBeVisible();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.wheel.targetId)).toBe('v2-ranged');const b=(await page.locator('#tactic-wheel').boundingBox())!;await page.mouse.move(b.x+b.width-25,b.y+b.height/2);await page.keyboard.up('g');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.partyTactics?.ranger?.kind)).toBe('focus');}
test('natural original zombie preparation displays a main-geometry sector with diagnostic collapsed',async({page})=>{await ready(page,'zombie');await expect(page.locator('[data-native-risk]')).toBeVisible({timeout:25000});expect(await page.locator('#en01-panel details').getAttribute('open')).toBeNull();await snap(page,'native-sector');});
test('continuous duo MIX: front shield, real offhand basic, G focus, Z and native ammo/roll',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await ready(page,'mix');await focus(page);await expect.poll(async()=>{const q=await page.evaluate(()=>{const p=(window as any).prototype,h=p.state.units.find((u:any)=>u.id==='hunter'),e=p.state.units.find((u:any)=>u.id==='v2-zombie');return {dx:e.pos.x-h.pos.x,dy:e.pos.y-h.pos.y,d:Math.hypot(e.pos.x-h.pos.x,e.pos.y-h.pos.y)};});for(const k of ['w','a','s','d'])await page.keyboard.up(k);if(q.d>.75)await page.keyboard.down(Math.abs(q.dy)>Math.abs(q.dx)?q.dy<0?'w':'s':q.dx<0?'a':'d');return q.d;},{timeout:15000,intervals:[100]}).toBeLessThan(.9);for(const k of ['w','a','s','d'])await page.keyboard.up(k);await aim(page,'v2-zombie');
 await page.mouse.down({button:'right'});await expect.poll(async()=>{await aim(page,'v2-zombie');const f=await page.evaluate(()=>{const s=(window as any).prototype.state,h=s.units.find((u:any)=>u.id==='hunter'),e=s.units.find((u:any)=>u.id==='v2-zombie');return {guard:h.hunterCombat?.special?.kind==='guard',block:e.enemyV2.trace.some((r:any)=>r.defense==='block')};});if(!f.guard){await page.mouse.up({button:'right'});await page.mouse.down({button:'right'});}return f.block;},{timeout:30000,intervals:[150]}).toBe(true).catch(async e=>{await snap(page,'mix-guard-failure');throw e;});await page.mouse.up({button:'right'});
 await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.combatIdentity.trace.some((r:any)=>r.type==='attack-released'&&r.context?.actorId==='ranger'&&r.context.kind==='basic')),{timeout:20000}).toBe(true);await snap(page,'mix-front-and-offhand');await snap(page,'mix-focus');
 await page.keyboard.press('z');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.controlledBodyId)).toBe('ranger');await aim(page,'v2-ranged');await page.mouse.down({button:'right'});await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').alCombat.trace.some((r:any)=>r.kind==='ammo-payment')),{timeout:20000}).toBe(true);await page.mouse.up({button:'right'});await page.keyboard.down('s');await expect.poll(async()=>{await page.keyboard.press('Shift');return page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').alCombat.rollCd>0);},{timeout:5000,intervals:[150]}).toBe(true);await page.keyboard.up('s');const end=await snap(page,'mix-switch-and-shoot');expect(end.units.filter((u:any)=>['hunter','ranger'].includes(u.id)&&!u.shadow)).toHaveLength(2);expect(errors).toEqual([]);
});
test('group natural native actions at 1x remain separate, deal damage and can kill',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 for(const mode of ['three','four','five']){await ready(page,mode);await page.keyboard.press('z');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.controlledBodyId)).toBe('ranger');
  await page.mouse.down({button:'right'});await expect.poll(async()=>{const q=await page.evaluate(()=>{const p=(window as any).prototype,s=p.state,e=s.units.filter((u:any)=>u.enemyV2&&u.life==='active').sort((a:any,b:any)=>Math.hypot(a.pos.x-6,a.pos.y-8)-Math.hypot(b.pos.x-6,b.pos.y-8))[0];return {id:e?.id,dead:s.units.some((u:any)=>u.enemyV2&&u.life==='dead')};});if(q.id)await aim(page,q.id);return q.dead;},{timeout:50000,intervals:[150]}).toBe(true);await page.mouse.up({button:'right'});const result=await snap(page,mode+'-combat');expect(result.units.filter((u:any)=>['hunter','ranger'].includes(u.id)&&!u.shadow)).toHaveLength(2);expect(result.combat.some((r:any)=>r.type==='hit-outcome')).toBe(true);
 }
 expect(errors).toEqual([]);
});
 test('four original enemies naturally commit two independent three-arrow groups at normal speed',async({page})=>{
  await ready(page,'four');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.enemyRuntime?.entities.filter((e:any)=>e.profile.visual==='ranged').length??0),{timeout:35000,intervals:[50]}).toBe(6);const committed=await snap(page,'four-six-committed');expect(new Set(committed.entities.map((e:any)=>e.context.actorId)).size).toBe(2);expect(new Set(committed.entities.map((e:any)=>e.id)).size).toBe(6);expect(committed.units.filter((u:any)=>['hunter','ranger'].includes(u.id)&&!u.shadow)).toHaveLength(2);await page.keyboard.press('z');await page.keyboard.down('s');await expect.poll(async()=>{await page.keyboard.press('Shift');return page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').alCombat.rollCd>0);},{timeout:10000,intervals:[150]}).toBe(true);await page.keyboard.up('s');await snap(page,'four-six-response');
 });
 test('natural five-enemy pressure controls Al at zero then real walking resumes',async({page})=>{
  await ready(page,'five');await focus(page);await page.keyboard.press('z');await expect.poll(async()=>{const q=await page.evaluate(()=>{const s=(window as any).prototype.state,h=s.units.find((u:any)=>u.id==='ranger'),e=s.units.filter((u:any)=>u.enemyV2&&u.life==='active').sort((a:any,b:any)=>Math.hypot(a.pos.x-h.pos.x,a.pos.y-h.pos.y)-Math.hypot(b.pos.x-h.pos.x,b.pos.y-h.pos.y))[0];return {dx:e.pos.x-h.pos.x,dy:e.pos.y-h.pos.y,d:Math.hypot(e.pos.x-h.pos.x,e.pos.y-h.pos.y),broken:s.postureRuntime.trace.some((r:any)=>r.kind==='PostureBroken'&&r.targetId==='ranger')};});for(const k of ['w','a','s','d'])await page.keyboard.up(k);if(!q.broken&&q.d>.65)await page.keyboard.down(Math.abs(q.dy)>Math.abs(q.dx)?q.dy<0?'w':'s':q.dx<0?'a':'d');return q.broken;},{timeout:35000,intervals:[100]}).toBe(true).catch(async e=>{await snap(page,'player-zero-not-observed');throw e;});for(const k of ['w','a','s','d'])await page.keyboard.up(k);const broken=await snap(page,'player-zero');const zero=broken.posture.find((r:any)=>r.kind==='PostureBroken'&&r.targetId==='ranger');expect(zero.before).toBeGreaterThan(0);expect(zero.after).toBe(0);const before=broken.units.find((u:any)=>u.id==='ranger').pos;await page.keyboard.down('s');await expect.poll(()=>page.evaluate(()=>{const h=(window as any).prototype.state.units.find((u:any)=>u.id==='ranger');return h.life==='active'&&h.stagger<=0&&h.posture>0;}),{timeout:12000,intervals:[100]}).toBe(true);await expect.poll(()=>page.evaluate((before:any)=>{const h=(window as any).prototype.state.units.find((u:any)=>u.id==='ranger');return Math.hypot(h.pos.x-before.x,h.pos.y-before.y);},before),{timeout:8000}).toBeGreaterThan(.3);await page.keyboard.up('s');const recovered=await snap(page,'player-recovered-walking');const h=recovered.units.find((u:any)=>u.id==='ranger');expect(Math.hypot(h.pos.x-before.x,h.pos.y-before.y)).toBeGreaterThan(.3);expect(recovered.units.filter((u:any)=>['hunter','ranger'].includes(u.id)&&!u.shadow)).toHaveLength(2);
 });
test('twenty main-world resets release original contexts and stale generation danger',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await ready(page,'five');const rows:any[]=[];
 for(let i=0;i<21;i++){if(i)await page.locator('[data-v2=reset]').click();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.time),{timeout:35000}).toBeGreaterThan(0);await page.keyboard.press('Space');rows.push(await page.evaluate(()=>{const p=(window as any).prototype,s=p.state;return {generation:s.combatIdentity.generation,memory:p.scene.renderer.info.memory,views:[...p.scene.unitVisuals.values()].filter((a:any)=>a.reference?.ready).map((a:any)=>({id:a.unit.id,w:a.reference.canvas.width,h:a.reference.canvas.height})),entities:s.enemyRuntime?.entities.length??0,trace:s.combatIdentity.trace.length,postureTrace:s.postureRuntime.trace.length};}));}
 writeFileSync(dir+'/reset-20.json',JSON.stringify(rows,null,2));expect(rows.at(-1).generation).toBe(rows[0].generation+20);expect(new Set(rows.map(r=>r.views.length)).size).toBe(1);expect(new Set(rows.slice(1).map(r=>r.memory.textures)).size).toBe(1);expect(new Set(rows.slice(1).map(r=>r.memory.geometries)).size).toBe(1);expect(rows.every(r=>r.entities===0&&r.trace<=512&&r.postureTrace<=512)).toBe(true);expect(errors).toEqual([]);
});
