import {test,expect} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
import {route} from './enbal01-browser-helpers';
const out='../work/EN-BAL-01-20261010/browser';mkdirSync(out,{recursive:true});
test.setTimeout(180000);
async function ready(page:any,url:string){await page.goto(url);if(!url.includes('enemies=v2')){await page.locator('[data-companion=ranger]').click();await page.locator('[data-action=carry]').click();}await expect.poll(()=>page.evaluate(()=>['hunter','ranger'].every(id=>(window as any).prototype?.scene.unitVisuals.get(id)?.reference?.ready)),{timeout:35000}).toBe(true);}
async function snapshot(page:any,label:string){const data=await page.evaluate(()=>{const s=(window as any).prototype.state;return {preset:s.enemyPressure,world:s.world?.id,time:s.time,phase:s.phase,context:s.context,units:s.units.filter((u:any)=>u.team==='enemy'||u.id==='hunter'||u.id==='ranger').map((u:any)=>({id:u.id,hp:u.hp,maxHp:u.maxHp,posture:u.posture,maxPosture:u.maxPosture,life:u.life,pos:u.pos,trace:u.enemyV2?.trace})),posture:s.postureRuntime?.trace,combat:s.combatIdentity?.trace,entities:s.enemyRuntime?.entities,stats:s.stats};});writeFileSync(out+'/'+label+'.json',JSON.stringify(data,null,2));await page.screenshot({path:out+'/'+label+'.png'});return data;}
async function approachOrdinary(page:any){
 const to=await page.evaluate(()=>{const s=(window as any).prototype.state,h=s.units.find((u:any)=>u.id==='hunter');return s.exploration.definition.encounters.filter((e:any)=>e.tier==='small').sort((a:any,b:any)=>Math.hypot(a.center.x-h.pos.x,a.center.y-h.pos.y)-Math.hypot(b.center.x-h.pos.x,b.center.y-h.pos.y))[0].center;});
 const path=await route(page,to);let i=0;const held=new Set<string>();
 for(let n=0;n<1600;n++){const d=await page.evaluate(()=>{const s=(window as any).prototype.state,h=s.units.find((u:any)=>u.id==='hunter');return {pos:h.pos,life:h.life,contact:s.combatIdentity.trace.some((r:any)=>r.type==='hit-outcome'&&r.context?.kind==='enemy'&&r.outcome?.hpLost>0&&r.outcome.targetId==='hunter'),enemy:s.units.filter((u:any)=>u.enemyV2&&u.life==='active'&&u.enemyV2.brain?.decision!=='idle'&&Math.hypot(u.pos.x-h.pos.x,u.pos.y-h.pos.y)<6).sort((a:any,b:any)=>Math.hypot(a.pos.x-h.pos.x,a.pos.y-h.pos.y)-Math.hypot(b.pos.x-h.pos.x,b.pos.y-h.pos.y))[0]?.pos};});if(d.contact){for(const k of held)await page.keyboard.up(k);return;}expect(d.life).toBe('active');if(d.enemy&&Math.hypot(d.enemy.x-d.pos.x,d.enemy.y-d.pos.y)<5){const dx=d.enemy.x-d.pos.x,dy=d.enemy.y-d.pos.y,next=[...(Math.abs(dx)>.4?[dx>0?'d':'a']:[]),...(Math.abs(dy)>.4?[dy>0?'s':'w']:[])];for(const k of [...held])if(!next.includes(k)){await page.keyboard.up(k);held.delete(k);}for(const k of next)if(!held.has(k)){await page.keyboard.down(k);held.add(k);}await page.waitForTimeout(60);continue;}while(i<path.length&&Math.hypot(path[i].x-d.pos.x,path[i].y-d.pos.y)<.3)i++;if(i===path.length)break;const dx=path[i].x-d.pos.x,dy=path[i].y-d.pos.y,next=[...(Math.abs(dx)>.13?[dx>0?'d':'a']:[]),...(Math.abs(dy)>.13?[dy>0?'s':'w']:[])];for(const k of [...held])if(!next.includes(k)){await page.keyboard.up(k);held.delete(k);}for(const k of next)if(!held.has(k)){await page.keyboard.down(k);held.add(k);}await page.waitForTimeout(60);}
 for(const k of held)await page.keyboard.up(k);
}
for(const [preset,width,height] of [['high-pressure-v1',1920,1080],['baseline',1440,900]] as const)test(`ordinary ${preset} actual contact and fixed HUD ${width}`,async({page})=>{
 await page.setViewportSize({width,height});await ready(page,'/?enemyPressure='+preset);await page.keyboard.press('AltLeft');await approachOrdinary(page);
 await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.combatIdentity.trace.some((r:any)=>r.type==='hit-outcome'&&r.context?.kind==='enemy'&&r.outcome?.hpLost>0&&r.outcome.targetId==='hunter')),{timeout:60000}).toBe(true);await page.keyboard.press('Space');const d=await snapshot(page,preset+'-ordinary-'+width);const hits=d.combat.filter((r:any)=>r.type==='hit-outcome'&&r.context?.kind==='enemy'&&r.outcome.hpLost>0&&r.outcome.targetId==='hunter');expect(hits.length).toBeGreaterThan(0);const h=d.units.find((u:any)=>u.id==='hunter');if(preset==='high-pressure-v1'){const first=hits[0].outcome;expect(first.hpLost/h.maxHp).toBeGreaterThan(.31);expect(first.hpLost/h.maxHp).toBeLessThan(.36);expect(first.enemyPressure).toBe(preset);await expect(page.locator('#world-status')).toContainText('敌方高压试验');}else expect(hits[0].outcome.hpLost/h.maxHp).toBeLessThan(.03);
 expect(d.preset).toBe(preset);expect(d.units.filter((u:any)=>u.id==='hunter'||u.id==='ranger')).toHaveLength(2);await expect(page.locator('.duo-face img')).toHaveAttribute('data-portrait-source','user');await page.keyboard.press('Space');await page.keyboard.press('z');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.controlledBodyId)).toBe('ranger');await page.keyboard.press('z');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.controlledBodyId)).toBe('hunter');
});
test('original named MIX remains baseline unless opted in',async({page})=>{await ready(page,'/?enemies=v2&mode=mix');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.some((u:any)=>u.enemyV2?.trace.some((r:any)=>r.kind==='contact'&&r.hpLost>0))),{timeout:50000}).toBe(true);await page.keyboard.press('Space');const d=await snapshot(page,'named-baseline');expect(d.preset).toBe('baseline');expect(d.units.flatMap((u:any)=>u.trace??[]).filter((r:any)=>r.hpLost>0).every((r:any)=>r.hpLost<10)).toBe(true);});
test('opted-in native zombie front guard and high contact remain on the original chain',async({page})=>{
 await ready(page,'/?enemies=v2&mode=zombie&enemyPressure=high-pressure-v1');const aim=async()=>{const q=await page.evaluate(()=>{const p=(window as any).prototype,e=p.state.units.find((u:any)=>u.enemyV2);return p.project(e.pos);});await page.mouse.move(q.x,q.y);};await aim();await page.mouse.down({button:'right'});
 await expect.poll(async()=>{await aim();const d=await page.evaluate(()=>{const s=(window as any).prototype.state,h=s.units.find((u:any)=>u.id==='hunter'),e=s.units.find((u:any)=>u.enemyV2);return {guard:h.hunterCombat.special?.kind==='guard',block:e.enemyV2.trace.some((r:any)=>r.defense==='block'),pos:h.pos,to:e.pos};});const dx=d.to.x-d.pos.x,dy=d.to.y-d.pos.y;for(const [key,down] of [['d',dx>.9],['a',dx<-.9],['s',dy>.9],['w',dy<-.9]]){if(down)await page.keyboard.down(key as string);else await page.keyboard.up(key as string);}if(!d.guard){await page.mouse.up({button:'right'});await page.mouse.down({button:'right'});}return d.block;},{timeout:55000,intervals:[100]}).toBe(true);await page.mouse.up({button:'right'});for(const k of ['w','a','s','d'])await page.keyboard.up(k);await page.keyboard.press('Space');const d=await snapshot(page,'high-native-guard');const h=d.units.find((u:any)=>u.id==='hunter');expect(h.hp).toBe(360);expect(d.posture.some((r:any)=>r.targetId==='hunter'&&r.raw===54&&r.guardMultiplier===.5&&r.loss===27)).toBe(true);
});
test('two opted-in native archers preserve six transports and real Z roll G response',async({page})=>{
 await ready(page,'/?enemies=v2&mode=four&enemyPressure=high-pressure-v1');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.enemyRuntime?.entities.filter((e:any)=>e.profile.visual==='ranged').length??0),{timeout:55000,intervals:[50]}).toBe(6);const d=await snapshot(page,'high-two-archers');const arrows=d.entities.filter((e:any)=>e.profile.visual==='ranged');expect(new Set(arrows.map((e:any)=>e.id)).size).toBe(6);expect(new Set(arrows.map((e:any)=>e.context.actorId)).size).toBe(2);await page.keyboard.press('z');await page.keyboard.down('s');await page.keyboard.press('Shift');await page.keyboard.up('s');await page.keyboard.down('g');await expect(page.locator('#tactic-wheel')).toBeVisible();const b=(await page.locator('#tactic-wheel').boundingBox())!;await page.mouse.move(b.x+b.width/2,b.y+b.height/2+90);await page.keyboard.up('g');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.combatIdentity.trace.some((r:any)=>r.type==='action-started'&&r.context?.actorId==='ranger'&&r.context?.executedAbilityId==='小黄翻滚'))).toBe(true);await page.waitForTimeout(1500);await page.keyboard.press('Space');await snapshot(page,'high-group-response');
});

for(const preset of ['baseline','high-pressure-v1'])test('native ranged real landing '+preset,async({page})=>{
 await ready(page,'/?enemies=v2&mode=ranged&enemyPressure='+preset);await page.keyboard.press('z');
 await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.enemyRuntime?.entities.some((e:any)=>e.kind==='transport')),{timeout:30000}).toBe(true);
 const aim=await page.evaluate(()=>{const s=(window as any).prototype.state,e=s.units.find((u:any)=>u.enemyV2),a=e.enemyV2.trace.filter((r:any)=>r.kind==='accepted').at(-1),p=s.enemyRuntime.entities.find((p:any)=>p.kind==='transport');return {target:a.targetId,to:p.to,current:s.controlledBodyId};});
 if(aim.current!==aim.target)await page.keyboard.press('z');
 const held=new Set<string>();let contacted=false;
 for(let n=0;n<500;n++){const d=await page.evaluate(()=>{const s=(window as any).prototype.state,u=s.units.find((u:any)=>u.id===s.controlledBodyId);return {pos:u.pos,hit:s.combatIdentity.trace.some((r:any)=>r.type==='hit-outcome'&&r.context?.kind==='enemy'&&r.outcome.resolveAccepted)};});if(d.hit){contacted=true;break;}const dx=aim.to.x-d.pos.x,dy=aim.to.y-d.pos.y,next=[...(Math.abs(dx)>.2?[dx>0?'d':'a']:[]),...(Math.abs(dy)>.2?[dy>0?'s':'w']:[])];for(const k of [...held])if(!next.includes(k)){await page.keyboard.up(k);held.delete(k);}for(const k of next)if(!held.has(k)){await page.keyboard.down(k);held.add(k);}await page.waitForTimeout(40);}
 for(const k of held)await page.keyboard.up(k);await page.keyboard.press('Space');const d=await snapshot(page,'native-ranged-'+preset);expect(contacted).toBe(true);
 const hits=d.combat.filter((r:any)=>r.type==='hit-outcome'&&r.context?.kind==='enemy'&&r.outcome.resolveAccepted),first=hits[0].outcome,target=d.units.find((u:any)=>u.id===first.targetId);expect(first.enemyPressure).toBe(preset);if(preset==='high-pressure-v1')expect(first.hpLost/target.maxHp).toBeCloseTo(1/3);else expect(first.hpLost/target.maxHp).toBeLessThan(.02);
 expect(d.units.flatMap((u:any)=>u.trace??[]).filter((r:any)=>r.kind==='committed').length).toBeGreaterThanOrEqual(3);
});
test('independent Action Lab still cycles original four ammo without pressure migration',async({page})=>{
 await page.goto('/action-lab.html');await expect(page.locator('#readiness')).toHaveText('原资源就绪');await page.locator('#player').selectOption('cannoneer');await expect(page.locator('#player-readiness')).toContainText('原魔弹射手骨架就绪');
 const b=(await page.locator('#arena').boundingBox())!,scale=Math.min(b.width/16,b.height/9);await page.mouse.move(b.x+b.width/2-6*scale,b.y+b.height/2);await page.mouse.down({button:'right'});
 await expect.poll(()=>page.evaluate(()=>(window as any).AL03Snapshot().events.filter((r:any)=>r.eventKind==='resource-payment').length)).toBe(4);await page.mouse.up({button:'right'});
 await expect.poll(()=>page.evaluate(()=>(window as any).AL03Snapshot().resources[0].value)).toBe('4 / 4');const facts=await page.evaluate(()=>({text:document.body.innerText,lab:(window as any).AL03Snapshot()}));writeFileSync(out+'/action-lab.json',JSON.stringify(facts,null,2));await page.screenshot({path:out+'/action-lab.png'});expect(facts.text).not.toContain('敌方高压试验');expect(facts.lab.events.filter((r:any)=>r.eventKind==='yellow-fire')).toHaveLength(4);
});
