import {expect,it} from 'vitest';
import * as THREE from 'three';
import {createGame,command} from '../src/core/engine';
import {startIntent} from '../src/core/attack-intent';
import {scheduleEnemyReaction} from '../src/core/enemy-combat';
import {TelegraphLayer} from '../src/view/telegraph';
function setup(){const s=createGame();command(s,{type:'selectJourney',journey:'exploration'});command(s,{type:'selectExplorationCompanion',id:'ines'});command(s,{type:'carry',gold:0,vitality:0});s.tiles.forEach(t=>{t.obstacle=false;t.layer=0;});const h=s.units[0],e=s.units.find(u=>u.role==='melee')!;s.units=[h,e];h.pos={x:11,y:10};e.pos={x:10,y:10};e.enemySense!.home={...e.pos};e.enemyMotion='engaged';e.pursuitTargetId=h.id;return {s,h,e};}
const world=(p:{x:number;y:number})=>new THREE.Vector3(p.x,.065,p.y);
it('ability uses same authoritative area and extra line while Basic keeps original style; buffers stay finite',()=>{const {s,h,e}=setup(),v=new TelegraphLayer();startIntent(s,e,h,'melee-heavy-cleave');v.update(s,world);const g=v.group.children[0];expect(g.userData.area).toBe(e.attackIntent!.area);expect(g.userData.label).toBe('裂阵重斩');expect(g.children[3].visible).toBe(true);for(const obj of g.children){const geom=(obj as THREE.Mesh).geometry,attr=geom.getAttribute('position');expect(attr.array.length%3).toBe(0);expect(Number.isFinite(geom.boundingSphere!.radius)).toBe(true);}e.attackIntent=undefined;s.time=1;startIntent(s,e,h);v.update(s,world);expect(v.group.children[0].children[3].visible).toBe(false);v.dispose();});
it('reaction Tell remains present throughout pending time, static arc/arrow is readable and hidden sources clean up',()=>{const {s,h,e}=setup(),v=new TelegraphLayer();scheduleEnemyReaction(s,e,h);v.update(s,world);expect(v.reactions.children).toHaveLength(1);expect(v.reactions.children[0].userData).toMatchObject({reaction:'counter-step',phase:'pending'});const geom=(v.reactions.children[0] as THREE.Line).geometry;expect(geom.drawRange.count).toBe(5);s.time=.14;v.update(s,world);expect((v.reactions.children[0] as THREE.Line).geometry).toBe(geom);e.pos={x:50,y:50};v.update(s,world);expect(v.reactions.children).toHaveLength(0);v.dispose();});
