import {legacyGame as createGame} from './legacy-fixtures';
import { describe, it, expect } from 'vitest';
import {  command, step, pathTo, enemyPathTo, canHit, rangeTiles, skillRangeTiles } from '../src/core/engine';
const battle = () => { const s = createGame(); command(s, { type: 'start' }); s.units.forEach(u=>u.skillCd=0); s.spawnTimer = 999;s.waves.forEach(w=>w.startAt=999); return s; };
describe('battle rules', () => {
    it('allows immediate reroutes without movement cooldown', () => { const s = battle(); expect(command(s, { type: 'move', id: 'hunter', to: { x: 4, y: 4 } }).ok).toBe(true); expect(command(s, { type: 'move', id: 'hunter', to: { x: 5, y: 4 } }).ok).toBe(true); expect(s.units[0].destination).toEqual({ x: 5, y: 4 }); });
    it('rejects occupied deployment without changing reserve state', () => { const s = battle(); expect(command(s, { type: 'deploy', id: 'guard', to: { x: 2, y: 4 }, facing: 'east' }).ok).toBe(false); expect(s.units.find(u => u.id === 'guard')!.life).toBe('reserve'); });
    it('finds a path around a blocked tile', () => { const s = battle(); s.barricades.push({ x: 3, y: 4 }); const p = pathTo(s, { x: 2, y: 4 }, { x: 4, y: 4 }); expect(p.length).toBeGreaterThan(2); expect(p).not.toContainEqual({ x: 3, y: 4 }); expect(p.at(-1)).toEqual({ x: 4, y: 4 }); });
    it('shares range preview and hit geometry including layers', () => { const s = battle(), u = s.units[0]; u.pos = { x: 2, y: 4 }; const target = { ...u, team: 'enemy' as const, pos: { x: 5, y: 4 } }; expect(canHit(s, u, target, 'east')).toBe(true); expect(rangeTiles(s, u, 'east')).toContainEqual(target.pos); expect(canHit(s, u, { ...target, pos: { x: 2, y: 3 } }, 'east')).toBe(true); });
    it('keeps damage on defeat but refills crystal only when reentering', () => { const s = battle(); s.units[0].hp = 33; s.crystalHp = 0; step(s, .1); expect(s.phase).toBe('result'); expect(s.result).toBe('defeat'); command(s, { type: 'continue' }); command(s, { type: 'enter', node: 1 }); expect(s.crystalHp).toBe(s.crystalMax); expect(s.units[0].hp).toBe(33); });
    it('rescues unexpired downed allies on defeat without reviving dead allies', () => { const s = battle(), g = s.units.find(u => u.id === 'guard')!, r = s.units.find(u => u.id === 'ranger')!; g.life = 'downed'; g.downTimer = 10; g.hp = 0; r.life = 'dead'; r.hp = 0; s.crystalHp = 0; step(s, .1); expect(g.life).toBe('rescued'); expect(g.hp).toBe(1); expect(r.life).toBe('dead'); });
    it('refreshes only deck cards and refuses invalid card targets', () => { const s = battle(); s.cards.push({...s.cards[0],id:'earned-exclusive',kind:'power',group:'exclusive'}); const keep = s.cards.filter(c => c.group !== 'deck').map(c => c.id); s.fragments = 100; expect(command(s, { type: 'draw' }).ok).toBe(true); expect(s.cards.filter(c => c.group === 'deck')).toHaveLength(4); expect(s.cards.filter(c => c.group !== 'deck').map(c => c.id)).toEqual(keep); const card = s.cards.find(c => c.kind === 'heal')!; const n = s.cards.length; expect(command(s, { type: 'card', cardId: card.id, to: { x: -1, y: 0 } }).ok).toBe(false); expect(s.cards).toHaveLength(n); });
    it('ordinary shadow resident freezes statuses and skill cooldown', () => { const s = battle(), g = s.units.find(u => u.id === 'guard')!; g.life = 'withdrawn'; g.shadowResident=true; g.skillCd = 10; g.statuses = [{ kind: 'poison', remaining: 9, power: 1 }]; const hp = g.hp; step(s, 1); expect(g.hp).toBe(hp); expect(g.statuses[0].remaining).toBe(9); expect(g.skillCd).toBeCloseTo(10); });
});
describe('movement and lifecycle integration', () => {
    it('does not permanently stop an ally when its blocking enemy dies', () => { const s = battle(), u = s.units[0]; const e = { ...structuredClone(u), id: 'foe', team: 'enemy' as const, pos: { x: 3, y: 4 }, drawPos: { x: 3, y: 4 }, hp: 1, maxHp: 1, path: [], destination: null }; s.units.push(e); command(s, { type: 'move', id: u.id, to: { x: 4, y: 4 } }); step(s, 4); expect(e.life).toBe('dead'); expect(u.pos).toEqual({ x: 4, y: 4 }); });
    it('disabled hunter crystal exit cannot trigger departure or respawn', () => { const s = battle(), u = s.units[0]; u.pos = { ...s.gate }; u.drawPos = { ...s.gate }; expect(command(s, { type: 'extract', id: u.id, via: 'gate' }).ok).toBe(false); step(s, 1); expect(u.life).toBe('active'); expect(command(s, { type: 'deploy', id: u.id, to: { x: 2, y: 4 }, facing: 'east' }).ok).toBe(false); });
    it('one click rescue saves nearby casualty and prevents redeployment this battle', () => { const s = battle(), u = s.units.find(u => u.id === 'guard')!; u.pos = { x: 3, y: 4 }; u.life = 'downed'; u.hp = 0; u.downTimer = 10; expect(command(s, { type: 'rescue', id: u.id }).ok).toBe(true); step(s, .1); expect(u.life).toBe('rescued'); expect(u.hp).toBe(1); expect(command(s, { type: 'deploy', id: u.id, to: { x: 4, y: 4 }, facing: 'east' }).ok).toBe(false); });
    it('moving away cancels skill damage and retains cooldown', () => { const s = battle(), u = s.units[0], e = { ...structuredClone(u), id: 'foe', team: 'enemy' as const, pos: { x: 6, y: 4 }, drawPos: { x: 6, y: 4 }, hp: 500, maxHp: 500, path: [], destination: null, damage: 0 }; s.units.push(e); command(s, { type: 'skill', id: u.id }); command(s, { type: 'move', id: u.id, to: { x: 2, y: 7 } }); step(s, 1.5); expect(e.hp).toBe(500); expect(u.skillTime).toBe(0); expect(u.skillCd).toBeGreaterThan(0); });
    it('rejoins an unwalked original route after a forced deviation', () => { const s = battle(), e = { ...structuredClone(s.units[0]), id: 'foe', team: 'enemy' as const, pos: { x: 6, y: 4 }, drawPos: { x: 6, y: 4 }, path: [], destination: { x: 0, y: 3 }, route: [{ x: 7, y: 2 }, { x: 6, y: 2 }, { x: 5, y: 2 }], routeIndex: 1, intent: 'move' as const }; s.units = [e]; step(s, .1); expect(e.path).toContainEqual({ x: 6, y: 2 }); expect(e.path).not.toContainEqual({ x: 7, y: 2 }); });
    it('shadow discovery from receiving an attack is local to that ally', () => { const s = battle(); s.mode = 'dark'; for (const u of s.units)
        u.light = 0; const h = s.units[0]; h.pos = { x: 2, y: 4 }; const e = { ...structuredClone(h), id: 'foe', team: 'enemy' as const, pos: { x: 3, y: 4 }, drawPos: { x: 3, y: 4 }, path: [], destination: null, defaultFacing: 'west' as const, facing: 'west' as const, reveal: 0 }; const other = s.units.find(u => u.id === 'ranger')!; other.life = 'active'; other.pos = { x: 1, y: 4 }; s.units.push(e); step(s, .4); expect(canHit(s, h, e, 'east')).toBe(true); expect(canHit(s, other, e, 'east')).toBe(false); });
});
describe('resource and settlement boundaries', () => {
    it('does not spend a barricade when placement seals the only passage', () => { const s = battle(); s.tiles.forEach(t => { t.obstacle = t.y !== 3; }); s.spawns = [{ x: 13, y: 3 }]; s.units = []; const c = s.cards.find(c => c.kind === 'barricade')!; expect(command(s, { type: 'card', cardId: c.id, to: { x: 7, y: 3 } }).ok).toBe(false); expect(s.cards.some(a => a.id === c.id)).toBe(true); expect(s.barricades).toHaveLength(0); });
    it('expiry at settlement takes precedence over automatic rescue', () => { const s = battle(), u = s.units.find(u => u.id === 'guard')!; u.life = 'downed'; u.downTimer = .01; u.hp = 0; s.crystalHp = 0; step(s, .05); expect(u.life).toBe('dead'); expect(u.hp).toBe(0); });
    it('spends one durability for a single attack without splash to the second target', () => { const s = battle(), u = s.units.find(u => u.id === 'guard')!; u.life = 'active'; u.pos = { x: 3, y: 3 }; u.weapons[0].durability = 3; const a = { ...structuredClone(u), id: 'foe-a', team: 'enemy' as const, pos: { x: 4, y: 3 }, hp: 100 }, b = { ...structuredClone(u), id: 'foe-b', team: 'enemy' as const, pos: { x: 4, y: 4 }, hp: 100 }; s.units = [u, a, b]; u.ready=0; a.ready=0;b.ready=0;step(s, .4); expect(a.hp).toBeLessThan(100); expect(b.hp).toBe(100); expect(u.weapons[0].durability).toBe(2); });
    it('exhausts reset opportunities without rolling back surviving health', () => { const s = battle(); s.retries = 0; s.units[0].hp = 17; s.crystalHp = 0; step(s, .1); expect(s.canStay).toBe(false); command(s, { type: 'continue' }); expect(s.phase).toBe('ended'); expect(s.units[0].hp).toBe(17); });
});
it('chooses nearest legal enemy across alternate directions when default has none', () => { const s = battle(), u = s.units[0]; u.pos = { x: 5, y: 4 }; u.drawPos = { ...u.pos }; u.defaultFacing = 'east'; const far = { ...structuredClone(u), id: 'north', team: 'enemy' as const, pos: { x: 5, y: 1 }, drawPos: { x: 5, y: 1 }, hp: 100 }, near = { ...structuredClone(u), id: 'west', team: 'enemy' as const, pos: { x: 4, y: 4 }, drawPos: { x: 4, y: 4 }, hp: 100 }; s.units = [u, far, near]; s.tiles.forEach(t => t.layer = 0); step(s, .4); expect(near.hp).toBeLessThan(100); expect(far.hp).toBe(100); });
describe('timing rules', () => {
    it('requires personal warmup before deployment rather than stunning after it', () => { const s = battle(), u = s.units.find(u => u.id === 'guard')!; expect(command(s, { type: 'deploy', id: u.id, to: { x: 3, y: 3 }, facing: 'east' }).ok).toBe(false); step(s, 10.1); expect(command(s, { type: 'deploy', id: u.id, to: { x: 3, y: 3 }, facing: 'east' }).ok).toBe(true); expect(u.ready).toBe(0); });
    it('ordinary movement updates authoritative position continuously', () => { const s = battle(), u = s.units[0]; command(s, { type: 'move', id: u.id, to: { x: 3, y: 4 } }); step(s, .7); expect(u.pos.x).toBeGreaterThan(2); expect(u.pos.x).toBeLessThan(3); expect(u.drawPos).toEqual(u.pos); });
    it('cross layer logical location switches after fade-out at boundary', () => { const s = battle(), u = s.units[0]; u.pos = { x: 4, y: 2 }; u.drawPos = { ...u.pos }; command(s, { type: 'move', id: u.id, to: { x: 4, y: 1 } }); for(let i=0;i<50&&!u.crossing;i++)step(s,.025); const from={...u.pos};step(s,.3);expect(u.pos).toEqual(from);step(s,.1);expect(u.pos.y).toBeLessThan(1.5);step(s,2);expect(u.pos).toEqual({x:4,y:1}); });
    it('dash card rapidly displaces one grid and provides brief evasion', () => { const s = battle(), u = s.units[0], c = s.cards.find(c => c.kind === 'dash')!; expect(command(s, { type: 'card', cardId: c.id, targetId: u.id, direction:'east', to: { x: 3, y: 4 } }).ok).toBe(true); expect(u.pos).toEqual({ x: 3, y: 4 }); expect(u.statuses.some(t => t.kind === 'guard')).toBe(true); });
    it('hunter independent skill remains active with its own area', () => { const s = battle(), u = s.units[0]; command(s, { type: 'skill', id: u.id }); step(s, 2.5); expect(u.skillTime).toBeGreaterThan(0); expect(skillRangeTiles(s, u, 'east')).toContainEqual({ x: 5, y: 3 }); });
    it('attack has cancellable windup and pays durability only on release', () => { const s = battle(), u = s.units[0], e = { ...structuredClone(u), id: 'foe', team: 'enemy' as const, pos: { x: 5, y: 4 }, drawPos: { x: 5, y: 4 }, hp: 100, attackTimer: 999 }; s.units.push(e); const durability = u.weapons[0].durability; step(s, .05); expect(e.hp).toBe(100); expect(u.weapons[0].durability).toBe(durability); command(s, { type: 'move', id: u.id, to: { x: 2, y: 7 } }); step(s, .5); expect(e.hp).toBe(100); });
});

it('reentry resets warmup and cannot carry pending attacks between nodes',()=>{const s=battle(),u=s.units.find(u=>u.id==='guard')!;u.ready=0;u.attackPending={targetId:'old',remaining:.1,facing:'east'};s.crystalHp=0;step(s,.1);command(s,{type:'continue'});command(s,{type:'enter',node:1});expect(u.ready).toBeGreaterThan(0);expect(u.attackPending).toBeUndefined();});
it('item range checks the actual target rather than an unrelated clicked tile',()=>{const s=battle(),u=s.units.find(u=>u.id==='guard')!;u.life='active';u.pos={x:12,y:7};u.hp=1;const count=s.inventory.heal;expect(command(s,{type:'item',item:'heal',to:{x:2,y:4},targetId:u.id}).ok).toBe(false);expect(s.inventory.heal).toBe(count);expect(u.hp).toBe(1);});
it('manual facing is rejected without changing automatic direction',()=>{const s=battle();expect(command(s,{type:'face',id:'hunter',facing:'north'}).ok).toBe(false);expect(s.units[0].facing).toBe('east');});
import {weightProfile,damageAfterDefense} from '../src/core/combat-config';
describe('damage weight and mental rules',()=>{
 it('matching subtype defense reduces damage while other subtypes bypass it',()=>{const s=battle(),u=s.units[0],w={...u.weapons[0],damageKind:'physical' as const,subtype:'pierce' as const};u.defense={subtype:'pierce',flat:12};expect(damageAfterDefense(w,u,25)).toBe(13);expect(damageAfterDefense({...w,damageKind:'arcane',subtype:'flame'},u,25)).toBe(25);});
 it('load bands reduce movement and attack speed when carried weight exceeds capacity',()=>{const s=battle(),u=s.units[0];u.capacity=10;u.weapons.forEach(w=>w.weight=6);expect(weightProfile(u).band).toBe('heavy');expect(weightProfile(u).move).toBeLessThan(1);expect(weightProfile(u).attack).toBeLessThan(1);u.weapons.forEach(w=>w.weight=10);expect(weightProfile(u).band).toBe('overweight');expect(weightProfile(u).dodge).toBe(0);});
 it('darkness alone never increases mental stress',()=>{const s=battle();s.mode='dark';const h=s.units[0];h.light=0;step(s,10);expect(h.stress).toBe(0);});
 it('taking damage at low health triggers stress once per internal cooldown',()=>{const s=battle(),h=s.units[0];h.hp=60;h.statuses=[{kind:'poison',power:1,remaining:10}];step(s,.1);const stress=h.stress;expect(stress).toBeGreaterThan(0);step(s,1);expect(h.stress).toBe(stress);});
 it('nearby ally falling triggers observer stress',()=>{const s=battle(),h=s.units[0],g=s.units.find(u=>u.id==='guard')!;g.life='active';g.ready=0;g.hp=1;g.pos={x:3,y:4};g.statuses=[{kind:'poison',power:100,remaining:1}];step(s,.1);expect(g.life).toBe('downed');expect(h.stress).toBeGreaterThan(0);});
 it('Fiorre mental threshold always gives a beneficial state',()=>{const s=battle(),f=s.units.find(u=>u.id==='fiorre')!;f.life='active';f.ready=0;f.stress=100;step(s,.1);expect(f.mental).toBe('inspired');expect(f.stress).toBeLessThan(100);});
 it('hunter retains manual movement under either mental outcome',()=>{const s=battle(),h=s.units[0];h.stress=100;step(s,.1);expect(['inspired','distressed']).toContain(h.mental);expect(command(s,{type:'move',id:h.id,to:{x:4,y:4}}).ok).toBe(true);});
 it('Fiorre support skill restores nearby allies without damaging enemies',()=>{const s=battle(),f=s.units.find(u=>u.id==='fiorre')!,h=s.units[0];f.life='active';f.ready=0;f.pos={x:2,y:3};h.hp=50;command(s,{type:'skill',id:f.id});step(s,1.1);expect(h.hp).toBeGreaterThan(50);});
 it('rejects incompatible spare weapon without changing current weapon',()=>{const s=battle(),h=s.units[0];h.compatibleClasses=['gun'];h.weapons[1].class='blade';expect(command(s,{type:'switchWeapon',id:h.id}).ok).toBe(false);expect(h.weaponIndex).toBe(0);});
});
it('an incompatible held weapon provides no hit range',()=>{const s=battle(),u=s.units[0],e={...structuredClone(u),id:'enemy-test',team:'enemy' as const,pos:{x:3,y:4}};u.compatibleClasses=['gun'];u.weapons[0].class='blade';expect(canHit(s,u,e,'east')).toBe(false);});
it('automatic draw refreshes deck at threshold even when deck hand is not empty',()=>{const s=battle();const old=s.cards.filter(c=>c.group==='deck').map(c=>c.id);s.fragments=20;s.autoDraw=true;step(s,.1);expect(s.fragments).toBe(0);expect(s.cards.filter(c=>c.group==='deck').some(c=>old.includes(c.id))).toBe(false);});
describe('complete encounter scenarios',()=>{
 it('allows same-layer diagonals without cutting blocked corners',()=>{const s=battle();expect(pathTo(s,{x:2,y:4},{x:3,y:5})).toEqual([{x:3,y:5}]);s.barricades.push({x:3,y:4});expect(pathTo(s,{x:2,y:4},{x:3,y:5})).not.toEqual([{x:3,y:5}]);});
 it('uses a cardinal step for a layer transition even when diagonal target is closer',()=>{const s=battle();s.tiles.find(t=>t.x===3&&t.y===5)!.layer=1;expect(pathTo(s,{x:2,y:4},{x:3,y:5}).length).toBeGreaterThan(1);});
 it('a three-wave joining-lane defense wins through real combat',()=>{const s=createGame();s.waves=s.waves.slice(0,3);s.totalEnemies=9;command(s,{type:'start'});step(s,10.1);expect(command(s,{type:'deploy',id:'guard',to:{x:2,y:7},facing:'east'}).ok).toBe(true);expect(command(s,{type:'deploy',id:'ranger',to:{x:3,y:4},facing:'east'}).ok).toBe(true);expect(command(s,{type:'deploy',id:'fiorre',to:{x:4,y:4},facing:'east'}).ok).toBe(true);expect(command(s,{type:'move',id:'hunter',to:{x:3,y:5}}).ok).toBe(true);for(let n=0;n<1600&&s.phase==='battle';n++){for(const u of s.units.filter(u=>u.team==='ally'&&['hunter','fiorre'].includes(u.role)&&u.life==='active'&&!u.path.length&&u.skillCd===0&&u.skillTime===0))command(s,{type:'skill',id:u.id});step(s,.25)}expect(s.result).toBe('victory');expect(s.kills).toBeGreaterThan(5);expect(s.crystalHp).toBeGreaterThan(0);expect(s.stats.skills).toBeGreaterThan(0);});
 it('an undefended encounter loses and reentry preserves actual combat losses',()=>{const s=createGame();command(s,{type:'start'});command(s,{type:'move',id:'hunter',to:{x:2,y:5}});for(let n=0;n<900&&s.units[0].weapons[0].durability===s.units[0].weapons[0].maxDurability;n++)step(s,.25);command(s,{type:'extract',id:'hunter',via:'gate'});for(let n=0;n<1000&&s.phase==='battle';n++)step(s,.25);expect(s.result).toBe('defeat');const h=s.units.find(u=>u.id==='hunter')!,hp=h.hp,durability=h.weapons[0].durability;expect(durability).toBeLessThan(h.weapons[0].maxDurability);expect(command(s,{type:'continue'}).ok).toBe(true);expect(command(s,{type:'enter',node:1}).ok).toBe(true);expect(h.hp).toBe(hp||1);expect(h.weapons[0].durability).toBe(durability);expect(s.crystalHp).toBe(s.crystalMax);});
});

it('Fiorre death disables current battle but restores one HP for the next entry',()=>{const s=battle();step(s,8.1);command(s,{type:'deploy',id:'fiorre',to:{x:3,y:4},facing:'east'});const f=s.units.find(u=>u.id==='fiorre')!;f.hp=1;f.statuses=[{kind:'poison',power:100,remaining:1}];step(s,.1);expect(f.life).toBe('rescued');expect(command(s,{type:'deploy',id:f.id,to:{x:4,y:4},facing:'east'}).ok).toBe(false);s.crystalHp=0;step(s,.1);command(s,{type:'continue'});command(s,{type:'enter',node:1});expect(f.life).toBe('reserve');expect(f.hp).toBe(1);});
describe('source-specific final rules',()=>{
 it('hunter respawn prefers an unoccupied cell around living Fiorre',()=>{const s=battle(),h=s.units[0],f=s.units.find(u=>u.id==='fiorre')!;f.life='active';f.ready=0;f.pos={x:9,y:3};h.life='respawning';h.respawnTimer=.01;step(s,.1);expect(h.life).toBe('active');expect(Math.abs(h.pos.x-f.pos.x)+Math.abs(h.pos.y-f.pos.y)).toBeLessThanOrEqual(3);expect(h.pos).not.toEqual(f.pos);});
 it('all spawned roles share the same slow base movement speed',()=>{const s=createGame();command(s,{type:'start'});step(s,51);expect(s.units.filter(u=>u.team==='enemy').length).toBeGreaterThanOrEqual(4);expect(new Set(s.units.map(u=>u.speed)).size).toBe(1);});
 it('exclusive hunter card is earned by kills rather than present initially',()=>{const s=battle(),h=s.units[0];expect(s.cards.filter(c=>c.group==='exclusive')).toHaveLength(0);for(let i=0;i<3;i++)s.units.push({...structuredClone(h),id:'reward-foe-'+i,team:'enemy',pos:{x:3,y:4},drawPos:{x:3,y:4},hp:1,dodge:0,speed:0,attackTimer:999});step(s,5);expect(s.cards.filter(c=>c.group==='exclusive')).toHaveLength(1);});
 it('manual weapon switch cancels pending shot while preserving remaining attack cycle',()=>{const s=battle(),h=s.units[0];h.attackTimer=.05;h.attackPending={targetId:'none',remaining:.2,facing:'east'};expect(command(s,{type:'switchWeapon',id:h.id}).ok).toBe(true);expect(h.attackTimer).toBe(.05);expect(h.attackPending).toBeUndefined();});
});


it('exclusive reward caps at one, can be earned after use, and survives reentry',()=>{const s=battle(),h=s.units[0];const add=(batch:number)=>{for(let i=0;i<3;i++)s.units.push({...structuredClone(h),id:'reward-'+batch+'-'+i,team:'enemy',pos:{x:3,y:4},drawPos:{x:3,y:4},hp:1,dodge:0,speed:0,attackTimer:999});step(s,5)};add(1);add(2);expect(s.cards.filter(c=>c.group==='exclusive')).toHaveLength(1);const first=s.cards.find(c=>c.group==='exclusive')!;expect(command(s,{type:'card',cardId:first.id,to:h.pos,targetId:h.id}).ok).toBe(true);add(3);const next=s.cards.find(c=>c.group==='exclusive')!;expect(next).toBeDefined();expect(next.id).not.toBe(first.id);s.crystalHp=0;step(s,.1);command(s,{type:'continue'});command(s,{type:'enter',node:1});expect(s.cards.some(c=>c.id===next.id)).toBe(true);});
describe('revised battle design',()=>{
 it('starts waves from their own previewed route and supports overlapping unequal timings',()=>{const s=createGame();expect(s.waves.length).toBeGreaterThanOrEqual(4);expect(s.waves.every(w=>w.previewAt<w.startAt)).toBe(true);expect(new Set(s.waves.slice(1).map((w,i)=>w.startAt-s.waves[i].startAt)).size).toBeGreaterThan(1);expect(s.waves.every(w=>w.count>0&&w.interval>0)).toBe(true);command(s,{type:'start'});step(s,s.waves[0].startAt+.01);expect(s.units.find(u=>u.team==='enemy')!.route).toEqual(s.waves[0].route.slice(1));});
 it('rejects duplicate card buffs from another group without consuming the card',()=>{const s=battle(),h=s.units[0],c=s.cards.find(c=>c.kind==='power')!;expect(command(s,{type:'card',cardId:c.id,to:h.pos,targetId:h.id}).ok).toBe(true);s.cards.push({...c,id:'same-effect-exclusive',group:'exclusive'});expect(command(s,{type:'card',cardId:'same-effect-exclusive',to:h.pos,targetId:h.id}).ok).toBe(false);expect(s.cards.some(c=>c.id==='same-effect-exclusive')).toBe(true);expect(h.statuses.filter(t=>t.kind==='attack')).toHaveLength(1);});
 it('uses one ground crystal for extraction and rejects shadow exit',()=>{const s=battle();expect(s.gate).toEqual(s.goal);expect(s.tiles.find(t=>t.x===s.goal.x&&t.y===s.goal.y)?.layer).toBe(0);expect(command(s,{type:'extract',id:'hunter',via:'shadow'}).ok).toBe(false);});
 it('guard is an 800 HP frontline and Fiorre heals the nearby group substantially',()=>{const s=battle(),g=s.units.find(u=>u.id==='guard')!,f=s.units.find(u=>u.id==='fiorre')!,h=s.units[0];expect(g.maxHp).toBe(800);f.life='active';f.ready=0;f.pos={x:3,y:4};h.hp=1;command(s,{type:'skill',id:f.id});step(s,1.1);expect(h.hp).toBeGreaterThanOrEqual(121);});
 it('manual facing is removed and idle facing points away from the crystal',()=>{const s=battle(),h=s.units[0];h.pos={x:0,y:2};h.drawPos={...h.pos};expect(command(s,{type:'face',id:h.id,facing:'south'}).ok).toBe(false);step(s,.1);expect(h.facing).toBe('north');expect(h.defaultFacing).toBe('north');});
});

it('enemies cannot use terraces as paths but allies still can cross layers',()=>{const s=createGame();expect(pathTo(s,{x:4,y:2},{x:4,y:1})).toHaveLength(1);expect(enemyPathTo(s,{x:4,y:2},{x:4,y:1})).toEqual([]);const p=enemyPathTo(s,s.spawns[0],s.goal);expect(p.length).toBeGreaterThan(0);expect(p.every(t=>s.tiles.find(a=>a.x===t.x&&a.y===t.y)?.layer===0)).toBe(true);});
it('enemies damage and destroy route barricades then continue toward crystal',()=>{const s=battle(),h=s.units[0],c=s.cards.find(c=>c.kind==='barricade')!;expect(command(s,{type:'card',cardId:c.id,to:{x:5,y:2}}).ok).toBe(true);h.life='reserve';const e={...structuredClone(h),id:'siege',team:'enemy' as const,life:'active' as const,pos:{x:6,y:2},drawPos:{x:6,y:2},ready:0,path:[{x:5,y:2},{x:4,y:2},{x:3,y:2},{x:2,y:2},{x:2,y:3},{x:1,y:3},{x:0,y:3}],route:[],destination:s.goal,intent:'move' as const};s.units.push(e);step(s,.1);expect(s.barrierHp!['5,2']).toBeLessThan(80);step(s,6);expect(s.barricades).not.toContainEqual({x:5,y:2});expect(e.pos.x).toBeLessThan(6);});
it('idle movement updates facing away from crystal without any direction choice',()=>{const s=battle(),h=s.units[0];h.pos={x:2,y:5};h.drawPos={...h.pos};command(s,{type:'move',id:h.id,to:{x:2,y:7}});step(s,1);expect(h.facing).toBe('south');});


it('between attacks the ally faces away from crystal even when a target is behind',()=>{const s=battle(),h=s.units[0];h.pos={x:5,y:4};h.drawPos={...h.pos};h.attackTimer=10;const e={...structuredClone(h),id:'rear-target',team:'enemy' as const,pos:{x:4,y:4},drawPos:{x:4,y:4},speed:0,attackTimer:999};s.units.push(e);step(s,.1);expect(h.facing).toBe('east');});
it('reentry resets displayed wave and all scheduled spawn counters',()=>{const s=battle();s.wave=4;s.waves.forEach(w=>w.spawned=w.count);s.crystalHp=0;step(s,.1);command(s,{type:'continue'});command(s,{type:'enter',node:1});expect(s.wave).toBe(0);expect(s.spawned).toBe(0);expect(s.waves.every(w=>w.spawned===0)).toBe(true);});
describe('independent skills and contact combat',()=>{
 it('hunter casting uses only skill events and never spends auto attack durability',()=>{const s=battle(),h=s.units[0],e={...structuredClone(h),id:'skill-target',team:'enemy' as const,pos:{x:3,y:4},drawPos:{x:3,y:4},hp:1000,maxHp:1000,speed:0,dodge:0,attackTimer:999};s.units.push(e);command(s,{type:'skill',id:h.id});const wear=h.weapons[0].durability;step(s,.4);expect(e.hp).toBeLessThan(1000);expect(s.effects.some(e=>e.sourceId===h.id&&e.action==='skill')).toBe(true);expect(s.effects.some(e=>e.sourceId===h.id&&e.action==='attack')).toBe(false);expect(h.weapons[0].durability).toBe(wear);expect(h.attackPending).toBeUndefined();});
 it('normal attack range does not expand when hunter skill starts',()=>{const s=battle(),h=s.units[0];const normal=rangeTiles(s,h,'east');command(s,{type:'skill',id:h.id});expect(rangeTiles(s,h,'east')).toEqual(normal);});
 it('opposing units on one logical tile can attack each other',()=>{const s=battle(),h=s.units[0],e={...structuredClone(h),id:'overlap',team:'enemy' as const,pos:{...h.pos},drawPos:{...h.pos},hp:1000,maxHp:1000,speed:0,dodge:0,attackTimer:0};h.dodge=0;s.units.push(e);expect(canHit(s,e,h)).toBe(true);const hp=h.hp;step(s,.4);expect(h.hp).toBeLessThan(hp);});
 it('deployment can share terrain cell without overlapping enemy footprints',()=>{const s=battle();step(s,10.1);const h=s.units[0],e={...structuredClone(h),id:'departing',team:'enemy' as const,pos:{x:5,y:2},drawPos:{x:4.8,y:2},path:[{x:4,y:2}],destination:s.goal,route:[{x:4,y:2},{x:3,y:2},{x:2,y:2},{x:2,y:3},{x:1,y:3},{x:0,y:3}],moveFrom:{x:5,y:2},moveProgress:.2,hp:1000,dodge:0,attackTimer:0};s.units.push(e);expect(command(s,{type:'deploy',id:'guard',to:{x:5.4,y:2},facing:'east'}).ok).toBe(true);const g=s.units.find(u=>u.id==='guard')!;const hp=g.hp;step(s,.4);expect(g.hp).toBeLessThan(hp);});
 it('guard poison toggle does not change permanent protection',()=>{const s=battle(),g=s.units.find(u=>u.id==='guard')!;g.life='active';g.ready=0;g.pos={x:3,y:4};g.statuses=[{kind:'poison',power:100,remaining:10}];const before=g.hp;step(s,.1);const normal=before-g.hp;command(s,{type:'skill',id:g.id});const activated=g.hp;step(s,.1);expect(normal).toBeLessThan(10);expect(activated-g.hp).toBeCloseTo(normal);});
 it('enemy death emits exactly one loot event at the death location',()=>{const s=battle(),h=s.units[0],e={...structuredClone(h),id:'loot-enemy',team:'enemy' as const,pos:{x:3,y:4},drawPos:{x:3,y:4},hp:1,speed:0,dodge:0,attackTimer:999};s.units.push(e);step(s,.4);const loot=s.effects.filter(e=>e.kind==='loot');expect(loot).toHaveLength(1);expect(loot[0].amount).toBe(4);expect(loot[0].from).toEqual({x:3,y:4});step(s,.1);expect(s.effects.filter(e=>e.kind==='loot')).toHaveLength(1);});
});

it('last enemy death retains loot for the result UI instead of clearing it with attacks',()=>{const s=battle(),h=s.units[0];s.spawned=s.totalEnemies=1;s.units.push({...structuredClone(h),id:'last-enemy',team:'enemy',pos:{x:3,y:4},drawPos:{x:3,y:4},hp:1,speed:0,dodge:0,attackTimer:999});step(s,.4);expect(s.result).toBe('victory');expect(s.effects.filter(e=>e.kind==='loot')).toHaveLength(1);});
it('skill areas remain independent of held weapon and match healing recipients',()=>{const s=battle(),f=s.units.find(u=>u.id==='fiorre')!,h=s.units[0],r=s.units.find(u=>u.id==='ranger')!;f.life='active';f.ready=0;f.pos={x:3,y:3};h.pos={x:3,y:4};h.hp=1;r.life='active';r.ready=0;r.pos={x:8,y:5};r.hp=1;expect(skillRangeTiles(s,f)).toContainEqual(h.pos);expect(skillRangeTiles(s,f)).not.toContainEqual(r.pos);const area=skillRangeTiles(s,h,'east');h.weapons[0].range=1;h.weapons[0].remote=false;expect(skillRangeTiles(s,h,'east')).toEqual(area);command(s,{type:'skill',id:f.id});step(s,1.1);expect(h.hp).toBe(161);expect(r.hp).toBe(1);});
describe('rev5 role and clone rules',()=>{
 it('battle entry resets skill charge instead of carrying previous cooldown',()=>{const s=battle(),h=s.units[0];h.skillCd=3;s.crystalHp=0;step(s,.1);command(s,{type:'continue'});command(s,{type:'enter',node:1});expect(h.skillCd).toBe(h.skillMax);});
 it('role weapons provide melee Fiorre, long-range ranger and throwing guard',()=>{const s=createGame();const f=s.units.find(u=>u.role==='fiorre')!,r=s.units.find(u=>u.role==='ranger')!,g=s.units.find(u=>u.role==='guard')!;expect(f.weapons[0].range).toBe(1);expect(f.weapons[0].remote).toBe(false);expect(r.weapons[0].range).toBe(7);expect(g.weapons[0].range).toBe(5);expect(g.weapons[0].remote).toBe(true);});
 it('Fiorre heal circle uses Euclidean radius three',()=>{const s=battle(),f=s.units.find(u=>u.role==='fiorre')!;f.pos={x:3,y:3};expect(skillRangeTiles(s,f)).toContainEqual({x:5,y:5});expect(skillRangeTiles(s,f)).not.toContainEqual({x:6,y:5});});
 it('ranger skill toggles permanent sniper mode without entering cast state',()=>{const s=battle(),r=s.units.find(u=>u.role==='ranger')!;r.life='active';r.ready=0;expect(command(s,{type:'skill',id:r.id}).ok).toBe(true);expect(r.sniperMode).toBe(true);expect(r.skillTime).toBe(0);step(s,20);expect(r.sniperMode).toBe(true);expect(command(s,{type:'skill',id:r.id}).ok).toBe(true);expect(r.sniperMode).toBe(false);});
 it('guard automatic poison skill defaults enabled and toggles off',()=>{const s=battle(),g=s.units.find(u=>u.role==='guard')!;expect(g.autoSkill).toBe(true);g.life='active';g.ready=0;expect(command(s,{type:'skill',id:g.id}).ok).toBe(true);expect(g.autoSkill).toBe(false);expect(g.skillTime).toBe(0);});
 it('clone costs fragments, has independent full-health state, cannot move and vanishes on extraction',()=>{const s=battle(),h=s.units[0];h.hp=20;s.fragments=50;expect(command(s,{type:'clone',id:h.id,to:{x:3,y:4}}).ok).toBe(true);const c=s.units.find(u=>u.cloneOf===h.id)!;expect(s.fragments).toBe(30);expect(c.hp).toBe(c.maxHp);expect(c.weapons).not.toBe(h.weapons);c.weapons[0].durability=5;expect(h.weapons[0].durability).not.toBe(5);expect(command(s,{type:'move',id:c.id,to:{x:4,y:4}}).ok).toBe(false);expect(command(s,{type:'clone',id:c.id,to:{x:4,y:4}}).ok).toBe(false);expect(command(s,{type:'extract',id:c.id,via:'shadow'}).ok).toBe(true);expect(s.units.some(u=>u.id===c.id)).toBe(false);});
 it('clone death skips downed and hunter respawn, and clones never carry between nodes',()=>{const s=battle(),h=s.units[0];s.fragments=100;command(s,{type:'clone',id:h.id,to:{x:3,y:4}});const c=s.units.find(u=>u.cloneOf===h.id)!;c.hp=1;c.statuses=[{kind:'poison',remaining:2,power:1000}];step(s,.1);expect(c.life).toBe('dead');command(s,{type:'clone',id:h.id,to:{x:4,y:4}});s.crystalHp=0;step(s,.1);expect(s.units.some(u=>u.cloneOf)).toBe(false);});
 it('directional dash moves one cardinal cell and invalid directions do not spend cards',()=>{const s=battle(),h=s.units[0],card=s.cards.find(c=>c.kind==='dash')!;expect(command(s,{type:'card',cardId:card.id,to:h.pos,targetId:h.id,direction:'north'}).ok).toBe(true);expect(h.pos).toEqual({x:2,y:3});});
});
