import {test,expect} from 'vitest';
import {createGame,command,step,visible,resolveHit} from '../src/core/engine';
import {positionKnown} from '../src/core/visibility';
import {validateExploration,explorationDefinition} from '../src/core/exploration-content';
function scene(){const s=createGame();s.economy.account.vitality=80;command(s,{type:'carry',gold:0,vitality:80});s.completed.push(1);s.phase='nodes';command(s,{type:'enter',node:4});return s;}
test('new exploration entry preserves an unfinished hunter respawn rather than creating an active zero-HP hunter',()=>{const s=scene(),h=s.units[0];command(s,{type:'exitExploration'});h.life='respawning';h.hp=0;h.respawnTimer=9;command(s,{type:'enter',node:4});expect(h.life).toBe('respawning');expect(h.respawnTimer).toBe(9);step(s,9.1);expect(h.life).toBe('active');expect(h.hp).toBeGreaterThan(0);});
test('patrol content rejects duplicate stable enemy identities and malformed entry',()=>{const d=explorationDefinition();d.enemies[1].id=d.enemies[0].id;expect(()=>validateExploration(d)).toThrow();const bad=explorationDefinition();bad.entry={x:-1,y:0};expect(()=>validateExploration(bad)).toThrow();});
test('lamp independently reveals enemies; after expiry memory remains but enemy targeting does not',()=>{const s=scene(),e=s.units.find(u=>u.team==='enemy')!;s.lights.push({pos:e.pos,radius:4,remaining:.2});step(s,.1);expect(visible(s,e)).toBe(true);step(s,.2);expect(visible(s,e)).toBe(false);expect(positionKnown(s,e.pos)).toBe(true);});
test('repeated enemy kills on a new visit restore health but cannot pay the same reward again',()=>{const s=scene(),h=s.units[0],e=s.units.find(u=>u.team==='enemy')!;resolveHit(s,e,{...h.weapons[0],damageKind:'arcane'},10000,h);const total=s.fragments;s.exploration!.lastActivity=-10;s.context='explorationIdle';command(s,{type:'exitExploration'});command(s,{type:'enter',node:4});const fresh=s.units.find(u=>u.team==='enemy')!;expect(fresh.hp).toBe(fresh.maxHp);resolveHit(s,fresh,{...h.weapons[0],damageKind:'arcane'},10000,h);expect(s.fragments).toBe(total);});
test('partially rejected group commands leave crossing bodies untouched and process another eligible body',()=>{const s=scene(),g=s.units.find(u=>u.id==='ines')!,r=s.units.find(u=>u.id==='ranger')!;for(const u of [g,r]){u.life='active';u.ready=0;u.pos={x:u===g?4:5,y:16};}g.crossing={from:g.pos,to:{x:4,y:17},elapsed:.2,duration:.75} as any;const before=structuredClone(g.crossing);expect(command(s,{type:'party',kind:'recall'}).ok).toBe(true);expect(g.crossing).toEqual(before);expect(g.life).toBe('active');expect(r.life).toBe('withdrawn');});
test('pure prayer healing and aiming do not enter party combat',()=>{const s=scene(),f=s.units.find(u=>u.id==='fiorre')!;expect(command(s,{type:'weapon',id:f.id,index:0}).ok).toBe(true);step(s,3);f.life='active';f.ready=0;f.pos={x:3,y:16};f.skillCd=0;expect(command(s,{type:'skill',id:f.id}).ok).toBe(true);step(s,1);expect(s.context).toBe('explorationIdle');});

test('overflow enemies can attack a body even when its engagement capacity is full',()=>{const s=scene(),h=s.units[0],es=s.units.filter(u=>u.team==='enemy').slice(0,2);h.pos={x:10,y:15};h.weapons.forEach(w=>w.damage=0);for(const [i,e] of es.entries()){e.pos={x:11,y:15+i*.4};e.weapons.forEach(w=>w.damage=30);e.enemySense!.home={...e.pos};}const hp=h.hp;step(s,1.6);expect(es.filter(e=>e.engagement?.targetId===h.id)).toHaveLength(1);expect(es.every(e=>e.pursuitTargetId===h.id)).toBe(true);expect(s.combatEvents!.some(e=>e.sourceId===es[1].id&&e.targetId===h.id)).toBe(true);expect(h.hp).toBeLessThan(hp);});
test('real source activity and calm threshold use simulation time independently of step partition',()=>{for(const dt of [.02,.1]){const s=scene(),h=s.units[0],e=s.units.find(u=>u.team==='enemy')!;resolveHit(s,e,h.weapons[0],1,h);const price=s.economy.draws,cd=h.skillCd;step(s,0);expect(h.skillCd).toBe(cd);for(let t=0;t<2.8;t+=dt)step(s,dt);expect(s.context).toBe('explorationBattle');for(let t=0;t<.4;t+=dt)step(s,dt);expect(s.context).toBe('explorationIdle');expect(s.economy.draws).toBe(price);}});
test('a returned enemy preserves damage rather than healing to max at its home',()=>{const s=scene(),h=s.units[0],e=s.units.find(u=>u.team==='enemy')!;h.pos={x:10,y:15};h.weapons.forEach(w=>w.damage=0);e.hp=22;step(s,.1);h.pos={x:2,y:16};step(s,10);expect(e.enemyMotion).toBe('route');expect(e.hp).toBe(22);});
test('full regroup area fails without deleting or overlapping the body, and hunter incapacity cancels a submitted channel',()=>{const s=scene(),g=s.units.find(u=>u.id==='ines')!;g.life='active';g.ready=0;g.pos={x:5,y:16};const original={...g.pos};s.tiles=s.tiles.map(t=>t.x<5?{...t,obstacle:true}:t);command(s,{type:'party',kind:'regroup'});expect(g.pos).toEqual(original);expect(g.life).toBe('active');s.tiles=explorationDefinition().tiles;s.context='explorationBattle';s.exploration!.lastActivity=0;command(s,{type:'party',kind:'regroup'});expect(g.partyTask).toBeDefined();s.units[0].life='respawning';step(s,.1);expect(g.partyTask).toBeUndefined();expect(g.life).toBe('active');});
