import {attackCommit} from '../src/core/exploration';
import {test,expect} from 'vitest';
import {createGame,command,step,resolveHit} from '../src/core/engine';
function scene(){const s=createGame();command(s,{type:'carry',gold:0,vitality:0});s.completed.push(1);s.phase='nodes';command(s,{type:'enter',node:4});return s;}
test('body poison ticks continue combat at their real source; removed copy poison never does',()=>{for(const clone of [false,true]){const s=scene(),h=s.units[0],e=s.units.find(u=>u.team==='enemy')!;const source={...structuredClone(h),id:clone?'gone-copy':h.id,cloneOf:clone?h.id:undefined};if(!clone)attackCommit(s,h);e.statuses=[{kind:'poison',power:1,remaining:5,origin:source} as any];step(s,.1);expect(s.context).toBe(clone?'explorationIdle':'explorationBattle');}});
test('already released delayed body hits still count while copy hits and environmental poison do not',()=>{const s=scene(),h=s.units[0],e=s.units.find(u=>u.team==='enemy')!;e.statuses=[{kind:'poison',power:1,remaining:1}];step(s,.1);expect(s.context).toBe('explorationIdle');attackCommit(s,h);const emitted=structuredClone(h);h.life='withdrawn';resolveHit(s,e,emitted.weapons[0],5,emitted,{derived:true});expect(s.context).toBe('explorationBattle');});
test('successful manual toggle replaces its group channel and does not cancel another body',()=>{const s=scene(),r=s.units.find(u=>u.id==='ranger')!,f=s.units.find(u=>u.id==='fiorre')!;for(const u of [r,f]){u.life='active';u.ready=0;u.pos={x:3+(u===f?1:0),y:16};}s.context='explorationBattle';s.exploration!.lastActivity=0;command(s,{type:'party',kind:'regroup'});expect(r.partyTask).toBeDefined();expect(command(s,{type:'skill',id:r.id}).ok).toBe(true);expect(r.partyTask).toBeUndefined();expect(f.partyTask).toBeDefined();});

test('accepted weapon change replaces only that body group action',()=>{const s=scene(),r=s.units.find(u=>u.id==='ranger')!,f=s.units.find(u=>u.id==='fiorre')!;for(const u of [r,f]){u.life='active';u.ready=0;u.pos={x:u===r?3:4,y:16};}s.context='explorationBattle';s.exploration!.lastActivity=0;command(s,{type:'party',kind:'regroup'});expect(command(s,{type:'weapon',id:r.id,index:1}).ok).toBe(true);expect(r.partyTask).toBeUndefined();expect(f.partyTask).toBeDefined();});
