import {legacyGame as createGame} from './legacy-fixtures';
import {describe,it,expect} from 'vitest';

import {initializeSkills,initializeProfile,currentSkill,configureSkill} from '../src/core/progression';
import {requestWeapon,tickLoadout,cancelLoadout} from '../src/core/loadout';
const setup=()=>{const s=createGame();initializeProfile(s);const u=s.units.find(a=>a.id==='fiorre')!;initializeSkills(u,s.profile);u.life='active';s.phase='battle';return {s,u};};
describe('weapon preparation and independent skill caches',()=>{
 it('commits profession only after the preparation time and starts the new skill empty',()=>{const {s,u}=setup();u.skillCd=7;expect(requestWeapon(s,u,2).ok).toBe(true);expect(u.weaponIndex).toBe(0);expect(u.skillId).toBe('prayer');expect(tickLoadout(s,u,.4)).toBe(false);expect(tickLoadout(s,u,.4)).toBe(true);expect(u.weaponIndex).toBe(2);expect(u.skillId).toBe('bell');expect(u.role).toBe('fiorre');expect(u.skillCd).toBe(20);expect(currentSkill(u).cd).toBe(20);expect(requestWeapon(s,u,0).ok).toBe(true);tickLoadout(s,u,.8);expect(u.skillCd).toBe(7);});
 it('beginning interrupts timed casting and cancellation never restores the cast',()=>{const {s,u}=setup();u.skillCd=0;u.skillTime=2;expect(requestWeapon(s,u,2).ok).toBe(true);expect(u.skillTime).toBe(0);expect(u.skillCd).toBe(18);cancelLoadout(u);expect(u.weaponIndex).toBe(0);expect(u.skillTime).toBe(0);expect(u.skillCd).toBe(18);});
 it('invalid requests neither cancel a cast nor change weapon state',()=>{const {s,u}=setup();u.skillTime=2;u.crossing={from:{x:0,y:0},to:{x:1,y:0},elapsed:.2,switched:false};expect(requestWeapon(s,u,2).ok).toBe(false);expect(u.skillTime).toBe(2);expect(u.loadout).toBeUndefined();u.crossing=undefined;expect(requestWeapon(s,u,99).ok).toBe(false);expect(u.skillTime).toBe(2);u.cloneOf='original';expect(requestWeapon(s,u,2).ok).toBe(false);});
 it('same profession weapon switch preserves chosen skill and cooldown',()=>{const {s,u}=setup();s.phase='briefing';configureSkill(s,u,'ward');s.phase='battle';u.skillCd=4;expect(requestWeapon(s,u,1).ok).toBe(true);tickLoadout(s,u,.8);expect(u.skillId).toBe('ward');expect(u.skillCd).toBe(4);expect(u.weapons[1].shadow).toBe(true);});
 it('a copied unit has independent build data and no original preparation action',()=>{const {s,u}=setup();requestWeapon(s,u,2);const copy=structuredClone(u);copy.id='copy';copy.cloneOf=u.id;initializeSkills(copy);expect(copy.loadout).toBeUndefined();expect(copy.weaponIndex).toBe(0);currentSkill(copy).stage=2;expect(currentSkill(u).stage).toBe(0);});
 it('configures a healthy reserve immediately before battle and freezes shadow combat permissions',()=>{const {s,u}=setup();s.phase='briefing';u.life='reserve';expect(requestWeapon(s,u,2).ok).toBe(true);expect(u.weaponIndex).toBe(2);expect(u.loadout).toBeUndefined();expect(u.weapons[2].attackPeriod).toBe(1.4);s.phase='battle';u.life='withdrawn';expect(requestWeapon(s,u,0).ok).toBe(false);expect(u.weaponIndex).toBe(2);});
 it('refuses a second weapon request without replacing or restarting current preparation',()=>{const {s,u}=setup();expect(requestWeapon(s,u,2).ok).toBe(true);tickLoadout(s,u,.3);expect(requestWeapon(s,u,1).ok).toBe(false);expect(u.loadout!.targetIndex).toBe(2);expect(u.loadout!.elapsed).toBe(.3);expect(tickLoadout(s,u,.5)).toBe(true);expect(u.weaponIndex).toBe(2);});
});
