import {legacyEnemy,hazard} from './legacy-enemy-fixture';
// AR06: retain these historical weapon/skill contracts on the Legacy branch.
vi.mock('../src/core/al-state',async importActual=>({...await importActual<object>(),isAlV2:()=>false}));
// AR05: this frozen historical suite verifies the retained pre-Blue branch.

vi.mock('../src/core/hunter-state',async importActual=>({...await importActual<object>(),isHunterV2:()=>false}));
import {vi,expect,test} from 'vitest';
import {createGame,command,step} from '../src/core/engine';
import {playerOwns} from '../src/core/autonomy';
export function fixture(companion='ines'){const s=createGame();command(s,{type:'selectJourney',journey:'exploration'});command(s,{type:'selectExplorationCompanion',id:companion});command(s,{type:'carry',gold:0,vitality:0});s.units=s.units.filter(u=>u.team==='ally');s.tiles.forEach(t=>{t.obstacle=false;t.layer=0;});s.units.forEach(u=>{u.ready=0;u.stagger=0;u.autoSkill=false;u.path=[];u.destination=null;});const h=s.units.find(u=>u.id==='hunter')!,p=s.units.find(u=>u.id===companion)!;h.pos={x:5,y:5};p.pos={x:7,y:5};h.drawPos={...h.pos};p.drawPos={...p.pos};s.exploration!.memory.seen=s.tiles.map(t=>`${t.x},${t.y}`);return {s,h,p};}
// New orders originate from Direct. Historical command-source orders retain their safety policy.
export function issue(s:any,u:any,to:any,source='command'){const previous=s.controlledBodyId;command(s,{type:'controlBody',id:u.id});expect(command(s,{type:'beginExplorationAim',id:u.id,kind:'path',source:'direct'}).ok).toBe(true);expect(command(s,{type:'confirmPathAim',to}).ok).toBe(true);if(source==='command'){s.explorationControl.moveOrders[u.id].source='command';command(s,{type:'controlBody',id:previous});}}
export const orders=(s:any)=>s.explorationControl?.moveOrders||{};
test('confirm creates actor-owned destination and source without changing Direct/focus',()=>{const {s,h,p}=fixture();issue(s,p,{x:10,y:5});expect(orders(s)[p.id]).toMatchObject({actorId:p.id,destination:{x:10,y:5},source:'command',issuedAt:0,state:'moving'});expect(p.path.at(-1)).toEqual({x:10,y:5});expect(s.controlledBodyId).toBe(h.id);expect(s.explorationControl?.commandFocusId).toBeNull();expect(s.explorationControl?.aim).toBeUndefined();});
test('direct and command orders coexist and replacement changes only same actor',()=>{const {s,h,p}=fixture();issue(s,h,{x:5,y:8},'direct');issue(s,p,{x:10,y:5});const old=orders(s)[p.id];issue(s,p,{x:9,y:7});expect(orders(s)[h.id].destination).toEqual({x:5,y:8});expect(orders(s)[h.id].source).toBe('direct');expect(orders(s)[p.id].destination).toEqual({x:9,y:7});expect(orders(s)[p.id].id).not.toBe(old.id);});
test('empty temporary route remains player owned after grace and is replanned',()=>{const {s,p}=fixture();issue(s,p,{x:10,y:5});p.path=[];p.destination=null;s.time=20;p.ai!.command=undefined;p.ai!.commandUntil=0;expect(playerOwns(s,p)).toBe(true);step(s,.02);expect(orders(s)[p.id]).toBeDefined();expect(p.path.at(-1)).toEqual({x:10,y:5});});
test('Aim suspends old order; cancellation resumes from changed current position',()=>{const {s,p}=fixture();issue(s,p,{x:10,y:5});const id=orders(s)[p.id]?.id;command(s,{type:'controlBody',id:p.id});expect(command(s,{type:'beginExplorationAim',id:p.id,kind:'path',source:'direct'}).ok).toBe(true);expect(orders(s)[p.id]).toMatchObject({id,state:'suspended',suspendReason:'aim'});expect(p.path).toEqual([]);p.pos={x:8,y:6};command(s,{type:'cancelCommandAim'});step(s,.02);expect(orders(s)[p.id]).toMatchObject({id,state:'moving',destination:{x:10,y:5}});expect(p.path.at(-1)).toEqual({x:10,y:5});});
import * as control from '../src/core/exploration-control';
import {advanceCompanionCombat} from '../src/core/companion-combat';
import {followParty} from '../src/core/party';
import {advanceMoveOrders,queryMoveOrderRoute,completeMoveOrder} from '../src/core/move-order';
import {startForcedMotion} from '../src/core/impact';
import {evadeAI} from '../src/core/evasion';
import {skillState} from '../src/core/progression';
import {resolveHit} from '../src/core/engine';
function combat(companion='ines'){const f=fixture(companion),{s,h,p}=f;const initial=createGame();command(initial,{type:'selectJourney',journey:'exploration'});command(initial,{type:'selectExplorationCompanion',id:'ines'});command(initial,{type:'carry',gold:0,vitality:0});const e=legacyEnemy(s);e.id='heavy-fixture';e.pos={x:8,y:5};e.drawPos={...e.pos};e.ready=0;e.hp=e.maxHp=10000;e.attackTimer=100;e.enemyMotion='engaged';e.pursuitTargetId=h.id;e.enemySense!.home={...e.pos};e.encounterRoom=1;s.units.push(e);s.context='explorationBattle';s.exploration!.definition.encounters=[{room:1,name:'fixture',tier:'strong',enemyIds:[e.id],center:{x:8,y:5},tacticalRadius:6.5}];h.attackTimer=100;p.attackTimer=0;p.weapons.forEach(w=>w.weight=0);p.facing='east';return {...f,e};}
const run=(s:any,time:number)=>{for(let t=0;t<time;t+=.02)step(s,.02);};
test('Order blocks tactical and follow but permits local auto; Reservation blocks both',()=>{const {s,p}=fixture();issue(s,p,{x:10,y:5});expect((control as any).tacticalAutonomyAllowed?.(s,p)).toBe(false);expect((control as any).localAutoCombatAllowed?.(s,p)).toBe(true);command(s,{type:'controlBody',id:p.id});command(s,{type:'beginExplorationAim',id:p.id,kind:'path',source:'direct'});expect((control as any).localAutoCombatAllowed?.(s,p)).toBe(false);});
test('Follow and tactical cannot seize an empty route after grace',()=>{const {s,p}=fixture();issue(s,p,{x:10,y:5});p.path=[];p.destination=null;s.time=20;p.ai!.commandUntil=0;followParty(s,.2);expect(p.path).toEqual([]);s.context='explorationBattle';advanceCompanionCombat(s);expect(p.path).toEqual([]);expect(orders(s)[p.id].destination).toEqual({x:10,y:5});});
test('active local Basic hits once then resumes before full attack cooldown',()=>{const {s,p,e}=combat();issue(s,p,{x:10,y:7});step(s,.02);expect(p.attackPending?.targetId).toBe(e.id);expect(orders(s)[p.id]).toMatchObject({state:'suspended',suspendReason:'basic'});const hp=e.hp;run(s,.28);expect(e.hp).toBeLessThan(hp);expect(p.attackPending).toBeUndefined();expect(p.attackTimer).toBeGreaterThan(0);expect(p.path.at(-1)).toEqual({x:10,y:7});const pos={...p.pos};step(s,.02);expect(p.pos).not.toEqual(pos);expect(orders(s)[p.id].destination).toEqual({x:10,y:7});});
test('Basic target leaves range; no chase or order destination rewrite',()=>{const {s,p,e}=combat();issue(s,p,{x:10,y:7});step(s,.02);e.pos={x:12,y:7};const hp=e.hp;run(s,.28);expect(e.hp).toBe(hp);expect(p.path.at(-1)).toEqual({x:10,y:7});expect(orders(s)[p.id].destination).toEqual({x:10,y:7});});
test('unengaged nearby enemy cannot interrupt an order with Basic',()=>{const {s,p,e}=combat();e.pursuitTargetId=undefined;e.enemyMotion='route';issue(s,p,{x:7,y:8},'direct');step(s,.02);expect(p.attackPending).toBeUndefined();expect(p.path.length).toBeGreaterThan(0);});
test('foreground automatic Rain suspends and resumes without altering background Snipe/CD',()=>{const {s,h,p,e}=combat('ranger');e.pos={x:9,y:5};e.defense=undefined;p.skillSlots=['rain','snipe',null];p.skillId='rain';const rain=skillState(p,'rain'),snipe=skillState(p,'snipe');rain.cd=0;snipe.enabled=true;issue(s,p,{x:7,y:8});step(s,.02);expect(rain.run).toBeDefined();expect(orders(s)[p.id]).toMatchObject({state:'suspended',suspendReason:'skill'});expect(snipe.enabled).toBe(true);p.attackTimer=100;const hp=e.hp;run(s,rain.run!.spec.duration+.02);expect(e.hp).toBeLessThan(hp);expect(rain.run).toBeUndefined();expect(orders(s)[p.id]?.destination).toEqual({x:7,y:8});expect(p.path.at(-1)).toEqual({x:7,y:8});expect(snipe.enabled).toBe(true);});
test('AI evasion survives and replans; successful manual evasion cancels',()=>{const {s,p}=fixture();issue(s,p,{x:10,y:5});expect(evadeAI(s,p,{x:0,y:1}).ok).toBe(true);advanceMoveOrders(s);expect(orders(s)[p.id].suspendReason).toBe('mobility');run(s,.3);expect(p.evasion?.action).toBeUndefined();expect(p.path.at(-1)).toEqual({x:10,y:5});command(s,{type:'controlBody',id:p.id});expect(command(s,{type:'evade',id:p.id,direction:{x:0,y:1}}).ok).toBe(true);expect(orders(s)[p.id]).toBeUndefined();});
test('Heavy impact and wall pin retain destination and resume from live position',()=>{const {s,p,e}=combat();p.attackTimer=100;issue(s,p,{x:10,y:7});const dest={...orders(s)[p.id].destination};p.posture=0;resolveHit(s,p,e.weapons[0],1,e,{kind:'ability',impact:{distance:1,direction:{x:0,y:1},wallPin:false},postureDamage:999});expect(p.forcedMotion).toBeDefined();step(s,.02);expect(orders(s)[p.id].destination).toEqual(dest);expect(orders(s)[p.id].suspendReason).toBe('forced');run(s,1.8);expect(p.pos.y).toBeGreaterThan(5);expect(p.path.at(-1)).toEqual(dest);const wallX=Math.floor(p.pos.x+.5)-1;s.tiles.find(t=>t.x===wallX&&t.y===Math.floor(p.pos.y+.5))!.obstacle=true;startForcedMotion(s,p,{distance:6,direction:{x:-1,y:0},wallPin:true});run(s,.3);expect(s.stats.wallPin).toBeGreaterThan(0);expect(orders(s)[p.id].suspendReason).toBe('stagger');run(s,1.8);expect(orders(s)[p.id]?.destination||p.pos).toEqual(dest);});
test('atomic crossing keeps its own route and cannot prematurely complete',()=>{const {s,p}=fixture();issue(s,p,{x:9,y:5});s.tiles.find(t=>t.x===8&&t.y===5)!.layer=1;s.tiles.find(t=>t.x===9&&t.y===5)!.layer=1;p.path=[];run(s,.35);expect(p.crossing).toBeDefined();const c=p.crossing,path=p.path;advanceMoveOrders(s);expect(p.crossing).toBe(c);expect(p.path).toBe(path);expect(completeMoveOrder(s,p)).toBe(false);for(let i=0;i<200&&orders(s)[p.id];i++)step(s,.02);expect(orders(s)[p.id]).toBeUndefined();expect(p.pos).toEqual({x:9,y:5});});
test('temporary occupied destination retries no sooner than .25s and resumes',()=>{const {s,h,p}=fixture();issue(s,p,{x:10,y:5});const clone={...structuredClone(h),id:'blocker',cloneOf:h.id,pos:{x:10,y:5},destination:null};s.units.push(clone);p.path=[];advanceMoveOrders(s);expect(orders(s)[p.id].state).toBe('blocked');const last=orders(s)[p.id].lastRepathAt;clone.pos={x:13,y:5};s.time+=.2;advanceMoveOrders(s);expect(orders(s)[p.id].state).toBe('blocked');expect(orders(s)[p.id].lastRepathAt).toBe(last);s.time+=.05;advanceMoveOrders(s);expect(orders(s)[p.id].state).toBe('moving');expect(p.path.at(-1)).toEqual({x:10,y:5});});
test('destination becomes obstacle cancels with reason even while route is present',()=>{const {s,p}=fixture();issue(s,p,{x:10,y:5});s.tiles.find(t=>t.x===10&&t.y===5)!.obstacle=true;advanceMoveOrders(s);expect(orders(s)[p.id]).toBeUndefined();expect(s.log[0]).toContain('destination-invalid');});
test('source safety survives later replan, Direct may deliberately enter dormant encounter',()=>{const {s,h,p}=fixture();issue(s,p,{x:10,y:5});const e={...structuredClone(p),id:'dormant',team:'enemy' as const,pos:{x:11,y:5},encounterRoom:9};s.units.push(e);p.path=[];advanceMoveOrders(s);expect(orders(s)[p.id]).toBeUndefined();expect(s.log[0]).toContain('inactive-encounter');issue(s,h,{x:10,y:5},'direct');h.path=[];advanceMoveOrders(s);expect(orders(s)[h.id]?.destination).toEqual({x:10,y:5});});
test('Focus/clear/identity and failed actions preserve order; successful direct cancels permanently',()=>{const {s,p}=fixture();issue(s,p,{x:10,y:5});const id=orders(s)[p.id].id;for(const focus of [null,'hunter','ines'])command(s,{type:'commandFocus',id:focus});command(s,{type:'controlBody',id:p.id});expect(s.controlledBodyId).toBe(p.id);expect(orders(s)[p.id].id).toBe(id);p.skillSlots=['prayer',null,null] as any;skillState(p,'prayer').cd=10;expect(command(s,{type:'skill',id:p.id,slot:2}).ok).toBe(false);p.evasion!.charges=0;expect(command(s,{type:'evade',id:p.id,direction:{x:1,y:0}}).ok).toBe(false);expect(orders(s)[p.id].id).toBe(id);expect(command(s,{type:'direct',id:p.id,direction:{x:0,y:1}}).ok).toBe(true);expect(orders(s)[p.id]).toBeUndefined();command(s,{type:'direct',id:p.id,direction:null});run(s,.2);expect(p.destination).not.toEqual({x:10,y:5});});
test.each(['skill','blink','weapon','switchWeapon','extract','collect'] as const)('only a successful %s commit cancels its actors order',kind=>{const {s,h}=fixture();issue(s,h,{x:5,y:8},'direct');let cmd:any={type:kind,id:h.id};if(kind==='skill'){h.skillSlots=['hunt',null,null];h.skillId='hunt';skillState(h,'hunt').cd=0;cmd.slot=0;}if(kind==='blink')cmd.direction={x:1,y:0};if(kind==='weapon')cmd.index=1;if(kind==='switchWeapon')cmd.index=1;if(kind==='extract')cmd.via='hunter';if(kind==='collect')cmd={type:'collect',id:h.id};const result=command(s,cmd);if(['extract','collect'].includes(kind)){expect(result.ok).toBe(false);expect(orders(s)[h.id]).toBeDefined();}else{expect(result.ok).toBe(true);expect(orders(s)[h.id]).toBeUndefined();}});
test('failed blocked Blink and cooldown skill preserve; successful companion recall cancels only accepted actor',()=>{const {s,h,p}=fixture();issue(s,h,{x:5,y:8},'direct');issue(s,p,{x:10,y:5});h.blink!.charges=0;expect(command(s,{type:'blink',id:h.id,direction:{x:1,y:0}}).ok).toBe(false);h.skillSlots=['prayer',null,null];skillState(h,'prayer').cd=10;expect(command(s,{type:'skill',id:h.id}).ok).toBe(false);expect(orders(s)[h.id]).toBeDefined();expect(command(s,{type:'party',kind:'regroup'}).ok).toBe(true);expect(orders(s)[p.id]).toBeUndefined();expect(orders(s)[h.id]).toBeDefined();});
test('new successful toggle cancels order and its unmodified old route',()=>{const {s,p}=fixture('fiorre');p.skillSlots=['dance','reap',null];skillState(p,'dance').enabled=true;issue(s,p,{x:10,y:5});command(s,{type:'controlBody',id:p.id});expect(command(s,{type:'skill',id:p.id,slot:0}).ok).toBe(true);expect(orders(s)[p.id]).toBeUndefined();expect(p.path).toEqual([]);});
test.each(['collect','extract'] as const)('accepted companion %s cancels only companion order',type=>{const {s,h,p}=fixture();issue(s,h,{x:5,y:8},'direct');issue(s,p,{x:10,y:5});p.pos={x:6,y:5};expect(command(s,{type,id:p.id} as any).ok).toBe(true);expect(orders(s)[p.id]).toBeUndefined();expect(orders(s)[h.id]).toBeDefined();});
test('successful rescue cancels Hunter order but preserves the rescue execution route',()=>{const {s,h,p}=fixture();issue(s,h,{x:5,y:8},'direct');p.life='downed';p.pos={x:10,y:5};expect(command(s,{type:'rescue',id:p.id}).ok).toBe(true);expect(orders(s)[h.id]).toBeUndefined();expect(h.rescueTarget).toBe(p.id);expect(h.path.length).toBeGreaterThan(0);});
test('atomic crossing rejects party recall without losing its order',()=>{const {s,p}=fixture();issue(s,p,{x:10,y:5});p.crossing={from:{...p.pos},to:{x:8,y:5},elapsed:0,switched:false};expect(command(s,{type:'party',kind:'recall'}).ok).toBe(false);expect(orders(s)[p.id]).toBeDefined();});
test('invalid life releases order on the next simulation tick',()=>{const {s,p}=fixture();issue(s,p,{x:10,y:5});p.life='downed';step(s,.02);expect(orders(s)[p.id]).toBeUndefined();});
test('blocked Blink with available charge preserves order',()=>{const {s,h}=fixture();issue(s,h,{x:5,y:8},'direct');h.pos={x:5.3,y:5};s.tiles.find(t=>t.x===6&&t.y===5)!.obstacle=true;expect(command(s,{type:'blink',id:h.id,direction:{x:1,y:0}}).ok).toBe(false);expect(orders(s)[h.id]).toBeDefined();});
test('failed idle regroup with no landing space preserves original order and route',()=>{const {s,h,p}=fixture();issue(s,p,{x:10,y:5});const path=p.path;h.pos={x:-20,y:-20};expect(command(s,{type:'party',kind:'regroup'}).ok).toBe(false);expect(orders(s)[p.id]).toBeDefined();expect(p.path).toBe(path);});
test('legal automatic Reap retains order through its outward and return route; Dance remains background',()=>{const {s,p,e}=combat('fiorre');e.defense=undefined;p.skillSlots=['dance','reap',null];const reap=skillState(p,'reap'),dance=skillState(p,'dance');reap.counter=5;dance.enabled=true;issue(s,p,{x:10,y:7});step(s,.02);expect(reap.run).toBeDefined();expect(orders(s)[p.id]).toMatchObject({state:'suspended',suspendReason:'skill'});p.attackTimer=100;for(let i=0;i<200&&reap.run;i++)step(s,.02);expect(reap.run).toBeUndefined();expect(dance.enabled).toBe(true);expect(orders(s)[p.id]?.destination).toEqual({x:10,y:7});expect(p.path.at(-1)).toEqual({x:10,y:7});});
test('Poison background remains enabled while an order moves',()=>{const {s,h}=fixture();h.skillSlots=['poison',null,null];h.weapons[0].profession='guard';const poison=skillState(h,'poison');poison.enabled=true;issue(s,h,{x:5,y:8},'direct');run(s,.2);expect(poison.enabled).toBe(true);expect(orders(s)[h.id]?.state).toBe('moving');});
