import {test,expect} from 'vitest';
import {createGame,command,step} from '../src/core/engine';
function scene(){const s=createGame();command(s,{type:'carry',gold:0,vitality:0});s.completed.push(1);s.phase='nodes';command(s,{type:'enter',node:4});const g=s.units.find(u=>u.id==='ines')!;g.life='active';g.ready=0;g.pos={x:5,y:16};g.drawPos={...g.pos};return {s,g};}
test('idle regroup only changes eligible body position, preserving health charge and warmup',()=>{const {s,g}=scene();g.hp=90;g.skillCd=4;const c={...structuredClone(g),id:'copy',cloneOf:g.id,pos:{x:6,y:17},drawPos:{x:6,y:17}};s.units.push(c);expect(command(s,{type:'party',kind:'regroup'} as any).ok).toBe(true);expect(g.pos.x).toBeLessThan(4.3);expect(g.hp).toBe(90);expect(g.skillCd).toBe(4);expect(g.ready).toBe(0);expect(c.pos).toEqual({x:6,y:17});expect(s.units[0].life).toBe('active');});
test('idle group recall excludes downed bodies and clones',()=>{const {s,g}=scene();const f=s.units.find(u=>u.id==='fiorre')!;f.life='downed';f.pos={x:4,y:17};f.hp=0;f.downTimer=45;expect(command(s,{type:'party',kind:'recall'} as any).ok).toBe(true);expect(g.life).toBe('withdrawn');expect(f.life).toBe('downed');expect(s.units[0].life).toBe('active');});
test('battle regroup is a distinct channel, repeat request preserves progress and explicit movement cancels only it',()=>{const {s,g}=scene();s.context='explorationBattle';s.exploration!.lastActivity=0;g.pos={x:3,y:16};expect(command(s,{type:'party',kind:'regroup'} as any).ok).toBe(true);step(s,.4);const elapsed=g.partyTask!.elapsed;expect(elapsed).toBeGreaterThan(0);command(s,{type:'party',kind:'regroup'} as any);expect(g.partyTask!.elapsed).toBeCloseTo(elapsed);expect(command(s,{type:'move',id:g.id,to:{x:4,y:16}}).ok).toBe(true);expect(g.partyTask).toBeUndefined();expect(g.life).toBe('active');});
test('idle follow never overwrites a committed player destination and copies stay put',()=>{const {s,g}=scene();expect(command(s,{type:'move',id:g.id,to:{x:5,y:17}}).ok).toBe(true);step(s,.2);expect(g.destination).toEqual({x:5,y:17});const h=s.units[0];command(s,{type:'direct',id:h.id,direction:{x:1,y:0}});const prior={...g.pos};step(s,.3);expect(g.destination).toEqual({x:5,y:17});expect(g.pos).not.toEqual(prior);});
test('idle detached body actually follows hunter and uses hunter pace rather than its own slower base',()=>{const {s,g}=scene();g.speed=.01;const x=g.pos.x;step(s,1);expect(g.pos.x).toBeLessThan(x-.5);expect(g.following).toBe(true);});

test('regroup channel forbids automatic rain releases and downing does not gain rescue protection',()=>{const {s,g}=scene(),r=s.units.find(u=>u.id==='ranger')!,e=s.units.find(u=>u.team==='enemy')!;r.life='active';r.ready=0;r.pos={x:3,y:16};expect(command(s,{type:'configureSkill',id:r.id,skillId:'rain'}).ok).toBe(true);r.skillCd=0;s.context='explorationBattle';s.exploration!.lastActivity=0;e.pos={x:6,y:16};command(s,{type:'party',kind:'regroup'});step(s,.1);expect(s.stats.rainArrows||0).toBe(0);g.hp=1;g.statuses=[{kind:'poison',power:1000,remaining:1}];step(s,.1);expect(g.life).toBe('downed');expect(g.partyTask).toBeUndefined();});
