import {expect,test} from 'vitest';
import {createGame,command} from '../src/core/engine';
import {beginExplorationAim,commandReserved,inputAuthority,ensureExplorationControl} from '../src/core/exploration-control';
import {queryPathAimPreview,PathAimPreviewCache} from '../src/core/path-aim';
function begin(){const s=createGame();command(s,{type:'selectJourney',journey:'exploration'});command(s,{type:'selectExplorationCompanion',id:'ines'});command(s,{type:'carry',gold:0,vitality:0});s.units=s.units.filter(u=>u.team==='ally');s.tiles.forEach(t=>{t.obstacle=false;t.layer=0;});s.units.forEach(u=>{u.ready=0;u.stagger=0;});const h=s.units.find(u=>u.id==='hunter')!,p=s.units.find(u=>u.id==='ines')!;h.pos={x:5,y:5};p.pos={x:7,y:5};return {s,h,p};}
test('Direct Aim owns input without Command Reservation; begin/cancel preserve focus clock',()=>{const {s,h,p}=begin();expect(beginExplorationAim(s,p.id,'path','direct').ok).toBe(false);expect(beginExplorationAim(s,h.id,'path','direct').ok).toBe(true);expect(inputAuthority(s)).toBe('aim');expect(commandReserved(s,h)).toBe(false);expect(s.explorationControl?.aim?.source).toBe('direct');const aim=s.explorationControl!.aim;expect(beginExplorationAim(s,h.id,'path','direct').ok).toBe(true);expect(s.explorationControl!.aim).toBe(aim);command(s,{type:'cancelExplorationAim'});expect(s.tacticalFocus).toBeUndefined();});
test.each(['command','direct'] as const)('%s preview is pure and confirmation moves only its owner once',source=>{const {s,h,p}=begin();if(source==='command')command(s,{type:'controlBody',id:p.id});const u=source==='command'?p:h;beginExplorationAim(s,u.id,'path','direct');const before=structuredClone(s),to={x:u.pos.x+1,y:u.pos.y};const q=queryPathAimPreview(s,u,to);expect(q.valid).toBe(true);expect(q.path.at(-1)).toEqual(to);expect(s).toEqual(before);expect(command(s,{type:'confirmPathAim',to}).ok).toBe(true);expect(s.stats.moves).toBe(1);expect(u.destination).toEqual(to);expect(s.controlledBodyId).toBe(u.id);expect(s.explorationControl?.commandFocusId).toBeNull();expect(s.explorationControl?.aim).toBeUndefined();expect(command(s,{type:'confirmPathAim',to}).ok).toBe(false);expect(s.stats.moves).toBe(1);});
test.each(['ready','attack','stun','crossing','forced','loadout'] as const)('busy %s allows preview but refuses confirmation without interrupting action',busy=>{const {s,h}=begin();beginExplorationAim(s,h.id,'path','direct');if(busy==='ready')h.ready=1;if(busy==='attack')h.attackPending={targetId:'enemy',remaining:1,facing:'east'};if(busy==='stun')h.statuses=[{kind:'stun',power:0,remaining:1}];if(busy==='crossing')h.crossing={from:h.pos,to:{x:6,y:5},elapsed:0,switched:false};if(busy==='forced')h.forcedMotion={remaining:1} as any;if(busy==='loadout')h.loadout={elapsed:0,duration:1,targetIndex:0};const to={x:6,y:5};expect(queryPathAimPreview(s,h,to).valid).toBe(true);expect(command(s,{type:'confirmPathAim',to}).reason).toContain('动作');expect(s.explorationControl?.aim).toBeDefined();expect(s.stats.moves).toBe(0);});
test('confirmation rechecks changed map; cache invalidates origin, obstacle and occupied destination',()=>{const {s,h}=begin();beginExplorationAim(s,h.id,'path','direct');const c=new PathAimPreviewCache(),to={x:6,y:5},first=c.query(s,h,to);expect(c.query(s,h,to)).toBe(first);const tile=s.tiles.find(t=>t.x===6&&t.y===5)!;tile.obstacle=true;expect(c.query(s,h,to).valid).toBe(false);expect(command(s,{type:'confirmPathAim',to}).ok).toBe(false);expect(s.explorationControl?.aim).toBeDefined();tile.obstacle=false;h.pos={x:5,y:6};expect(c.query(s,h,to)).not.toBe(first);s.units.push({...structuredClone(h),id:'copy',cloneOf:h.id,pos:to});expect(c.query(s,h,to).valid).toBe(false);expect(s.stats.moves).toBe(0);});
test('unknown, invalid coordinate, body clearance and unreachable destinations fail safely',()=>{const {s,h}=begin();for(const to of [{x:NaN,y:5},{x:900,y:900}])expect(queryPathAimPreview(s,h,to).valid).toBe(false);h.bodyRadius=.7;s.tiles.find(t=>t.x===6&&t.y===6)!.obstacle=true;expect(queryPathAimPreview(s,h,{x:6,y:5}).valid).toBe(false);h.bodyRadius=.18;s.tiles.forEach(t=>{if(t.x===6)t.obstacle=true;});s.exploration!.memory.seen.push('7,5');expect(queryPathAimPreview(s,h,{x:7,y:5}).valid).toBe(false);});
test('Command preview rejects inactive encounter path while Direct can explore it',()=>{const {s,h,p}=begin();const e={...structuredClone(p),id:'inactive',team:'enemy' as const,pos:{x:10,y:5},encounterRoom:8};s.units.push(e);command(s,{type:'controlBody',id:p.id});beginExplorationAim(s,p.id,'path','direct');expect(queryPathAimPreview(s,p,{x:8,y:5}).valid).toBe(true);command(s,{type:'controlBody',id:h.id});beginExplorationAim(s,h.id,'path','direct');expect(queryPathAimPreview(s,h,{x:8,y:5}).valid).toBe(true);});
test('invalid Direct owner and Legacy cannot retain Aim',()=>{const {s,h,p}=begin();beginExplorationAim(s,h.id,'path','direct');command(s,{type:'controlBody',id:p.id});ensureExplorationControl(s);expect(s.explorationControl?.aim).toBeUndefined();expect(beginExplorationAim(createGame(),'hunter','path','direct').ok).toBe(false);});
test('layer-aware navigation keeps legitimate crossing, rejects a mismatched landing footprint',()=>{const {s,h}=begin();s.tiles.find(t=>t.x===6&&t.y===5)!.layer=1;expect(queryPathAimPreview(s,h,{x:6,y:5}).valid).toBe(true);h.bodyRadius=.7;expect(queryPathAimPreview(s,h,{x:6,y:5}).valid).toBe(false);});
test('Command busy preview and confirm leave committed attack/clock untouched until a manual ready retry',()=>{const {s,p}=begin();command(s,{type:'controlBody',id:p.id});p.attackPending={targetId:'enemy',remaining:1,facing:'east'};beginExplorationAim(s,p.id,'path','direct');const to={x:8,y:5},pending=p.attackPending;expect(queryPathAimPreview(s,p,to).valid).toBe(true);expect(command(s,{type:'confirmPathAim',to}).ok).toBe(false);expect(p.attackPending).toBe(pending);expect(s.tacticalFocus).toBeUndefined();p.attackPending=undefined;expect(s.stats.moves).toBe(0);expect(command(s,{type:'confirmPathAim',to}).ok).toBe(true);expect(s.tacticalFocus).toBeUndefined();});
test('cache invalidates encounter activation without changing geometry or origins',()=>{const {s,p,h}=begin();s.context='explorationBattle';const e={...structuredClone(p),id:'inactive',team:'enemy' as const,pos:{x:10,y:5},encounterRoom:8};s.units.push(e);s.exploration!.definition.encounters=[{room:8,name:'fixture',center:e.pos,tacticalRadius:5,tier:'strong',enemyIds:[e.id]}];command(s,{type:'controlBody',id:p.id});beginExplorationAim(s,p.id,'path','direct');const c=new PathAimPreviewCache(),to={x:8,y:5};const first=c.query(s,p,to);expect(first.valid).toBe(true);e.pursuitTargetId=h.id;expect(c.query(s,p,to)).not.toBe(first);expect(c.query(s,p,to).valid).toBe(true);});
