import {test,expect,type Page} from '@playwright/test';
async function start(page:Page){await page.goto('/');await page.getByRole('button',{name:'进入战斗',exact:true}).click();await page.evaluate(()=>{const s=(window as any).prototype.state;s.waves=[];s.totalEnemies=999;s.units.forEach((u:any)=>u.ready=0);s.fragments=100;});}
test('number selection and held WASD preserve selected character, release and blur stop movement',async({page})=>{await start(page);await page.keyboard.press('1');await expect(page.locator('#time-mode')).toContainText('0.1');const x=await page.evaluate(()=>(window as any).prototype.state.units[0].pos.x);await page.keyboard.down('d');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units[0].pos.x)).toBeGreaterThan(x+.15);await page.keyboard.up('d');await expect(page.locator('#control-status')).toContainText('猎人');const after=await page.evaluate(()=>(window as any).prototype.state.units[0].pos.x);expect(after).toBeGreaterThan(x+.15);expect(await page.evaluate(()=>(window as any).prototype.interaction.selectedId)).toBe('hunter');await page.waitForTimeout(200);expect(await page.evaluate(()=>(window as any).prototype.state.units[0].pos.x)).toBeCloseTo(after,3);await page.keyboard.down('a');await page.evaluate(()=>window.dispatchEvent(new Event('blur')));const p=await page.evaluate(()=>(window as any).prototype.state.units[0].pos.x);await page.waitForTimeout(250);expect(await page.evaluate(()=>(window as any).prototype.state.units[0].pos.x)).toBeCloseTo(p,3);await page.keyboard.up('a');});
test('E keeps selection, stops held movement and does not silently resume; pause survives right cancel',async({page})=>{await start(page);await page.evaluate(()=>(window as any).prototype.state.units[0].skillCd=0);await page.keyboard.press('1');await page.keyboard.down('d');await page.waitForTimeout(100);await page.keyboard.press('e');expect(await page.evaluate(()=>(window as any).prototype.interaction.selectedId)).toBe('hunter');const p=await page.evaluate(()=>(window as any).prototype.state.units[0].pos.x);await page.waitForTimeout(200);expect(await page.evaluate(()=>(window as any).prototype.state.units[0].pos.x)).toBeCloseTo(p,3);expect(await page.evaluate(()=>(window as any).prototype.state.units[0].skillTime)).toBeGreaterThan(0);await page.keyboard.up('d');await page.keyboard.press('Space');await page.mouse.click(800,400,{button:'right'});await expect(page.locator('#time-mode')).toHaveText('战术暂停');});
test('mouse-only blink, separate copy control and healthy shadow return use actual buttons',async({page})=>{await start(page);await page.locator('[data-action="blink"]').click();const to=await page.evaluate(()=>(window as any).prototype.project({x:3,y:4}));await page.mouse.click(to.x,to.y);await expect(page.locator('#blink-stock')).toHaveText('9 / 10');await page.locator('[data-unit="ines"]').click();const p=await page.evaluate(()=>(window as any).prototype.project({x:4,y:4}));await page.mouse.click(p.x,p.y);await page.locator('[data-unit="ines"]').click();await expect(page.locator('#unit-detail')).toContainText('伊内丝');await page.locator('[data-extract="ines"]').click();await page.evaluate(async()=>{const {step}=await import('/src/core/engine.ts' as string);step((window as any).prototype.state,1.2);});await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ines').life)).toBe('withdrawn');await expect(page.locator('#life-ines')).toContainText('始动');await expect(page.locator('#crystal-retreat')).toBeHidden();});
test('Shift uses held direction and cannot blink hunter while another character selected',async({page})=>{await start(page);await page.keyboard.down('d');await page.keyboard.press('Shift');await page.keyboard.up('d');await expect(page.locator('#blink-stock')).toHaveText('9 / 10');await page.keyboard.press('2');await page.keyboard.press('Shift');await expect(page.locator('#blink-stock')).toHaveText('9 / 10');});
test('real map keyboard recall, redeployment and explicit casualty rescue form one loop',async({page})=>{
 await start(page);await page.keyboard.press('3');const p=await page.evaluate(()=>(window as any).prototype.project({x:3,y:4}));await page.mouse.click(p.x,p.y);
 await page.keyboard.press('3');await page.keyboard.press('q');
 await page.evaluate(async()=>{const {step}=await import('/src/core/engine.ts' as string);step((window as any).prototype.state,1.2);});
 await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units[2].life)).toBe('withdrawn');
 await page.evaluate(async()=>{const {step}=await import('/src/core/engine.ts' as string);step((window as any).prototype.state,10);});
 await page.locator('[data-unit="ines"]').click();await page.mouse.click(p.x,p.y);
 await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units[2].life)).toBe('active');
 await page.evaluate(()=>{const u=(window as any).prototype.state.units[2];u.life='downed';u.hp=0;u.downTimer=5;});
 await page.locator('[data-world-rescue="ines"]').click();
 await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units[2].life)).toBe('rescued');
 await expect(page.locator('#life-ines')).toContainText('已获救');
 await page.locator('[data-unit="ines"]').click();await page.mouse.click(p.x,p.y);
 expect(await page.evaluate(()=>(window as any).prototype.state.units[2].life)).toBe('rescued');
});
test('menu interruption requires release and press again; right cancel keeps submitted recall',async({page})=>{
 await start(page);await page.keyboard.down('d');await page.getByRole('button',{name:/行囊/}).click();await page.mouse.click(800,400,{button:'right'});const p=await page.evaluate(()=>(window as any).prototype.state.units[0].pos.x);await page.waitForTimeout(250);expect(await page.evaluate(()=>(window as any).prototype.state.units[0].pos.x)).toBeCloseTo(p,3);await page.keyboard.up('d');await page.keyboard.down('d');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units[0].pos.x)).toBeGreaterThan(p+.1);await page.keyboard.up('d');
 await page.keyboard.press('3');const q=await page.evaluate(()=>(window as any).prototype.project({x:5,y:4}));await page.mouse.click(q.x,q.y);await page.keyboard.press('3');await page.keyboard.press('q');await page.mouse.click(800,400,{button:'right'});expect(await page.evaluate(()=>(window as any).prototype.state.units[2].recall)).toBeTruthy();
});
test('compact reduced-motion controls remain reachable and render ten reserve marks',async({page})=>{
 await page.setViewportSize({width:1000,height:720});await page.emulateMedia({reducedMotion:'reduce'});await start(page);await page.keyboard.press('1');await expect(page.locator('#blink-ticks i')).toHaveCount(10);await expect(page.locator('#recall-range')).toBeVisible();const r=await page.locator('#personal-controls').boundingBox();expect(r!.x).toBeGreaterThanOrEqual(0);expect(r!.x+r!.width).toBeLessThanOrEqual(1000);await page.locator('[data-action="collect"]').click();await expect(page.locator('#control-status')).toContainText('收纳瞄准');await page.mouse.click(700,300,{button:'right'});await expect(page.locator('#control-status')).toContainText('默认控制');
});
