import {captureRecallProtection} from '../src/core/personal';
import {simulationDelta} from '../src/interaction';
import {describe,it,expect} from 'vitest';
import {arena,foe} from './rework-fixtures';
import {createGame,command,resolveHit,step} from '../src/core/engine';
import {currentSkill} from '../src/core/progression';
import {resetPressure} from '../src/core/pressure';
import {createClone} from '../src/core/clones';
import type {Unit,Weapon} from '../src/core/types';
const w:Weapon={name:'架势测试',damage:10,range:1,width:0,remote:false,durability:60,maxDurability:60,shadow:false,postureDamage:45};
function setup(index=0){const s=arena(),u=s.units[index];u.life='active';u.pos={x:5,y:5};u.drawPos={...u.pos};resetPressure(u);const e=foe(s,6,5);resetPressure(e);return {s,u,e};}
function breakTwice(s:ReturnType<typeof arena>,u:Unit,e:Unit){resolveHit(s,u,{...w,postureDamage:1000},0,e);resolveHit(s,u,w,0,e);}
describe('unified pressure hit settlement',()=>{
 it('spawns roster/enemies with posture independently from health',()=>{const s=createGame();expect(s.units.map(u=>u.maxPosture)).toEqual([90,110,140,70]);command(s,{type:'carry',gold:0,vitality:0});command(s,{type:'start'});step(s,18.1);expect(s.units.find(u=>u.team==='enemy')?.maxPosture).toBe(90);});
 it('shield blocks HP only and defense does not erase configured posture damage',()=>{const {s,u,e}=setup();u.statuses.push({kind:'shield',power:100,remaining:20});resolveHit(s,u,w,30,e);expect(u.hp).toBe(360);expect(u.grayHp).toBe(0);expect(u.posture).toBe(45);resolveHit(s,u,w,30,e);expect(u.posture).toBe(0);expect(u.stagger).toBe(0);resolveHit(s,u,w,30,e);expect(u.stagger).toBe(.6);});
 it('dodge and duplicated hit identity cannot drain posture twice',()=>{const {s,u,e}=setup();u.dodge=1;resolveHit(s,u,w,30,e,{eventId:10});expect(u.posture).toBe(90);u.dodge=0;resolveHit(s,u,w,30,e,{eventId:10});expect(u.posture).toBe(90);resolveHit(s,u,w,30,e,{eventId:11});resolveHit(s,u,w,30,e,{eventId:11});expect(u.posture).toBe(45);expect(u.grayHp).toBe(30);});
 it('gray life derives from post-shield real loss, and overkill grants no imaginary reclaim',()=>{const {s,u,e}=setup();u.statuses.push({kind:'shield',power:20,remaining:10});resolveHit(s,u,{...w,postureDamage:0},30,e);expect(u.hp).toBe(350);expect(u.grayHp).toBe(10);e.hp=2;resolveHit(s,e,w,500,u,{kind:'basic'});expect(u.hp).toBe(351);expect(u.grayHp).toBe(9);});
 it('healing item clamps gray life immediately',()=>{const {s,u,e}=setup();resolveHit(s,u,{...w,postureDamage:0},50,e);expect(command(s,{type:'item',item:'heal',to:u.pos,targetId:u.id}).ok).toBe(true);expect(u.hp).toBe(355);expect(u.grayHp).toBe(5);});
 it('death and node completion remove pressure without healing damage away',()=>{const {s,u,e}=setup(3);resolveHit(s,u,w,30,e);command(s,{type:'abandonBattle'});expect(u.grayHp).toBe(0);expect(u.posture).toBe(70);expect(u.hp).toBe(230);
  const other=setup(3);resolveHit(other.s,other.u,w,1000,other.e);expect(other.u.life).toBe('downed');expect(other.u.grayHp).toBe(0);expect(other.u.stagger).toBe(0);
 });
 it('copies spawn at full independent posture without source gray life or hit timers',()=>{const {s,u,e}=setup();resolveHit(s,u,w,30,e);const c=createClone(u,'copy',1,{x:4,y:4});expect(c.posture).toBe(90);expect(c.grayHp).toBe(0);expect(c.postureDelay).toBe(0);s.units.push(c);resolveHit(s,c,w,20,e);expect(c.posture).toBe(45);expect(u.posture).toBe(45);resolveHit(s,c,w,20,e);expect(u.posture).toBe(45);expect(c.posture).toBe(0);});
 it('a shared cast budget survives intervening ticks and covers later hits',()=>{const {s,u,e}=setup(3);resolveHit(s,u,{...w,postureDamage:0},150,e);u.skillId='rain';u.skillCd=0;step(s,.1);const before=u.hp,cast=currentSkill(u).run!.id;for(let i=0;i<100;i++)resolveHit(s,e,{...w,postureDamage:0},100,u,{skillId:'rain',castId:cast});const after=u.hp;expect(after-before).toBeLessThanOrEqual(26);step(s,.1);resolveHit(s,e,w,100,u,{skillId:'rain',castId:cast});expect(u.hp).toBe(after);});
 it('finite skill attack pressure and reclaim parameters are snapshotted for every emitted hit',()=>{const {s,u,e}=setup(3);u.skillId='rain';u.skillCd=0;step(s,.016);const run=currentSkill(u).run!;run.weapon.postureDamage=0;const posture=e.posture;step(s,.016);expect(e.posture).toBe(posture);});
 it('hundreds of finished basics release budget entries rather than retaining per-hit history',()=>{const {s,u,e}=setup();for(let i=0;i<200;i++){resolveHit(s,e,{...w,postureDamage:0},.1,u);step(s,.01);}expect(Object.keys(s.recoveryBudgets||{})).toHaveLength(0);});
 it('actual high-frequency rain across several enemies cannot exceed its whole-window gray recovery budget',()=>{const {s,u,e}=setup(3);resolveHit(s,u,{...w,postureDamage:0},150,e);u.skillId='rain';u.skillCd=0;currentSkill(u).stage=2;currentSkill(u).branches={C:2};for(let i=0;i<6;i++)foe(s,6+i*.1,5);step(s,3);expect(s.stats.rainArrows).toBeGreaterThan(300);expect(u.hp).toBeCloseTo(136);});
 it('node cleanup discards old cast budgets immediately',()=>{const {s,u,e}=setup();resolveHit(s,u,{...w,postureDamage:0},60,e);resolveHit(s,e,w,10,u,{castId:99});expect(Object.keys(s.recoveryBudgets!)).toHaveLength(1);command(s,{type:'abandonBattle'});expect(Object.keys(s.recoveryBudgets!)).toHaveLength(0);});
 it('posture and gray timers obey 0.1x, 1x, 2x, pause and hidden simulation time',()=>{for(const [slow,speed] of [[true,1],[false,1],[false,2]] as const){const {s,u,e}=setup();resolveHit(s,u,w,60,e);for(let i=0;i<240;i++)step(s,simulationDelta(1/60,false,false,slow,speed));const elapsed=slow?.4:4*speed;expect(u.posture).toBeCloseTo(Math.min(90,45+Math.max(0,elapsed-1.5)*22.5));expect(u.grayHp).toBeCloseTo(Math.max(0,60-Math.max(0,elapsed-4)*36));const snap=[u.grayHp,u.posture,u.grayDelay];step(s,simulationDelta(1,true,false,slow,speed));step(s,simulationDelta(1,false,true,slow,speed));expect([u.grayHp,u.posture,u.grayDelay]).toEqual(snap);}});
});
describe('stagger owns action boundaries, not emitted effects',()=>{
 it('same hit stagger must not revoke already sampled lethal recall protection',()=>{const {s,u,e}=setup(3);const h=s.units[0];h.life='active';h.pos={x:4,y:5};u.posture=0;u.hp=1;command(s,{type:'extract',id:u.id,via:'shadow'});captureRecallProtection(s);resolveHit(s,u,{...w,postureDamage:20},100,e);expect(u.life).toBe('rescued');expect(u.hp).toBe(1);expect(u.grayHp).toBe(0);});
 it('a generated return-seat effect survives the caster staggering until its own expiry',()=>{const {s,u,e}=setup(1);u.skillId='reap';currentSkill(u).counter=5;currentSkill(u).branches={C:1};step(s,.05);const seat=s.skillEffects!.find(a=>a.kind==='seat')!;expect(seat).toBeDefined();breakTwice(s,u,e);step(s,.1);expect(s.skillEffects!.some(a=>a.id===seat.id)).toBe(true);step(s,2.1);expect(s.skillEffects!.some(a=>a.id===seat.id)).toBe(false);});
 it('pauses an accepted movement route and resumes it after stagger instead of losing the destination',()=>{const {s,u,e}=setup();command(s,{type:'move',id:u.id,to:{x:3,y:5}});step(s,.1);breakTwice(s,u,e);const before={...u.pos};step(s,.3);expect(u.pos).toEqual(before);step(s,4);expect(u.pos.x).toBeCloseTo(3);});
 it('cancels unreleased basic attacks and blocks new movement, skill and weapon commands',()=>{const {s,u,e}=setup();u.attackTimer=0;step(s,.05);expect(u.attackPending).toBeDefined();breakTwice(s,u,e);expect(u.attackPending).toBeUndefined();const hp=e.hp,pos={...u.pos};expect(command(s,{type:'move',id:u.id,to:{x:4,y:4}}).ok).toBe(false);expect(command(s,{type:'direct',id:u.id,direction:{x:1,y:0}}).ok).toBe(false);expect(command(s,{type:'skill',id:u.id}).ok).toBe(false);expect(command(s,{type:'switchWeapon',id:u.id}).ok).toBe(false);step(s,.3);expect(e.hp).toBe(hp);expect(u.pos).toEqual(pos);});
 it('interrupts a committed one-shot into normal cooldown without refunding it',()=>{const {s,u,e}=setup(1);u.weaponIndex=0;u.skillId='prayer';u.skillCd=0;u.hp=20;expect(command(s,{type:'skill',id:u.id}).ok).toBe(true);breakTwice(s,u,e);expect(u.skillTime).toBe(0);expect(u.skillCd).toBe(18);step(s,1.1);expect(u.hp).toBe(20);});
 it('rain window runs during stagger, discards slots and resumes without catch-up',()=>{const {s,u,e}=setup(3);u.skillId='rain';u.skillCd=0;step(s,.08);const st=currentSkill(u),id=st.run!.id,arrows=s.stats.rainArrows;breakTwice(s,u,e);step(s,.3);expect(st.run?.id).toBe(id);expect(st.time).toBeCloseTo(5.62);expect(s.stats.rainArrows).toBe(arrows);step(s,.3);const count=s.stats.rainArrows;step(s,.016);expect(s.stats.rainArrows-count).toBeLessThanOrEqual(3);});
 it('scythe and sniper modes stay enabled while attacks stop',()=>{for(const index of [1,3]){const {s,u,e}=setup(index);currentSkill(u).enabled=true;u.attackTimer=0;breakTwice(s,u,e);step(s,.3);expect(currentSkill(u).enabled).toBe(true);expect(u.attackPending).toBeUndefined();}});
 it('already created sanctuary continues its own healing and duration through stagger',()=>{const {s,u,e}=setup(2);u.skillId='sanctuary';u.skillCd=0;u.hp=100;command(s,{type:'skill',id:u.id});const run=currentSkill(u).run!.id;breakTwice(s,u,e);step(s,.55);expect(currentSkill(u).run?.id).toBe(run);expect(u.skillTime).toBeCloseTo(11.45);expect(u.hp).toBe(104);});
 it('released sniper echoes survive stagger and keep their cast identity',()=>{const {s,u,e}=setup(3);currentSkill(u).enabled=true;currentSkill(u).stage=2;u.attackTimer=0;step(s,.31);const hp=e.hp;expect(s.skillEffects?.some(a=>a.kind==='snipeEcho')).toBe(true);breakTwice(s,u,e);step(s,.36);expect(e.hp).toBeLessThan(hp);});
 it('stagger cancels a pending equipment change and recall channel',()=>{const {s,u,e}=setup(3);const h=s.units[0];h.life='active';h.pos={x:4,y:5};expect(command(s,{type:'switchWeapon',id:u.id}).ok).toBe(true);breakTwice(s,u,e);expect(u.loadout).toBeUndefined();step(s,.7);expect(u.weaponIndex).toBe(0);expect(command(s,{type:'extract',id:u.id,via:'shadow'}).ok).toBe(true);breakTwice(s,u,e);expect(u.recall).toBeUndefined();});
 it('zero dt/paused phase does not advance posture or gray timers',()=>{const {s,u,e}=setup();resolveHit(s,u,w,30,e);const before=[u.posture,u.grayHp,u.postureDelay];step(s,0);s.phase='nodes';step(s,10);expect([u.posture,u.grayHp,u.postureDelay]).toEqual(before);});
});

