import {legacyGame as createGame} from './legacy-fixtures';
import {describe,it,expect} from 'vitest';

import {buyUpgrade,configureSkill,currentSkill,initializeProfile,initializeSkills,resetNodeSkills,resetExpeditionSkills,setUnlockPreset,canConfigure} from '../src/core/progression';
import {resolveSkill} from '../src/core/skill-catalog';

const setup=()=>{const s=createGame();initializeProfile(s);const u=s.units.find(a=>a.id==='fiorre')!;initializeSkills(u,s.profile);s.fragments=1000;return {s,u};};
describe('independent skill progression',()=>{
 it('buys one stage atomically and refuses the stale purchase without a second charge',()=>{const {s,u}=setup();expect(buyUpgrade(s,u,'stage',undefined,0).ok).toBe(true);expect(s.fragments).toBe(976);expect(resolveSkill(u).heal).toBe(190);expect(buyUpgrade(s,u,'stage',undefined,0).ok).toBe(false);expect(s.fragments).toBe(976);expect(currentSkill(u).stage).toBe(1);});
 it('buys branch levels by replacement and keeps the third branch locked after two choices',()=>{const {s,u}=setup();expect(buyUpgrade(s,u,'branch','reach',0).ok).toBe(true);expect(buyUpgrade(s,u,'branch','reach',1).ok).toBe(true);expect(resolveSkill(u).range).toBeCloseTo(4.6);expect(buyUpgrade(s,u,'branch','shelter',0).ok).toBe(true);const balance=s.fragments;expect(buyUpgrade(s,u,'branch','afterglow',0).ok).toBe(false);expect(s.fragments).toBe(balance);expect(resolveSkill(u).defense).toBe(.12);expect(resolveSkill(u).regen).toBe(0);});
 it('rejects insufficient money, invalid IDs and locked caps with zero mutation',()=>{const {s,u}=setup();s.fragments=1;expect(buyUpgrade(s,u,'stage',undefined,0).ok).toBe(false);expect(currentSkill(u).stage).toBe(0);expect(s.fragments).toBe(1);s.fragments=100;setUnlockPreset(s,'starter');expect(buyUpgrade(s,u,'branch','afterglow',0).ok).toBe(false);expect(buyUpgrade(s,u,'branch','missing',0).ok).toBe(false);expect(s.fragments).toBe(100);expect(buyUpgrade(s,u,'stage',undefined,0).ok).toBe(true);expect(buyUpgrade(s,u,'stage',undefined,1).ok).toBe(false);});
 it('preserves cooldown fraction and a casting snapshot when upgraded',()=>{const {s,u}=setup();u.skillCd=9;const st=currentSkill(u);st.time=2;st.snapshot=resolveSkill(u);expect(buyUpgrade(s,u,'stage',undefined,0).ok).toBe(true);expect(u.skillCd).toBeCloseTo(8.5);expect(u.skillMax).toBe(17);expect(st.snapshot!.heal).toBe(160);expect(resolveSkill(u).heal).toBe(190);});
 it('permits dead originals to buy without reviving and refuses copies',()=>{const {s,u}=setup();s.phase='battle';u.life='dead';u.hp=0;expect(buyUpgrade(s,u,'stage',undefined,0).ok).toBe(true);expect(u.life).toBe('dead');expect(u.hp).toBe(0);const copy=structuredClone(u);copy.id='copy';copy.cloneOf=u.id;initializeSkills(copy,s.profile);const balance=s.fragments;expect(buyUpgrade(s,copy,'stage',undefined,1).ok).toBe(false);expect(s.fragments).toBe(balance);});
 it('keeps defaults per profession and refuses combat or shadow configuration',()=>{const {s,u}=setup();expect(configureSkill(s,u,'ward').ok).toBe(true);expect(u.skillId).toBe('ward');expect(s.profile!.defaults[u.id].healer).toBe('ward');s.phase='battle';expect(canConfigure(s)).toBe(false);expect(configureSkill(s,u,'prayer').ok).toBe(false);u.life='withdrawn';expect(configureSkill(s,u,'prayer').ok).toBe(false);s.context='explorationIdle';expect(configureSkill(s,u,'prayer').ok).toBe(true);expect(configureSkill(s,u,'bell').ok).toBe(false);});
 it('rebinds cloned compatibility fields to independent runtime records',()=>{const {u}=setup();u.skillCd=7;const copy=structuredClone(u);copy.id='copy';copy.cloneOf=u.id;initializeSkills(copy);copy.skillCd=3;expect(currentSkill(copy).cd).toBe(3);expect(currentSkill(u).cd).toBe(7);expect(u.skillCd).toBe(7);});
 it('node reset preserves cultivation while expedition reset keeps profile and clears purchases',()=>{const {s,u}=setup();configureSkill(s,u,'ward');buyUpgrade(s,u,'stage',undefined,0);u.skillCd=1;resetNodeSkills(u);expect(currentSkill(u).stage).toBe(1);expect(u.skillCd).toBe(22);const profile=s.profile;resetExpeditionSkills(s);expect(s.profile).toBe(profile);expect(s.profile!.defaults[u.id].healer).toBe('ward');expect(currentSkill(u).stage).toBe(0);expect(currentSkill(u).branches).toEqual({});});
 it('changing a configured skill interrupts its cast into cooldown and keeps both caches',()=>{const {s,u}=setup();u.skillCd=0;u.skillTime=2;expect(configureSkill(s,u,'ward').ok).toBe(true);expect(u.skillStates!.prayer.time).toBe(0);expect(u.skillStates!.prayer.cd).toBe(18);u.skillCd=7;expect(configureSkill(s,u,'prayer').ok).toBe(true);expect(u.skillCd).toBe(18);expect(u.skillStates!.ward.cd).toBe(7);});
 it('changing the unlock preset never removes already paid build effects',()=>{const {s,u}=setup();buyUpgrade(s,u,'stage',undefined,0);buyUpgrade(s,u,'stage',undefined,1);buyUpgrade(s,u,'branch','afterglow',0);buyUpgrade(s,u,'branch','afterglow',1);setUnlockPreset(s,'starter');expect(resolveSkill(u).heal).toBe(220);expect(resolveSkill(u).regen).toBe(8);expect(currentSkill(u).stage).toBe(2);const balance=s.fragments;expect(buyUpgrade(s,u,'branch','reach',0).ok).toBe(true);expect(s.fragments).toBe(balance-12);});
 it('node reentry resets every cached skill without erasing purchases or charging backends',()=>{const {s,u}=setup();buyUpgrade(s,u,'stage',undefined,0);u.skillCd=2;configureSkill(s,u,'ward');buyUpgrade(s,u,'stage',undefined,0);u.skillCd=3;const balance=s.fragments;resetNodeSkills(u);expect(u.skillStates!.prayer.cd).toBe(17);expect(u.skillStates!.prayer.stage).toBe(1);expect(u.skillStates!.ward.cd).toBe(22);expect(u.skillStates!.ward.stage).toBe(1);expect(s.fragments).toBe(balance);});
 it('an idle development context cannot reopen configuration after the expedition ended',()=>{const {s,u}=setup();s.context='explorationIdle';s.phase='ended';expect(canConfigure(s)).toBe(false);expect(configureSkill(s,u,'ward').ok).toBe(false);expect(u.skillId).toBe('prayer');});
});
