import {test,expect} from '@playwright/test';
import {walk,snapshot} from './qst01-browser-helpers';
import {mkdirSync,writeFileSync} from 'node:fs';
const dir='../work/NIGHT-UI-20261010/QST-01A/browser-world';mkdirSync(dir,{recursive:true});test.setTimeout(480000);
for(const [width,height]of [[1440,900],[1280,720],[1920,1080]])test(`ordinary complete native encounters and persistent world ${width}`,async({page})=>{
 const errors:string[]=[],contextErrors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(/Too many active WebGL|CONTEXT_LOST|context lost/i.test(m.text()))contextErrors.push(m.text());});
 await page.setViewportSize({width,height});await page.goto('/');await page.locator('[data-companion=ranger]').click();await page.locator('[data-action=carry]').click();await expect.poll(()=>page.evaluate(()=>['hunter','ranger'].every(id=>(window as any).prototype.scene.unitVisuals.get(id)?.reference?.ready)),{timeout:30000}).toBe(true);
 const initial=await page.evaluate(()=>{const p=(window as any).prototype,s=p.state;return {groups:s.exploration.definition.encounters,enemyCount:s.units.filter((u:any)=>u.team==='enemy').length,families:s.units.filter((u:any)=>u.team==='enemy').map((u:any)=>u.enemyV2?.profile.visual),old:s.units.filter((u:any)=>u.enemyCombat||u.enemySense||u.attackIntent).length,loaded:p.scene.unitVisuals.size};});
 expect(initial.enemyCount).toBeGreaterThan(40);expect(initial.enemyCount).toBeLessThanOrEqual(48);expect(initial.families.every((f:string)=>f==='zombie'||f==='ranged')).toBe(true);expect(initial.old).toBe(0);expect(initial.loaded).toBeLessThan(15);expect(await page.locator('[data-v2]').count()).toBe(0);
 await page.locator('#exploration-objective summary').click();await page.locator('[data-exploration-point=campfire-1]').click();await expect(page.locator('[data-exploration-point=campfire-1]')).toBeDisabled();await page.keyboard.press('AltLeft');const facts:any[]=[];
 for(const tier of ['small','normal','strong']){const g=initial.groups.filter((g:any)=>g.tier===tier).sort((a:any,b:any)=>Math.hypot(a.center.x-6,a.center.y-8)-Math.hypot(b.center.x-6,b.center.y-8))[0];await walk(page,g.center,`${tier}-${width}`);await page.screenshot({path:dir+`/${tier}-${width}.png`});facts.push(await page.evaluate(()=>{const p=(window as any).prototype,s=p.state;return {time:s.time,kills:s.kills,memory:p.scene.renderer.info.memory,loaded:p.scene.unitVisuals.size,views:[...p.scene.unitVisuals.values()].map((a:any)=>({id:a.unit.id,visible:a.group.visible,ready:a.reference?.ready,failed:a.loadFailed,pose:a.reference?.pose})),events:s.units.filter((u:any)=>u.enemyV2).map((u:any)=>({id:u.id,life:u.life,profile:u.enemyV2.profile.id,brain:u.enemyV2.brain,events:u.enemyV2.trace.slice(-20)})),entities:s.enemyRuntime?.entities};}));}
 // Exercise both players and all main controls through real inputs.
 await page.keyboard.press('z');const shot=await page.evaluate(()=>{const p=(window as any).prototype,s=p.state,a=s.units.find((u:any)=>u.id===s.controlledBodyId);return p.project({x:a.pos.x+3,y:a.pos.y});});await page.mouse.move(shot.x,shot.y);await page.mouse.down({button:'right'});await page.waitForTimeout(1600);await page.mouse.up({button:'right'});await page.keyboard.press('Shift');await page.keyboard.press('e');await page.keyboard.press('z');await page.mouse.down({button:'right'});await page.waitForTimeout(200);await page.mouse.up({button:'right'});await page.keyboard.press('f');await page.keyboard.press('Escape');await page.keyboard.down('g');await page.keyboard.press('Escape');await page.keyboard.up('g');
 const end=await page.evaluate(()=>(window as any).prototype.state.exploration.definition.exit);await walk(page,end);await page.waitForTimeout(1200);if(!await page.locator('#exploration-objective details').evaluate((e:HTMLDetailsElement)=>e.open))await page.locator('#exploration-objective summary').click();await expect(page.locator('[data-action=exit-exploration]')).toBeEnabled({timeout:20000});await page.keyboard.press('Space');const before=await snapshot(page);expect(before.kills).toBeGreaterThan(0);
 const enemyBefore=await page.evaluate(()=>(window as any).prototype.state.units.filter((u:any)=>u.enemyV2).map((u:any)=>({id:u.id,hp:u.hp,posture:u.posture,delay:u.postureDelay,life:u.life,ready:u.enemyV2.readyAt,home:u.enemyV2.brain?.home})));
 await page.locator('[data-action=exit-exploration]').click();const outside=await snapshot(page);await expect(page.locator('.exploration-ended')).toBeVisible();await page.screenshot({path:dir+`/outside-${width}.png`});expect(outside.units).toEqual(before.units.map(u=>({...u,hunter:u.hunter&&{...u.hunter,held:false},al:u.al&&{...u.al,held:false,shotHeld:false}})));expect(outside.settled).toBeNull();await page.waitForTimeout(250);expect((await snapshot(page)).time).toBe(outside.time);await page.locator('[data-action=continue-world]').click();await page.keyboard.press('Space');const back=await snapshot(page);
 expect(back.world).toBe(before.world);expect(back.dead).toEqual(before.dead);expect(back.rewards).toEqual(before.rewards);expect(back.resources).toEqual(before.resources);
 const enemyAfter=await page.evaluate(()=>(window as any).prototype.state.units.filter((u:any)=>u.enemyV2).map((u:any)=>({id:u.id,hp:u.hp,posture:u.posture,delay:u.postureDelay,life:u.life,ready:u.enemyV2.readyAt,home:u.enemyV2.brain?.home})));expect(enemyAfter).toEqual(enemyBefore);await page.screenshot({path:dir+`/continued-${width}.png`});
 expect(back.used).toEqual(before.used);expect(back.units.map(u=>u.weapons)).toEqual(before.units.map(u=>u.weapons));await expect(page.locator('[data-exploration-point=campfire-1]')).toBeDisabled();await page.locator('[data-action=restart-world]').click();await page.locator('[data-action=cancel-economic]').click();expect((await snapshot(page)).world).toBe(before.world);await page.locator('[data-action=restart-world]').click();await page.locator('[data-action=confirm-economic]').click();await page.locator('[data-companion=ranger]').click();await page.locator('[data-action=carry]').click();const fresh=await snapshot(page);expect(fresh.world).not.toBe(before.world);expect(fresh.used).not.toContain('campfire-1');writeFileSync(dir+`/lifecycle-${width}.json`,JSON.stringify({method:"real mouse and keyboard; no state, HP, position or command injection",initial,facts,before,outside,back,fresh,enemyBefore,enemyAfter,errors,contextErrors},null,2));expect(errors).toEqual([]);expect(contextErrors).toEqual([]);
});
test('offscreen native skeleton leases release and ordinary missing assets never fall back',async({page})=>{
 await page.goto('/?enemies=v2&mode=four');await expect.poll(()=>page.evaluate(()=>(window as any).prototype?.state.time??0),{timeout:30000}).toBeGreaterThan(0);await page.keyboard.down('a');await page.waitForTimeout(4000);await page.keyboard.up('a');
 const views=await page.evaluate(()=>{const p=(window as any).prototype;return [...p.scene.unitVisuals.values()].filter((a:any)=>a.unit.enemyV2).map((a:any)=>({visible:a.group.visible,ready:a.reference?.ready}));});expect(views.every(v=>v.visible)).toBe(true);
 await page.route('**/__al01-assets/zombie/unit.json',r=>r.fulfill({status:404,body:'missing original'}));await page.goto('/');await page.locator('[data-companion=ranger]').click();await page.locator('[data-action=carry]').click();const target=await page.evaluate(()=>{const s=(window as any).prototype.state;return s.exploration.definition.encounters.find((g:any)=>g.tier!=='safe').center;});
 // A missing visible original stops simulation, so travel cannot finish. This is the expected failure path.
 await walk(page,target).catch(e=>expect(String(e)).toContain('real movement blocked'));
 await expect(page.locator('#error')).toBeVisible();const failed=await page.evaluate(()=>{const p=(window as any).prototype;return [...p.scene.unitVisuals.values()].filter((a:any)=>a.unit.enemyV2&&a.loadFailed).map((a:any)=>({profile:a.unit.enemyVisualProfileId,fallback:!!a.spine}));});expect(failed.length).toBeGreaterThan(0);expect(failed.every(x=>!x.fallback)).toBe(true);
});
test('ordinary repeated fresh worlds bound native GPU owners and clean released views',async({page})=>{
 const errors:string[]=[],warnings:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(/Too many active WebGL|CONTEXT_LOST|context lost/i.test(m.text()))warnings.push(m.text());});
 await page.goto('/');const rows:any[]=[];
 for(let visit=0;visit<3;visit++){
  await page.locator('[data-companion=ranger]').click();await page.locator('[data-action=carry]').click();await expect.poll(()=>page.evaluate(()=>(window as any).prototype?.state.time??0),{timeout:30000}).toBeGreaterThan(0);
  const target=await page.evaluate(()=>(window as any).prototype.state.exploration.definition.encounters.filter((g:any)=>g.tier==='normal').sort((a:any,b:any)=>Math.hypot(a.center.x-6,a.center.y-8)-Math.hypot(b.center.x-6,b.center.y-8))[0].center);await walk(page,target,'repeat-'+visit);await page.waitForTimeout(500);
  const row=await page.evaluate(()=>{const p=(window as any).prototype,s=p.state,views=[...p.scene.unitVisuals.values()];return {world:s.world.id,time:s.time,enemyCount:s.units.filter((u:any)=>u.enemyV2).length,memory:p.scene.renderer.info.memory,models:views.filter((a:any)=>a.unit.enemyV2).map((a:any)=>({id:a.unit.id,family:a.reference?.family,ready:a.reference?.ready,visible:a.group.visible,pose:a.reference?.pose,leases:a.reference?.pool.leases})),familyOwners:new Set(views.filter((a:any)=>a.unit.enemyV2&&a.reference).map((a:any)=>a.reference.pool)).size};});
  expect(row.enemyCount).toBe(44);expect(row.models.length).toBeGreaterThan(0);expect(row.models.every((m:any)=>m.visible&&m.ready)).toBe(true);expect(row.familyOwners).toBeLessThanOrEqual(2);rows.push(row);await page.screenshot({path:dir+`/repeat-${visit}.png`});
  await page.locator('[data-action=restart-world]').click();await page.locator('[data-action=confirm-economic]').click();await expect(page.locator('[data-action=carry]')).toBeVisible();await page.waitForTimeout(300);
  expect(await page.evaluate(()=>[...(window as any).prototype.scene.unitVisuals.values()].filter((a:any)=>a.unit.enemyV2).length)).toBe(0);
 }
 expect(new Set(rows.map(r=>r.world)).size).toBe(3);expect(Math.max(...rows.map(r=>r.memory.textures))-Math.min(...rows.map(r=>r.memory.textures))).toBeLessThan(25);
 writeFileSync(dir+'/repeat-worlds.json',JSON.stringify({rows,errors,warnings},null,2));expect(errors).toEqual([]);expect(warnings).toEqual([]);
});
