import {expect,type Page} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
const dir='../work/NIGHT-UI-20261010/QST-01A/browser-world';mkdirSync(dir,{recursive:true});
type Point={x:number;y:number};
export async function snapshot(page:Page){return page.evaluate(()=>{const s=(window as any).prototype.state;return {world:s.world?.id,visit:s.world?.visit,phase:s.phase,time:s.time,resources:s.economy.carried,settled:s.economy.settled,rewards:s.economy.rewards,seen:s.exploration?.memory.seen,used:s.exploration?.memory.mechanisms,units:s.units.filter((u:any)=>u.id==='hunter'||u.id==='ranger').map((u:any)=>({id:u.id,hp:u.hp,gray:u.grayHp,posture:u.posture,life:u.life,pos:u.pos,weapons:u.weapons.map((w:any)=>({name:w.name,durability:w.durability})),hunter:u.hunterCombat&&{held:u.hunterCombat.held,frost:u.hunterCombat.frost,activeCooldown:u.hunterCombat.activeCooldown,finalRecoveryUntil:u.hunterCombat.finalRecoveryUntil},al:u.alCombat&&{held:u.alCombat.held,shotHeld:u.alCombat.shotHeld,ammo:u.alCombat.ammo,rocketCd:u.alCombat.rocketCd}})),dead:s.units.filter((u:any)=>u.team==='enemy'&&u.life==='dead').map((u:any)=>u.id),kills:s.kills};});}

// Read-only route planning; travel and attacks are actual keyboard/mouse events.
export async function route(page:Page,to:Point){return page.evaluate((to)=>{const s=(window as any).prototype.state,h=s.units.find((u:any)=>u.id==='hunter'),key=(p:Point)=>p.x+','+p.y,open=new Set(s.tiles.filter((t:any)=>!t.obstacle).map(key)),start={x:Math.round(h.pos.x),y:Math.round(h.pos.y)},end={x:Math.round(to.x),y:Math.round(to.y)},queue=[start],prev=new Map<string,Point|undefined>([[key(start),undefined]]);for(let i=0;i<queue.length;i++){const p=queue[i];if(key(p)===key(end)){const path:Point[]=[];let q:Point|undefined=p;while(q){path.unshift(q);q=prev.get(key(q));}return path;}for(const d of [{x:1,y:0},{x:-1,y:0},{x:0,y:1},{x:0,y:-1}]){const n={x:p.x+d.x,y:p.y+d.y};if(open.has(key(n))&&!prev.has(key(n))){prev.set(key(n),p);queue.push(n);}}}return [];},to);}
export async function walk(page:Page,to:Point,label?:string){
 let captured=false;
 let way=await route(page,to);expect(way.length,'reachable route').toBeGreaterThan(0);let cursor=0;const held=new Set<string>();let stagnant=0,last:Point|undefined;
 const keys=async(next:string[])=>{for(const k of [...held])if(!next.includes(k)){await page.keyboard.up(k);held.delete(k);}for(const k of next)if(!held.has(k)){await page.keyboard.down(k);held.add(k);}};
 for(let n=0;n<2200;n++){
  const data=await page.evaluate(async()=>{const {clearShot}=await import('/src/core/spatial.ts' as string),p=(window as any).prototype,s=p.state,h=s.units.find((u:any)=>u.id==='hunter'),e=s.units.filter((u:any)=>u.team==='enemy'&&u.life==='active'&&clearShot(s,h.pos,u.pos)).sort((a:any,b:any)=>Math.hypot(a.pos.x-h.pos.x,a.pos.y-h.pos.y)-Math.hypot(b.pos.x-h.pos.x,b.pos.y-h.pos.y))[0];return {pos:{...h.pos},life:h.life,hp:h.hp,enemy:e&&{id:e.id,d:Math.hypot(e.pos.x-h.pos.x,e.pos.y-h.pos.y),screen:p.project(e.pos)}};});
  if(n%30===0){console.log('real route',n,data.pos,data.hp,data.enemy?.id,data.enemy?.d);writeFileSync(dir+'/progress.json',JSON.stringify({n,data}));}
  expect(data.life,'hunter remains playable').toBe('active');
  if(data.enemy&&data.enemy.d<3.5){await keys([]);if(label&&!captured){await page.waitForTimeout(300);await page.screenshot({path:dir+`/live-${label}.png`});captured=true;}await page.mouse.move(data.enemy.screen.x,data.enemy.screen.y);if(data.enemy.d>1.65){const enemyPos=await page.evaluate(id=>{const e=(window as any).prototype.state.units.find((u:any)=>u.id===id);return {...e.pos};},data.enemy.id);const dx=enemyPos.x-data.pos.x,dy=enemyPos.y-data.pos.y;await keys([...(Math.abs(dx)>.2?[dx>0?'d':'a']:[]),...(Math.abs(dy)>.2?[dy>0?'s':'w']:[])]);}await page.mouse.down();await page.waitForTimeout(200);await page.mouse.up();await keys([]);way=await route(page,to);cursor=0;stagnant=0;continue;}
  while(cursor<way.length&&Math.hypot(way[cursor].x-data.pos.x,way[cursor].y-data.pos.y)<.3)cursor++;
  if(cursor===way.length){await keys([]);return;}
  const goal=way[cursor],dx=goal.x-data.pos.x,dy=goal.y-data.pos.y;
  const next:string[]=[];if(Math.abs(dx)>.13)next.push(dx>0?'d':'a');if(Math.abs(dy)>.13)next.push(dy>0?'s':'w');await keys(next);await page.waitForTimeout(Math.min(110,Math.max(16,Math.hypot(dx,dy)*1000/24)));
  if(last&&Math.hypot(last.x-data.pos.x,last.y-data.pos.y)<.015)stagnant++;else stagnant=0;last=data.pos;
  if(stagnant>25){const diagnostic=await page.evaluate(()=>{const p=(window as any).prototype,s=p.state;return {scale:p.effectiveTimeScale,time:s.time,world:s.world.id,modal:['help','economy-confirm','exploration-exit-confirm'].map(id=>({id,hidden:document.getElementById(id)?.hidden})),notice:s.notice,interaction:p.interaction,actors:s.units.filter((u:any)=>u.team==='ally').map((u:any)=>({id:u.id,direct:u.direct,life:u.life,stagger:u.stagger,basic:u.basicAction,hunter:u.hunterCombat})),views:[...p.scene.unitVisuals.values()].map((a:any)=>({id:a.unit.id,visible:a.group.visible,ready:a.reference?.ready,failed:a.loadFailed,family:a.reference?.family}))};});writeFileSync(dir+'/blocked-diagnostic.json',JSON.stringify(diagnostic,null,2));await keys([]);await page.screenshot({path:dir+'/blocked.png'});throw Error('real movement blocked at '+JSON.stringify(data));}
 }
 await keys([]);throw Error('natural route deadline');
}
