import {describe,it,expect} from 'vitest';
import {arena,foe} from './rework-fixtures';
import {command,step,resolveHit} from '../src/core/engine';
import {currentSkill} from '../src/core/progression';
import {planReapPath} from '../src/core/reap-path';
function f(){const s=arena(),u=s.units[1];u.life='active';u.pos={x:5,y:5};u.drawPos={...u.pos};u.weapons[4].damage=40;u.attackTimer=0;return {s,u};}
describe('charged scythe mode and unrestricted target count',()=>{
 it('charges before automatic entry, keeps mode without enemies, E exits into empty charge',()=>{const {s,u}=f();step(s,17);expect(currentSkill(u).enabled).toBe(false);step(s,1);expect(currentSkill(u).enabled).toBe(true);step(s,20);expect(currentSkill(u).enabled).toBe(true);expect(command(s,{type:'skill',id:u.id}).ok).toBe(true);expect(u.skillCd).toBe(18);});
 for(const count of [1,3,10,20])it(`damages ${count} legal targets, healing cap does not cap damage`,()=>{const {s,u}=f();currentSkill(u).enabled=true;currentSkill(u).branches={B:2};u.hp=100;const targets=Array.from({length:count},(_,i)=>foe(s,6,5+(i-count/2)*.015));step(s,.31);targets.forEach(t=>expect(t.hp).toBe(9954));expect(u.hp).toBeCloseTo(100+Math.min(5,count)*3.5);expect(u.weapons[4].durability).toBe(59);});
 it('has a delayed fixed-position return blade and only original sweeps refresh cracks',()=>{const {s,u}=f();const st=currentSkill(u);st.enabled=true;st.stage=2;st.branches={A:2};const e=foe(s,6,5),back=foe(s,4,5);step(s,.31);expect(e.hp).toBe(9954);expect(back.hp).toBe(10000);u.attackTimer=999;step(s,.25);expect(e.hp).toBeCloseTo(9937.9);expect(back.hp).toBeCloseTo(9983.9);expect(u.weapons[4].durability).toBe(59);u.attackTimer=0;step(s,.31);expect(e.hp).toBeCloseTo(9877.9);});
});
describe('automatic out-and-back skill and body-swept route',()=>{
 it('keeps full basic count when no route hits an enemy and scores a diagonal crowd rather than four directions',()=>{const {s,u}=f();u.skillId='reap';currentSkill(u).counter=5;step(s,.2);expect(currentSkill(u).counter).toBe(5);expect(currentSkill(u).run).toBeUndefined();foe(s,6,6);foe(s,7,7);foe(s,8,5);const path=planReapPath(s,u);expect(path).toBeDefined();expect(path!.heading).toBeCloseTo(Math.PI/4);});
 it('does not sweep a body through a wall, narrow gap, raised edge or a dynamic barricade',()=>{const {s,u}=f();foe(s,7,5);s.tiles.find(t=>t.x===6&&t.y===5)!.obstacle=true;expect(planReapPath(s,u)).toBeUndefined();s.tiles.find(t=>t.x===6&&t.y===5)!.obstacle=false;s.tiles.find(t=>t.x===6&&t.y===5)!.layer=1;expect(planReapPath(s,u)).toBeUndefined();s.tiles.find(t=>t.x===6&&t.y===5)!.layer=0;s.barricades=[{x:6,y:5}];expect(planReapPath(s,u)).toBeUndefined();});
 it('each leg hits each enemy once and returns to the real original position',()=>{const {s,u}=f();u.skillId='reap';const st=currentSkill(u);st.counter=5;st.stage=2;st.branches={A:2,B:2};const e=foe(s,6.5,5),a=s.units[0];a.life='active';a.pos={x:5.7,y:5.7};a.hp=100;step(s,1.8);expect(st.run).toBeUndefined();expect(st.counter).toBe(0);expect(u.pos.x).toBeCloseTo(5);expect(u.pos.y).toBeCloseTo(5);expect(e.hp).toBeCloseTo(9827.6);expect(a.hp).toBe(114);});
 it('copy casts a virtual route, consumes independent count and never moves its body',()=>{const {s,u}=f();u.skillId='reap';s.fragments=100;expect(command(s,{type:'clone',id:u.id,to:{x:8,y:5}}).ok).toBe(true);const c=s.units.at(-1)!;currentSkill(c).counter=5;const e=foe(s,9.5,5);step(s,1.5);expect(c.pos).toEqual({x:8,y:5});expect(e.hp).toBe(9864);expect(currentSkill(u).counter).toBe(0);});
 it('lethal damage and user movement end the action without refunding the consumed count or leaving a lock',()=>{const {s,u}=f();u.skillId='reap';currentSkill(u).counter=5;const e=foe(s,6.5,5);step(s,.15);expect(currentSkill(u).run).toBeDefined();expect(command(s,{type:'move',id:u.id,to:{x:5,y:7}}).ok).toBe(true);expect(currentSkill(u).run).toBeUndefined();expect(currentSkill(u).counter).toBe(0);step(s,.1);resolveHit(s,u,{...e.weapons[0],subtype:'impact'},9999,e);expect(currentSkill(u).run).toBeUndefined();expect(u.life).toBe('rescued');});
 it('a newly blocked return endpoint chooses a nearby legal point and ends normally without teleporting through walls',()=>{const {s,u}=f();u.skillId='reap';currentSkill(u).counter=5;foe(s,7,5);step(s,.3);const a=s.units[0];a.life='active';a.pos={x:5,y:5};step(s,2);expect(currentSkill(u).run).toBeUndefined();expect(Math.hypot(u.pos.x-5,u.pos.y-5)).toBeGreaterThan(.43);expect(Math.hypot(u.pos.x-5,u.pos.y-5)).toBeLessThan(1.5);});
});
