import {describe,it,expect} from 'vitest';
import {arena,foe} from './rework-fixtures';
import {command,step,resolveHit} from '../src/core/engine';
import {buyUpgrade,currentSkill,resetNodeSkills,resetExpeditionSkills} from '../src/core/progression';
import {resolveSkill} from '../src/core/skill-catalog';
import {damageAfterDefense} from '../src/core/combat-config';
import {skillStatus} from '../src/skill-ui';
import type {SkillId} from '../src/core/types';
import {canStop} from '../src/core/spatial';
describe('all six build transaction combinations',()=>{
 it('buys 342 valid configurations in both branch orders, rejects the third branch atomically and keeps counts on upgrades',()=>{
  const configurations:Record<string,number>[]=[{}];for(const b of ['A','B','C'])for(const n of [1,2])configurations.push({[b]:n});for(const [a,b] of [['A','B'],['A','C'],['B','C']])for(const x of [1,2])for(const y of [1,2])configurations.push({[a]:x,[b]:y});
  let count=0;for(const id of ['pain','sanctuary','snipe','rain','dance','reap'] as SkillId[])for(const tier of [0,1,2])for(const selection of configurations){
   const outcomes=[];for(const reverse of [false,true]){const s=arena();s.phase='briefing';const u=s.units[id==='pain'||id==='sanctuary'?2:id==='snipe'||id==='rain'?3:1];command(s,{type:'configureSkill',id:u.id,skillId:id});const st=currentSkill(u);st.counter=3;
    for(let t=0;t<tier;t++)expect(buyUpgrade(s,u,'stage',undefined,t).ok).toBe(true);
    const entries=Object.entries(selection);if(reverse)entries.reverse();for(const [b,n] of entries)for(let level=0;level<n;level++)expect(buyUpgrade(s,u,'branch',b,level).ok).toBe(true);
    const expected=1000-[0,24,64][tier]-Object.values(selection).reduce((n,level)=>n+[0,12,32][level],0);expect(s.fragments).toBe(expected);expect(st.counter).toBe(3);expect(resolveSkill(u).tier).toBe(tier);
    if(entries.length===2){const before=s.fragments,third=['A','B','C'].find(b=>!(b in selection))!;expect(buyUpgrade(s,u,'branch',third,0).ok).toBe(false);expect(s.fragments).toBe(before);}
    outcomes.push(resolveSkill(u));
   }expect(outcomes[0]).toEqual(outcomes[1]);count++;
  }expect(count).toBe(342);
 });
});
describe('field, mode and action lifetimes',()=>{
 it('field exit strips growing/core resistance and trailing heal stops on reentry without recursion',()=>{const s=arena(),u=s.units[2],a=s.units[0],e=foe(s);u.life=a.life='active';u.pos={x:5,y:5};a.pos={x:6,y:5};a.hp=100;u.skillId='sanctuary';const st=currentSkill(u);st.cd=0;st.stage=2;st.branches={B:2,C:2};e.defense={subtype:'impact',flat:10};command(s,{type:'skill',id:u.id});step(s,6);expect(damageAfterDefense({...u.weapons[0],subtype:'impact'},e,20)).toBe(17);
  command(s,{type:'move',id:u.id,to:{x:4,y:5}});step(s,.05);expect(damageAfterDefense({...u.weapons[0],subtype:'impact'},e,20)).toBe(12.5);
  st.cd=0;command(s,{type:'skill',id:u.id});step(s,.55);a.pos={x:10,y:5};step(s,.05);expect(a.statuses.find(b=>b.source==='field-trail:'+u.id)?.power).toBe(8);a.pos={x:6,y:5};step(s,.05);expect(a.statuses.some(b=>b.source==='field-trail:'+u.id)).toBe(false);
 });
 it('paid upgrades do not edit a launched echo while a continuous mode uses the next current build',()=>{const s=arena(),u=s.units[2],a=s.units[0];u.life=a.life='active';u.pos={x:5,y:5};a.pos={x:6,y:5};a.hp=10;currentSkill(u).counter=5;currentSkill(u).stage=1;command(s,{type:'skill',id:u.id});buyUpgrade(s,u,'stage',undefined,1);step(s,1.5);expect(a.hp).toBe(118);});
 it('cross-profession mode closes into charge, node clears every event count, shadow only advances Fiorre current time',()=>{const s=arena(),f=s.units[1],u=s.units[2];f.life='active';currentSkill(f).enabled=true;currentSkill(f).cd=0;command(s,{type:'weapon',id:f.id,index:0});step(s,.8);expect(f.skillStates!.dance.enabled).toBe(false);expect(f.skillStates!.dance.cd).toBe(18);f.life='withdrawn';f.shadowResident=true;f.skillCd=10;step(s,1);expect(f.skillCd).toBeCloseTo(9);u.shadowResident=true;u.life='withdrawn';u.skillId='sanctuary';currentSkill(u).cd=10;step(s,1);expect(u.skillCd).toBe(10);currentSkill(f).counter=3;resetNodeSkills(f);expect(currentSkill(f).counter).toBe(0);buyUpgrade({...s,phase:'briefing'},f,'stage',undefined,0);resetExpeditionSkills(s);expect(currentSkill(f).stage).toBe(0);});
 it('shows automatic skills as informational and a charged infinite mode as exit only',()=>{const s=arena(),f=s.units[1],u=s.units[2],a=s.units[3];currentSkill(u).counter=3;expect(skillStatus(u)).toMatchObject({label:'痛印 3/8 · 治疗 6%',fill:.375,canActivate:true});a.skillId='rain';expect(skillStatus(a).canActivate).toBe(false);expect(command(s,{type:'skill',id:a.id}).ok).toBe(false);expect(skillStatus(f).canActivate).toBe(false);currentSkill(f).enabled=true;expect(skillStatus(f).canActivate).toBe(true);});
 it('stops a body-overlapping return action at a reachable legal point when explicitly redirected',()=>{const s=arena(),u=s.units[1];u.life='active';u.pos={x:5,y:5};u.skillId='reap';currentSkill(u).counter=5;foe(s,6,5);step(s,1/6);expect(Math.abs(u.pos.x-6)).toBeLessThan(.05);expect(command(s,{type:'move',id:u.id,to:{x:5,y:7}}).ok).toBe(true);step(s,3);expect(currentSkill(u).run).toBeUndefined();expect(u.pos.y).toBeGreaterThan(5.3);expect(currentSkill(u).counter).toBe(0);});
 it('death during infinite mode closes it and death during a real slide keeps the actual position',()=>{const s=arena(),u=s.units[1],e=foe(s);u.life='active';currentSkill(u).enabled=true;resolveHit(s,u,e.weapons[0],99999,e);expect(currentSkill(u).enabled).toBe(false);});
 it('recall interrupts a finite field immediately, but stun only delays automatic entry while time charge continues',()=>{const s=arena(),h=s.units[0],u=s.units[2],a=s.units[3];h.life=u.life=a.life='active';h.pos={x:4,y:5};u.pos={x:5,y:5};u.skillId='sanctuary';currentSkill(u).cd=0;command(s,{type:'skill',id:u.id});expect(command(s,{type:'extract',id:u.id}).ok).toBe(true);expect(currentSkill(u).run).toBeUndefined();expect(u.skillCd).toBe(36);a.skillId='rain';currentSkill(a).cd=.1;a.statuses.push({kind:'stun',power:0,remaining:1,source:'test'});step(s,.3);expect(a.skillCd).toBe(0);expect(currentSkill(a).run).toBeUndefined();});
 it('clears pending echoes and audit events on a new expedition instead of carrying source ids into the new node',()=>{const s=arena(),u=s.units[2];u.life='active';u.pos={x:5,y:5};currentSkill(u).counter=2;currentSkill(u).stage=1;command(s,{type:'skill',id:u.id});resolveHit(s,foe(s),u.weapons[0],3,u);expect(s.skillEffects!.length).toBeGreaterThan(0);expect(command(s,{type:'abandon'}).ok).toBe(true);expect(command(s,{type:'newExpedition'}).ok).toBe(true);expect(s.skillEffects||[]).toHaveLength(0);expect(s.combatEvents||[]).toHaveLength(0);});
 for(const action of ['direct','weapon'] as const)it(`settles physically without new hits before ${action} after interrupting an overlapping slide`,()=>{const s=arena(),u=s.units[1];u.life='active';u.pos={x:5,y:5};u.skillId='reap';currentSkill(u).counter=5;const e=foe(s,6,5);step(s,1/6);const hp=e.hp;expect(command(s,action==='direct'?{type:'direct',id:u.id,direction:{x:0,y:1}}:{type:'weapon',id:u.id,index:0}).ok).toBe(true);step(s,1.5);expect(canStop(s,u.pos,u)).toBe(true);expect(u.skillLanding).toBeUndefined();expect(e.hp).toBe(hp);});
 it('copies born while the parent is settling inherit no movement/action reference',()=>{const s=arena(),u=s.units[1];u.life='active';u.pos={x:5,y:5};u.skillLanding={origin:{x:5,y:5},after:{x:8,y:5}};command(s,{type:'clone',id:u.id,to:{x:5,y:7}});const c=s.units.at(-1)!;expect(c.skillLanding).toBeUndefined();expect(currentSkill(c).counter).toBe(0);});
 it('already launched clone healing echoes finish their approved lifetime after clone destruction',()=>{const s=arena(),u=s.units[2],a=s.units[0];u.life=a.life='active';u.pos={x:5,y:5};a.pos={x:6,y:5};a.hp=10;currentSkill(u).stage=1;command(s,{type:'clone',id:u.id,to:{x:5,y:6}});const c=s.units.at(-1)!;currentSkill(c).counter=5;command(s,{type:'skill',id:c.id});expect(a.hp).toBe(90);command(s,{type:'extract',id:c.id,via:'shadow'});step(s,.75);expect(a.hp).toBe(118);});
 it('a full slide can be recalled from an overlapping point and no finite action survives recall',()=>{const s=arena(),h=s.units[0],u=s.units[1];h.life=u.life='active';h.pos={x:5,y:6};u.pos={x:5,y:5};u.skillId='reap';currentSkill(u).counter=5;foe(s,6,5);step(s,1/6);expect(command(s,{type:'extract',id:u.id,via:'shadow'}).ok).toBe(true);step(s,.2);expect(u.skillLanding).toBeUndefined();expect(canStop(s,u.pos,u)).toBe(true);expect(currentSkill(u).run).toBeUndefined();});
});
