import {it,expect} from 'vitest';
import {arena,foe} from './rework-fixtures';
import {command,step,resolveHit} from '../src/core/engine';
import {currentSkill} from '../src/core/progression';
import {damageAfterDefense} from '../src/core/combat-config';
for(const tier of [0,1,2]){
 it(`arrow trace branch works at T${tier}, hits once independently and respects its live trace cap`,()=>{const s=arena(),u=s.units[3];u.life='active';u.pos={x:5,y:5};u.skillId='rain';u.weapons[0].damage=40;const st=currentSkill(u);st.cd=0;st.stage=tier;st.branches={C:2};foe(s,7,5);step(s,.41);expect(s.combatEvents!.filter(e=>e.derived&&e.skillId==='rain')).toHaveLength(6);step(s,.2);expect(s.combatEvents!.filter(e=>e.derived&&e.skillId==='rain')).toHaveLength(6);step(s,1.4);expect(s.skillEffects!.filter(e=>e.kind==='rainTrace').length).toBeLessThanOrEqual(3);expect(u.weapons[0].durability).toBe(60);});
 it(`scythe trace branch works at T${tier}, each trace hits once and only the newest remains`,()=>{const s=arena(),u=s.units[1];u.life='active';u.pos={x:5,y:5};u.weapons[4].damage=40;u.attackTimer=0;const st=currentSkill(u);st.cd=0;st.enabled=true;st.stage=tier;st.branches={C:2};const e=foe(s,6.65,5);step(s,.31);expect(e.hp).toBe(9954);step(s,.01);expect(e.hp).toBe(9938);expect(s.combatEvents!.filter(e=>e.skillId==='dance'&&e.derived)).toHaveLength(1);u.attackTimer=0;step(s,.3);expect(s.skillEffects!.filter(e=>e.kind==='scytheTrace')).toHaveLength(1);});
 it(`return origin seat branch works at T${tier} without granting basic count or repeat contact hits`,()=>{const s=arena(),u=s.units[1];u.life='active';u.pos={x:5,y:5};u.skillId='reap';u.weapons[4].damage=40;const st=currentSkill(u);st.counter=5;st.stage=tier;st.branches={C:2};const e=foe(s,5.6,5);step(s,.1);expect(st.counter).toBe(0);const seats=()=>s.combatEvents!.filter(a=>a.targetId===e.id&&a.skillId==='reap'&&a.power===32);expect(seats()).toHaveLength(1);step(s,.2);expect(seats()).toHaveLength(1);expect(e.statuses.some(st=>st.source?.startsWith('seat:'))).toBe(true);});
}
it('sniper pin is primary-only and target ICD is independent between copies',()=>{const s=arena(),u=s.units[3];u.life='active';u.pos={x:5,y:5};const st=currentSkill(u);st.enabled=true;st.branches={B:2};u.attackTimer=0;const e=foe(s,6,5);step(s,.31);expect(e.statuses.find(a=>a.source==='pin:'+u.id)?.power).toBe(.8);const deadline=st.targetClocks![e.id];u.attackTimer=0;step(s,.31);expect(st.targetClocks![e.id]).toBe(deadline);expect(command(s,{type:'clone',id:u.id,to:{x:5,y:6}}).ok).toBe(true);const c=s.units.at(-1)!;currentSkill(c).enabled=true;step(s,.31);expect(currentSkill(c).targetClocks![e.id]).toBeGreaterThan(deadline);expect(e.statuses.some(a=>a.source==='pin:'+c.id)).toBe(true);});
it('multiple fields take strongest capped defense reduction and wards consume strongest then weaker, independently',()=>{const s=arena(),u=s.units[2],a=s.units[0],e=foe(s);u.life=a.life='active';u.pos={x:5,y:5};a.pos={x:6,y:5};a.hp=300;currentSkill(u).counter=1;currentSkill(u).branches={A:2};command(s,{type:'skill',id:u.id});command(s,{type:'clone',id:u.id,to:{x:5,y:6}});const c=s.units.at(-1)!;currentSkill(c).branches={A:1};currentSkill(c).counter=1;command(s,{type:'skill',id:c.id});const w={...e.weapons[0],subtype:'impact' as const};resolveHit(s,a,w,100,e);expect(a.hp).toBeCloseTo(332-100+360*.08);expect(a.statuses.filter(st=>st.kind==='warding')).toHaveLength(1);e.statuses=[{kind:'resistBreak',power:.6,remaining:2,source:'one'},{kind:'resistBreak',power:.9,remaining:2,source:'two'}];e.defense={subtype:'impact',flat:10};expect(damageAfterDefense(w,e,20)).toBeCloseTo(17);});
