import {legacyGame as createGame} from './legacy-fixtures';
import {expect,test} from 'vitest';
import {command,step,skillRangeTiles,canHit} from '../src/core/engine';
import type {GameState,Unit,Command} from '../src/core/types';

function arena(){const s=createGame();s.phase='battle';s.waves=[];s.totalEnemies=999;s.width=12;s.height=9;s.tiles=Array.from({length:108},(_,i)=>({x:i%12,y:Math.floor(i/12),layer:0,obstacle:false}));s.goal={x:0,y:0};s.fragments=500;s.units.forEach((u,i)=>{u.pos={x:2+i,y:3};u.drawPos={...u.pos};u.ready=0;u.weapons.forEach(w=>w.damage=0);});return s;}
function request(s:GameState,c:unknown){return command(s,c as Command);}
function fiorre(s:GameState){const f=s.units[1];f.life='active';f.skillCd=0;return f;}
function enemy(s:GameState,pos={x:5,y:3}){const e={...structuredClone(s.units[0]),id:'foe-'+s.nextId++,team:'enemy' as const,role:'melee' as const,life:'active' as const,pos,drawPos:{...pos},hp:500,maxHp:500,speed:0,dodge:0,attackTimer:999,skillTime:0,path:[],destination:null};e.weapons=e.weapons.map(w=>({...w,damage:0,range:1}));s.units.push(e);return e;}

test('ward skill gives nearby allies a missing-health shield that absorbs damage before HP',()=>{const s=arena();s.phase='briefing';expect(request(s,{type:'configureSkill',id:'fiorre',skillId:'ward'}).ok).toBe(true);s.phase='battle';const f=fiorre(s),h=s.units[0];h.hp=100;expect(command(s,{type:'skill',id:f.id}).ok).toBe(true);step(s,1.05);expect(h.hp).toBe(100);h.statuses.push({kind:'poison',power:40,remaining:1});step(s,.5);expect(h.hp).toBe(100);});
test('weapon change channels before changing profession and its active skill',()=>{const s=arena(),f=fiorre(s);expect(request(s,{type:'weapon',id:f.id,index:2}).ok).toBe(true);expect(f.weaponIndex).toBe(0);step(s,.3);expect(f.weaponIndex).toBe(0);step(s,2);expect(f.weaponIndex).toBe(2);expect(skillRangeTiles(s,f)).toContainEqual({x:7,y:3});});
test('copies keep birth profession and do not share later parent upgrades',()=>{const s=arena(),f=fiorre(s);expect(request(s,{type:'weapon',id:f.id,index:2}).ok).toBe(true);step(s,2);expect(command(s,{type:'clone',id:f.id,to:{x:8,y:5}}).ok).toBe(true);const c=s.units.at(-1)!;expect(c.weaponIndex).toBe(2);expect(request(s,{type:'upgradeSkill',id:c.id,kind:'stage',expectedLevel:0}).ok).toBe(false);expect(request(s,{type:'weapon',id:c.id,index:0}).ok).toBe(false);});
test('cantor skill hits legal enemies once and applies a temporary slow without basic attacks',()=>{const s=arena(),f=fiorre(s),e=enemy(s);expect(request(s,{type:'weapon',id:f.id,index:2}).ok).toBe(true);step(s,2);f.skillCd=0;f.weapons[2].damage=300;const durability=f.weapons[2].durability,hp=e.hp;expect(command(s,{type:'skill',id:f.id}).ok).toBe(true);step(s,1.1);expect(e.hp).toBeLessThan(hp);expect(e.hp).toBeGreaterThan(hp-100);expect(e.statuses.some(t=>t.kind==='slow')).toBe(true);const after=e.hp;step(s,.95);expect(e.hp).toBe(after);expect(f.weapons[2].durability).toBe(durability);});
test('successful movement cancels a pending loadout but blocked blink leaves it running',()=>{const s=arena(),h=s.units[0];expect(request(s,{type:'weapon',id:h.id,index:1}).ok).toBe(true);expect(command(s,{type:'move',id:h.id,to:{x:2,y:4}}).ok).toBe(true);step(s,2);expect(h.weaponIndex).toBe(0);h.pos={x:2.32,y:4};h.drawPos={...h.pos};h.path=[];s.tiles.find(t=>t.x===3&&t.y===4)!.obstacle=true;expect(request(s,{type:'weapon',id:h.id,index:1}).ok).toBe(true);expect(command(s,{type:'blink',id:h.id,direction:{x:1,y:0}}).ok).toBe(false);step(s,2);expect(h.weaponIndex).toBe(1);});
test('repairing a broken primary weapon does not silently change current profession',()=>{const s=arena(),f=fiorre(s);expect(request(s,{type:'weapon',id:f.id,index:2}).ok).toBe(true);step(s,2);f.weapons[0].durability=0;expect(command(s,{type:'item',item:'weapon',to:f.pos,targetId:f.id}).ok).toBe(true);expect(f.weapons[0].durability).toBe(f.weapons[0].maxDurability);expect(f.weaponIndex).toBe(2);});
test('changing weapons suppresses basic attacks and taking damage does not interrupt the channel',()=>{const s=arena(),h=s.units[0],e=enemy(s,{x:3,y:3});h.weapons[0].damage=100;h.statuses=[{kind:'poison',remaining:1,power:5}];expect(request(s,{type:'weapon',id:h.id,index:1}).ok).toBe(true);const hp=e.hp;step(s,.3);expect(e.hp).toBe(hp);expect(h.hp).toBeLessThan(h.maxHp);step(s,2);expect(h.weaponIndex).toBe(1);});
test('skill use and starting a weapon change are rejected during crossing or recall',()=>{const s=arena(),f=fiorre(s);f.crossing={from:{...f.pos},to:{x:3,y:4},elapsed:0,switched:false};expect(request(s,{type:'weapon',id:f.id,index:2}).ok).toBe(false);f.crossing=undefined;command(s,{type:'extract',id:f.id,via:'shadow'});expect(request(s,{type:'weapon',id:f.id,index:2}).ok).toBe(false);f.recall=undefined;expect(request(s,{type:'weapon',id:f.id,index:2}).ok).toBe(true);expect(command(s,{type:'skill',id:f.id}).ok).toBe(false);});
test('a cooldown card clears only the current skill, leaving other professions suspended',()=>{const s=arena(),f=fiorre(s);f.skillCd=9;expect(request(s,{type:'weapon',id:f.id,index:2}).ok).toBe(true);step(s,2);f.skillCd=8;const card=s.cards.find(c=>c.kind==='cooldown')!;expect(command(s,{type:'card',cardId:card.id,to:f.pos,targetId:f.id}).ok).toBe(true);expect(f.skillCd).toBe(0);expect(request(s,{type:'weapon',id:f.id,index:0}).ok).toBe(true);step(s,2);expect(f.skillCd).toBeCloseTo(7,5);});
test('a stationary direct movement blocked by terrain does not cancel a valid loadout',()=>{const s=arena(),h=s.units[0];h.pos={x:2.32,y:3};h.drawPos={...h.pos};s.tiles.find(t=>t.x===3&&t.y===3)!.obstacle=true;expect(request(s,{type:'weapon',id:h.id,index:1}).ok).toBe(true);command(s,{type:'direct',id:h.id,direction:{x:1,y:0}});step(s,1);expect(h.weaponIndex).toBe(1);expect(h.pos.x).toBeCloseTo(2.32);});
test('Fiorre may select a carried profession in initial preparation and on the node map',()=>{const s=createGame(),f=s.units[1];expect(request(s,{type:'weapon',id:f.id,index:2}).ok).toBe(true);expect(f.weaponIndex).toBe(2);s.phase='nodes';expect(request(s,{type:'weapon',id:f.id,index:0}).ok).toBe(true);expect(f.weaponIndex).toBe(0);});
test('same-source shields refresh their amount while independent casters stack shields',()=>{const s=arena();s.phase='briefing';request(s,{type:'configureSkill',id:'fiorre',skillId:'ward'});s.phase='battle';const f=fiorre(s),h=s.units[0];h.hp=100;command(s,{type:'skill',id:f.id});step(s,2);const first=h.statuses.filter(t=>t.kind==='shield');expect(first).toHaveLength(1);expect(first[0].power).toBe(108);f.skillCd=0;command(s,{type:'skill',id:f.id});step(s,2);expect(h.statuses.filter(t=>t.kind==='shield')).toHaveLength(1);expect(h.statuses.find(t=>t.kind==='shield')?.power).toBe(108);command(s,{type:'clone',id:f.id,to:{x:2,y:4}});const c=s.units.at(-1)!;c.skillCd=0;command(s,{type:'skill',id:c.id});step(s,1.1);expect(h.statuses.filter(t=>t.kind==='shield')).toHaveLength(2);});
test('Fiorre shadow advances only her equipped skill and never applies off-field skill effects',()=>{const s=arena(),f=fiorre(s);f.skillCd=0;command(s,{type:'skill',id:f.id});expect(request(s,{type:'weapon',id:f.id,index:2}).ok).toBe(true);step(s,2);f.skillCd=10;s.units[0].hp=50;command(s,{type:'extract',id:f.id,via:'shadow'});step(s,3);expect(f.life).toBe('withdrawn');expect(f.skillCd).toBeLessThan(10);expect(s.units[0].hp).toBe(50);expect(request(s,{type:'weapon',id:f.id,index:0}).ok).toBe(false);});
test('new expedition clears cultivation but retains unlock settings and existing injuries',()=>{const s=arena(),f=fiorre(s);request(s,{type:'unlockPreset',preset:'expanded'});expect(request(s,{type:'upgradeSkill',id:f.id,kind:'stage',expectedLevel:0}).ok).toBe(true);f.hp=37;f.weapons[0].durability=12;expect(request(s,{type:'abandon'}).ok).toBe(true);expect(request(s,{type:'newExpedition'}).ok).toBe(true);s.economy.account.vitality=100;expect(command(s,{type:'carry',gold:0,vitality:80}).ok).toBe(true);expect(f.hp).toBe(37);expect(f.weapons[0].durability).toBe(12);expect(request(s,{type:'upgradeSkill',id:f.id,kind:'stage',expectedLevel:0}).ok).toBe(true);});
test('upgrading during a timed cast preserves its damage snapshot until the next cast',()=>{const s=arena(),f=fiorre(s),h=s.units[0];h.hp=10;expect(command(s,{type:'skill',id:f.id}).ok).toBe(true);expect(request(s,{type:'upgradeSkill',id:f.id,kind:'stage',expectedLevel:0}).ok).toBe(true);step(s,1.1);expect(h.hp).toBe(170);step(s,1);expect(h.hp).toBe(170);f.skillCd=0;command(s,{type:'skill',id:f.id});step(s,1.1);expect(h.hp).toBe(360);});
test('cultivation persists through node reentry while all learned skill cooldowns restart empty',()=>{const s=arena(),f=fiorre(s);expect(request(s,{type:'upgradeSkill',id:f.id,kind:'stage',expectedLevel:0}).ok).toBe(true);f.hp=71;f.skillCd=0;s.crystalHp=0;step(s,.05);command(s,{type:'continue'});command(s,{type:'enter',node:1});expect(f.hp).toBe(71);expect(f.skillCd).toBe(f.skillMax);expect(request(s,{type:'upgradeSkill',id:f.id,kind:'stage',expectedLevel:0}).ok).toBe(false);expect(request(s,{type:'upgradeSkill',id:f.id,kind:'stage',expectedLevel:1}).ok).toBe(true);});
test('death clears an unfinished weapon change without changing weapons or reviving the unit',()=>{const s=arena(),g=s.units[2];g.life='active';g.hp=1;request(s,{type:'weapon',id:g.id,index:1});g.statuses=[{kind:'poison',remaining:1,power:10000}];step(s,1);expect(g.life).toBe('downed');expect(g.loadout).toBeUndefined();expect(g.weaponIndex).toBe(0);expect(request(s,{type:'upgradeSkill',id:g.id,kind:'stage',expectedLevel:0}).ok).toBe(false);expect(g.life).toBe('downed');});
test('cancelled weapon change leaves the interrupted timed skill on cooldown',()=>{const s=arena(),h=s.units[0];h.skillCd=0;command(s,{type:'skill',id:h.id});expect(h.skillTime).toBe(8);request(s,{type:'weapon',id:h.id,index:1});expect(h.skillTime).toBe(0);expect(h.skillCd).toBe(18);command(s,{type:'move',id:h.id,to:{x:2,y:4}});expect(h.loadout).toBeUndefined();expect(h.skillTime).toBe(0);expect(h.skillCd).toBe(18);});
test('Fiorre area heal ignores a wall but cantor damage respects the same wall',()=>{const s=arena(),f=fiorre(s),h=s.units[0];s.tiles.find(t=>t.x===4&&t.y===3)!.obstacle=true;h.pos={x:5,y:3};h.drawPos={...h.pos};h.hp=10;command(s,{type:'skill',id:f.id});step(s,1.1);expect(h.hp).toBe(170);request(s,{type:'weapon',id:f.id,index:2});step(s,1);f.skillCd=0;const e=enemy(s,{x:5,y:3}),hp=e.hp;command(s,{type:'skill',id:f.id});step(s,1.1);expect(e.hp).toBe(hp);expect(e.statuses.some(t=>t.kind==='slow')).toBe(false);});
test('new regeneration and defense branches produce real healing and reduce incoming damage',()=>{const s=arena(),f=fiorre(s),h=s.units[0];for(const branch of ['shelter','afterglow'])expect(request(s,{type:'upgradeSkill',id:f.id,kind:'branch',branch,expectedLevel:0}).ok).toBe(true);h.hp=10;command(s,{type:'skill',id:f.id});step(s,1.1);const after=h.hp;expect(after).toBeGreaterThanOrEqual(170);step(s,.5);expect(h.hp).toBeGreaterThan(after);expect(h.statuses.find(t=>t.kind==='defense')?.power).toBeCloseTo(.12);h.statuses=[...h.statuses.filter(t=>t.kind==='defense'),{kind:'poison',remaining:1,power:100}];const before=h.hp;step(s,.5);expect(h.hp).toBeCloseTo(before-44,5);});
test('cantor slow decreases actual enemy movement rather than only adding a status label',()=>{const a=arena(),b=arena();for(const s of [a,b]){s.units.forEach(u=>u.life='reserve');const e=enemy(s,{x:8,y:3});e.speed=.85;e.route=[{x:8,y:3},{x:9,y:3}];e.routeIndex=1;e.enemyMotion='return';e.returnPoint={x:9,y:3};e.path=[{x:9,y:3}];}a.units.at(-1)!.statuses=[{kind:'slow',remaining:2,power:.25}];step(a,.5);step(b,.5);expect(a.units.at(-1)!.pos.x-8).toBeCloseTo((b.units.at(-1)!.pos.x-8)*.75,5);});
test('direct movement into a layer transition cancels loadout before its fade completes',()=>{const s=arena(),h=s.units[0];h.pos={x:2.3,y:3};h.drawPos={...h.pos};s.tiles.filter(t=>t.x>=3).forEach(t=>t.layer=1);request(s,{type:'weapon',id:h.id,index:1});command(s,{type:'direct',id:h.id,direction:{x:1,y:0}});step(s,.2);expect(h.loadout).toBeUndefined();step(s,1);expect(h.weaponIndex).toBe(0);});
test('new expedition cannot reveal an unseen enemy through a reused enemy identifier',()=>{const s=arena();s.mode='dark';s.reveals={'enemy-reused:hunter':1000};command(s,{type:'abandon'});command(s,{type:'newExpedition'});command(s,{type:'carry',gold:0,vitality:0});s.units[0].light=0;const e=enemy(s,{x:3,y:4});e.id='enemy-reused';expect(canHit(s,s.units[0],e)).toBe(false);});
test('entering a node clears previous reveal rights before its clock starts again',()=>{const s=arena();s.mode='dark';s.phase='nodes';s.reveals={'enemy-reused:hunter':1000};command(s,{type:'enter',node:1});s.units[0].light=0;const e=enemy(s,{x:3,y:4});e.id='enemy-reused';expect(canHit(s,s.units[0],e)).toBe(false);});
test('range previews use the active cast snapshot and show the upgraded radius only after it ends',()=>{const s=arena(),f=fiorre(s),r=s.units[3];r.life='active';r.pos={x:6,y:4};r.drawPos={...r.pos};r.hp=10;command(s,{type:'skill',id:f.id});expect(request(s,{type:'upgradeSkill',id:f.id,kind:'branch',branch:'reach',expectedLevel:0}).ok).toBe(true);expect(skillRangeTiles(s,f)).not.toContainEqual({x:6,y:4});step(s,1.1);expect(r.hp).toBe(10);step(s,1);expect(skillRangeTiles(s,f)).toContainEqual({x:6,y:4});f.skillCd=0;command(s,{type:'skill',id:f.id});step(s,1.1);expect(r.hp).toBe(170);});
