import {describe,it,expect} from 'vitest';
import {createGame} from '../src/core/engine';
import {buyUpgrade,configureSkill,initializeProfile,initializeSkills} from '../src/core/progression';
import {requestWeapon} from '../src/core/loadout';
import {resolveSkill,SKILL_CATALOG} from '../src/core/skill-catalog';
const setup=()=>{const s=createGame();initializeProfile(s);const u=s.units.find(a=>a.id==='fiorre')!;initializeSkills(u,s.profile);s.fragments=1000;return {s,u};};
const twice=(s:ReturnType<typeof createGame>,u:ReturnType<typeof createGame>['units'][number],kind:'stage'|'branch',branch?:string)=>{expect(buyUpgrade(s,u,kind,branch,0).ok).toBe(true);expect(buyUpgrade(s,u,kind,branch,1).ok).toBe(true);};
describe('resolved prototype builds',()=>{
 it('every two-branch pairing remains purchasable at each stage for all three demonstration skills',()=>{for(const id of ['prayer','ward','bell'] as const){const def=SKILL_CATALOG[id];for(let stage=0;stage<=2;stage++)for(let a=0;a<3;a++)for(let b=a+1;b<3;b++){const {s,u}=setup();if(id==='bell')expect(requestWeapon(s,u,2).ok).toBe(true);else expect(configureSkill(s,u,id).ok).toBe(true);for(let tier=0;tier<stage;tier++)expect(buyUpgrade(s,u,'stage',undefined,tier).ok).toBe(true);twice(s,u,'branch',def.branches[a].id);twice(s,u,'branch',def.branches[b].id);expect(u.skillStates![id].stage).toBe(stage);expect(Object.values(u.skillStates![id].branches)).toEqual([2,2]);expect(s.fragments).toBe(1000-64-(stage===2?64:stage===1?24:0));const balance=s.fragments;expect(buyUpgrade(s,u,'branch',def.branches[3-a-b].id,0).ok).toBe(false);expect(s.fragments).toBe(balance);expect(resolveSkill(u).id).toBe(id);expect(u.role).toBe('fiorre');}}});
 it('prayer combines both highest selected branches with the latest stage without old-tier stacking',()=>{const {s,u}=setup();twice(s,u,'branch','reach');twice(s,u,'branch','shelter');twice(s,u,'stage');const value=resolveSkill(u);expect(value.range).toBe(4.6);expect(value.heal).toBe(220);expect(value.defense).toBe(.22);expect(value.defenseDuration).toBe(6);expect(value.cooldown).toBe(16);expect(value.pulseAt).toBe(1);expect(value.pulsePeriod).toBe(0);expect(resolveSkill(u)).toEqual(value);});
 it('ward regeneration duration follows the combined longer shield and max stage uses only latest ratio',()=>{const {s,u}=setup();configureSkill(s,u,'ward');twice(s,u,'branch','longwatch');twice(s,u,'branch','warmth');twice(s,u,'stage');const value=resolveSkill(u);expect(value.shieldBase).toBe(60);expect(value.missingHpScale).toBe(.5);expect(value.shieldDuration).toBe(10);expect(value.regenDuration).toBe(10);expect(value.regen).toBe(8);expect(value.range).toBe(2.5);});
 it('cantor combines a stun branch with ally healing without altering Fiorre identity or old healer build',()=>{const {s,u}=setup();twice(s,u,'branch','reach');u.life='reserve';expect(requestWeapon(s,u,2).ok).toBe(true);twice(s,u,'branch','silence');twice(s,u,'branch','mercy');twice(s,u,'stage');const value=resolveSkill(u);expect(value.power).toBe(75);expect(value.slow).toBe(.35);expect(value.stun).toBe(.7);expect(value.allyHeal).toBe(40);expect(value.cooldown).toBe(18);expect(u.role).toBe('fiorre');expect(requestWeapon(s,u,0).ok).toBe(true);expect(resolveSkill(u).range).toBe(4.6);expect(resolveSkill(u).stun).toBe(0);});
});
