import {expect,test} from 'vitest';
import {createGame,command,step} from '../src/core/engine';
import {updateVision} from '../src/core/visibility';
import {standaloneDefinition} from '../src/core/standalone-exploration';
import map from '../src/core/dark-dungeon-map.json';
import {enemyAlert} from '../src/enemy-alerts';
import {updateExplorationEnemy} from '../src/core/exploration';
function run(){const s=createGame();expect(command(s,{type:'selectJourney',journey:'exploration',seed:18}).ok).toBe(true);expect(command(s,{type:'selectExplorationCompanion',id:'fiorre'}).ok).toBe(true);expect(command(s,{type:'carry',gold:0,vitality:0}).ok).toBe(true);return s;}
test('standalone selection enters exploration directly; safe exit settles once without an objective',()=>{const s=run();expect(s.phase).toBe('battle');expect(s.ruleset).toBe('exploration');expect(s.exploration!.definition.victoryCondition).toBe('exit');expect(s.waves).toEqual([]);expect(s.exploration!.definition.points.filter(p=>p.kind==='campfire')).toHaveLength(3);s.units=s.units.filter(u=>u.team==='ally');for(const u of s.units)if(u.life==='active'){u.pos={...s.goal};u.ready=0;}expect(command(s,{type:'exitExploration'}).ok).toBe(true);expect(s.result).toBe('victory');expect(s.phase).toBe('ended');expect(s.economy.active).toBe(false);expect(command(s,{type:'exitExploration'}).ok).toBe(false);});
test('campfire rejects combat without consumption, restores living bodies once and keeps durability and death',()=>{const s=run(),p=s.exploration!.definition.points.find(p=>p.kind==='campfire')!,h=s.units.find(u=>u.id==='hunter')!,f=s.units.find(u=>u.id==='fiorre')!,g=s.units.find(u=>u.id==='ines')!,r=s.units.find(u=>u.id==='ranger')!;s.units=s.units.filter(u=>u.team==='ally');h.pos={...p.pos};updateVision(s,true);h.hp=10;h.stress=65;h.posture=1;h.grayHp=20;h.statuses=[{kind:'poison',power:3,remaining:10}];h.weapons[0].durability=4;for(const st of Object.values(h.skillStates!))st.cd=12;g.life='dead';r.life='rescued';f.life='rescued';s.rescueRestrictions={[r.id]:s.node,[f.id]:s.node};s.context='explorationBattle';expect(command(s,{type:'interactExploration',id:p.id}).ok).toBe(false);expect(h.hp).toBe(10);s.context='explorationIdle';expect(command(s,{type:'interactExploration',id:p.id}).ok).toBe(true);expect(h.hp).toBe(10+h.maxHp*.5);expect(h.stress).toBe(25);expect(h.posture).toBe(h.maxPosture);expect(h.grayHp).toBe(0);expect(h.statuses).toEqual([]);expect(Object.values(h.skillStates!).every(st=>st.cd===0)).toBe(true);expect(h.weapons[0].durability).toBe(4);expect(g.life).toBe('dead');expect(r.life).toBe('rescued');expect(s.rescueRestrictions[r.id]).toBe(s.node);expect(f.life).not.toBe('rescued');expect(s.rescueRestrictions[f.id]).toBeUndefined();expect(command(s,{type:'interactExploration',id:p.id}).ok).toBe(false);h.life='respawning';h.respawnTimer=.01;step(s,.1);expect(Math.hypot(h.pos.x-p.pos.x,h.pos.y-p.pos.y)).toBeLessThanOrEqual(2);});
test('seeded encounters are reproducible, vary across seeds and keep safe event buffers',()=>{const a=standaloneDefinition(1),b=standaloneDefinition(2);expect(a.enemies).toEqual(standaloneDefinition(1).enemies);expect(a.enemies).not.toEqual(b.enemies);for(const d of [a,b])for(const e of d.enemies){expect(d.tiles.find(t=>t.x===e.pos.x&&t.y===e.pos.y)?.obstacle).toBe(false);for(const p of [d.entry,d.exit,...d.points.map(p=>p.pos)])expect(Math.hypot(e.pos.x-p.x,e.pos.y-p.y)).toBeGreaterThan(5);}});
test('imported room centres and all event points belong to the entry connected component',()=>{const d=standaloneDefinition(18),open=new Set(d.tiles.filter(t=>!t.obstacle).map(t=>t.x+','+t.y)),seen=new Set<string>(),queue=[d.entry];for(let i=0;i<queue.length;i++){const p=queue[i],key=p.x+','+p.y;if(seen.has(key))continue;seen.add(key);for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const n={x:p.x+dx,y:p.y+dy},k=n.x+','+n.y;if(open.has(k)&&!seen.has(k))queue.push(n);}}for(const p of [d.exit,...d.points.map(p=>p.pos),...map.rooms.map(r=>r.pos)])expect(seen.has(p.x+','+p.y)).toBe(true);expect(map.rooms).toHaveLength(20);expect(d.enemies.every(e=>e.enemyProfileId&&!(e.patrol?.length))).toBe(true);});
test('campfires refuse distant interaction and nearby danger without consuming their use',()=>{const s=run(),p=s.exploration!.definition.points[1],h=s.units[0];expect(command(s,{type:'interactExploration',id:p.id}).ok).toBe(false);h.pos={...p.pos};const e=s.units.find(u=>u.team==='enemy')!;e.pos={...p.pos};e.pursuitTargetId=h.id;expect(command(s,{type:'interactExploration',id:p.id}).ok).toBe(false);expect(s.exploration!.memory.mechanisms).toEqual([]);});
test('walking into the safe exit completes automatically, while downed allies prevent automatic abandonment',()=>{const s=run();s.units=s.units.filter(u=>u.team==='ally');for(const u of s.units){u.pos={...s.goal};u.drawPos={...u.pos};u.ready=0;}const a=s.units[1];a.life='downed';a.hp=0;a.downTimer=40;step(s,.1);expect(s.phase).toBe('battle');a.life='withdrawn';step(s,.1);expect(s.phase).toBe('ended');expect(s.result).toBe('victory');});
