import {test,expect} from '@playwright/test';
import {writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
test('120 summon removals release private canvases and return GPU resources to warm baseline',async({page})=>{
 await page.goto('/');await expect(page.getByRole('button',{name:'进入战斗',exact:true})).toBeEnabled();
 const data=await page.evaluate(async()=>{const {BattleScene}=await import('/src/view/scene.ts' as string),{createGame,command}=await import('/src/core/engine.ts' as string);const host=document.createElement('div');Object.assign(host.style,{position:'fixed',width:'400px',height:'300px'});document.body.append(host);const scene=new BattleScene(host),s=createGame(),o={selectedId:null,hover:null,path:[],range:[],deployTiles:[],targeting:false};s.phase='battle';s.fragments=10000;scene.update(s,o,0);const memory=()=>({...((scene as any).renderer.info.memory)}),base={actors:scene.unitVisuals.size,memory:memory()},rows=[];let released:any;
 try{for(let cycle=0;cycle<5;cycle++){let count=0;for(let y=2;y<=6;y++)for(let x=2;x<=6;x++)if(command(s,{type:'clone',id:'hunter',to:{x,y}}).ok)count++;scene.update(s,o,0);const peak={actors:scene.unitVisuals.size,memory:memory()};const copies=s.units.filter((u:any)=>u.cloneOf);released=scene.unitVisuals.get(copies[0].id)!;for(const c of copies)command(s,{type:'destroyClone',id:c.id});scene.update(s,o,0);rows.push({count,peak,after:{actors:scene.unitVisuals.size,memory:memory()}});}return {base,rows,canvases:[released.barCanvas.width,released.buffCanvas.width,released.spine?.canvas.width],balance:s.fragments};}finally{scene.dispose();host.remove();}});
 writeFileSync(fileURLToPath(new URL('../../记录/验证/T-010/resource-pressure.json',import.meta.url)),JSON.stringify(data,null,2));expect(data.canvases).toEqual([0,0,0]);expect(data.balance).toBe(7600);for(const r of data.rows){expect(r.count).toBe(24);expect(r.after).toEqual(data.base);}
});
