import {prepareRegression} from './browser-helpers';
import {test,expect,type Page} from '@playwright/test';
async function start(page:Page){await page.goto('/');await prepareRegression(page);await page.getByRole('button',{name:'进入战斗',exact:true}).click();await page.evaluate(()=>{const s=(window as any).prototype.state;s.waves=[];s.waveState=null;s.totalEnemies=999;s.units.forEach((u:any)=>u.ready=0);});}
async function summon(page:Page,p={x:3,y:4}){await page.locator('[data-clone="hunter"]').click();const point=await page.evaluate(p=>(window as any).prototype.project(p),p);await page.mouse.click(point.x,point.y);await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.filter((u:any)=>u.cloneOf).length)).toBeGreaterThan(0);}
for(const viewport of [{width:1440,height:900},{width:1000,height:720}])test(`copy list and readonly build support single destroy at ${viewport.width}`,async({page})=>{
 await page.setViewportSize(viewport);await start(page);await summon(page);await summon(page,{x:4,y:4});await page.locator('[data-unit="hunter"]').click();await expect(page.locator('[data-copy-select]')).toHaveCount(2);await page.locator('[data-copy-select]').first().click();await expect(page.locator('.clone-build')).toContainText('出生构筑');await expect(page.locator('#unit-detail')).toContainText('来源：猎人');await expect(page.locator('#unit-detail [data-action="build"]')).toHaveCount(0);await page.screenshot({path:'../记录/验证/T-011/detail-'+viewport.width+'.png'});await page.keyboard.press('AltLeft');await page.locator('[data-destroy-clone]').click();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.filter((u:any)=>u.cloneOf).length)).toBe(1);await expect(page.locator('#time-mode')).toHaveText('');await expect(page.locator('#speed-btn')).toHaveText('2×');await page.keyboard.press('1');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.interaction.selectedId)).toBe('hunter');
});
test('orphaned summon aim returns to default speed when source leaves',async({page})=>{await start(page);await page.keyboard.press('AltLeft');await page.locator('[data-clone="hunter"]').click();await expect(page.locator('#time-mode')).toContainText('0.1');await page.evaluate(()=>(window as any).prototype.state.units[0].life='withdrawn');await expect(page.locator('#time-mode')).toHaveText('');await expect(page.locator('#speed-btn')).toHaveText('2×');});
test('repeated summon and removal releases actor instances and canvas textures',async({page})=>{
 await start(page);const counts=await page.evaluate(async()=>{const {BattleScene}=await import('/src/view/scene.ts' as string),{createGame,command}=await import('/src/core/engine.ts' as string);const host=document.createElement('div');Object.assign(host.style,{position:'fixed',width:'400px',height:'300px',top:'0'});document.body.append(host);const scene=new BattleScene(host),s=createGame(),overlay={selectedId:null,hover:null,path:[],range:[],deployTiles:[],targeting:false};command(s,{type:'carry',gold:0,vitality:0});s.phase='battle';s.fragments=1000;scene.update(s,overlay,0);const base=scene.unitVisuals.size,rows=[];for(let i=0;i<12;i++){command(s,{type:'clone',id:'hunter',to:{x:3,y:4}});scene.update(s,overlay,0);const c=s.units.find((u:any)=>u.cloneOf)!;command(s,{type:'destroyClone',id:c.id});scene.update(s,overlay,0);rows.push(scene.unitVisuals.size);}scene.dispose();host.remove();return {base,rows};});expect(counts.rows).toEqual(Array(12).fill(counts.base));
});

test('drag summon creates exactly one instance and charges once',async({page})=>{await start(page);const b=await page.locator('[data-clone="hunter"]').boundingBox();const p=await page.evaluate(()=>(window as any).prototype.project({x:3,y:4}));await page.mouse.move(b!.x+b!.width/2,b!.y+b!.height/2);await page.mouse.down();await page.mouse.move(p.x,p.y,{steps:10});await page.mouse.up();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.filter((u:any)=>u.cloneOf).length)).toBe(1);expect(await page.evaluate(()=>(window as any).prototype.state.fragments)).toBe(20);});
test('source gone and upgraded old/new builds stay readable in existing sidebar',async({page})=>{await start(page);await page.evaluate(async()=>{const {command}=await import('/src/core/engine.ts' as string);const s=(window as any).prototype.state;s.fragments=100;const u=s.units[2];command(s,{type:'deploy',id:u.id,to:{x:3,y:4},facing:'east'});command(s,{type:'clone',id:u.id,to:{x:4,y:4}});command(s,{type:'upgradeSkill',id:u.id,kind:'stage',expectedLevel:0});command(s,{type:'clone',id:u.id,to:{x:5,y:4}});u.life='withdrawn';});await page.locator('[data-unit="ines"]').click();await page.locator('[data-copy-select]').first().click();await expect(page.locator('.clone-build')).toContainText('来源：伊内丝');await expect(page.locator('.clone-build')).toContainText('进阶 0/2');await page.locator('[data-copy-select]').last().click();await expect(page.locator('.clone-build')).toContainText('进阶 1/2');await page.screenshot({path:'../记录/验证/T-011/clone-detail-1440.png'});});
test('late skeleton load cannot reattach to removed actor',async({page})=>{await start(page);const result=await page.evaluate(async()=>{const {BattleScene}=await import('/src/view/scene.ts' as string),{SpineVisual}=await import('/src/view/spine.ts' as string),{createGame,command}=await import('/src/core/engine.ts' as string);const host=document.createElement('div');Object.assign(host.style,{width:'400px',height:'300px',position:'fixed'});document.body.append(host);const scene=new BattleScene(host),s=createGame(),o={selectedId:null,hover:null,path:[],range:[],deployTiles:[],targeting:false};s.economy.account.vitality=20;command(s,{type:'carry',gold:0,vitality:20});s.phase='battle';scene.update(s,o,0);const originalPrepared=SpineVisual.prepared,originalLoad=SpineVisual.load;let resolve:any;const visual=originalPrepared('Galore')!;SpineVisual.prepared=()=>null;SpineVisual.load=()=>new Promise(r=>resolve=r);try{command(s,{type:'clone',id:'hunter',to:{x:3,y:4}});scene.update(s,o,0);const c=s.units.find((u:any)=>u.cloneOf)!,actor=scene.unitVisuals.get(c.id)!;command(s,{type:'destroyClone',id:c.id});scene.update(s,o,0);resolve(visual);await new Promise(r=>setTimeout(r,0));return {absent:!scene.unitVisuals.has(c.id),children:actor.group.children.length,attached:!!actor.spine};}finally{SpineVisual.prepared=originalPrepared;SpineVisual.load=originalLoad;scene.dispose();host.remove();}});expect(result).toEqual({absent:true,children:0,attached:false});});
