import {test,expect} from '@playwright/test';
import {writeFileSync,mkdirSync} from 'node:fs';

test('debug explains task lifetime and releases comfort and contribution graphics',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.locator('[data-action="carry"]').click();await page.locator('[data-action="start"]').click();await page.locator('[data-action="pause"]').click();await page.locator('[data-action="debug"]').click();
 await page.evaluate(async()=>{const p=(window as any).prototype,s=p.state,{step}=await import('/src/core/engine.ts' as string);s.waveState=null;s.waves=[];s.totalEnemies=999;s.mode='standard';s.node=1;s.width=14;s.height=10;s.tiles=Array.from({length:140},(_,i)=>({x:i%14,y:Math.floor(i/14),layer:0,obstacle:false}));for(const u of s.units){u.life='reserve';u.ai=undefined;u.ready=0;}const g=s.units.find((u:any)=>u.id==='ines');g.life='active';g.pos={x:4,y:4};g.drawPos={...g.pos};g.attackTimer=100;g.weapons[0].range=1;const e={...structuredClone(g),id:'t016-foe',team:'enemy',role:'melee',speed:0,block:0,pos:{x:4,y:2.1},drawPos:{x:4,y:2.1},route:[],path:[],enemyMotion:'route',ai:undefined};s.units.push(e);step(s,.3);e.life='dead';step(s,.05);});
 await expect(page.locator('#debug-readings')).toContainText('settle');await expect(page.locator('#debug-readings')).toContainText('舒适区');await expect(page.locator('#debug-readings')).toContainText('任务目标失效');
 const cycles=await page.evaluate(()=>{const p=(window as any).prototype,s=p.state,o={selectedId:null,hover:null,path:[],range:[],deployTiles:[],targeting:false},rows=[];for(let i=0;i<6;i++){p.scene.update(s,{...o,debugAutonomy:true},0,0);const on={...p.scene.renderer.info.memory};p.scene.update(s,o,0,0);rows.push({on,off:{...p.scene.renderer.info.memory}});}return rows;});
 expect(cycles[0].on.geometries).toBeGreaterThan(cycles[0].off.geometries);expect(cycles.map(c=>c.off)).toEqual(Array(6).fill(cycles[0].off));expect(errors).toEqual([]);mkdirSync('../记录/验证/T-016',{recursive:true});writeFileSync('../记录/验证/T-016/debug-resources.json',JSON.stringify({cycles,errors},null,2));await page.screenshot({path:'../记录/验证/T-016/task-settle.png'});
});
