import {test,expect} from 'vitest';
import {createGame,command,step,canHit} from '../src/core/engine';
import {distance} from '../src/core/spatial';
import {currentSkill} from '../src/core/progression';
import type {GameState,Unit} from '../src/core/types';

function arena(){const s=createGame();command(s,{type:'carry',gold:0,vitality:0});s.phase='battle';s.waveState=null;s.waves=[];s.totalEnemies=999;s.width=14;s.height=10;s.tiles=Array.from({length:140},(_,i)=>({x:i%14,y:Math.floor(i/14),layer:0,obstacle:false}));for(const u of s.units){u.life='reserve';u.ready=0;u.path=[];u.destination=null;}return s;}
function place(u:Unit,x:number,y:number,range=1){u.life='active';u.ready=0;u.pos={x,y};u.drawPos={...u.pos};u.weapons[u.weaponIndex].range=range;u.attackTimer=100;}
function enemy(s:GameState,x:number,y:number,id:string){const e={...structuredClone(s.units[0]),id,team:'enemy' as const,role:'melee' as const,cloneOf:undefined,life:'active' as const,pos:{x,y},drawPos:{x,y},speed:0,block:0,attackTimer:100,route:[],path:[],destination:null,enemyMotion:'route' as const,ai:undefined};e.weapons=[{...e.weapons[0],remote:false,range:1,damage:0}];s.units.push(e);return e;}

test('P1 broken posture cancels an approach and refuses new move/direct commands',()=>{const s=arena(),g=s.units.find(u=>u.id==='ines')!;place(g,4,4);enemy(s,5.9,4,'e');step(s,.1);expect(g.path.length).toBeGreaterThan(0);g.posture=0;g.postureDelay=2;const p={...g.pos};step(s,.1);expect(g.pos).toEqual(p);expect(g.path).toEqual([]);expect(command(s,{type:'move',id:g.id,to:{x:3,y:4}}).reason).toMatch(/架势/);expect(command(s,{type:'direct',id:g.id,direction:{x:1,y:0}}).ok).toBe(false);});
test('P2 broken posture stops Return and recovers through a fresh decision',()=>{const s=arena(),g=s.units.find(u=>u.id==='ines')!;place(g,4.9,4);g.ai={anchor:{x:4,y:4},intent:'hold',phase:'hold',nextDecision:0,movedAt:-10,commandUntil:0,directTravel:0};step(s,.1);expect(g.ai.phase).toBe('return');g.posture=0;g.postureDelay=2;const p={...g.pos};step(s,.2);expect(g.pos).toEqual(p);expect(g.path).toEqual([]);g.posture=1;step(s,.5);expect(g.pos.x).toBeLessThan(p.x);});
test('P3 broken posture pauses exploration follow without losing recovery',()=>{const s=createGame();command(s,{type:'carry',gold:0,vitality:0});s.completed.push(1);s.phase='nodes';command(s,{type:'enter',node:4});const h=s.units[0],g=s.units.find(u=>u.id==='ines')!;place(h,7,16);place(g,3,16);s.units=s.units.filter(u=>u.team==='ally');g.posture=0;g.postureDelay=2;const p={...g.pos};step(s,.5);expect(g.pos).toEqual(p);g.posture=1;step(s,.5);expect(distance(g.pos,h.pos)).toBeLessThan(distance(p,h.pos));});
test('P4 broken posture retains regroup request and replans after recovery',()=>{const s=arena(),h=s.units[0],g=s.units.find(u=>u.id==='ines')!;place(h,6,4);place(g,3,4);expect(command(s,{type:'party',kind:'regroup'}).ok).toBe(true);g.posture=0;g.postureDelay=2;const p={...g.pos};step(s,.5);expect(g.pos).toEqual(p);expect(g.partyTask?.kind).toBe('regroup');g.posture=1;step(s,.5);expect(g.pos.x).toBeGreaterThan(p.x);});
test('S1-S2 shieldguard braces against multiple enemies and target death alone does not reposition',()=>{const s=arena(),g=s.units.find(u=>u.id==='ines')!;place(g,4,4);const a=enemy(s,4.7,4,'a'),b=enemy(s,4,4.7,'b');a.engagement={targetId:g.id,anchor:{...g.pos}};b.engagement={targetId:g.id,anchor:{...g.pos}};step(s,.1);const p={...g.pos};expect(g.ai?.phase).toBe('brace');a.life='dead';step(s,.6);expect(g.pos).toEqual(p);expect(g.ai?.phase).toBe('brace');});
test('S3 direct threat that cannot be countered permits a discrete adjustment then braces',()=>{const s=arena(),g=s.units.find(u=>u.id==='ines')!;place(g,4,4);const e=enemy(s,5.8,4,'e');e.engagement={targetId:g.id,anchor:{...g.pos}};expect(canHit(s,g,e)).toBe(false);step(s,.4);expect(g.pos.x).toBeGreaterThan(4);step(s,.5);expect(canHit(s,g,e)).toBe(true);expect(g.ai?.phase).toBe('brace');});
test('S4 adding a third reachable target does not move an already effective shieldguard',()=>{const s=arena(),g=s.units.find(u=>u.id==='ines')!;place(g,4,4);enemy(s,4.8,4,'a');enemy(s,4,4.8,'b');step(s,.1);const p={...g.pos};enemy(s,3.2,4,'c');step(s,.5);expect(g.pos).toEqual(p);expect(g.ai?.phase).toBe('brace');});
test('S1 four enemies surrounding the shieldguard cause no left-right locomotion for eight simulated seconds',()=>{const s=arena(),g=s.units.find(u=>u.id==='ines')!;place(g,4,4);g.attackTimer=0;for(const [i,p] of [{x:4.8,y:4},{x:3.2,y:4},{x:4,y:4.8},{x:4,y:3.2}].entries()){const e=enemy(s,p.x,p.y,'crowd-'+i);e.hp=e.maxHp=100000;e.engagement={targetId:g.id,anchor:{...g.pos}};}const start={...g.pos};for(let i=0;i<160;i++){step(s,.05);expect(g.pos).toEqual(start);expect(g.ai?.phase).toBe('brace');}});
test('broken posture preserves stationary attacks and an allowed skill',()=>{const s=arena(),h=s.units[0],f=s.units.find(u=>u.id==='fiorre')!;place(h,4,4);const e=enemy(s,4.7,4,'e');h.posture=0;h.postureDelay=3;h.attackTimer=0;const hp=e.hp;step(s,.5);expect(e.hp).toBeLessThan(hp);expect(h.stagger).toBe(0);place(f,6,4);f.weaponIndex=0;f.posture=0;f.postureDelay=3;f.hp=100;f.skillId='prayer';f.skillCd=0;currentSkill(f).cd=0;expect(command(s,{type:'skill',id:f.id})).toMatchObject({ok:true});});
test('broken posture retains walking recall and replans when posture returns',()=>{const s=arena(),h=s.units[0],g=s.units.find(u=>u.id==='ines')!;place(h,6,4);place(g,3,4);expect(command(s,{type:'extract',id:g.id,via:'shadow'}).ok).toBe(true);g.posture=0;g.postureDelay=2;const p={...g.pos};step(s,.4);expect(g.pos).toEqual(p);expect(g.recall).toBeDefined();g.posture=1;step(s,.4);expect(g.pos.x).toBeGreaterThan(p.x);});
test('broken posture blocks walking but permits an already-in-range recall channel',()=>{const s=arena(),h=s.units[0],g=s.units.find(u=>u.id==='ines')!;place(h,4,4);place(g,3,4);g.posture=0;g.postureDelay=3;expect(command(s,{type:'extract',id:g.id,via:'shadow'}).ok).toBe(true);step(s,1.1);expect(g.life).toBe('withdrawn');});
test('an in-progress crossing finishes atomically before the broken-posture stop',()=>{const s=arena(),g=s.units.find(u=>u.id==='ines')!;place(g,4,4);g.crossing={from:{x:4,y:4},to:{x:4.5,y:4},elapsed:.2,switched:false};g.path=[{x:4.5,y:4},{x:5,y:4}];g.destination={x:5,y:4};g.posture=0;g.postureDelay=2;step(s,.6);expect(g.crossing).toBeUndefined();expect(g.pos).toEqual({x:4.5,y:4});step(s,.1);expect(g.pos).toEqual({x:4.5,y:4});expect(g.path).toEqual([]);});
test('enemy posture zero does not change its existing route locomotion',()=>{const s=arena(),e=enemy(s,4,4,'e');e.speed=2;e.posture=0;e.postureDelay=3;e.path=[{x:5,y:4}];e.route=[{x:5,y:4}];const p={...e.pos};step(s,.2);expect(e.pos.x).toBeGreaterThan(p.x);});
test('shieldguard holds for the release delay after its last attackable enemy leaves',()=>{const s=arena(),g=s.units.find(u=>u.id==='ines')!;place(g,4.8,4);g.ai={anchor:{x:4,y:4},intent:'hold',phase:'hold',nextDecision:0,movedAt:-10,commandUntil:0,directTravel:0};const e=enemy(s,5.5,4,'e');step(s,.1);expect(g.ai.phase).toBe('brace');e.life='dead';const p={...g.pos};step(s,.3);expect(g.pos).toEqual(p);expect(g.ai.phase).toBe('brace');step(s,.5);expect(g.pos.x).toBeLessThan(p.x);});
test('shieldguard blocks a recent ordinary reverse Return but permits it after 1.2 seconds',()=>{const s=arena(),g=s.units.find(u=>u.id==='ines')!;place(g,4.8,4);g.ai={anchor:{x:4,y:4},intent:'hold',phase:'hold',nextDecision:0,movedAt:-10,commandUntil:0,directTravel:0,lastAutoMoveAt:0,lastAutoMoveDirection:{x:1,y:0}};const p={...g.pos};step(s,.8);expect(g.pos).toEqual(p);step(s,1);expect(g.pos.x).toBeLessThan(p.x);});
test('loss of Brace duty permits a reverse Return after release even inside 1.2 seconds',()=>{const s=arena(),g=s.units.find(u=>u.id==='ines')!;place(g,4.8,4);g.ai={anchor:{x:4,y:4},intent:'hold',phase:'hold',nextDecision:0,movedAt:-10,commandUntil:0,directTravel:0,lastAutoMoveAt:0,lastAutoMoveDirection:{x:1,y:0}};const e=enemy(s,5.5,4,'e');step(s,.1);expect(g.ai.phase).toBe('brace');e.life='dead';const p={...g.pos};step(s,.7);expect(g.pos.x).toBeLessThan(p.x);});
test('a new direct threat that cannot be countered releases Brace despite another attackable foe',()=>{const s=arena(),g=s.units.find(u=>u.id==='ines')!;place(g,4,4);g.attackTimer=0;enemy(s,4,4.8,'near');step(s,.1);expect(g.ai?.phase).toBe('brace');const far=enemy(s,5.8,4,'far');far.engagement={targetId:g.id,anchor:{...g.pos}};expect(canHit(s,g,far)).toBe(false);const p={...g.pos};step(s,.3);expect(g.pos.x).toBeGreaterThan(p.x);expect(g.ai?.targetId).toBe(far.id);});
test('player movement clears Brace and reversal memory while broken posture still has final authority',()=>{const s=arena(),g=s.units.find(u=>u.id==='ines')!;place(g,4,4);enemy(s,4.7,4,'e');step(s,.1);expect(g.ai?.phase).toBe('brace');g.ai!.lastAutoMoveAt=s.time;g.ai!.lastAutoMoveDirection={x:1,y:0};expect(command(s,{type:'move',id:g.id,to:{x:3,y:4}}).ok).toBe(true);expect(g.ai?.phase).toBe('player');expect(g.ai?.braceUntil).toBeUndefined();expect(g.ai?.lastAutoMoveDirection).toBeUndefined();g.posture=0;g.postureDelay=2;expect(command(s,{type:'move',id:g.id,to:{x:3,y:5}}).ok).toBe(false);});
