import {test,expect,type Page} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';

const views=[[1920,1080],[1600,900],[1440,1000],[1280,720]];
async function tower(page:Page){await page.goto('/');await page.locator('[data-action="carry"]').click();await page.locator('[data-action="start"]').click();await page.locator('[data-action="pause"]').click();}
async function projection(page:Page){return page.evaluate(()=>{const p=(window as any).prototype,s=p.state,c=p.scene.camera;return {center:p.project({x:(s.width-1)/2,y:(s.height-1)/2}),corners:[{x:0,y:0},{x:s.width-1,y:0},{x:0,y:s.height-1},{x:s.width-1,y:s.height-1}].map(q=>p.project(q)),matrix:[...c.projectionMatrix.elements]};});}
for(const [width,height]of views)test(`full viewport centers the tower and fits the ground at ${width}x${height}`,async({page})=>{
 await page.setViewportSize({width,height});await tower(page);const p=await projection(page);const canvas=await page.locator('#scene canvas').boundingBox();expect(canvas).toEqual({x:0,y:0,width,height});expect(Math.abs(p.center.x-width/2)).toBeLessThan(1);expect(Math.abs(p.center.y-height/2)).toBeLessThan(2);expect(p.corners.every(q=>q.x>=0&&q.x<=width&&q.y>=0&&q.y<=height)).toBe(true);expect(Math.max(...p.corners.map(q=>q.x))-Math.min(...p.corners.map(q=>q.x))).toBeGreaterThan(width*.75);mkdirSync('../记录/验证/T-017',{recursive:true});writeFileSync(`../记录/验证/T-017/after-${width}x${height}.json`,JSON.stringify({viewport:[width,height],canvas,...p},null,2));await page.screenshot({path:`../记录/验证/T-017/after-${width}x${height}.png`});
});

test('visible HUD backgrounds consume input while transparent HUD space remains a world surface',async({page})=>{
 await tower(page);await page.evaluate(()=>{(window as any).scenePointerEvents=0;document.querySelector('#scene')!.addEventListener('pointerdown',()=>{(window as any).scenePointerEvents++;});});await page.mouse.click(12,20);expect(await page.evaluate(()=>(window as any).scenePointerEvents)).toBe(0);const dock=await page.locator('.roster-section').boundingBox();await page.mouse.click(dock!.x+3,dock!.y+12);expect(await page.evaluate(()=>(window as any).scenePointerEvents)).toBe(0);expect(await page.evaluate(()=>document.elementFromPoint(350,170)?.closest('#scene')!==null)).toBe(true);await page.mouse.click(350,170);expect(await page.evaluate(()=>(window as any).scenePointerEvents)).toBe(1);
});

test('captured roster drag released over HUD cannot deploy into the valid ground behind it',async({page})=>{
 await page.setViewportSize({width:1280,height:720});await tower(page);await page.evaluate(async()=>{const {step}=await import('/src/core/engine.ts' as string);step((window as any).prototype.state,10.1);});const drop=await page.evaluate(async()=>{const p=(window as any).prototype,s=p.state,u=s.units.find((u:any)=>u.id==='ines'),{canDeployAt}=await import('/src/core/engine.ts' as string);return s.tiles.filter((q:any)=>canDeployAt(s,q,u)).map((q:any)=>({...p.project(q),tile:q})).find((q:any)=>document.elementFromPoint(q.x,q.y)?.closest('.bottom-dock')&&p.scene.pick(q.x,q.y).tile);});expect(drop,'fixture must expose actual ground underneath the HUD').toBeTruthy();const from=await page.locator('[data-unit="ines"]').boundingBox();await page.mouse.move(from!.x+from!.width/2,from!.y+from!.height/2);await page.mouse.down();await page.mouse.move(drop.x,drop.y,{steps:12});await page.mouse.up();expect(await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ines').life)).toBe('reserve');
});

async function explore(page:Page){await page.goto('/');await page.locator('[data-action="carry"]').click();await page.evaluate(()=>{const s=(window as any).prototype.state;s.completed.push(1);s.phase='nodes';});await page.locator('[data-node="4"]').click();await page.locator('[data-action="pause"]').click();}
for(const mode of ['tower','explore'])test(`${mode} UI toggles and sale drag never change a static world's projection`,async({page})=>{
 await (mode==='tower'?tower(page):explore(page));const before=await projection(page),rows:any[]=[];const unchanged=async(label:string)=>{const after=await projection(page);expect(after.matrix).toEqual(before.matrix);expect(Math.abs(after.center.x-before.center.x)).toBeLessThan(.01);expect(Math.abs(after.center.y-before.center.y)).toBeLessThan(.01);rows.push({label,...after});};
 for(const action of ['backpack','debug']){await page.locator(`[data-action="${action}"]`).click();await unchanged(action+' on');await page.locator(`[data-action="${action}"]`).click();await unchanged(action+' off');}
 await page.getByRole('button',{name:'职业与构筑',exact:true}).click();await expect(page.locator('#build-panel')).toBeVisible();await unchanged('build on');await page.locator('[data-action="close-build"]').click();await unchanged('build off');
 await page.locator('[data-unit="hunter"]').click();await expect(page.locator('#unit-detail')).toBeVisible();await expect(page.locator('#world-skill [data-skill]')).toBeVisible();await unchanged('detail and world skill on');const skill=await page.evaluate(()=>{const p=(window as any).prototype,h=p.state.units[0],q=p.project(h.drawPos||h.pos),el=document.querySelector('#world-skill') as HTMLElement;return {q,left:parseFloat(el.style.left),top:parseFloat(el.style.top)};});expect(skill.left-skill.q.x).toBeCloseTo(22,3);expect(skill.top-skill.q.y).toBeCloseTo(-47,3);
 await page.keyboard.press('Tab');await expect(page.locator('#tactical-hand')).toHaveAttribute('aria-hidden','false');await page.locator('[data-card]').first().click();await expect(page.locator('#notice')).not.toBeEmpty();await unchanged('card aim and notice');await page.mouse.click(700,350,{button:'right'});await unchanged('detail and world skill off');
 await page.locator('[data-action="pause"]').click();const card=await page.locator('[data-card]').first().boundingBox(),sell=await page.locator('#sell-zone').boundingBox();await page.mouse.move(card!.x+card!.width/2,card!.y+card!.height/2);await page.mouse.down();await page.mouse.move(sell!.x+sell!.width/2,sell!.y+sell!.height/2,{steps:12});await expect(page.locator('#sell-zone')).toHaveClass(/selling/);await unchanged('sale drag');await page.mouse.click(700,350,{button:'right'});await page.mouse.up();await unchanged('sale cancel');writeFileSync(`../记录/验证/T-017/${mode}-ui-projection.json`,JSON.stringify(rows,null,2));
});

for(const reduced of [false,true])test(`exploration retains paused hunter follow and bounded companion offset, reduced=${reduced}`,async({page})=>{
 if(reduced)await page.emulateMedia({reducedMotion:'reduce'});await explore(page);await page.evaluate(()=>{const s=(window as any).prototype.state,h=s.units[0];h.pos={x:13,y:16};h.drawPos={...h.pos};});await expect.poll(()=>page.evaluate(()=>{const p=(window as any).prototype;return Math.abs(p.project({x:13,y:16}).x-innerWidth/2);})).toBeLessThan(3);
 await page.evaluate(()=>{const s=(window as any).prototype.state,g=s.units.find((u:any)=>u.id==='ines');g.life='active';g.ready=0;g.pos={x:23,y:16};g.drawPos={...g.pos};});await page.locator('[data-unit="ines"]').click();await expect.poll(()=>page.evaluate(()=>{const p=(window as any).prototype;return Math.abs(p.project({x:16,y:16}).x-innerWidth/2);})).toBeLessThan(3);const focus=await page.evaluate(()=>(window as any).prototype.scene.cameraFocus.x);expect(Number.isFinite(focus)).toBe(true);await page.screenshot({path:`../记录/验证/T-017/exploration-follow-${reduced}.png`});
});

test('workbench tower shares the full viewport fit and centered world',async({page})=>{
 await page.goto('/');await page.locator('[data-action="carry"]').click();await page.locator('[data-mode="workbench"]').click();await page.locator('[data-action="start"]').click();await page.locator('[data-action="pause"]').click();const p=await projection(page);expect(Math.abs(p.center.x-720)).toBeLessThan(1);expect(Math.abs(p.center.y-450)).toBeLessThan(2);expect(p.corners.every(q=>q.x>=0&&q.x<=1440&&q.y>=0&&q.y<=900)).toBe(true);await page.screenshot({path:'../记录/验证/T-017/workbench-fit.png'});
});
