import {test,expect,type Page} from '@playwright/test';
import {mkdirSync} from 'node:fs';
const evidence='../记录/验证/T-020';
async function promote(page:Page){await page.evaluate(async()=>{const {command}=await import('/src/core/engine.ts' as string);command((window as any).prototype.state,{type:'promoteCommandFocus'});});}
async function begin(page:Page){await page.goto('/');await page.locator('[data-journey="exploration"]').click();await page.locator('[data-companion="ines"]').click();await page.locator('[data-action="carry"]').click();await page.locator('[data-action="pause"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.terrain.userData.loaded),{timeout:45000}).toBe(true);}
const actor=(page:Page)=>page.evaluate(()=>(window as any).prototype.state.controlledBodyId);
test('original focus keeps DirectActor while clone inspection leaves its skills available',async({page})=>{
 await begin(page);await page.keyboard.press('c');expect(await actor(page)).toBe('hunter');await expect(page.locator('[data-unit="ines"]')).toContainText('指令');await promote(page);expect(await actor(page)).toBe('ines');await expect(page.locator('[data-unit="ines"]')).toContainText('当前操控');await expect(page.locator('#world-skill [data-skill="ines"]')).toBeVisible();
 await page.evaluate(async()=>{const p=(window as any).prototype,{command,cloneTiles}=await import('/src/core/engine.ts' as string);p.state.fragments=40;command(p.state,{type:'clone',id:'ines',to:cloneTiles(p.state,'ines')[0]});});await page.locator('[data-copy-select]').first().click();expect(await actor(page)).toBe('ines');await expect(page.locator('#unit-detail')).toContainText('当前操控：伊内丝');await expect(page.locator('#world-skill [data-skill="ines"]')).toBeVisible();
 mkdirSync(evidence,{recursive:true});await page.screenshot({path:evidence+'/clone-observation.png'});
 await page.locator('[data-action="pause"]').click();await page.keyboard.down('d');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ines').direct?.direction?.x)).toBe(1);await page.keyboard.press('c');expect(await actor(page)).toBe('ines');await page.keyboard.up('d');await page.keyboard.down('d');await expect.poll(()=>actor(page)).toBe('hunter');await page.keyboard.up('d');
});
test('modal aim and panels block quick control without canceling the action',async({page})=>{
 test.setTimeout(90000);await begin(page);await page.keyboard.press('Tab');await page.locator('[data-card]').first().click();await page.keyboard.press('c');expect(await actor(page)).toBe('hunter');await expect(page.locator('#notice')).toContainText('完成或取消');await page.keyboard.press('Escape');
 await page.evaluate(()=>{(window as any).prototype.state.fragments=40;});await page.locator('[data-clone="hunter"]').click();await page.keyboard.press('2');expect(await actor(page)).toBe('hunter');await page.keyboard.press('Escape');
 await page.locator('[data-action="backpack"]').click();await page.keyboard.press('c');expect(await actor(page)).toBe('hunter');await page.keyboard.press('Escape');
 await page.locator('[data-action="build"]').first().click();await page.keyboard.press('2');expect(await actor(page)).toBe('hunter');await page.keyboard.press('Escape');await page.keyboard.press('2');await promote(page);await expect.poll(()=>actor(page)).toBe('ines');
});
test('camera follows current primary with capped offset, smooth switching and fixed projection',async({page})=>{
 test.setTimeout(90000);await begin(page);await page.evaluate(()=>{const s=(window as any).prototype.state,h=s.units[0],a=s.units.find((u:any)=>u.id==='ines');h.pos={x:10,y:10};h.drawPos={...h.pos};a.pos={x:30,y:10};a.drawPos={...a.pos};});
 await expect.poll(()=>page.evaluate(()=>{const p=(window as any).prototype;return Math.abs(p.project({x:13,y:10}).x-innerWidth/2);})).toBeLessThan(4);
 const before=await page.evaluate(()=>{const c=(window as any).prototype.scene.camera;return {p:[...c.projectionMatrix.elements],x:c.position.x};});await page.keyboard.press('c');await promote(page);await expect.poll(()=>page.evaluate(()=>{const p=(window as any).prototype;return Math.abs(p.project({x:27,y:10}).x-innerWidth/2);})).toBeLessThan(4);expect(await page.evaluate(()=>(window as any).prototype.scene.camera.projectionMatrix.elements)).toEqual(before.p);
 const smooth=await page.evaluate(async()=>{const p=(window as any).prototype,{command}=await import('/src/core/engine.ts' as string),v=p.scene.cameraFocus.clone();command(p.state,{type:'controlBody',id:'hunter'});p.scene.followCamera(p.state,.016,null);const end=p.scene.world({x:13,y:10});end.y=0;return {actual:p.scene.cameraFocus.distanceTo(v),expected:end.distanceTo(v)*(1-Math.exp(-.016*8)),total:end.distanceTo(v)};});expect(smooth.actual).toBeCloseTo(smooth.expected,5);expect(smooth.actual).toBeLessThan(smooth.total);
 await page.emulateMedia({reducedMotion:'reduce'});await begin(page);const reduced=await page.evaluate(async()=>{const p=(window as any).prototype,s=p.state,h=s.units[0],a=s.units.find((u:any)=>u.id==='ines'),{command}=await import('/src/core/engine.ts' as string);h.pos={x:10,y:10};h.drawPos={...h.pos};a.pos={x:30,y:10};a.drawPos={...a.pos};command(s,{type:'controlBody',id:'ines'});p.scene.followCamera(s,.016,null);const end=p.scene.world({x:27,y:10});end.y=0;return p.scene.cameraFocus.distanceTo(end);});expect(reduced).toBeLessThan(.00001);
});

test('skill input stays on controlled companion and incapacitation updates control without revival theft',async({page})=>{
 test.setTimeout(90000);await begin(page);await page.keyboard.press('2');await page.evaluate(async()=>{const p=(window as any).prototype,{command,cloneTiles}=await import('/src/core/engine.ts' as string);p.state.fragments=40;command(p.state,{type:'clone',id:'ines',to:cloneTiles(p.state,'ines')[0]});});await page.locator('[data-copy-select]').first().click();await page.locator('[data-action="pause"]').click();await page.evaluate(()=>{const s=(window as any).prototype.state;for(const u of s.units)if(u.id==='ines'||u.cloneOf==='ines')u.skillStates[u.skillId].counter=8;});await page.keyboard.press('e');await expect.poll(()=>page.evaluate(()=>{const u=(window as any).prototype.state.units.find((u:any)=>u.id==='ines');return u.skillStates[u.skillId].counter;})).toBe(0);expect(await page.evaluate(()=>{const u=(window as any).prototype.state.units.find((u:any)=>u.cloneOf==='ines');return u.skillStates[u.skillId].counter;})).toBe(8);await page.evaluate(()=>{const u=(window as any).prototype.state.units.find((u:any)=>u.id==='ines');u.skillStates[u.skillId].counter=8;});await page.locator('#world-skill [data-skill="ines"]').click();await expect.poll(()=>page.evaluate(()=>{const u=(window as any).prototype.state.units.find((u:any)=>u.id==='ines');return u.skillStates[u.skillId].counter;})).toBe(0);
 await page.evaluate(()=>{const s=(window as any).prototype.state,a=s.units.find((u:any)=>u.id==='ines');a.life='downed';});await expect.poll(()=>actor(page)).toBe('hunter');await expect(page.locator('[data-unit="hunter"]')).toContainText('当前操控');await page.evaluate(()=>{const s=(window as any).prototype.state,a=s.units.find((u:any)=>u.id==='ines');a.life='active';a.hp=a.maxHp;});await expect(page.locator('[data-unit="ines"]')).toContainText('AI');expect(await actor(page)).toBe('hunter');
});

test('blink, item, drag, economy and exit confirmation retain exclusive input',async({page})=>{
 test.setTimeout(90000);await begin(page);
 await page.locator('[data-action="blink"]').click();await page.keyboard.press('2');expect(await actor(page)).toBe('hunter');await expect(page.locator('#notice')).toContainText('完成或取消');await page.keyboard.press('Escape');
 await page.evaluate(()=>{(window as any).prototype.state.inventory.heal=1;});await page.locator('[data-action="backpack"]').click();await page.locator('[data-equip="heal"]').click();await page.locator('[data-item="heal"]').click();await page.keyboard.press('c');expect(await actor(page)).toBe('hunter');await page.keyboard.press('Escape');
 await page.locator('[data-action="abandon"]').click();await expect(page.locator('#economy-confirm')).toBeVisible();await page.keyboard.press('2');expect(await actor(page)).toBe('hunter');await expect(page.locator('#economy-confirm')).toBeVisible();await page.keyboard.press('Escape');
 await page.locator('[data-action="pause"]').click();await page.keyboard.press('Tab');const hand=page.locator('[data-card]').first();await hand.click({trial:true});const card=await hand.boundingBox();await page.mouse.move(card!.x+card!.width/2,card!.y+card!.height/2);await page.mouse.down();await page.mouse.move(card!.x+50,card!.y-30,{steps:3});await page.keyboard.press('c');expect(await actor(page)).toBe('hunter');await page.mouse.up();await page.keyboard.press('Escape');await page.locator('[data-action="pause"]').click();
 await page.evaluate(()=>{const s=(window as any).prototype.state,h=s.units[0],a=s.units.find((u:any)=>u.id==='ines');for(const u of s.units)if(u.team==='enemy')u.life='dead';h.pos={...s.goal};h.drawPos={...h.pos};a.life='downed';s.context='explorationIdle';});await page.locator('[data-action="exit-exploration"]').click();await expect(page.locator('#exploration-exit-confirm')).toBeVisible();await page.keyboard.press('c');expect(await actor(page)).toBe('hunter');await expect(page.locator('#exploration-exit-confirm')).toBeVisible();
});
