import {test,expect,type Page} from '@playwright/test';
import {mkdirSync} from 'node:fs';
async function begin(page:Page){await page.goto('/');await page.locator('[data-journey="exploration"]').click();await page.locator('[data-companion="ines"]').click();await page.locator('[data-action="carry"]').click();await page.locator('[data-action="pause"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).prototype?.scene.terrain.userData.loaded),{timeout:45000}).toBe(true);}
async function encounter(page:Page,role:string){return page.evaluate(async role=>{const p=(window as any).prototype,s=p.state,h=s.units[0],a=s.units.find((u:any)=>u.id==='ines'),e=s.units.find((u:any)=>u.team==='enemy');for(const u of s.units)if(u.team==='enemy')u.life='dead';e.life='active';e.role=role;e.hp=e.maxHp=10000;e.pos={x:h.pos.x-1,y:h.pos.y};e.drawPos={...e.pos};e.path=[];e.attackTimer=0;e.enemySense.home={...e.pos};e.enemySense.patrol=[];e.enemySense.lastSeen={...h.pos};e.pursuitTargetId=h.id;e.enemyMotion='engaged';e.weapons[0].remote=role==='ranged';e.weapons[0].range=role==='ranged'?4:1;e.statuses=[];h.attackTimer=a.attackTimer=100;a.life='withdrawn';const {startIntent}=await import('/src/core/attack-intent.ts' as string);startIntent(s,e,h);return {id:e.id,hp:h.hp,posture:h.posture};},role);}
for(const role of ['melee','ranged'])test(role+' telegraph uses locked core geometry and real WASD can avoid',async({page})=>{test.setTimeout(90000);await begin(page);const start=await encounter(page,role);await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.telegraphs.group.children.length)).toBe(1);expect(await page.evaluate(()=>{const g=(window as any).prototype.scene.telegraphs.group.children[0];return g.userData.phase;})).toBe('tracking');await page.locator('[data-action="pause"]').click();await expect.poll(()=>page.evaluate(()=>{const e=(window as any).prototype.state.units.find((u:any)=>u.attackIntent);return e?.attackIntent.phase;}),{intervals:[10]}).toBe('locked');await page.keyboard.down(role==='melee'?'d':'s');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.stats.telegraphPositionAvoids||0),{intervals:[20]}).toBeGreaterThan(0);await page.keyboard.up(role==='melee'?'d':'s');await page.locator('[data-action="pause"]').click();expect(await page.evaluate(()=>(window as any).prototype.state.units[0].hp)).toBe(start.hp);expect(await page.evaluate(()=>(window as any).prototype.state.units[0].posture)).toBe(start.posture);mkdirSync('../记录/验证/T-022',{recursive:true});await page.screenshot({path:'../记录/验证/T-022/'+role+'-avoid.png'});});
test('standing in a ranged line receives damage and reduced motion still distinguishes lock',async({page})=>{test.setTimeout(90000);await page.emulateMedia({reducedMotion:'reduce'});await begin(page);const start=await encounter(page,'ranged');await page.locator('[data-action="pause"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.telegraphs.group.children[0]?.userData.phase),{intervals:[10]}).toBe('locked');expect(await page.evaluate(()=>{const g=(window as any).prototype.scene.telegraphs.group.children[0];return {fill:g.children[0].material.opacity,dashed:g.children[1].material.type};})).toEqual({fill:.28,dashed:'LineBasicMaterial'});await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.stats.telegraphHits||0),{intervals:[20]}).toBe(1);await page.locator('[data-action="pause"]').click();expect(await page.evaluate(()=>(window as any).prototype.state.units[0].hp)).toBeLessThan(start.hp);});
test('enemy attack animation begins with tracking intent',async({page})=>{await begin(page);const {id}=await encounter(page,'melee');await expect.poll(()=>page.evaluate(id=>(window as any).prototype.scene.unitVisuals.get(id)?.attackRemaining,id)).toBeGreaterThan(0);});
test('heavy locked area resolves against both originals in the browser',async({page})=>{await begin(page);const start=await encounter(page,'heavy');const hp=await page.evaluate(()=>{const p=(window as any).prototype,s=p.state,h=s.units[0],a=s.units.find((u:any)=>u.id==='ines');a.life='active';a.pos={x:h.pos.x-.1,y:h.pos.y+.2};a.drawPos={...a.pos};a.attackTimer=100;a.ai={...a.ai,task:{kind:'hold'}};return a.hp;});await page.locator('[data-action="pause"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.stats.telegraphHits||0),{intervals:[10]}).toBe(2);await page.locator('[data-action="pause"]').click();expect(await page.evaluate(()=>(window as any).prototype.state.units[0].hp)).toBeLessThan(start.hp);expect(await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ines').hp)).toBeLessThan(hp);});
for(const delay of [.07,.14])test('real Shift '+(delay<.1?'active':'expired')+' window inside a locked heavy area',async({page})=>{
 await begin(page);await encounter(page,'heavy');await page.keyboard.press('2');
 await page.evaluate(()=>{const p=(window as any).prototype,s=p.state,h=s.units[0],a=s.units.find((u:any)=>u.id==='ines'),e=s.units.find((u:any)=>u.attackIntent);a.life='active';a.pos={x:e.pos.x+.45,y:e.pos.y};a.drawPos={...a.pos};a.path=[];a.ai={...a.ai,task:{kind:'hold'}};h.life='withdrawn';e.pursuitTargetId=a.id;e.attackIntent.targetId=a.id;e.attackIntent.phase='locked';e.attackIntent.resolveAt=s.time+10;});
 await page.locator('[data-action="pause"]').click();
 // Freeze in the same event turn after the real Shift handler, avoiding wall-clock polling drift.
 await page.evaluate(()=>{const pause=(e:KeyboardEvent)=>{if(e.code!=='ShiftLeft')return;window.removeEventListener('keydown',pause);window.dispatchEvent(new KeyboardEvent('keydown',{code:'Space',key:' ',bubbles:true}));};window.addEventListener('keydown',pause);});
 await page.keyboard.down('d');await page.keyboard.press('Shift');await page.keyboard.up('d');expect(await page.evaluate(()=>(window as any).prototype.state.stats.evadeUses||0)).toBe(1);
 const result=await page.evaluate(async delay=>{const s=(window as any).prototype.state,a=s.units.find((u:any)=>u.id==='ines'),e=s.units.find((u:any)=>u.attackIntent),hp=a.hp,posture=a.posture;const {step}=await import('/src/core/engine.ts' as string);const {start}= {start:a.evasion.action?.startedAt};if(start===undefined)throw Error('fixture did not pause during evade');const remain=Math.max(.001,start+delay-s.time);e.attackIntent.resolveAt=s.time+remain;step(s,remain);return {hp,posture,afterHp:a.hp,afterPosture:a.posture,active:s.stats.activeEvades||0,hit:s.stats.telegraphHits||0,avoid:s.stats.telegraphPositionAvoids||0};},delay);
 expect(result.avoid).toBe(0);if(delay<.1){expect(result.active).toBe(1);expect(result.afterHp).toBe(result.hp);expect(result.afterPosture).toBe(result.posture);}else{expect(result.active).toBe(0);expect(result.hit).toBe(1);expect(result.afterHp).toBeLessThan(result.hp);}
});
test('paused tracking and locked screenshots preserve world picking',async({page})=>{await begin(page);await encounter(page,'melee');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.telegraphs.group.children.length)).toBe(1);const picks=await page.evaluate(()=>{const p=(window as any).prototype,r=document.querySelector('#scene')!.getBoundingClientRect(),x=r.x+r.width/2,y=r.y+r.height/2,before=p.scene.pick(x,y);p.scene.telegraphs.group.visible=false;const hidden=p.scene.pick(x,y);p.scene.telegraphs.group.visible=true;return {before,hidden};});expect(picks.before.tile).not.toBeNull();expect(picks.before).toEqual(picks.hidden);mkdirSync('../记录/验证/T-022',{recursive:true});await page.screenshot({path:'../记录/验证/T-022/tracking.png'});await page.evaluate(()=>{const e=(window as any).prototype.state.units.find((u:any)=>u.attackIntent);e.attackIntent.phase='locked';});await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.telegraphs.group.children[0]?.userData.phase)).toBe('locked');await page.screenshot({path:'../记录/验证/T-022/locked.png'});});
