import {test,expect,type Page} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
const folder='../记录/验证/T-024';
async function promote(page:Page){await page.evaluate(async()=>{const {command}=await import('/src/core/engine.ts' as string);command((window as any).prototype.state,{type:'promoteCommandFocus'});});}
async function begin(page:Page){await page.goto('/');await page.locator('[data-journey="exploration"]').click();await page.locator('[data-companion="ranger"]').click();await page.locator('[data-action="carry"]').click();await page.locator('[data-action="pause"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.terrain.userData.loaded),{timeout:45000}).toBe(true);mkdirSync(folder,{recursive:true});}
test('same Heavy and build front/back damage and Broken counts, ordinary enemies remain neutral',async({page})=>{
 await begin(page);const proof=await page.evaluate(async()=>{const s=(window as any).prototype.state,h=s.units[0],e=s.units.find((u:any)=>u.role==='heavy'),{resolveHit}=await import('/src/core/engine.ts' as string);s.units=[h,e];h.dodge=e.dodge=0;e.defense=undefined;h.pos={x:11,y:10};e.pos={x:10,y:10};e.heading=0;const w={...h.weapons[0],weight:0};const cases=[];
 for(const role of ['heavy','melee','ranged'])for(const x of [11,9]){const profile=role==='heavy'?'heavy-rear-core':'neutral';e.role=role;e.directionalProfileId=profile;h.pos.x=x;e.hp=e.maxHp=10000;e.posture=e.maxPosture=150;e.stagger=0;resolveHit(s,e,w,100,h,{postureDamage:15});const first={hp:10000-e.hp,posture:150-e.posture};let hits=1;while(e.posture>0&&hits<20){resolveHit(s,e,w,0,h,{postureDamage:15});hits++;}cases.push({profile,x,first,hits});}return cases;});
 expect(proof.map(x=>x.first)).toEqual([{hp:65,posture:10.5},{hp:125,posture:20.25},{hp:100,posture:15},{hp:100,posture:15},{hp:100,posture:15},{hp:100,posture:15}]);expect(proof.map(x=>x.hits)).toEqual([15,8,10,10,10,10]);writeFileSync(folder+'/front-back.json',JSON.stringify(proof,null,2));
});
test('real C and WASD let Arl circle a locked Heavy, show short weakpoint feedback and debug only indicators',async({page})=>{
 test.setTimeout(90000);await begin(page);await page.evaluate(async()=>{const s=(window as any).prototype.state,h=s.units[0],a=s.units.find((u:any)=>u.id==='ranger'),e=s.units.find((u:any)=>u.role==='heavy');for(const u of s.units)if(u.team==='enemy')u.life='dead';s.tiles.forEach((t:any)=>{t.obstacle=false;t.layer=0;});h.pos={x:11,y:10};a.pos={x:11,y:11};e.pos={x:10,y:10};for(const u of [h,a,e]){u.drawPos={...u.pos};u.ready=0;u.attackTimer=100;u.path=[];u.dodge=0;u.weapons[0].weight=0;}e.life='active';e.hp=e.maxHp=10000;e.defense=undefined;e.enemyMotion='engaged';e.pursuitTargetId=h.id;e.enemySense.home={...e.pos};e.postureDelay=100;const {startIntent}=await import('/src/core/attack-intent.ts' as string);startIntent(s,e,h);e.attackIntent.phase='locked';e.attackIntent.resolveAt=s.time+100;a.ai={...a.ai,commandUntil:s.time+100,task:undefined,moving:false};});
 await page.keyboard.press('c');await promote(page);expect(await page.evaluate(()=>(window as any).prototype.state.controlledBodyId)).toBe('ranger');
 await page.keyboard.press('Space');await page.keyboard.down('a');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').direct?.direction?.x)).toBe(-1);
 await page.evaluate(async()=>{const {step}=await import('/src/core/engine.ts' as string);step((window as any).prototype.state,.8);});await page.keyboard.up('a');await page.keyboard.down('w');await page.evaluate(async()=>{const {step}=await import('/src/core/engine.ts' as string);step((window as any).prototype.state,.3);});await page.keyboard.up('w');await page.keyboard.press('Space');
 const proof=await page.evaluate(async()=>{const p=(window as any).prototype,s=p.state,a=s.units.find((u:any)=>u.id==='ranger'),e=s.units.find((u:any)=>u.role==='heavy'&&u.life==='active'),{step}=await import('/src/core/engine.ts' as string),{hitDirection}=await import('/src/core/directionality.ts' as string);const direction=hitDirection(e,a.pos);a.attackTimer=0;a.facing='east';a.heading=0;step(s,.3);return {position:a.pos,heading:e.heading,direction,event:s.weakpointEvents.at(-1)};});
 expect(proof.direction).toBe('back');expect(proof.heading).toBe(0);expect(proof.event.weakpointId).toBe('rear-core');await expect.poll(()=>page.evaluate(()=>{const p=(window as any).prototype,e=p.state.units.find((u:any)=>u.role==='heavy'&&u.life==='active');return p.scene.unitVisuals.get(e.id)?.lastBar.includes('弱点');})).toBe(true);
 expect(await page.evaluate(()=>(window as any).prototype.scene.directions.group.children.length)).toBe(0);await page.screenshot({path:folder+'/manual-back-weakpoint.png'});await page.locator('[data-action="debug"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.directions.group.children.length)).toBeGreaterThan(0);await page.screenshot({path:folder+'/debug-facing.png'});
 await page.evaluate(async()=>{const s=(window as any).prototype.state;s.units.forEach((u:any)=>u.attackTimer=100);const {step}=await import('/src/core/engine.ts' as string);step(s,.8);});await expect.poll(()=>page.evaluate(()=>{const p=(window as any).prototype,e=p.state.units.find((u:any)=>u.role==='heavy'&&u.life==='active');return p.scene.unitVisuals.get(e.id)?.lastBar.includes('弱点');})).toBe(false);writeFileSync(folder+'/manual-back.json',JSON.stringify(proof,null,2));
});
test('back Broken followed by real Arl enhanced arrow pins Heavy to an existing dungeon wall',async({page})=>{
 await begin(page);await page.evaluate(async()=>{const s=(window as any).prototype.state,h=s.units[0],a=s.units.find((u:any)=>u.id==='ranger'),e=s.units.find((u:any)=>u.role==='heavy');for(const u of s.units)if(u.team==='enemy')u.life='dead';const {surface}=await import('/src/core/spatial.ts' as string);const t=s.tiles.filter((t:any)=>!t.obstacle&&t.layer===0&&surface(s,{x:t.x+1,y:t.y})?.obstacle&&[1,2].every(n=>{const q=surface(s,{x:t.x-n,y:t.y});return q&&!q.obstacle&&q.layer===0;})).sort((l:any,r:any)=>Math.hypot(l.x-h.pos.x,l.y-h.pos.y)-Math.hypot(r.x-h.pos.x,r.y-h.pos.y))[0];if(!t)throw Error('missing natural wall');e.life='active';e.pos={x:t.x,y:t.y};h.pos={x:t.x-.8,y:t.y};a.pos={x:t.x-1.2,y:t.y};for(const u of [h,a,e]){u.drawPos={...u.pos};u.ready=0;u.path=[];u.attackTimer=100;u.dodge=0;u.weapons[0].weight=0;}e.hp=e.maxHp=10000;e.defense=undefined;e.heading=0;e.posture=40.5;e.postureDelay=100;e.enemySense.home={...e.pos};e.enemyMotion='engaged';e.pursuitTargetId=h.id;a.ai={...a.ai,commandUntil:s.time+100,task:undefined,moving:false};a.skillId='snipe';a.facing='east';a.heading=0;s.context='explorationBattle';s.exploration.visionAt=-1;const {startIntent}=await import('/src/core/attack-intent.ts' as string);startIntent(s,e,h);e.heading=0;e.attackIntent.heading=0;e.attackIntent.phase='locked';e.attackIntent.resolveAt=s.time+100;const {resolveHit}=await import('/src/core/engine.ts' as string);resolveHit(s,e,h.weapons[0],1,h,{postureDamage:15,kind:'basic'});resolveHit(s,e,h.weapons[0],1,h,{postureDamage:15,kind:'basic'});if(e.posture!==0||e.stagger!==0)throw Error('Broken timing changed');});
 await page.keyboard.press('c');await promote(page);await page.locator('[data-world-skill]').click();await page.evaluate(async()=>{const s=(window as any).prototype.state,a=s.units.find((u:any)=>u.id==='ranger'),{step}=await import('/src/core/engine.ts' as string);a.attackTimer=0;step(s,.3);step(s,.3);step(s,.22);});
 const proof=await page.evaluate(()=>{const p=(window as any).prototype,s=p.state,e=s.units.find((u:any)=>u.role==='heavy'&&u.life==='active');return {stats:s.stats,wallPin:e.wallPin,heading:e.heading,event:s.combatEvents.at(-1)};});writeFileSync(folder+'/pin-attempt.json',JSON.stringify(proof,null,2));expect(proof.stats.wallPin).toBe(1);expect(proof.stats.break).toBe(1);expect(proof.event.direction).toBe('back');expect(proof.event.skillId).toBe('snipe');await page.screenshot({path:folder+'/back-break-wall-pin.png'});writeFileSync(folder+'/back-break-wall-pin.json',JSON.stringify(proof,null,2));
});
test('reduced motion keeps the weakpoint label readable without a growing ring',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});await begin(page);await page.evaluate(async()=>{const s=(window as any).prototype.state,h=s.units[0],e=s.units.find((u:any)=>u.role==='heavy'),{resolveHit}=await import('/src/core/engine.ts' as string);for(const u of s.units)if(u.team==='enemy')u.life='dead';e.life='active';e.pos={x:h.pos.x+1,y:h.pos.y};e.drawPos={...e.pos};e.heading=0;e.dodge=0;h.weapons[0].weight=0;resolveHit(s,e,h.weapons[0],10,h,{kind:'basic'});});
 await expect.poll(()=>page.evaluate(()=>{const p=(window as any).prototype,e=p.state.units.find((u:any)=>u.role==='heavy'&&u.life==='active');return p.scene.unitVisuals.get(e.id)?.lastBar.includes('弱点');})).toBe(true);
 expect(await page.evaluate(()=>{const p=(window as any).prototype;return {reduced:p.scene.reducedMotion,debug:p.scene.directions.group.children.length,ringScale:p.scene.effectsGroup.children.find((o:any)=>o.geometry?.parameters?.innerRadius===.33)?.scale.x};})).toEqual({reduced:true,debug:0,ringScale:1});await page.screenshot({path:folder+'/weakpoint-reduced-motion.png'});
});
