import {test,expect,type Page} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
const folder='../记录/验证/T-025';
async function promote(page:Page){await page.evaluate(async()=>{const {command}=await import('/src/core/engine.ts' as string);command((window as any).prototype.state,{type:'promoteCommandFocus'});});}
async function begin(page:Page,id:string){
 await page.goto('/');await page.locator('[data-journey="exploration"]').click();await page.locator(`[data-companion="${id}"]`).click();await page.locator('[data-action="carry"]').click();await page.locator('[data-action="pause"]').click();
 await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.terrain.userData.loaded),{timeout:45000}).toBe(true);
 await page.evaluate((id)=>{const s=(window as any).prototype.state,u=s.units.find((u:any)=>u.id===id),h=s.units[0],e=s.units.find((u:any)=>u.team==='enemy');for(const a of s.units)if(a.team==='enemy')a.life='dead';s.tiles.forEach((t:any)=>{t.obstacle=false;t.layer=0;});u.pos={x:10,y:10};h.pos={x:10,y:11};e.pos={x:11,y:10};e.life='active';e.hp=e.maxHp=1e8;e.defense=undefined;e.enemySense.home={...e.pos};e.speed=0;e.attackTimer=1000;e.weapons[0].damage=0;e.dodge=0;for(const a of [u,h,e]){a.drawPos={...a.pos};a.ready=0;a.path=[];a.following=false;a.attackTimer=1000;a.dodge=0;a.weapons[a.weaponIndex].weight=0;}u.ai={anchor:{...u.pos},commandUntil:1000};s.context='explorationBattle';s.exploration.visionAt=-1;},id);
 await page.keyboard.press('c');await promote(page);await expect(page.locator('#world-skill [data-skill-slot]')).toHaveCount(3);mkdirSync(folder,{recursive:true});
}
test('Ranger real E toggle survives automatic Rain, third slot is empty and Build swaps only run slots',async({page})=>{
 await begin(page,'ranger');await expect(page.locator('#world-skill [data-skill-slot="2"]')).toContainText('空');await page.locator('[data-action="pause"]').click();await page.keyboard.press('e');await page.locator('[data-action="pause"]').click();
 const proof=await page.evaluate(async()=>{const s=(window as any).prototype.state,u=s.units.find((u:any)=>u.id==='ranger'),{step}=await import('/src/core/engine.ts' as string);u.skillStates.rain.cd=0;step(s,.15);return {enabled:u.skillStates.snipe.enabled,rain:!!u.skillStates.rain.run,arrows:s.stats.rainArrows};});expect(proof.enabled).toBe(true);expect(proof.rain).toBe(true);expect(proof.arrows).toBeGreaterThan(0);
 await page.screenshot({path:folder+'/ranger-parallel.png'});writeFileSync(folder+'/ranger.json',JSON.stringify(proof,null,2));
 await page.evaluate(async()=>{const s=(window as any).prototype.state,{step}=await import('/src/core/engine.ts' as string);step(s,6.2);});
 await page.locator('[data-action="build"]').first().click();await page.locator('[data-build-unit="ranger"]').click();await page.locator('[data-build-slot="1"]').click();await page.locator('[data-config-skill="empty"]').click();await page.locator('[data-build-slot="2"]').click();await page.locator('[data-config-skill="rain"]').click();
 expect(await page.evaluate(()=>{const s=(window as any).prototype.state;return {run:s.units.find((u:any)=>u.id==='ranger').skillSlots,profile:s.profile.loadouts.ranger.ranger};})).toEqual({run:['snipe',null,'rain'],profile:['snipe','rain',null]});
 await page.keyboard.press('e');expect(await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').skillStates.snipe.enabled)).toBe(true);
});
test('Shieldguard real R casts Sanctuary while Pain counts independently; foreground cannot be unloaded',async({page})=>{
 await begin(page,'ines');await page.evaluate(()=>{(window as any).prototype.state.units.find((u:any)=>u.id==='ines').skillStates.sanctuary.cd=0;});await page.locator('[data-action="pause"]').click();await page.keyboard.press('r');await page.locator('[data-action="pause"]').click();
 const proof=await page.evaluate(async()=>{const s=(window as any).prototype.state,u=s.units.find((u:any)=>u.id==='ines'),e=s.units.find((u:any)=>u.team==='enemy'&&u.life==='active'),{resolveHit,command}=await import('/src/core/engine.ts' as string);resolveHit(s,u,e.weapons[0],1,e);return {pain:u.skillStates.pain.counter,sanctuary:!!u.skillStates.sanctuary.run,unload:command(s,{type:'configureSkillSlot',id:u.id,slot:1,skillId:null}).ok};});expect(proof).toEqual({pain:1,sanctuary:true,unload:false});await page.screenshot({path:folder+'/shieldguard-parallel.png'});writeFileSync(folder+'/shieldguard.json',JSON.stringify(proof,null,2));
 await page.evaluate(async()=>{const s=(window as any).prototype.state,u=s.units.find((u:any)=>u.id==='ines'),{step,command}=await import('/src/core/engine.ts' as string);step(s,13);command(s,{type:'configureSkillSlot',id:u.id,slot:1,skillId:null});command(s,{type:'configureSkillSlot',id:u.id,slot:2,skillId:'sanctuary'});u.skillStates.sanctuary.cd=0;});
 await page.locator('[data-action="pause"]').click();await page.keyboard.press('t');await page.locator('[data-action="pause"]').click();expect(await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ines').skillStates.sanctuary.time)).toBeGreaterThan(0);

});
test('Scythe mode remains enabled across Reap; slot preview, clone view and actor switch stay separate',async({page})=>{
 await begin(page,'fiorre');const proof=await page.evaluate(async()=>{const s=(window as any).prototype.state,u=s.units.find((u:any)=>u.id==='fiorre'),{step,command,cloneTiles}=await import('/src/core/engine.ts' as string);u.skillStates.dance.cd=0;u.skillStates.reap.counter=5;step(s,.05);const started=!!u.skillStates.reap.run;step(s,1.5);s.fragments=100;command(s,{type:'clone',id:u.id,to:cloneTiles(s,u.id)[0]});return {started,mode:u.skillStates.dance.enabled,returned:!u.skillStates.reap.run};});expect(proof).toEqual({started:true,mode:true,returned:true});
 await page.locator('#world-skill [data-skill-slot="1"]').hover();await expect(page.locator('#range-caption')).toContainText('离魂回镰');await page.screenshot({path:folder+'/scythe-parallel.png'});writeFileSync(folder+'/scythe.json',JSON.stringify(proof,null,2));
 await page.locator('[data-copy-select]').first().click();await expect(page.locator('#unit-detail')).toContainText('出生技能槽');await expect(page.locator('#world-skill [data-skill="fiorre"]')).toBeVisible();await page.keyboard.press('c');await promote(page);await expect(page.locator('#world-skill [data-skill="hunter"]')).toBeVisible();
});
