import {test,expect,type Page} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
const folder='../记录/验证/T-026';
const runtimeErrors=new WeakMap<Page,string[]>();
test.beforeEach(async({page})=>{const errors:string[]=[];runtimeErrors.set(page,errors);page.on('pageerror',e=>errors.push(e.message));});
test.afterEach(async({page})=>{expect(runtimeErrors.get(page),'no runtime error banner may be hidden by successful combat assertions').toEqual([]);});
async function promote(page:Page){await page.evaluate(async()=>{const {command}=await import('/src/core/engine.ts' as string);command((window as any).prototype.state,{type:'promoteCommandFocus'});});}
async function begin(page:Page){await page.goto('/');await page.locator('[data-journey="exploration"]').click();await page.locator('[data-companion="ranger"]').click();await page.locator('[data-action="carry"]').click();await page.locator('[data-action="pause"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.terrain.userData.loaded),{timeout:45000}).toBe(true);mkdirSync(folder,{recursive:true});}
async function fixture(page:Page,role:string,range=1){return page.evaluate(async({role,range})=>{
 const s=(window as any).prototype.state,h=s.units[0],p=s.units.find((u:any)=>u.id==='ranger'),e=s.units.find((u:any)=>u.role===role);if(!e)throw Error('missing '+role);
 const origin={...h.pos};s.units=[h,p,e];s.tiles.forEach((t:any)=>{t.obstacle=false;t.layer=0;});e.pos={x:origin.x-1,y:origin.y};h.pos={x:e.pos.x+range,y:e.pos.y};p.pos={x:e.pos.x+1,y:e.pos.y+1};
 for(const u of s.units){u.drawPos={...u.pos};u.hp=u.maxHp=10000;u.path=[];u.destination=null;u.ready=0;u.dodge=0;u.defense=undefined;u.attackTimer=100;u.attackIntent=undefined;u.weapons.forEach((w:any)=>w.weight=0);u.postureDelay=100;}
 p.life='withdrawn';e.enemySense.home={...e.pos};e.enemyMotion='engaged';e.pursuitTargetId=h.id;e.enemyCombat.armed=true;e.enemyCombat.abilityReadyAt=0;e.enemyCombat.reactionReadyAt=0;e.enemyCombat.reaction=undefined;s.context='explorationBattle';e.attackTimer=0;s.controlledBodyId=h.id;s.exploration.visionAt=-1;return {id:e.id,pos:e.pos,hp:h.hp};
 },{role,range});}
async function advance(page:Page,seconds:number){await page.evaluate(async seconds=>{const {step}=await import('/src/core/engine.ts' as string);step((window as any).prototype.state,seconds);},seconds);}
test('Melee selects Cleave, lock stays frozen, Basic remains, real direct hit starts delayed side step',async({page})=>{
 await begin(page);await fixture(page,'melee');await advance(page,.05);
 await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.telegraphs.group.children.find((g:any)=>g.userData.kind==='ability')?.children[3].visible)).toBe(true);
 const first=await page.evaluate(()=>{const p=(window as any).prototype,e=p.state.units.find((u:any)=>u.team==='enemy');return {intent:e.attackIntent,bar:p.scene.unitVisuals.get(e.id)?.lastBar};});expect(first.intent.label).toBe('裂阵重斩');expect(first.bar).toContain('裂阵重斩');await page.screenshot({path:folder+'/melee-cleave.png'});
 await advance(page,.85);expect(await page.evaluate(()=>(window as any).prototype.state.stats.enemyAbilitiesReleased)).toBe(1);
 await page.evaluate(async()=>{const s=(window as any).prototype.state,h=s.units[0],e=s.units.find((u:any)=>u.team==='enemy'),{step,resolveHit}=await import('/src/core/engine.ts' as string);e.attackTimer=0;step(s,.05);if(e.attackIntent.kind!=='basic')throw Error('basic disappeared');step(s,.55);resolveHit(s,e,h.weapons[0],1,h,{kind:'basic',postureDamage:1});});
 await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.telegraphs.reactions.children[0]?.userData.phase)).toBe('pending');await page.screenshot({path:folder+'/melee-counter-tell.png'});
 const proof=await page.evaluate(async()=>{const s=(window as any).prototype.state,e=s.units.find((u:any)=>u.team==='enemy'),from={...e.pos},cd=e.enemyCombat.reactionReadyAt,{step}=await import('/src/core/engine.ts' as string);step(s,.14);const pending=e.enemyCombat.reaction.phase;step(s,.19);return {from,to:e.pos,pending,cd,reaction:e.enemyCombat.reaction,stats:s.stats};});expect(proof.pending).toBe('pending');expect(Math.hypot(proof.to.x-proof.from.x,proof.to.y-proof.from.y)).toBeCloseTo(.55);expect(proof.reaction).toBeUndefined();writeFileSync(folder+'/melee.json',JSON.stringify(proof,null,2));
});
test('Ranged Power Shot resolves through shared hit; real W proximity triggers delayed Backstep with finite cooldown',async({page})=>{
 await begin(page);await fixture(page,'ranged',3);await advance(page,.05);await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.unitVisuals.get((window as any).prototype.state.units.find((u:any)=>u.team==='enemy').id)?.lastBar)).toContain('蓄力穿射');await page.screenshot({path:folder+'/ranged-power-shot.png'});await advance(page,1.05);
 expect(await page.evaluate(()=>(window as any).prototype.state.combatEvents.at(-1).enemyAbilityId)).toBe('ranged-power-shot');
 await page.evaluate(()=>{const s=(window as any).prototype.state,h=s.units[0],e=s.units.find((u:any)=>u.team==='enemy');h.pos={x:e.pos.x,y:e.pos.y+1.7};h.drawPos={...h.pos};h.attackTimer=100;e.attackTimer=100;});
 await page.evaluate(async()=>{const {step}=await import('/src/core/engine.ts' as string);const freeze=(e:KeyboardEvent)=>{if(e.code==='KeyW'){window.removeEventListener('keydown',freeze);step((window as any).prototype.state,.1);document.body.dispatchEvent(new KeyboardEvent('keydown',{code:'Space',bubbles:true}));}};window.addEventListener('keydown',freeze);});await page.keyboard.press('Space');await page.keyboard.down('w');await page.keyboard.up('w');
 await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.team==='enemy').enemyCombat.reaction?.id)).toBe('backstep-evade');await page.screenshot({path:folder+'/ranged-backstep-tell.png'});
 const proof=await page.evaluate(async()=>{const s=(window as any).prototype.state,h=s.units[0],e=s.units.find((u:any)=>u.team==='enemy'),a=e.enemyCombat.reaction,{step,resolveHit}=await import('/src/core/engine.ts' as string);step(s,a.activeAt+.02-s.time);const hp=e.hp,posture=e.posture,miss=!resolveHit(s,e,h.weapons[0],100,h,{postureDamage:100});step(s,.07);const hit=resolveHit(s,e,h.weapons[0],10,h);step(s,.15);const count=s.stats.enemyReactions;step(s,.3);return {miss,hp,posture,hit,active:s.stats.activeEvades,count,after:s.stats.enemyReactions,cd:e.enemyCombat.reactionReadyAt,now:s.time};});writeFileSync(folder+'/ranged-attempt.json',JSON.stringify(proof,null,2));expect(proof.miss).toBe(true);expect(proof.hit).toBe(true);expect(proof.active).toBe(1);expect(proof.after).toBe(proof.count);expect(proof.cd).toBeGreaterThan(proof.now);writeFileSync(folder+'/ranged.json',JSON.stringify(proof,null,2));
});
test('Heavy Slam hits both originals and Brace has a visible tell, front armour, real C/W back Weakpoint',async({page})=>{
 await begin(page);await fixture(page,'heavy');await page.evaluate(()=>{const s=(window as any).prototype.state,e=s.units.find((u:any)=>u.team==='enemy'),p=s.units.find((u:any)=>u.id==='ranger');p.life='active';p.ai={...p.ai,commandUntil:100,task:{kind:'hold'},moving:false};p.pos={x:e.pos.x-.4,y:e.pos.y+.8};p.drawPos={...p.pos};});await advance(page,.05);await page.screenshot({path:folder+'/heavy-slam.png'});await advance(page,1.15);
 const hits=await page.evaluate(()=>(window as any).prototype.state.combatEvents.filter((e:any)=>e.enemyAbilityId==='heavy-ground-slam'));expect(hits).toHaveLength(2);expect(hits[0].castId).toBe(hits[1].castId);
 const front=await page.evaluate(async()=>{const s=(window as any).prototype.state,h=s.units[0],e=s.units.find((u:any)=>u.team==='enemy'),{resolveHit,step}=await import('/src/core/engine.ts' as string);e.attackTimer=100;e.heading=0;h.pos={x:e.pos.x+1,y:e.pos.y};resolveHit(s,e,h.weapons[0],1,h,{postureDamage:1});const phase=e.enemyCombat.reaction.phase;step(s,.15);const hp=e.hp,posture=e.posture;resolveHit(s,e,h.weapons[0],100,h,{postureDamage:10});return {phase,damage:hp-e.hp,posture:posture-e.posture};});expect(front.phase).toBe('pending');expect(front.damage).toBeCloseTo(45.5);expect(front.posture).toBeCloseTo(4.9);await page.screenshot({path:folder+'/heavy-brace.png'});
 await page.keyboard.press('c');await promote(page);expect(await page.evaluate(()=>(window as any).prototype.state.controlledBodyId)).toBe('ranger');await page.evaluate(async()=>{const {step}=await import('/src/core/engine.ts' as string);const freeze=(e:KeyboardEvent)=>{if(e.code==='KeyW'){window.removeEventListener('keydown',freeze);step((window as any).prototype.state,.15);document.body.dispatchEvent(new KeyboardEvent('keydown',{code:'Space',bubbles:true}));}};window.addEventListener('keydown',freeze);});await page.keyboard.press('Space');await page.keyboard.down('w');await page.keyboard.up('w');
 const back=await page.evaluate(async()=>{const s=(window as any).prototype.state,p=s.units.find((u:any)=>u.id==='ranger'),e=s.units.find((u:any)=>u.team==='enemy'),{step}=await import('/src/core/engine.ts' as string),{hitDirection}=await import('/src/core/directionality.ts' as string);const direction=hitDirection(e,p.pos);p.attackTimer=0;step(s,.3);return {direction,event:s.weakpointEvents.at(-1),brace:e.enemyCombat.reaction?.id,heading:e.heading};});writeFileSync(folder+'/heavy-attempt.json',JSON.stringify({hits,front,back},null,2));expect(back.direction).toBe('back');expect(back.event.weakpointId).toBe('rear-core');expect(back.brace).toBe('front-brace');await page.screenshot({path:folder+'/heavy-back-weakpoint.png'});writeFileSync(folder+'/heavy.json',JSON.stringify({hits,front,back},null,2));
});
for(const phase of ['tracking','locked'])test('real hit Break interrupts '+phase+' ability, no Resolve and cooldown retained',async({page})=>{
 await begin(page);await fixture(page,'heavy');await advance(page,.05);if(phase==='locked')await advance(page,.75);
 const proof=await page.evaluate(async()=>{const s=(window as any).prototype.state,h=s.units[0],e=s.units.find((u:any)=>u.team==='enemy'),{resolveHit,step}=await import('/src/core/engine.ts' as string);const before={phase:e.attackIntent.phase,cd:e.enemyCombat.abilityReadyAt};e.posture=0;e.postureDelay=100;resolveHit(s,e,h.weapons[0],1,h,{kind:'basic',postureDamage:1});const cancelled=!e.attackIntent,cd=e.enemyCombat.abilityReadyAt;step(s,1.2);return {before,cancelled,cd,released:s.stats.enemyAbilitiesReleased||0,hp:h.hp,stats:s.stats};});expect(proof.before.phase).toBe(phase);expect(proof.cancelled).toBe(true);expect(proof.cd).toBe(proof.before.cd);expect(proof.released).toBe(0);expect(proof.hp).toBe(10000);await page.screenshot({path:folder+'/break-'+phase+'.png'});writeFileSync(folder+'/break-'+phase+'.json',JSON.stringify(proof,null,2));
});
test('normal four-role encounter runs multiple cycles with deterministic offsets and readable telegraphs',async({page})=>{
 await begin(page);const proof=await page.evaluate(async()=>{const s=(window as any).prototype.state,h=s.units[0],origin={...h.pos},m=s.units.find((u:any)=>u.role==='melee'),r=s.units.find((u:any)=>u.role==='ranged'),b=structuredClone(m),d=structuredClone(m);b.id='group-melee-2';d.id='group-flexible';s.units=[h,m,b,r,d];s.tiles.forEach((t:any)=>{t.obstacle=false;t.layer=0;});const {initializeEnemyCombat}=await import('/src/core/enemy-combat.ts' as string),{step}=await import('/src/core/engine.ts' as string);const coords=[[-1,0],[-.7,.7],[3,0],[.4,-1]];for(const [i,u]of [m,b,r,d].entries()){u.pos={x:origin.x+coords[i][0],y:origin.y+coords[i][1]};u.drawPos={...u.pos};u.path=[];u.attackTimer=0;u.hp=u.maxHp=10000;u.dodge=0;u.enemySense.home={...u.pos};u.enemyMotion='engaged';u.pursuitTargetId=h.id;initializeEnemyCombat(s,u,'normal-'+i);}h.hp=h.maxHp=10000;h.attackTimer=100;h.dodge=0;s.context='explorationBattle';const starts:any[]=[];for(let i=0;i<240;i++){step(s,.05);for(const u of [m,b,r,d])if(u.attackIntent?.kind==='ability'&&!starts.some(x=>x.id===u.id&&x.at===u.attackIntent.startedAt))starts.push({id:u.id,at:u.attackIntent.startedAt});}return {starts,offsets:[m,b,r,d].map(u=>u.enemyCombat.initialOffset),stats:s.stats};});expect(proof.starts.length).toBeGreaterThan(4);const first=proof.starts.filter((v,i,a)=>a.findIndex(x=>x.id===v.id)===i);expect(new Set(first.map(x=>x.at)).size).toBeGreaterThan(1);expect(proof.stats.enemyAbilitiesReleased).toBeGreaterThan(4);writeFileSync(folder+'/normal-encounter.json',JSON.stringify(proof,null,2));await page.screenshot({path:folder+'/normal-encounter.png'});
});
test('reduced motion preserves ability double edge, reaction tell, debug cooldowns and world picking',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});await begin(page);await fixture(page,'melee');await advance(page,.05);await page.locator('[data-action="debug"]').click();await expect(page.locator('#ec01-readings')).toContainText('melee-v1');
 const picks=await page.evaluate(()=>{const p=(window as any).prototype,r=document.querySelector('#scene')!.getBoundingClientRect(),x=r.x+r.width/2,y=r.y+r.height/2,a=p.scene.pick(x,y);p.scene.telegraphs.group.visible=false;const b=p.scene.pick(x,y);p.scene.telegraphs.group.visible=true;const g=p.scene.telegraphs.group.children.find((g:any)=>g.userData.kind==='ability');return {a,b,double:g.children[3].visible,reduced:p.scene.reducedMotion};});expect(picks.a).toEqual(picks.b);expect(picks.a.tile).not.toBeNull();expect(picks.double).toBe(true);expect(picks.reduced).toBe(true);
 await page.evaluate(async()=>{const s=(window as any).prototype.state,e=s.units.find((u:any)=>u.team==='enemy'),h=s.units[0],{scheduleEnemyReaction}=await import('/src/core/enemy-combat.ts' as string);e.attackIntent=undefined;scheduleEnemyReaction(s,e,h);});await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.telegraphs.reactions.children[0]?.userData.phase)).toBe('pending');await page.screenshot({path:folder+'/reduced-motion-debug.png'});
});
