import {test,expect,type Page} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
const folder='../记录/验证/T-027',errors=new WeakMap<Page,string[]>();
test.beforeEach(async({page})=>{const list:string[]=[];errors.set(page,list);page.on('pageerror',e=>list.push(e.message));});
test.afterEach(async({page})=>expect(errors.get(page)).toEqual([]));
async function promote(page:Page){await page.evaluate(async()=>{const {command}=await import('/src/core/engine.ts' as string);command((window as any).prototype.state,{type:'promoteCommandFocus'});});}
async function begin(page:Page,id='ranger'){await page.goto('/');await page.locator('[data-journey="exploration"]').click();await page.locator(`[data-companion="${id}"]`).click();await page.locator('[data-action="carry"]').click();await page.locator('[data-action="pause"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.terrain.userData.loaded),{timeout:45000}).toBe(true);mkdirSync(folder,{recursive:true});}
async function fixture(page:Page){await page.evaluate(()=>{
 const s=(window as any).prototype.state,h=s.units[0],p=s.units.find((u:any)=>u.id===s.explorationCompanionId),e=s.units.find((u:any)=>u.role==='heavy'),x=h.pos.x+3,y=h.pos.y;s.units=[h,p,e];s.tiles.forEach((t:any)=>{t.obstacle=false;t.layer=0;});h.pos={x:x+1,y};p.pos={x:x-4,y};e.pos={x,y};
 for(const u of s.units){u.drawPos={...u.pos};u.path=[];u.destination=null;u.ready=0;u.hp=u.maxHp=10000;u.posture=u.maxPosture;u.attackTimer=100;u.ai=undefined;u.companionCombat=undefined;u.weapons.forEach((w:any)=>w.weight=0);u.dodge=0;u.defense=undefined;}
 p.life='active';e.enemySense.home={...e.pos};e.enemyMotion='engaged';e.pursuitTargetId=h.id;e.encounterRoom=1;e.encounterId='fixture';e.enemyCombat.armed=true;e.enemyCombat.abilityReadyAt=100;e.statuses=[{kind:'stun',remaining:100,power:0}];s.time=0;s.context='explorationBattle';s.exploration.lastActivity=0;s.exploration.definition.encounters=[{room:1,name:'active fixture',tier:'strong',enemyIds:['fixture'],center:{...e.pos},tacticalRadius:6.5}];
 });}
async function advance(page:Page,t:number){await page.evaluate(async t=>{const {step}=await import('/src/core/engine.ts' as string);step((window as any).prototype.state,t);},t);}
async function proof(page:Page,name:string){await page.screenshot({path:folder+'/'+name+'.png'});const value=await page.evaluate(()=>{const s=(window as any).prototype.state;return {time:s.time,actor:s.controlledBodyId,stats:s.stats,bodies:s.units.map((u:any)=>({id:u.id,pos:u.pos,hp:u.hp,ai:u.companionCombat,evade:u.evasion,blink:u.blink}))};});writeFileSync(folder+'/'+name+'.json',JSON.stringify(value,null,2));return value;}
test('AI Al crosses the old two-unit limit inside its encounter without pulling an inactive group',async({page})=>{await begin(page);await fixture(page);const from=await page.evaluate(()=>{const s=(window as any).prototype.state,e=s.units[2],p=s.units[1],next=structuredClone(e);next.id='inactive';next.encounterRoom=2;next.encounterId='inactive';next.pos={x:e.pos.x+13,y:e.pos.y};next.enemySense.home={...next.pos};next.enemyMotion='route';next.pursuitTargetId=undefined;next.statuses=[];s.units.push(next);s.exploration.definition.encounters.push({room:2,name:'inactive',tier:'normal',enemyIds:['inactive'],center:{...next.pos},tacticalRadius:6.5});return {...p.pos};});await advance(page,3);const v=await proof(page,'cross-room');expect(Math.hypot(v.bodies[1].pos.x-from.x,v.bodies[1].pos.y-from.y)).toBeGreaterThan(2);expect(await page.evaluate(()=>(window as any).prototype.state.units[3].pursuitTargetId)).toBeUndefined();});
test('Al autonomously flanks Heavy and produces a real directional hit',async({page})=>{await begin(page);await fixture(page);await page.evaluate(()=>{const s=(window as any).prototype.state,h=s.units[0],p=s.units[1],e=s.units[2];h.pos={x:e.pos.x,y:e.pos.y+2};p.pos={x:e.pos.x+2.5,y:e.pos.y};p.attackTimer=0;e.heading=0;});await advance(page,4);expect(await page.evaluate(()=>(window as any).prototype.state.combatEvents.some((e:any)=>e.sourceId==='ranger'&&['side','back'].includes(e.direction)))).toBe(true);await proof(page,'flank');});
test('visible Slam has a real reaction delay and walking preserves mobility charges',async({page})=>{await begin(page);await fixture(page);await page.evaluate(async()=>{const s=(window as any).prototype.state,p=s.units[1],e=s.units[2],{startIntent}=await import('/src/core/attack-intent.ts' as string),{advanceCompanionCombat}=await import('/src/core/companion-combat.ts' as string);e.statuses=[];p.pos={x:e.pos.x+1.5,y:e.pos.y};startIntent(s,e,p,'heavy-ground-slam');advanceCompanionCombat(s);});await advance(page,.1);expect(await page.evaluate(()=>(window as any).prototype.state.units[1].path.length)).toBe(0);await advance(page,.12);expect(await page.evaluate(()=>(window as any).prototype.state.units[1].companionCombat.mobilityEscape)).toBe('walk');await advance(page,.95);const v=await proof(page,'walking');expect(v.bodies[1].evade.charges).toBe(2);expect(v.bodies[1].hp).toBe(10000);});
test('companion under real Slow consumes real Evade when walking cannot finish before Slam',async({page})=>{await begin(page);await fixture(page);await page.evaluate(async()=>{const s=(window as any).prototype.state,p=s.units[1],e=s.units[2],{startIntent}=await import('/src/core/attack-intent.ts' as string);e.statuses=[];p.pos={x:e.pos.x+1,y:e.pos.y};p.statuses=[{kind:'slow',power:.9,remaining:5}];startIntent(s,e,p,'heavy-ground-slam');});await advance(page,.25);const v=await proof(page,'ai-evade');expect(v.bodies[1].evade.charges).toBe(1);expect(v.stats.aiMobilityEscapes).toBeGreaterThan(0);});
test('real C leaves Hunter as AI and emergency Blink consumes its charge',async({page})=>{await begin(page);await fixture(page);await page.keyboard.press('c');await promote(page);expect(await page.evaluate(()=>(window as any).prototype.state.controlledBodyId)).toBe('ranger');await page.evaluate(async()=>{const s=(window as any).prototype.state,h=s.units[0],e=s.units[2],{startIntent}=await import('/src/core/attack-intent.ts' as string);e.statuses=[];h.pos={x:e.pos.x+1,y:e.pos.y};h.statuses=[{kind:'slow',power:.9,remaining:5}];startIntent(s,e,h,'heavy-ground-slam');});await advance(page,.25);const v=await proof(page,'ai-blink');expect(v.bodies[0].blink.charges).toBe(9);expect(v.bodies[0].ai.mobilityEscape).toBe('blink');});
test('Ines crosses the old radius to peel a threat to the DirectActor',async({page})=>{await begin(page,'ines');await fixture(page);await advance(page,.05);const a=await page.evaluate(()=>(window as any).prototype.state.units[1].companionCombat);expect(a.intent).toBe('peel');const from=await page.evaluate(()=>(window as any).prototype.state.units[1].pos);await advance(page,2);const v=await proof(page,'ines-peel');expect(Math.hypot(v.bodies[1].pos.x-from.x,v.bodies[1].pos.y-from.y)).toBeGreaterThan(2);});
test('explicit move then real C finishes the destination before AI freely resumes; 20 seconds remain stable',async({page})=>{test.setTimeout(90000);await page.emulateMedia({reducedMotion:'reduce'});await begin(page);await fixture(page);await page.keyboard.press('c');await promote(page);await expect.poll(()=>page.evaluate(()=>{const p=(window as any).prototype,u=p.state.units[1],q=p.project({x:u.pos.x-1,y:u.pos.y-1});const hit=p.scene.pick(q.x,q.y);return !!document.elementFromPoint(q.x,q.y)?.closest('#scene')&&!!hit.tile&&!hit.unitId&&Math.hypot(hit.tile.x-u.pos.x,hit.tile.y-u.pos.y)>.4;})).toBe(true);const to=await page.evaluate(()=>{const p=(window as any).prototype,u=p.state.units[1],q=p.project({x:u.pos.x-1,y:u.pos.y-1});return {...q,hit:p.scene.pick(q.x,q.y).tile};});expect(to.hit).toBeTruthy();await page.mouse.click(to.x,to.y);expect(await page.evaluate(()=>(window as any).prototype.state.units[1].ai.command)).toBe('move');await page.keyboard.press('c');await promote(page);await advance(page,.3);expect(await page.evaluate(()=>(window as any).prototype.state.units[1].ai.command)).toBe('move');await advance(page,1.5);expect(await page.evaluate(()=>(window as any).prototype.state.units[1].ai.command)).toBeUndefined();await advance(page,18.2);const v=await proof(page,'stability');expect(v.time).toBeCloseTo(20);expect(v.bodies[1].ai.targetId).toBeTruthy();expect(await page.evaluate(()=>(window as any).prototype.state.units[1].path.length)).toBe(0);});
test('generated Normal encounter runs twenty simulation seconds with real AI, fog and terrain',async({page})=>{
 test.setTimeout(120000);await begin(page);
 const baseline=await page.evaluate(async()=>{
  const s=(window as any).prototype.state,{canStop,distance}=await import('/src/core/spatial.ts' as string),{updateExplorationEnemy}=await import('/src/core/exploration.ts' as string);
  const group=s.exploration.definition.encounters.find((a:any)=>a.tier==='normal'),h=s.units[0],p=s.units.find((u:any)=>u.id==='ranger');
  const foe=s.units.find((u:any)=>u.encounterRoom===group.room),spots=s.tiles.filter((t:any)=>!t.obstacle&&distance(t,foe.pos)<2&&canStop(s,t,h)).sort((a:any,b:any)=>distance(a,foe.pos)-distance(b,foe.pos));if(!spots.length)throw Error('no legal entry fixture');
  h.pos={x:spots[0].x,y:spots[0].y};p.pos={...spots.find((a:any)=>distance(a,h.pos)>.6&&canStop(s,a,p))||spots[0]};
  for(const u of [h,p]){u.pos={x:u.pos.x,y:u.pos.y};u.drawPos={...u.pos};u.path=[];u.destination=null;u.ready=0;u.attackTimer=0;u.ai=undefined;u.companionCombat=undefined;}
  s.time=0;s.context='explorationBattle';s.exploration.lastActivity=0;for(const e of s.units.filter((u:any)=>u.team==='enemy'))updateExplorationEnemy(s,e);
  return {room:group.room,start:[{...h.pos},{...p.pos}],hp:[h.hp,p.hp]};
 });
 const report=await page.evaluate(async baseline=>{
  const s=(window as any).prototype.state,{step}=await import('/src/core/engine.ts' as string),{activeEncounters}=await import('/src/core/encounter-domain.ts' as string);
  const frames:any[]=[];for(let i=0;i<200;i++){step(s,.1);const h=s.units[0],p=s.units.find((u:any)=>u.id==='ranger');frames.push({time:s.time,pos:{...p.pos},intent:p.companionCombat?.intent,target:p.companionCombat?.targetId,hp:p.hp,rooms:activeEncounters(s).map((a:any)=>a.room),separation:Math.hypot(h.pos.x-p.pos.x,h.pos.y-p.pos.y)});}
  const reversals=frames.slice(2).filter((f,i)=>{const a=frames[i],b=frames[i+1],v={x:b.pos.x-a.pos.x,y:b.pos.y-a.pos.y},w={x:f.pos.x-b.pos.x,y:f.pos.y-b.pos.y};return a.intent===f.intent&&a.target===f.target&&f.intent!=='evade'&&Math.hypot(v.x,v.y)>.02&&Math.hypot(w.x,w.y)>.02&&(v.x*w.x+v.y*w.y)<-.5*Math.hypot(v.x,v.y)*Math.hypot(w.x,w.y);}).length;
  return {baseline,frames,reversals,stats:s.stats,events:s.combatEvents,bodyHp:[s.units[0].hp,s.units.find((u:any)=>u.id==='ranger').hp]};
 },baseline);
 writeFileSync(folder+'/normal-group-simulation.json',JSON.stringify(report,null,2));expect(report.frames.at(-1).time).toBeCloseTo(20);expect(report.reversals).toBeLessThan(5);expect(new Set(report.frames.flatMap(f=>f.rooms))).toEqual(new Set([baseline.room]));expect(report.stats.enemyAbilitiesReleased||0).toBeGreaterThan(0);expect(report.stats.aiWalkingAvoids||report.stats.aiMobilityEscapes||0).toBeGreaterThan(0);expect(report.bodyHp[0]+report.bodyHp[1]).toBeLessThan(baseline.hp[0]+baseline.hp[1]);await proof(page,'normal-group');await page.keyboard.press('Tab');await page.locator('[data-action="debug"]').click();await expect(page.locator('#debug-readings')).toContainText('AI2');await expect(page.locator('#debug-readings')).toContainText('Rooms');await expect(page.locator('#debug-readings')).toContainText('Hazard');await proof(page,'debug-domain');const recovery=await page.evaluate(async()=>{const s=(window as any).prototype.state,{step}=await import('/src/core/engine.ts' as string),before=s.units.find((u:any)=>u.id==='ranger');const interrupted={posture:before.posture,stagger:before.stagger,forced:before.forcedMotion,statuses:before.statuses};for(const e of s.units.filter((u:any)=>u.team==='enemy'))e.life='dead';step(s,15);const h=s.units[0],p=s.units.find((u:any)=>u.id==='ranger');return {interrupted,separation:Math.hypot(h.pos.x-p.pos.x,h.pos.y-p.pos.y),context:s.context,ai:p.companionCombat};});writeFileSync(folder+'/normal-regroup-recovery.json',JSON.stringify(recovery,null,2));expect(recovery.context).toBe('explorationIdle');expect(recovery.ai).toBeUndefined();expect(recovery.separation).toBeLessThanOrEqual(3.5);
});
