import {test,expect,type Page} from '@playwright/test';
import {mkdirSync} from 'node:fs';
const evidence='../记录/验证/T-029';
const errors=new WeakMap<Page,string[]>();
test.beforeEach(async({page})=>{const e:string[]=[];errors.set(page,e);page.on('pageerror',v=>e.push(v.message));});
test.afterEach(async({page})=>expect(errors.get(page)).toEqual([]));
async function begin(page:Page){await page.goto('/');await page.locator('[data-journey="exploration"]').click();await page.locator('[data-companion="ines"]').click();await page.locator('[data-action="carry"]').click();await page.locator('[data-action="pause"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.terrain.userData.loaded),{timeout:45000}).toBe(true);await page.evaluate(()=>{const s=(window as any).prototype.state;s.units=s.units.filter((u:any)=>u.team==='ally');s.units.forEach((u:any)=>{u.stagger=0;u.posture=u.maxPosture;});});}
const controls=(p:Page)=>p.evaluate(()=>{const s=(window as any).prototype.state;return {direct:s.controlledBodyId,focus:s.explorationControl?.commandFocusId,selected:(window as any).prototype.interaction.selectedId};});
test('DirectMode retains temporary legacy ground click movement',async({page})=>{await begin(page);const q=await page.evaluate(async()=>{const p=(window as any).prototype,s=p.state,h=s.units.find((u:any)=>u.id==='hunter'),{command}=await import('/src/core/engine.ts' as string);for(const tile of s.tiles){if(Math.hypot(tile.x-h.pos.x,tile.y-h.pos.y)<1||Math.hypot(tile.x-h.pos.x,tile.y-h.pos.y)>4)continue;const q=p.project(tile),hit=p.scene.pick(q.x,q.y);if(hit.unitId||!hit.tile||!document.elementFromPoint(q.x,q.y)?.closest('#scene'))continue;if(command(structuredClone(s),{type:'move',id:h.id,to:hit.tile}).ok)return q;}throw Error('no reachable empty tile');});await page.mouse.click(q.x,q.y);expect(await controls(page)).toMatchObject({direct:'hunter',focus:null});expect(await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').path.length)).toBeGreaterThan(0);});
test('world original click focuses, clicking current DirectActor clears without selection mirroring',async({page})=>{await begin(page);for(const id of ['ines','hunter']){const q=await page.evaluate(id=>{const p=(window as any).prototype,u=p.state.units.find((u:any)=>u.id===id),q=p.project(u.drawPos||u.pos);for(let dy=-80;dy<=10;dy+=5)for(let dx=-25;dx<=25;dx+=5){const hit={x:q.x+dx,y:q.y+dy};if(p.scene.pick(hit.x,hit.y).unitId===id&&document.elementFromPoint(hit.x,hit.y)?.closest('#scene'))return hit;}throw Error('original not pickable');},id);await page.mouse.click(q.x,q.y);expect(await controls(page)).toEqual({direct:'hunter',focus:id==='ines'?'ines':null,selected:null});}});
async function proof(p:Page,name:string){mkdirSync(evidence,{recursive:true});await p.screenshot({path:evidence+'/'+name+'.png'});}
test('C and original cards focus without takeover, digits toggle current actor, HUD and skills stay separate',async({page})=>{await begin(page);await page.keyboard.press('c');expect(await controls(page)).toEqual({direct:'hunter',focus:'ines',selected:null});await expect(page.locator('[data-unit="ines"]')).toContainText('指令');await expect(page.locator('[data-unit="hunter"]')).toContainText('当前操控');await expect(page.locator('#world-skill [data-skill="hunter"]')).toBeVisible();await page.keyboard.press('3');expect((await controls(page)).focus).toBe('ines');await page.keyboard.press('c');expect((await controls(page)).focus).toBeNull();await page.keyboard.press('2');expect((await controls(page)).focus).toBe('ines');await page.keyboard.press('1');expect((await controls(page)).focus).toBeNull();await page.locator('[data-unit="ines"]').click();expect((await controls(page)).direct).toBe('hunter');await page.locator('[data-unit="hunter"]').click();expect((await controls(page)).focus).toBeNull();await proof(page,'focus-identities');});
test('same W promotes and moves; failure still commits takeover',async({page})=>{await begin(page);await page.keyboard.press('c');await page.locator('[data-action="pause"]').click();await page.keyboard.down('w');await expect.poll(()=>controls(page)).toMatchObject({direct:'ines',focus:null});await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ines').direct?.direction.y)).toBe(-1);await page.keyboard.up('w');await page.locator('[data-action="pause"]').click();await page.keyboard.press('c');await page.evaluate(()=>{const h=(window as any).prototype.state.units[0];h.stagger=10;h.posture=0;});await page.locator('[data-action="pause"]').click();await page.keyboard.press('w');expect((await controls(page)).direct).toBe('hunter');expect((await controls(page)).focus).toBeNull();});
for(const key of ['e','r','t'])test('same '+key+' promotes even empty/cooldown slot',async({page})=>{await begin(page);await page.keyboard.press('c');await page.evaluate(()=>{const s=(window as any).prototype.state,p=s.units.find((u:any)=>u.id==='ines');p.skillSlots=[null,null,null];});await page.locator('[data-action="pause"]').click();await page.keyboard.press(key);expect(await controls(page)).toMatchObject({direct:'ines',focus:null});expect(await page.evaluate(()=>(window as any).prototype.state.tacticalFocus)).toBeUndefined();});
test('Shift depleted still promotes; Escape clears focus, higher modal keeps it',async({page})=>{await begin(page);await page.keyboard.press('c');await page.locator('[data-action="backpack"]').click();await page.keyboard.press('Escape');expect((await controls(page)).focus).toBe('ines');await page.keyboard.press('Escape');expect((await controls(page)).focus).toBeNull();await page.keyboard.press('c');await page.evaluate(()=>{(window as any).prototype.state.units.find((u:any)=>u.id==='ines').evasion.charges=0;});await page.locator('[data-action="pause"]').click();await page.mouse.move(700,430);await page.keyboard.press('Shift');expect(await controls(page)).toMatchObject({direct:'ines',focus:null});});
test('Command ground click issues no path; real clock expires retaining focus and camera primary',async({page})=>{await begin(page);await page.keyboard.press('c');const before=await page.evaluate(()=>{const p=(window as any).prototype,s=p.state;return {paths:s.units.map((u:any)=>JSON.stringify(u.path)),direct:s.controlledBodyId,camera:p.scene.camera.position.toArray()};});const xy=await page.evaluate(()=>{const p=(window as any).prototype,h=p.state.units[0];for(let dx=2;dx<6;dx++){const q=p.project({x:h.pos.x+dx,y:h.pos.y});const hit=p.scene.pick(q.x,q.y);if(hit.tile&&!hit.unitId&&q.x>400&&q.x<innerWidth-100)return q;}throw new Error('no empty ground');});await page.mouse.click(xy.x,xy.y);expect(await page.evaluate(()=>(window as any).prototype.state.units.map((u:any)=>JSON.stringify(u.path)))).toEqual(before.paths);expect((await controls(page)).direct).toBe(before.direct);await page.locator('[data-action="pause"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.tacticalFocus),{timeout:6000}).toBeUndefined();expect((await controls(page)).focus).toBe('ines');await proof(page,'command-mode');});
for(const [key,slot] of [['e',0],['r',1],['t',2]] as const)test('same '+key+' promotes and executes a nonempty ready slot',async({page})=>{await begin(page);await page.evaluate(async slot=>{const s=(window as any).prototype.state,p=s.units.find((u:any)=>u.id==='ines'),{skillState}=await import('/src/core/progression.ts' as string);p.skillSlots=slot===0?['pain',null,null]:['sanctuary',null,null];p.skillSlots[slot]='pain';p.skillId=p.skillSlots[0];skillState(p,'pain').counter=2;p.hp-=50;},slot);await page.keyboard.press('c');await page.locator('[data-action="pause"]').click();await page.keyboard.press(key);expect(await controls(page)).toMatchObject({direct:'ines',focus:null});expect(await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ines').skillStates.pain.counter)).toBe(0);expect(await page.evaluate(()=>(window as any).prototype.state.stats.skills)).toBeGreaterThan(0);});
test('Shift ready promotes and spends one actual partner charge',async({page})=>{await begin(page);await page.keyboard.press('c');await page.locator('[data-action="pause"]').click();await page.mouse.move(700,430);await page.keyboard.press('Shift');expect(await controls(page)).toMatchObject({direct:'ines',focus:null});await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.stats.evadeUses)).toBe(1);expect(await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ines').evasion.charges)).toBe(1);});
test('world skill button keeps DirectActor while focus continues and ground preview is absent',async({page})=>{await begin(page);await page.keyboard.press('c');await page.evaluate(()=>{const h=(window as any).prototype.state.units.find((u:any)=>u.id==='hunter');h.skillStates[h.skillId].cd=0;});await page.locator('#world-skill [data-skill="hunter"]').first().click();expect(await controls(page)).toMatchObject({direct:'hunter',focus:'ines'});await page.mouse.move(710,400);await expect(page.locator('#move-route')).toHaveCSS('display','none');});
test('modal UI blocks focus and all direct takeover keys; paused only blocks direct actions',async({page})=>{await begin(page);await page.locator('[data-action="build"]').first().click();for(const k of ['c','2','w','e','r','t','Shift'])await page.keyboard.press(k);expect(await controls(page)).toMatchObject({direct:'hunter',focus:null});await expect(page.locator('#build-panel')).toBeVisible();await page.keyboard.press('Escape');await page.keyboard.press('c');for(const k of ['w','e','r','t','Shift'])await page.keyboard.press(k);expect(await controls(page)).toMatchObject({direct:'hunter',focus:'ines'});});
test('clone inspection leaves focus and DirectActor independent',async({page})=>{await begin(page);await page.evaluate(async()=>{const p=(window as any).prototype,{command,cloneTiles}=await import('/src/core/engine.ts' as string);p.state.fragments=40;const result=command(p.state,{type:'clone',id:'ines',to:cloneTiles(p.state,'ines')[0]});if(!result.ok)throw Error(result.reason);});await page.keyboard.press('c');await page.locator('[data-copy-select]').first().click();expect(await controls(page)).toMatchObject({direct:'hunter',focus:'ines'});await expect(page.locator('#unit-detail')).toContainText('影复制体');await expect(page.locator('#world-skill [data-skill="hunter"]')).toBeVisible();});
