import {test,expect,type Page} from '@playwright/test';
import {mkdirSync} from 'node:fs';
const evidence='../记录/验证/T-030';
const errors=new WeakMap<Page,string[]>();
test.beforeEach(async({page})=>{const list:string[]=[];errors.set(page,list);page.on('pageerror',e=>list.push(e.message));});
test.afterEach(async({page})=>expect(errors.get(page)).toEqual([]));
async function begin(page:Page){await page.goto('/');await page.locator('[data-journey="exploration"]').click();await page.locator('[data-companion="ines"]').click();await page.locator('[data-action="carry"]').click();await page.locator('[data-action="pause"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.terrain.userData.loaded),{timeout:45000}).toBe(true);await page.evaluate(()=>{const s=(window as any).prototype.state;s.units=s.units.filter((u:any)=>u.team==='ally');s.units.forEach((u:any)=>{u.stagger=0;u.posture=u.maxPosture;u.ready=0;});});await page.keyboard.press('c');}
async function aim(page:Page,kind='path'){return page.evaluate(async kind=>{const p=(window as any).prototype,{command}=await import('/src/core/engine.ts' as string);const r=command(p.state,{type:'beginCommandAim',kind});if(!r.ok)throw Error(r.reason);return p.state.explorationControl.aim;},kind);}
const controls=(p:Page)=>p.evaluate(()=>{const s=(window as any).prototype.state;return {direct:s.controlledBodyId,focus:s.explorationControl?.commandFocusId,aim:s.explorationControl?.aim?.kind};});
async function resume(page:Page){await page.locator('[data-action="pause"]').click();}
for(const key of ['w','e','r','t','Shift'])test('official Aim escapes via real '+key+' and retains takeover on rejected action',async({page})=>{await begin(page);await aim(page,'skill');await page.evaluate(()=>{const s=(window as any).prototype.state,p=s.units.find((u:any)=>u.id==='ines');p.skillSlots=[null,null,null];p.evasion.charges=0;if(p.blink)p.blink.charges=0;});await resume(page);await page.mouse.move(700,430);if(key==='w'){await page.keyboard.down(key);await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ines').direct?.direction.y)).toBe(-1);await page.keyboard.up(key);}else await page.keyboard.press(key);expect(await controls(page)).toEqual({direct:'ines',focus:null,aim:undefined});});
for(const [key,slot] of [['e',0],['r',1],['t',2]] as const)test('Aim escape via '+key+' executes the same ready skill slot',async({page})=>{await begin(page);await page.evaluate(async slot=>{const p=(window as any).prototype.state.units.find((u:any)=>u.id==='ines'),{skillState}=await import('/src/core/progression.ts' as string);p.skillSlots=['pain',null,null];p.skillSlots[slot]='pain';skillState(p,'pain').counter=2;p.hp-=50;},slot);await aim(page,'skill');await resume(page);await page.keyboard.press(key);expect(await controls(page)).toEqual({direct:'ines',focus:null,aim:undefined});expect(await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ines').skillStates.pain.counter)).toBe(0);});
test('Shift from Aim uses one real Evade charge',async({page})=>{await begin(page);await aim(page,'mobility');await resume(page);await page.mouse.move(700,430);await page.keyboard.press('Shift');expect(await controls(page)).toEqual({direct:'ines',focus:null,aim:undefined});await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.stats.evadeUses)).toBe(1);});
test('Escape cancels only Aim; modal and paused takeover remain guarded',async({page})=>{await begin(page);await aim(page);await page.locator('[data-action="backpack"]').click();for(const key of ['w','e','r','t','Shift'])await page.keyboard.press(key);expect(await controls(page)).toMatchObject({direct:'hunter',focus:'ines',aim:'path'});await page.keyboard.press('Escape');expect((await controls(page)).aim).toBe('path');for(const key of ['w','e','r','t','Shift'])await page.keyboard.press(key);expect((await controls(page)).aim).toBe('path');await page.keyboard.press('Escape');expect(await controls(page)).toEqual({direct:'hunter',focus:'ines',aim:undefined});await page.keyboard.press('Escape');expect((await controls(page)).focus).toBeNull();});
test('Focus alone follows; Aim stops; cancellation replans after leader changes',async({page})=>{await begin(page);await page.evaluate(()=>{const s=(window as any).prototype.state,h=s.units[0],p=s.units.find((u:any)=>u.id==='ines');s.tiles.forEach((t:any)=>{t.obstacle=false;t.layer=0;});h.pos={x:15,y:10};p.pos={x:10,y:10};s.context='explorationIdle';});await resume(page);await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ines').following)).toBe(true);await aim(page);const pos=await page.evaluate(()=>({...((window as any).prototype.state.units.find((u:any)=>u.id==='ines').pos)}));await page.waitForTimeout(500);expect(await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ines').pos)).toEqual(pos);await page.locator('[data-action="debug"]').click();await expect(page.locator('#command-reservation-readings')).toContainText('ready');await expect(page.locator('#command-reservation-readings')).toContainText('Reserved true');mkdirSync(evidence,{recursive:true});await page.screenshot({path:evidence+'/reservation-ready.png'});await page.evaluate(()=>{(window as any).prototype.state.units[0].pos={x:18,y:13};});await page.keyboard.press('Escape');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ines').path.length)).toBeGreaterThan(0);expect((await controls(page)).focus).toBe('ines');});
test('real pending Basic resolves once while Aim blocks its next start',async({page})=>{await begin(page);await page.evaluate(()=>{const s=(window as any).prototype.state,h=s.units[0],p=s.units.find((u:any)=>u.id==='ines');s.tiles.forEach((t:any)=>{t.obstacle=false;t.layer=0;});h.pos={x:17,y:12};p.pos={x:15,y:10};p.drawPos={...p.pos};p.facing='west';p.heading=Math.PI;p.attackTimer=0;p.path=[];p.destination=null;p.following=false;p.attackPending={targetId:'fixture',remaining:.2,facing:'west'};const e={...structuredClone(p),id:'fixture',team:'enemy',role:'heavy',pos:{x:14,y:10},drawPos:{x:14,y:10},hp:10000,maxHp:10000,path:[],skillSlots:undefined,skillStates:undefined,attackPending:undefined,attackTimer:100,enemyMotion:'engaged',pursuitTargetId:'hunter',statuses:[{kind:'stun',power:0,remaining:100}],encounterRoom:1,encounterId:'fixture'};s.units.push(e);s.context='explorationBattle';s.exploration.definition.encounters=[{room:1,name:'fixture',tier:'strong',enemyIds:['fixture'],center:e.pos,tacticalRadius:6.5}];});await aim(page);await resume(page);await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='fixture').hp)).toBeLessThan(10000);const hp=await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='fixture').hp);await page.waitForTimeout(600);expect(await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='fixture').hp)).toBe(hp);expect(await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ines').attackPending)).toBeUndefined();});
test('reserved Focus remains in real Ability area and takes damage',async({page})=>{await begin(page);await page.evaluate(async()=>{const s=(window as any).prototype.state,h=s.units[0],p=s.units.find((u:any)=>u.id==='ines'),{createGame,command}=await import('/src/core/engine.ts' as string),{startIntent}=await import('/src/core/attack-intent.ts' as string);const seed=createGame();command(seed,{type:'selectJourney',journey:'exploration'});command(seed,{type:'selectExplorationCompanion',id:'ranger'});command(seed,{type:'carry',gold:0,vitality:0});const e=structuredClone(seed.units.find((u:any)=>u.role==='heavy'));s.tiles.forEach((t:any)=>{t.obstacle=false;t.layer=0;});h.pos={x:17,y:12};p.pos={x:15,y:10};p.drawPos={...p.pos};p.hp=p.maxHp=10000;p.path=[];p.destination=null;p.following=false;e.id='ability-fixture';e.pos={x:14,y:10};e.drawPos={...e.pos};e.enemySense.home={...e.pos};e.enemyMotion='engaged';e.pursuitTargetId=h.id;e.encounterRoom=1;e.encounterId='fixture';e.enemyCombat.armed=true;e.enemyCombat.abilityReadyAt=100;e.attackTimer=100;s.units.push(e);s.context='explorationBattle';s.exploration.definition.encounters=[{room:1,name:'fixture',tier:'strong',enemyIds:['fixture'],center:e.pos,tacticalRadius:6.5}];startIntent(s,e,p,'heavy-ground-slam');});await aim(page,'skill');await resume(page);await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ines').hp),{timeout:12000}).toBeLessThan(10000);expect((await controls(page)).aim).toBe('skill');mkdirSync(evidence,{recursive:true});await page.screenshot({path:evidence+'/reserved-real-damage.png'});});
