import {test,expect,type Page} from '@playwright/test';
import {mkdirSync} from 'node:fs';
test.setTimeout(60000);
test.beforeEach(async({page})=>{page.on('pageerror',e=>{throw e;});});
async function begin(page:Page){await page.goto('/');await page.locator('[data-journey="exploration"]').click();await page.locator('[data-companion="ranger"]').click();await page.locator('[data-action="carry"]').click();await page.locator('[data-action="pause"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.terrain.userData.loaded),{timeout:45000}).toBe(true);await page.evaluate(()=>{const s=(window as any).prototype.state;s.units=s.units.filter((u:any)=>u.team==='ally');s.units.forEach((u:any)=>{u.ready=0;u.stagger=0;u.path=[];u.destination=null;u.attackTimer=100;u.autoSkill=false;});});}
async function target(page:Page,exclude?:any){return page.evaluate(async(exclude)=>{const p=(window as any).prototype,s=p.state,{queryPathAimPreview}=await import('/src/core/path-aim.ts' as string),u=s.units.find((a:any)=>a.id===(s.explorationControl.aim?.actorId||s.controlledBodyId));for(const tile of s.tiles){const d=Math.hypot(tile.x-u.pos.x,tile.y-u.pos.y);if(d<1.5||d>4||exclude&&Math.hypot(tile.x-exclude.x,tile.y-exclude.y)<1)continue;const q=p.project(tile),hit=p.scene.pick(q.x,q.y);if(!hit.tile||hit.unitId||!document.elementFromPoint(q.x,q.y)?.closest('#scene'))continue;if(queryPathAimPreview(s,u,hit.tile).valid)return {q,to:hit.tile,id:u.id};}throw Error('no reachable pickable destination');},exclude);}
const state=(page:Page)=>page.evaluate(()=>{const s=(window as any).prototype.state;return {orders:s.explorationControl.moveOrders||{},aim:s.explorationControl.aim,direct:s.controlledBodyId,focus:s.explorationControl.commandFocusId};});
async function issue(page:Page,exclude?:any){await page.keyboard.press('f');const t=await target(page,exclude);await page.mouse.click(t.q.x,t.q.y);const to=(await state(page)).orders[t.id]?.destination;expect(to).toBeDefined();expect(Math.hypot(to.x-t.to.x,to.y-t.to.y)).toBeLessThan(.1);return {...t,to};}
test('A real Command F/LMB order walks to arrival without Follow stealing it',async({page})=>{await begin(page);await page.keyboard.press('c');const t=await issue(page);expect(await state(page)).toMatchObject({direct:'hunter',focus:'ranger',aim:undefined});await page.evaluate(async()=>{const s=(window as any).prototype.state,p=s.units.find((u:any)=>u.id==='ranger'),{createGame,command}=await import('/src/core/engine.ts' as string),f=createGame();command(f,{type:'selectJourney',journey:'exploration'});command(f,{type:'selectExplorationCompanion',id:'ines'});command(f,{type:'carry',gold:0,vitality:0});const e=structuredClone(f.units.find((u:any)=>u.role==='heavy'));Object.assign(e,{id:'order-encounter',pos:{x:p.pos.x+1,y:p.pos.y},drawPos:{x:p.pos.x+1,y:p.pos.y},hp:1,defense:undefined,dodge:0,ready:0,attackTimer:100,speed:0,enemyMotion:'engaged',pursuitTargetId:'hunter',encounterRoom:1});e.enemyCombat.abilityReadyAt=100;e.enemySense.home={...e.pos};s.units.push(e);s.context='explorationBattle';s.exploration.definition.encounters=[{room:1,name:'order fixture',tier:'strong',enemyIds:[e.id],center:{...p.pos},tacticalRadius:6.5}];p.attackTimer=0;p.weapons.forEach((w:any)=>w.weight=0);p.facing='east';});await page.keyboard.press('Space');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').attackPending?.targetId),{timeout:15000}).toBe('order-encounter');expect((await state(page)).orders.ranger.suspendReason).toBe('basic');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='order-encounter').hp),{timeout:15000}).toBe(0);await expect.poll(()=>page.evaluate(id=>!!(window as any).prototype.state.explorationControl.moveOrders[id],t.id),{timeout:30000}).toBe(false);expect(await page.evaluate(to=>(window as any).prototype.state.log.some((l:string)=>l.includes('arrived')),t.to)).toBe(true);});
test('B re-Aim freezes original order; RMB resumes from live position',async({page})=>{await begin(page);await page.keyboard.press('c');const t=await issue(page),id=(await state(page)).orders.ranger.id;await page.keyboard.press('f');expect((await state(page)).orders.ranger).toMatchObject({state:'suspended',suspendReason:'aim',id});await page.mouse.click(t.q.x,t.q.y,{button:'right'});await page.keyboard.press('Space');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.explorationControl.moveOrders.ranger?.state)).toBe('moving');expect((await state(page)).orders.ranger).toMatchObject({id,destination:t.to});});
test('C confirming B replaces A for only its actor',async({page})=>{await begin(page);await page.keyboard.press('c');const a=await issue(page),id=(await state(page)).orders.ranger.id,b=await issue(page,a.to);expect((await state(page)).orders.ranger.destination).toEqual(b.to);expect((await state(page)).orders.ranger.id).not.toBe(id);});
test('D WASD takeover cancels; release never restores old order',async({page})=>{await begin(page);await page.keyboard.press('c');await issue(page);await page.keyboard.press('Space');await page.keyboard.down('w');await expect.poll(async()=>(await state(page)).direct).toBe('ranger');await expect.poll(async()=>!!(await state(page)).orders.ranger).toBe(false);await page.keyboard.up('w');await page.waitForTimeout(200);expect((await state(page)).orders.ranger).toBeUndefined();});
test('E failed skill/no-charge Blink preserves the existing order',async({page})=>{await begin(page);const t=await issue(page),id=(await state(page)).orders.hunter.id;await page.evaluate(()=>{const h=(window as any).prototype.state.units[0];h.blink.charges=0;Object.values(h.skillStates).forEach((a:any)=>a.cd=100);});await page.keyboard.press('Space');await page.keyboard.press('e');await page.keyboard.press('r');expect((await state(page)).orders.hunter).toMatchObject({id,destination:t.to});});
test('F actual Break2 impact retains order and recovers from the displaced body',async({page})=>{await begin(page);await page.keyboard.press('c');const t=await issue(page);await page.evaluate(async()=>{const s=(window as any).prototype.state,p=s.units.find((u:any)=>u.id==='ranger'),{resolveHit}=await import('/src/core/engine.ts' as string);p.posture=0;p.weapons.forEach((w:any)=>w.weight=0);resolveHit(s,p,s.units[0].weapons[0],.1,s.units[0],{kind:'ability',postureDamage:999,impact:{distance:.5,direction:{x:0,y:1},wallPin:false}});});await page.keyboard.press('Space');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.explorationControl.moveOrders.ranger?.suspendReason)).toBe('forced');expect((await state(page)).orders.ranger.destination).toEqual(t.to);await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.explorationControl.moveOrders.ranger?.state),{timeout:6000}).toBe('moving');});
test('G two bodies keep separate orders in the same frame',async({page})=>{await begin(page);const h=await issue(page);await page.keyboard.press('c');const p=await issue(page);expect((await state(page)).orders).toMatchObject({hunter:{source:'direct',destination:h.to},ranger:{source:'command',destination:p.to}});});
test('H Focus clear/switch preserves the actor-owned order; capture real view',async({page})=>{await begin(page);await page.keyboard.press('c');const t=await issue(page),id=(await state(page)).orders.ranger.id;for(const key of ['c','1','2'])await page.keyboard.press(key);expect((await state(page)).orders.ranger).toMatchObject({id,destination:t.to});mkdirSync('../记录/验证/T-032',{recursive:true});await page.screenshot({path:'../记录/验证/T-032/双层控制与持续命令.png'});});
