import {expect,test} from 'vitest';
import {createGame,command,step} from '../src/core/engine';
import {startIntent} from '../src/core/attack-intent';
import {BASIC_PROFILES,advanceBasicInputs,requestBasic,autoBasicAllowed} from '../src/core/basic-chain';
import {advanceCommandDefense,commandDefenseEligible,commandDefenseMobility} from '../src/core/command-defense';
import {advanceMoveOrders} from '../src/core/move-order';
import {queryEvade} from '../src/core/evasion';
import {commandReserved,localAutoCombatAllowed} from '../src/core/exploration-control';
import {skillState} from '../src/core/progression';
export function fixture(){
 const s=createGame();command(s,{type:'selectJourney',journey:'exploration'});command(s,{type:'selectExplorationCompanion',id:'ranger'});command(s,{type:'carry',gold:0,vitality:0});
 s.tiles.forEach(t=>{t.obstacle=false;t.layer=0;});const h=s.units[0],p=s.units.find(u=>u.id==='ranger')!,e=s.units.find(u=>u.role==='heavy')!;s.units=[h,p,e];
 h.pos={x:15,y:10};p.pos={x:10,y:10};e.pos={x:16,y:10};for(const u of s.units){u.drawPos={...u.pos};u.path=[];u.ready=0;u.attackTimer=0;u.skillSlots=[null,null,null];u.weapons.forEach(w=>w.weight=0);u.hp=u.maxHp=10000;}
 p.attackTimer=100;e.attackTimer=100;e.speed=0;e.enemyMotion='engaged';e.pursuitTargetId=h.id;e.enemySense!.home={...e.pos};e.encounterRoom=1;e.enemyCombat!.abilityReadyAt=100;e.statuses=[{kind:'stun',remaining:100,power:0}];s.context='explorationBattle';s.exploration!.definition.encounters=[{room:1,name:'fixture',tier:'strong',enemyIds:[e.id],center:{...h.pos},tacticalRadius:6.5}];return {s,h,p,e};
}
const basic=(s:any,id:string,aim:any,requestId:number)=>command(s,{type:'basic',id,aim,requestId} as any);
const run=(s:any,t:number)=>{for(let i=0;i<t-1e-8;i+=.02)step(s,.02);};
test('Direct does not auto Basic, one request produces one stage and one hit',()=>{const {s,h,e}=fixture();run(s,.4);expect(h.attackPending).toBeUndefined();expect(basic(s,h.id,e.pos,1).ok).toBe(true);run(s,2);expect((h as any).basicChain.stageIndex).toBe(0);expect(s.stats.basicAttacksReleased).toBe(1);});
test('second actual input starts A2; duplicate, early spam and target change cannot bypass recovery',()=>{const {s,h,e}=fixture();expect(basic(s,h.id,e.pos,1).ok).toBe(true);const allowed=(h as any).basicChain.nextStageAllowedAt;for(let i=2;i<12;i++)expect(basic(s,h.id,e.pos,i).ok).toBe(false);expect((h as any).basicChain.nextStageAllowedAt).toBe(allowed);run(s,allowed);expect(basic(s,h.id,e.pos,12).ok).toBe(true);expect((h as any).basicChain.stageIndex).toBe(1);expect(basic(s,h.id,e.pos,12).ok).toBe(false);});
test('single short buffer consumes once and dead target cannot redirect it',()=>{const {s,h,e}=fixture();basic(s,h.id,e.pos,1);run(s,(h as any).basicChain.nextStageAllowedAt-.1);expect(basic(s,h.id,e.pos,2).ok).toBe(true);expect((h as any).basicChain.buffer).toBeDefined();e.life='dead';run(s,.3);expect((h as any).basicChain.buffer).toBeUndefined();expect((h as any).basicChain.stageIndex).toBe(0);});
test('whiff commits, cancels only own Order, and never damages opposite-direction enemy',()=>{const {s,h,e}=fixture();command(s,{type:'beginExplorationAim',id:h.id,kind:'path',source:'direct'});command(s,{type:'confirmPathAim',to:{x:15,y:13}});const hp=e.hp;expect(basic(s,h.id,{x:14,y:10},1).ok).toBe(true);expect(s.explorationControl?.moveOrders?.[h.id]).toBeUndefined();run(s,.3);expect(e.hp).toBe(hp);expect(s.stats.basicAttacksReleased||0).toBe(0);});
test('Command gives Direct limited defensive walk without changing identity or starting Basic',()=>{const {s,h,p,e}=fixture();e.pos={x:14,y:10};e.statuses=[];startIntent(s,e,h,'heavy-ground-slam');command(s,{type:'commandFocus',id:p.id});run(s,.24);expect((h as any).commandDefense?.action).toBe('walk');expect(h.path.length).toBeGreaterThan(0);expect(s.controlledBodyId).toBe(h.id);expect(h.attackPending).toBeUndefined();});
test('Command Aim reserves only focus and keeps defensive authorization after slow window',()=>{const {s,h,p}=fixture();command(s,{type:'commandFocus',id:p.id});command(s,{type:'beginCommandAim',kind:'path'});s.tacticalFocus=undefined;step(s,.02);expect((h as any).commandDefense).toBeDefined();expect(s.explorationControl?.aim?.actorId).toBe(p.id);});
test('buffer commits exactly one A2, then stops; profiles support three real stages',()=>{const {s,h,e}=fixture();BASIC_PROFILES.proof=[...BASIC_PROFILES.default,BASIC_PROFILES.default[0]];h.basicProfileId='proof';basic(s,h.id,e.pos,1);run(s,h.basicChain!.nextStageAllowedAt-.1);basic(s,h.id,e.pos,2);run(s,.14);expect(h.basicChain!.stageIndex).toBe(1);run(s,h.basicChain!.nextStageAllowedAt-s.time);basic(s,h.id,e.pos,3);expect(h.basicChain!.stageIndex).toBe(2);run(s,3);expect(s.stats.basicStagesStarted).toBe(3);delete BASIC_PROFILES.proof;});
test.each(['beginAim','focus','switch','clearInput','stagger','death','WASD','newOrder','weapon'])('%s invalidates unconsumed input, not recovery',kind=>{const {s,h,p,e}=fixture();basic(s,h.id,e.pos,1);run(s,h.basicChain!.nextStageAllowedAt-.1);basic(s,h.id,e.pos,2);const allowed=h.basicChain!.nextStageAllowedAt;
 if(kind==='beginAim')command(s,{type:'beginExplorationAim',id:h.id,kind:'path',source:'direct'});
 if(kind==='focus')command(s,{type:'commandFocus',id:p.id});if(kind==='switch')command(s,{type:'controlBody',id:p.id});if(kind==='clearInput')command(s,{type:'clearBasicInputs'});if(kind==='stagger')h.stagger=1;if(kind==='death')h.life='dead';if(kind==='WASD')command(s,{type:'direct',id:h.id,direction:{x:0,y:1}});if(kind==='weapon')command(s,{type:'switchWeapon',id:h.id});
 if(kind==='newOrder'){command(s,{type:'beginExplorationAim',id:h.id,kind:'path',source:'direct'});command(s,{type:'confirmPathAim',to:{x:15,y:13}});}
 advanceBasicInputs(s);if(kind==='death'){expect(h.basicChain).toBeUndefined();return;}expect(h.basicChain!.buffer).toBeUndefined();expect(h.basicChain!.nextStageAllowedAt).toBe(allowed);
});
test('source never grants permanent AI permission; Auto skill gate remains independent',()=>{const {s,h,p,e}=fixture();expect(requestBasic(s,h,e.pos,1,'companion-ai').ok).toBe(false);command(s,{type:'controlBody',id:p.id});expect(requestBasic(s,h,e.pos,2,'companion-ai').ok).toBe(true);command(s,{type:'controlBody',id:h.id});expect(autoBasicAllowed(s,h)).toBe(false);expect(localAutoCombatAllowed(s,h)).toBe(true);expect(requestBasic(s,h,e.pos,3,'order-auto').ok).toBe(false);});
test('manual moving target whiffs at Release, later explicit new target starts A1',()=>{const {s,h,e}=fixture();basic(s,h.id,e.pos,1);const hp=e.hp;e.pos={x:25,y:10};run(s,.3);expect(e.hp).toBe(hp);run(s,h.basicChain!.nextStageAllowedAt-s.time);e.pos={x:14,y:10};expect(basic(s,h.id,e.pos,2).ok).toBe(true);expect(h.basicChain!.stageIndex).toBe(0);});
test('normal Direct, invalid focus and idle have no defense authority; another actor Aim does not deny it',()=>{const {s,h,p}=fixture();expect(commandDefenseEligible(s,h)).toBe(false);command(s,{type:'commandFocus',id:p.id});expect(commandDefenseEligible(s,h)).toBe(true);expect(commandDefenseEligible(s,p)).toBe(false);command(s,{type:'beginCommandAim',kind:'skill'});expect(commandReserved(s,p)).toBe(true);expect(commandDefenseEligible(s,h)).toBe(true);command(s,{type:'cancelCommandAim'});expect(commandDefenseEligible(s,h)).toBe(true);s.context='explorationIdle';expect(commandDefenseEligible(s,h)).toBe(false);});
test.each(['hunter','ranger'])('%s emergency defense consumes one real resource and respects requester authority',id=>{const {s,h,p,e}=fixture();const u=id==='hunter'?h:p,other=id==='hunter'?p:h;u.pos={x:15,y:10};other.pos={x:10,y:10};e.pos={x:14,y:10};e.statuses=[];command(s,{type:'controlBody',id:u.id});command(s,{type:'commandFocus',id:other.id});startIntent(s,e,u,'heavy-ground-slam');advanceCommandDefense(s);s.time=.9;const charges=u.id==='hunter'?u.blink!.charges:u.evasion!.charges;advanceCommandDefense(s);expect(u.commandDefense?.action).toBe(id==='hunter'?'blink':'evade');expect(id==='hunter'?u.blink!.charges:u.evasion!.charges).toBe(charges-1);advanceCommandDefense(s);expect(id==='hunter'?u.blink!.charges:u.evasion!.charges).toBe(charges-1);if(id==='ranger')expect(queryEvade(s,u,true).ok).toBe(false);command(s,{type:'commandFocus',id:null});expect(commandDefenseMobility(s,u,{x:1,y:0}).ok).toBe(false);});
test.each(['noResource','stagger','foreground','crossing','forced'])('defense %s cannot cheat real action lifecycle',kind=>{const {s,h,p,e}=fixture();e.pos={x:14,y:10};e.statuses=[];command(s,{type:'commandFocus',id:p.id});startIntent(s,e,h,'heavy-ground-slam');advanceCommandDefense(s);s.time=.9;if(kind==='noResource')h.blink!.charges=0;if(kind==='stagger')h.stagger=1;if(kind==='foreground'){h.skillSlots=['hunt',null,null];skillState(h,'hunt').time=1;}if(kind==='crossing')h.crossing={from:{...h.pos},to:{x:15,y:11},elapsed:0,switched:false};if(kind==='forced')h.forcedMotion={from:{...h.pos},to:{x:15,y:11},startedAt:0,duration:1} as any;const pos={...h.pos},charges=h.blink!.charges;advanceCommandDefense(s);expect(h.pos).toEqual(pos);expect(h.blink!.charges).toBe(charges);});
test('ability first walks preserving resources; order is suspended under defense owner and restored from new position',()=>{const {s,h,p,e}=fixture();command(s,{type:'beginExplorationAim',id:h.id,kind:'path',source:'direct'});command(s,{type:'confirmPathAim',to:{x:15,y:13}});const o={...s.explorationControl!.moveOrders![h.id]},charges=h.blink!.charges;command(s,{type:'commandFocus',id:p.id});e.pos={x:14,y:10};e.statuses=[];startIntent(s,e,h,'heavy-ground-slam');advanceCommandDefense(s);s.time=.2;advanceCommandDefense(s);const owned=h.path;advanceMoveOrders(s);expect(h.path).toBe(owned);expect(s.explorationControl!.moveOrders![h.id]).toMatchObject({id:o.id,source:o.source,destination:o.destination,state:'suspended',suspendReason:'defense'});expect(h.blink!.charges).toBe(charges);command(s,{type:'commandFocus',id:null});expect(h.path).toEqual([]);e.attackIntent=undefined;h.pos={x:15,y:11};advanceMoveOrders(s);expect(h.path.at(-1)).toEqual(o.destination);});
test('proximity uses only short walking; safe body holds and spends no mobility',()=>{const {s,h,p,e}=fixture();e.statuses=[];command(s,{type:'commandFocus',id:p.id});const b=h.blink!.charges;advanceCommandDefense(s);expect(h.commandDefense?.reason).toBe('visible-proximity');expect(h.commandDefense?.action).toBe('walk');expect(h.blink!.charges).toBe(b);e.pos={x:25,y:10};command(s,{type:'commandFocus',id:null});command(s,{type:'commandFocus',id:p.id});advanceCommandDefense(s);expect(h.commandDefense?.action).toBe('hold');expect(h.path).toEqual([]);});
test('exit never clears a newer player path and successful input wins over defense',()=>{const {s,h,p}=fixture();command(s,{type:'commandFocus',id:p.id});advanceCommandDefense(s);const path=[{x:15,y:13}];h.path=path;command(s,{type:'commandFocus',id:null});expect(h.path).toBe(path);});

test('real Ability Release hits an unassisted Direct but defensive walk avoids it',()=>{const baseline=fixture(),defended=fixture();for(const {s,h,e} of [baseline,defended]){e.pos={x:14,y:10};e.statuses=[];startIntent(s,e,h,'heavy-ground-slam');}const charges=defended.h.blink!.charges;command(defended.s,{type:'commandFocus',id:defended.p.id});run(baseline.s,1.3);run(defended.s,1.3);expect(baseline.h.hp).toBeLessThan(baseline.h.maxHp);expect(defended.h.hp).toBe(defended.h.maxHp);expect(defended.s.stats.commandDefenseWalks).toBeGreaterThan(0);expect(defended.h.blink!.charges).toBe(charges);expect(defended.s.stats.basicStagesStarted||0).toBe(0);});
test('real late threat with no mobility resource still deals damage',()=>{const {s,h,p,e}=fixture();e.pos={x:14,y:10};e.statuses=[];command(s,{type:'commandFocus',id:p.id});startIntent(s,e,h,'heavy-ground-slam');e.attackIntent!.phase='locked';e.attackIntent!.resolveAt=.05;h.blink!.charges=0;h.commandDefense={action:'hold',reason:'observed',nextDecision:0,hazards:{[e.id+':'+e.attackIntent!.startedAt]:-.3}};run(s,.1);expect(h.hp).toBeLessThan(h.maxHp);expect(h.blink!.charges).toBe(0);expect(s.stats.commandDefenseMobility||0).toBe(0);});
test('Standalone clone retains legacy automatic Basic without granting Direct authority',()=>{const {s,h,e}=fixture();const c=structuredClone(h);c.id='proof-clone';c.cloneOf=h.id;c.pos={x:16,y:11};c.facing='north';c.ai=undefined;c.basicChain=undefined;c.attackTimer=0;s.units.push(c);run(s,.06);expect(c.attackPending).toBeDefined();expect(h.attackPending).toBeUndefined();});

test('D14 Focus preserves a committed stage and never auto chains it',()=>{const {s,h,p,e}=fixture();basic(s,h.id,e.pos,1);command(s,{type:'commandFocus',id:p.id});const hp=e.hp;run(s,.3);expect(e.hp).toBeLessThan(hp);run(s,2);expect(s.stats.basicStagesStarted).toBe(1);});
test('D20 no Order means defense stops at new safe point, with no rubberband',()=>{const {s,h,p,e}=fixture();e.pos={x:14,y:10};e.statuses=[];command(s,{type:'commandFocus',id:p.id});startIntent(s,e,h,'heavy-ground-slam');run(s,1.3);e.pos={x:25,y:10};const at={...h.pos};run(s,1);expect(h.path).toEqual([]);expect(h.pos).toEqual(at);expect(s.explorationControl?.moveOrders?.[h.id]).toBeUndefined();});
test('failed Basic preserves Order, and a successful player action overrides defensive route',()=>{const {s,h,p,e}=fixture();command(s,{type:'beginExplorationAim',id:h.id,kind:'path',source:'direct'});command(s,{type:'confirmPathAim',to:{x:15,y:13}});const o=s.explorationControl!.moveOrders![h.id];h.stagger=1;expect(basic(s,h.id,e.pos,1).ok).toBe(false);expect(s.explorationControl!.moveOrders![h.id]).toBe(o);h.stagger=0;e.statuses=[];command(s,{type:'commandFocus',id:p.id});advanceCommandDefense(s);expect(h.commandDefense?.ownedPath).toBe(h.path);const charges=h.blink!.charges;command(s,{type:'commandFocus',id:null});expect(command(s,{type:'direct',id:h.id,direction:{x:0,y:1}}).ok).toBe(true);advanceCommandDefense(s);expect(h.commandDefense).toBeUndefined();expect(h.direct?.direction).toEqual({x:0,y:1});expect(h.blink!.charges).toBe(charges);});

test('D10 enclosed physical map has no safe route and permits real damage',()=>{const {s,h,p,e}=fixture();e.pos={x:14,y:10};e.statuses=[];for(const t of s.tiles)t.obstacle=!(t.y===10&&(t.x===14||t.x===15));command(s,{type:'commandFocus',id:p.id});startIntent(s,e,h,'heavy-ground-slam');const charges=h.blink!.charges;run(s,1.3);expect(h.hp).toBeLessThan(h.maxHp);expect(h.blink!.charges).toBe(charges);expect(h.path).toEqual([]);});
test('D15 mobility Aim reserves focus independently from original Direct defense',()=>{const {s,h,p,e}=fixture();command(s,{type:'commandFocus',id:p.id});command(s,{type:'beginCommandAim',kind:'mobility'});expect(commandReserved(s,p)).toBe(true);expect(commandDefenseEligible(s,h)).toBe(true);e.pos={x:14,y:10};e.statuses=[];startIntent(s,e,h,'heavy-ground-slam');run(s,.24);expect(h.commandDefense?.action).toBe('walk');expect(s.explorationControl?.aim?.actorId).toBe(p.id);});

test('incapacitated nearby enemy is not pressure and committed Basic remains legal',()=>{const {s,h,p,e}=fixture();command(s,{type:'commandFocus',id:p.id});advanceCommandDefense(s);expect(h.commandDefense?.action).toBe('hold');expect(h.path).toEqual([]);});
test('exit during owned crossing finishes only the atomic edge, not old defense remainder',()=>{const {s,h,p}=fixture();command(s,{type:'commandFocus',id:p.id});h.path=[{x:15,y:11},{x:15,y:12}];h.commandDefense={action:'walk',reason:'fixture',nextDecision:0,ownedPath:h.path};h.crossing={from:{...h.pos},to:{x:15,y:11},elapsed:.1,switched:false};const cross=h.crossing;command(s,{type:'commandFocus',id:null});expect(h.crossing).toBe(cross);expect(h.path).toEqual([{x:15,y:11}]);expect(h.commandDefense).toBeUndefined();});
