import {test,expect,type Page} from '@playwright/test';
import {mkdirSync} from 'node:fs';
test.setTimeout(60000);
const errors=new WeakMap<Page,string[]>();
test.beforeEach(async({page})=>{const e:string[]=[];errors.set(page,e);page.on('pageerror',x=>e.push(x.message));});
test.afterEach(async({page})=>expect(errors.get(page)).toEqual([]));
async function begin(page:Page,companion='ranger'){await page.goto('/');await page.locator('[data-journey="exploration"]').click();await page.locator('[data-companion="'+companion+'"]').click();await page.locator('[data-action="carry"]').click();await page.locator('[data-action="pause"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.terrain.userData.loaded),{timeout:45000}).toBe(true);
 await page.evaluate(()=>{const s=(window as any).prototype.state;s.units=s.units.filter((u:any)=>u.team==='ally'&&(u.id==='hunter'||u.id===s.explorationCompanionId));s.tiles.forEach((t:any)=>{t.obstacle=false;t.layer=0;});for(const u of s.units){u.ready=0;u.stagger=0;u.path=[];u.destination=null;u.attackTimer=0;u.skillSlots=[null,null,null];u.weapons.forEach((w:any)=>w.weight=0);u.hp=u.maxHp=10000;}s.units[0].pos={x:15,y:10};s.units[0].drawPos={x:15,y:10};s.units[1].pos={x:10,y:10};s.units[1].drawPos={x:10,y:10};s.context='explorationBattle';});await page.waitForTimeout(1200);}
async function ground(page:Page){return page.evaluate(()=>{const p=(window as any).prototype,s=p.state,h=s.units.find((u:any)=>u.id===s.controlledBodyId);for(const tile of s.tiles){if(s.exploration.definition.points.some((a:any)=>Math.hypot(a.pos.x-tile.x,a.pos.y-tile.y)<1)||Math.hypot(s.exploration.definition.exit.x-tile.x,s.exploration.definition.exit.y-tile.y)<1)continue;if(Math.hypot(tile.x-h.pos.x,tile.y-h.pos.y)<.8||Math.hypot(tile.x-h.pos.x,tile.y-h.pos.y)>3)continue;const q=p.project(tile),hit=p.scene.pick(q.x,q.y);if(hit.tile&&!hit.unitId&&[[-15,-15],[-15,15],[15,-15],[15,15]].every(([dx,dy])=>document.elementFromPoint(q.x+dx,q.y+dy)?.closest('#scene')&&!p.scene.pick(q.x+dx,q.y+dy).unitId))return {q,aim:hit.tile};}throw Error('no empty ground');});}
test('empty swing Release keeps animation and requests one sound without Hit',async({page})=>{await begin(page);await page.evaluate(async()=>{const a=(window as any).prototype.audio,old=a.play;(window as any).swingSounds=[];a.play=function(name:any){(window as any).swingSounds.push({name,time:(window as any).prototype.state.time,context:this.context?.state,muted:this.muted});return old.call(this,name);};});await page.keyboard.press('Space');const t=await ground(page);await page.mouse.click(t.q.x,t.q.y);await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units[0].attackPending?.remaining)).toBeDefined();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units[0].attackPending),{timeout:8000}).toBeUndefined();await page.waitForTimeout(60);const reading=await page.evaluate(()=>{const p=(window as any).prototype,h=p.state.units[0];return {release:h.basicRelease,sounds:(window as any).swingSounds,actor:[...p.scene.unitVisuals.values()].find((a:any)=>a.unit.id===h.id)?.attackRemaining,hit:p.state.stats.basicAttacksReleased||0};});mkdirSync('../work/T034',{recursive:true});await page.screenshot({path:'../work/T034/whiff.png'});console.log(JSON.stringify(reading));expect(reading.sounds.filter((x:any)=>['shot','melee'].includes(x.name))).toHaveLength(1);expect(reading.release).toBeDefined();expect(reading.actor).toBeGreaterThan(0);expect(reading.sounds[0].context).toBe('running');expect(reading.sounds[0].muted).toBe(false);expect(reading.hit).toBe(0);});



async function danger(page:Page,id='hunter',late=false){await page.evaluate(async({id,late})=>{const p=(window as any).prototype,s=p.state,{createGame,command}=await import('/src/core/engine.ts' as string),{startIntent}=await import('/src/core/attack-intent.ts' as string);const f=createGame();command(f,{type:'selectJourney',journey:'exploration'});command(f,{type:'selectExplorationCompanion',id:'ranger'});command(f,{type:'carry',gold:0,vitality:0});const u=s.units.find((u:any)=>u.id===id),e=structuredClone(f.units.find((u:any)=>u.role==='heavy'));Object.assign(e,{id:'defense-threat',pos:{x:u.pos.x-1,y:u.pos.y},drawPos:{x:u.pos.x-1,y:u.pos.y},ready:0,speed:0,hp:10000,maxHp:10000,attackTimer:100,enemyMotion:'engaged',pursuitTargetId:id,encounterRoom:1});e.enemyCombat.abilityReadyAt=100;e.enemySense.home={...e.pos};s.units.push(e);s.exploration.definition.encounters=[{room:1,name:'defense fixture',tier:'strong',enemyIds:[e.id],center:{...u.pos},tacticalRadius:6.5}];startIntent(s,e,u,'heavy-ground-slam');if(late){e.attackIntent.phase='locked';e.attackIntent.resolveAt=s.time+.12;u.commandDefense={action:'hold',reason:'fixture-observed',nextDecision:0,hazards:{[e.id+':'+e.attackIntent.startedAt]:s.time-.3}};}}, {id,late});}
const stateOf=(page:Page)=>page.evaluate(()=>{const s=(window as any).prototype.state;return {direct:s.controlledBodyId,focus:s.explorationControl?.commandFocusId,aim:s.explorationControl?.aim,orders:s.explorationControl?.moveOrders,stats:s.stats,units:s.units.map((u:any)=>({id:u.id,pos:u.pos,skills:u.skillStates,chain:u.basicChain}))};});
async function loadSkills(page:Page,ids:any[]){await page.evaluate(async(ids)=>{const s=(window as any).prototype.state,p=s.units[1],{skillState}=await import('/src/core/progression.ts' as string);p.skillSlots=ids;p.skillId=ids[0];for(const id of ids.filter(Boolean)){const st=skillState(p,id);Object.assign(st,{time:0,cd:id==='rain'?100:0,counter:id==='pain'?4:0,enabled:false,run:undefined});}},ids);}
const prepare=async(page:Page,slot=0)=>{await page.locator('#command-skill-buttons [data-skill-slot="'+slot+'"]').click();await expect.poll(async()=>(await stateOf(page)).aim?.kind).toBe('skill');};
const confirm=async(page:Page)=>{const t=await ground(page);await page.mouse.click(t.q.x,t.q.y);};
test('Ines Command Pain rechecks marks, then Sanctuary casts without Direct takeover',async({page})=>{await begin(page,'ines');await loadSkills(page,['pain','sanctuary',null]);await page.keyboard.press('Space');await page.keyboard.press('c');await prepare(page);expect((await stateOf(page)).direct).toBe('hunter');expect((await stateOf(page)).units[1].skills.pain.counter).toBe(4);await page.evaluate(()=>{(window as any).prototype.state.units[1].skillStates.pain.counter=2;});await confirm(page);await expect.poll(async()=>(await stateOf(page)).units[1].skills.pain.counter).toBe(0);expect((await stateOf(page)).stats.skills).toBe(1);expect((await stateOf(page)).direct).toBe('hunter');await prepare(page,1);await confirm(page);await expect.poll(async()=>(await stateOf(page)).stats.skills).toBe(2);expect((await stateOf(page)).units[1].skills.sanctuary.run).toBeDefined();expect((await stateOf(page)).focus).toBe('ines');mkdirSync('../记录/验证/T-034',{recursive:true});await page.screenshot({path:'../记录/验证/T-034/伊内丝指令技能.png'});});
test('Al Snipe confirms only a mode; E takes over; Direct bar does not cast',async({page})=>{await begin(page);await loadSkills(page,['snipe','rain',null]);await page.keyboard.press('Space');await page.keyboard.press('c');await prepare(page);await confirm(page);expect((await stateOf(page)).direct).toBe('hunter');expect((await stateOf(page)).units[1].skills.snipe.enabled).toBe(true);expect((await stateOf(page)).stats.basicStagesStarted||0).toBe(0);await page.keyboard.press('e');await expect.poll(async()=>(await stateOf(page)).direct).toBe('ranger');expect((await stateOf(page)).units[1].skills.snipe.enabled).toBe(false);await page.waitForTimeout(900);const bar=await page.locator('#world-skill [data-skill-slot="0"]').boundingBox();await page.mouse.click(bar!.x+bar!.width/2,bar!.y+bar!.height/2);expect((await stateOf(page)).units[1].skills.snipe.enabled).toBe(false);expect((await stateOf(page)).aim).toBeUndefined();await page.waitForTimeout(1200);await confirm(page);await expect.poll(async()=>(await stateOf(page)).stats.basicStagesStarted).toBe(1);});
test('RMB cancels Skill only and restores Order; F replaces Skill, Esc exits one layer',async({page})=>{await begin(page);await loadSkills(page,['snipe','rain',null]);await page.keyboard.press('Space');await page.keyboard.press('c');await page.keyboard.press('f');await confirm(page);const before=(await stateOf(page)).orders.ranger;expect(before).toBeDefined();await prepare(page);await page.mouse.click(700,300,{button:'right'});expect((await stateOf(page)).aim).toBeUndefined();expect((await stateOf(page)).focus).toBe('ranger');expect((await stateOf(page)).units[1].skills.snipe.enabled).toBe(false);expect((await stateOf(page)).orders.ranger.id).toBe(before.id);await prepare(page);await page.keyboard.press('f');expect((await stateOf(page)).aim.kind).toBe('path');await page.keyboard.press('Escape');expect((await stateOf(page)).aim).toBeUndefined();expect((await stateOf(page)).focus).toBe('ranger');await page.keyboard.press('Escape');expect((await stateOf(page)).focus).toBeNull();});
test('real Direct defense continues during Command SkillAim; confirmation stays on Al',async({page})=>{await begin(page);await loadSkills(page,['snipe','rain',null]);await page.keyboard.press('Space');await page.keyboard.press('c');await prepare(page);await danger(page,'hunter',true);await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.stats.commandDefenseMobility||0),{timeout:8000}).toBeGreaterThan(0);expect((await stateOf(page)).aim.actorId).toBe('ranger');await confirm(page);expect((await stateOf(page)).units[1].skills.snipe.enabled).toBe(true);expect((await stateOf(page)).direct).toBe('hunter');expect((await stateOf(page)).stats.basicStagesStarted||0).toBe(0);mkdirSync('../记录/验证/T-034',{recursive:true});await page.screenshot({path:'../记录/验证/T-034/防御期间指令.png'});});
test('pause and blur invalidate SkillAim with no stale cast',async({page})=>{await begin(page);await loadSkills(page,['snipe','rain',null]);await page.keyboard.press('Space');await page.keyboard.press('c');await prepare(page);await page.keyboard.press('Space');expect((await stateOf(page)).aim).toBeUndefined();await page.keyboard.press('Space');expect((await stateOf(page)).units[1].skills.snipe.enabled).toBe(false);await prepare(page);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));expect((await stateOf(page)).aim).toBeUndefined();expect((await stateOf(page)).units[1].skills.snipe.enabled).toBe(false);});


for(const kind of ['hit','target-leaves','W-cancel','focus-slow'])test('Basic presentation '+kind,async({page})=>{await begin(page);await page.evaluate(()=>{const a=(window as any).prototype.audio,old=a.play;(window as any).swingSounds=[];a.play=function(name:any){(window as any).swingSounds.push({name,time:(window as any).prototype.state.time,context:this.context?.state});return old.call(this,name);};});if(kind==='hit'||kind==='target-leaves'){await page.evaluate(()=>{(window as any).prototype.state.units[1].attackTimer=100;});await danger(page);await page.evaluate(()=>{const s=(window as any).prototype.state,e=s.units.find((u:any)=>u.id==='defense-threat');e.attackIntent=undefined;e.statuses=[{kind:'stun',power:0,remaining:100}];e.defense=undefined;});}await page.keyboard.press('Space');const t=kind==='hit'||kind==='target-leaves'?await page.evaluate(()=>{const p=(window as any).prototype,e=p.state.units.find((u:any)=>u.id==='defense-threat');return {q:p.project(e.pos)};}):await ground(page);await page.mouse.click(t.q.x,t.q.y);await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units[0].attackPending)).toBeDefined();const started=await page.evaluate(()=>(window as any).prototype.state.time);if(kind==='target-leaves')await page.evaluate(()=>{(window as any).prototype.state.units.find((u:any)=>u.id==='defense-threat').pos={x:40,y:40};});if(kind==='focus-slow')await page.keyboard.press('c');if(kind==='W-cancel'){await page.keyboard.down('w');await page.waitForTimeout(60);await page.keyboard.up('w');}await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units[0].attackPending),{timeout:8000}).toBeUndefined();await page.waitForTimeout(70);const reading=await page.evaluate(()=>{const p=(window as any).prototype,s=p.state,h=s.units[0];return {at:s.time,release:h.basicRelease,sounds:(window as any).swingSounds,hits:s.stats.basicAttacksReleased||0,enemy:s.units.find((u:any)=>u.id==='defense-threat')?.hp,animation:p.scene.unitVisuals.get(h.id)?.attackRemaining};});console.log(JSON.stringify({kind,started,...reading}));if(kind==='W-cancel'){expect(reading.release).toBeUndefined();expect(reading.sounds.filter((x:any)=>['shot','melee'].includes(x.name))).toHaveLength(0);}else{expect(reading.release).toBeDefined();expect(reading.sounds.filter((x:any)=>['shot','melee'].includes(x.name))).toHaveLength(1);expect(reading.animation).toBeGreaterThan(0);}expect(reading.hits).toBe(kind==='hit'?1:0);if(kind==='hit')expect(reading.enemy).toBeLessThan(10000);});
