import {expect,test} from 'vitest';
import {createGame,command,step} from '../src/core/engine';
import {beginSkillAim,querySkillAimPreview,querySkillIntent,querySkillTarget,uniqueSkillUnitCandidate,pointerSkillTarget} from '../src/core/skill-intent';
import {skillState} from '../src/core/progression';
function fixture(){const s=createGame();command(s,{type:'selectJourney',journey:'exploration'});command(s,{type:'selectExplorationCompanion',id:'ines'});command(s,{type:'carry',gold:0,vitality:0});s.units=s.units.filter(u=>u.team==='ally');s.tiles.forEach(t=>{t.obstacle=false;t.layer=0;});for(const u of s.units){u.ready=0;u.stagger=0;u.attackTimer=0;u.path=[];u.pos={x:15,y:10};u.drawPos={...u.pos};}s.context='explorationBattle';s.effects=[];const p=s.units.find(u=>u.id==='ines')!;p.skillSlots=['pain','sanctuary',null];skillState(p,'pain').counter=4;command(s,{type:'commandFocus',id:p.id});return {s,p,h:s.units[0]};}
test('Command prepares without consuming; confirmation rechecks marks and commits once',()=>{const {s,p,h}=fixture();expect(beginSkillAim(s,p.id,0,'command').ok).toBe(true);const id=s.explorationControl!.aim!.skill!.sessionId;expect(skillState(p,'pain').counter).toBe(4);skillState(p,'pain').counter=2;expect(querySkillAimPreview(s).counter).toBe(2);expect(command(s,{type:'confirmSkillAim',sessionId:id}).ok).toBe(true);expect(skillState(p,'pain').counter).toBe(0);expect(s.controlledBodyId).toBe(h.id);expect(command(s,{type:'confirmSkillAim',sessionId:id}).ok).toBe(false);});
test('slot replacement invalidates prepared identity instead of casting replacement',()=>{const {s,p}=fixture();beginSkillAim(s,p.id,0,'command');p.skillSlots![0]='sanctuary';expect(command(s,{type:'confirmSkillAim',sessionId:s.explorationControl!.aim!.skill!.sessionId}).ok).toBe(false);expect(s.explorationControl?.aim).toBeUndefined();expect(skillState(p,'sanctuary').run).toBeUndefined();});
test('legal empty Basic Release emits presentation without a fake combat hit',()=>{const {s,h}=fixture();command(s,{type:'commandFocus',id:null});h.skillSlots=[null,null,null];expect(command(s,{type:'basic',id:h.id,aim:{x:16,y:10},requestId:1}).ok).toBe(true);for(let i=0;i<20;i++)step(s,.02);expect(h.basicRelease?.id).toBeGreaterThan(0);expect(s.stats.basicAttacksReleased||0).toBe(0);expect(s.combatEvents?.length||0).toBe(0);});

import {SKILL_CATALOG} from '../src/core/skill-catalog';
import {commandReserved} from '../src/core/exploration-control';
import {advanceMoveOrders} from '../src/core/move-order';
import {commandDefenseEligible} from '../src/core/command-defense';
function equip(p:any,id:any){p.weapons[p.weaponIndex].profession=SKILL_CATALOG[id].profession;p.skillSlots=[id,null,null];for(const st of Object.values(p.skillStates||{}) as any[]){st.time=0;st.cd=0;st.run=undefined;st.enabled=false;}const st=skillState(p,id);st.cd=0;st.time=0;st.counter=3;st.enabled=false;return st;}
test.each(['prayer','ward','bell','pain','sanctuary','hunt','snipe','poison'] as const)('%s uses own real range and existing runtime once',id=>{const {s,p,h}=fixture();const st=equip(p,id);const before=s.stats.skills||0;expect(beginSkillAim(s,p.id,0,'command').ok).toBe(true);const aim=s.explorationControl!.aim!;expect(commandReserved(s,p)).toBe(true);expect(commandReserved(s,h)).toBe(false);expect(commandDefenseEligible(s,h)).toBe(true);const snap=JSON.stringify(s);const q=querySkillAimPreview(s);expect(JSON.stringify(s)).toBe(snap);expect(q.center).toEqual(p.pos);expect(aim.skill!.target).toEqual({kind:'self'});expect(command(s,{type:'confirmSkillAim',sessionId:aim.skill!.sessionId}).ok).toBe(true);if(['snipe','poison'].includes(id)){expect(st.enabled).toBe(true);expect(s.effects.length).toBe(0);}else expect(s.stats.skills).toBe(before+1);expect(s.explorationControl?.commandFocusId).toBe(p.id);expect(s.controlledBodyId).toBe(h.id);expect(s.explorationControl?.aim).toBeUndefined();});
test.each(['rain','reap','dance'] as const)('%s Auto is not turned into manual entry',id=>{const {s,p}=fixture();equip(p,id);expect(beginSkillAim(s,p.id,0,'command').ok).toBe(false);expect(s.explorationControl?.aim).toBeUndefined();});
test('Dance only confirms exit from already enabled mode',()=>{const {s,p}=fixture();const st=equip(p,'dance');st.enabled=true;expect(beginSkillAim(s,p.id,0,'command').ok).toBe(true);expect(st.enabled).toBe(true);expect(command(s,{type:'confirmSkillAim',sessionId:s.explorationControl!.aim!.skill!.sessionId}).ok).toBe(true);expect(st.enabled).toBe(false);});
test.each(['cooldown','busy','stagger','emptyMarks'] as const)('%s confirmation fails recoverably without consuming or dropping session',kind=>{const {s,p}=fixture();const id=kind==='emptyMarks'?'pain':'sanctuary';const st=equip(p,id);beginSkillAim(s,p.id,0,'command');if(kind==='cooldown')st.cd=2;if(kind==='busy')p.attackPending={targetId:'',remaining:.2,facing:'east'};if(kind==='stagger')p.stagger=1;if(kind==='emptyMarks')st.counter=0;const aim=s.explorationControl!.aim!;const before=JSON.stringify(st);expect(command(s,{type:'confirmSkillAim',sessionId:aim.skill!.sessionId}).ok).toBe(false);expect(JSON.stringify(st)).toBe(before);expect(s.explorationControl?.aim).toBe(aim);expect(s.stats.skills||0).toBe(0);});
test('replacement token cannot confirm the new session; Path and Skill share one owner',()=>{const {s,p}=fixture();beginSkillAim(s,p.id,0,'command');const old=s.explorationControl!.aim!.skill!.sessionId;beginSkillAim(s,p.id,1,'command');expect(command(s,{type:'confirmSkillAim',sessionId:old}).ok).toBe(false);expect(s.explorationControl!.aim!.skill!.slot).toBe(1);command(s,{type:'beginCommandAim',kind:'path'});expect(s.explorationControl!.aim!.kind).toBe('path');expect(s.explorationControl!.aim!.skill).toBeUndefined();beginSkillAim(s,p.id,0,'command');expect(s.explorationControl!.aim!.kind).toBe('skill');});
test('cancel resumes existing MoveOrder; only successful caster loses own Order',()=>{const {s,p,h}=fixture();command(s,{type:'beginCommandAim',kind:'path'});expect(command(s,{type:'confirmPathAim',to:{x:18,y:10}}).ok).toBe(true);const order=s.explorationControl!.moveOrders![p.id];beginSkillAim(s,p.id,0,'command');expect(s.explorationControl!.moveOrders![p.id]).toBe(order);command(s,{type:'cancelExplorationAim'});advanceMoveOrders(s);expect(order.state).not.toBe('cancelled');beginSkillAim(s,p.id,0,'command');command(s,{type:'confirmSkillAim',sessionId:s.explorationControl!.aim!.skill!.sessionId});expect(s.explorationControl!.moveOrders![p.id]).toBeUndefined();expect(s.controlledBodyId).toBe(h.id);});
test('dead actor, profession change and expired phase never cast stale Aim',()=>{for(const kind of ['dead','profession','phase']){const {s,p}=fixture();beginSkillAim(s,p.id,0,'command');const id=s.explorationControl!.aim!.skill!.sessionId;if(kind==='dead')p.life='dead';if(kind==='profession')p.weapons[p.weaponIndex].profession='hunter';if(kind==='phase')s.phase='ended';expect(command(s,{type:'confirmSkillAim',sessionId:id}).ok).toBe(false);expect(s.stats.skills||0).toBe(0);}});
test('controlled Direction/Point/Unit descriptors validate real target data without a production cast',()=>{const {s,p,h}=fixture();const definition={target:'direction',direct:'aimConfirm',command:'aimConfirm',description:'test only'} as const;expect(querySkillTarget(s,p,definition,3,{kind:'direction',direction:{x:0,y:0}}).ok).toBe(false);expect(querySkillTarget(s,p,definition,3,{kind:'direction',direction:{x:1,y:0}}).ok).toBe(true);const point={...definition,target:'point'} as const;expect(querySkillTarget(s,p,point,3,{kind:'point',point:{x:16,y:10}}).ok).toBe(true);expect(querySkillTarget(s,p,point,3,{kind:'point',point:{x:30,y:10}}).ok).toBe(false);const e=structuredClone(h);e.id='only-target';e.team='enemy';e.pos={x:16,y:10};s.units.push(e);const unit={...definition,target:'unit'} as const;const candidate=uniqueSkillUnitCandidate(s,p,unit,3)!;expect(candidate).toEqual({kind:'unit',unitId:e.id});expect(s.stats.skills||0).toBe(0);e.life='dead';expect(querySkillTarget(s,p,unit,3,candidate).ok).toBe(false);expect(uniqueSkillUnitCandidate(s,p,unit,3)).toBeUndefined();e.life='active';e.pos={x:45,y:40};expect(querySkillTarget(s,p,unit,50,candidate).ok).toBe(false);});
test('true WASD cancel has no Release presentation and no fake Hit',()=>{const {s,h}=fixture();command(s,{type:'commandFocus',id:null});h.skillSlots=[null,null,null];command(s,{type:'basic',id:h.id,aim:{x:16,y:10},requestId:1});command(s,{type:'direct',id:h.id,direction:{x:0,y:1}});for(let i=0;i<20;i++)step(s,.02);expect(h.basicRelease).toBeUndefined();expect(s.stats.basicAttacksReleased||0).toBe(0);});


test('Command can prepare during atomic loadout, but cannot confirm before completion',()=>{const {s,p}=fixture();p.loadout={targetIndex:0,elapsed:0,duration:1};expect(beginSkillAim(s,p.id,0,'command').ok).toBe(true);const aim=s.explorationControl!.aim!;expect(command(s,{type:'confirmSkillAim',sessionId:aim.skill!.sessionId}).ok).toBe(false);expect(p.loadout).toBeDefined();expect(skillState(p,'pain').counter).toBe(4);expect(s.explorationControl?.aim).toBe(aim);});

test('framework pointer stores immutable world point and normalized direction',()=>{const {s,p}=fixture();const point={x:18,y:14};const def={target:'point',direct:'aimConfirm',command:'aimConfirm',description:'controlled'} as const;const stored=pointerSkillTarget(s,p,def,5,point)!;point.x=35;p.pos={x:17,y:10};expect(stored).toEqual({kind:'point',point:{x:18,y:14}});expect(pointerSkillTarget(s,p,{...def,target:'direction'},5,{x:20,y:14})).toEqual({kind:'direction',direction:{x:.6,y:.8}});});
