import {test,expect,type Page} from '@playwright/test';
import {mkdirSync} from 'node:fs';
test.setTimeout(60000);
async function begin(page:Page,companion='ranger'){await page.goto('/');await page.locator('[data-journey="exploration"]').click();await page.locator('[data-companion="'+companion+'"]').click();await page.locator('[data-action="carry"]').click();await page.locator('[data-action="pause"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.terrain.userData.loaded),{timeout:45000}).toBe(true);
 await page.evaluate(()=>{const s=(window as any).prototype.state;s.units=s.units.filter((u:any)=>u.team==='ally'&&(u.id==='hunter'||u.id===s.explorationCompanionId));s.tiles.forEach((t:any)=>{t.obstacle=false;t.layer=0;});for(const u of s.units){u.ready=0;u.stagger=0;u.path=[];u.destination=null;u.attackTimer=0;u.skillSlots=[null,null,null];u.weapons.forEach((w:any)=>w.weight=0);u.hp=u.maxHp=10000;}s.units[0].pos={x:15,y:10};s.units[0].drawPos={x:15,y:10};s.units[1].pos={x:10,y:10};s.units[1].drawPos={x:10,y:10};s.context='explorationBattle';});await page.waitForTimeout(1200);}

test('A held W switches Direct immediately and diagonals transfer once',async({page})=>{await begin(page);await page.keyboard.press('Space');await page.keyboard.down('w');await page.keyboard.press('c');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.controlledBodyId)).toBe('ranger');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').direct?.direction.y)).toBe(-1);await page.keyboard.down('d');await page.keyboard.press('c');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.controlledBodyId)).toBe('hunter');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units[0].direct?.direction.x)).toBeGreaterThan(0);await page.keyboard.up('w');await page.keyboard.up('d');});

async function ground(page:Page){return page.evaluate(()=>{const p=(window as any).prototype,s=p.state,h=s.units.find((u:any)=>u.id===s.controlledBodyId);for(const tile of s.tiles){if(s.exploration.definition.points.some((a:any)=>Math.hypot(a.pos.x-tile.x,a.pos.y-tile.y)<1)||Math.hypot(s.exploration.definition.exit.x-tile.x,s.exploration.definition.exit.y-tile.y)<1)continue;if(Math.hypot(tile.x-h.pos.x,tile.y-h.pos.y)<.8||Math.hypot(tile.x-h.pos.x,tile.y-h.pos.y)>3)continue;const q=p.project(tile),hit=p.scene.pick(q.x,q.y);if(hit.tile&&!hit.unitId&&[[-15,-15],[-15,15],[15,-15],[15,15]].every(([dx,dy])=>document.elementFromPoint(q.x+dx,q.y+dy)?.closest('#scene')&&!p.scene.pick(q.x+dx,q.y+dy).unitId))return {q,aim:hit.tile};}throw Error('no empty ground');});}

async function danger(page:Page,id='hunter',late=false){await page.evaluate(async({id,late})=>{const p=(window as any).prototype,s=p.state,{createGame,command}=await import('/src/core/engine.ts' as string),{startIntent}=await import('/src/core/attack-intent.ts' as string);const f=createGame();command(f,{type:'selectJourney',journey:'exploration'});command(f,{type:'selectExplorationCompanion',id:'ranger'});command(f,{type:'carry',gold:0,vitality:0});const u=s.units.find((u:any)=>u.id===id),e=structuredClone(f.units.find((u:any)=>u.role==='heavy'));Object.assign(e,{id:'defense-threat',pos:{x:u.pos.x-1,y:u.pos.y},drawPos:{x:u.pos.x-1,y:u.pos.y},ready:0,speed:0,hp:10000,maxHp:10000,attackTimer:100,enemyMotion:'engaged',pursuitTargetId:id,encounterRoom:1});e.enemyCombat.abilityReadyAt=100;e.enemySense.home={...e.pos};s.units.push(e);s.exploration.definition.encounters=[{room:1,name:'defense fixture',tier:'strong',enemyIds:[e.id],center:{...u.pos},tacticalRadius:6.5}];startIntent(s,e,u,'heavy-ground-slam');if(late){e.attackIntent.phase='locked';e.attackIntent.resolveAt=s.time+.12;u.commandDefense={action:'hold',reason:'fixture-observed',nextDecision:0,hazards:{[e.id+':'+e.attackIntent.startedAt]:s.time-.3}};}}, {id,late});}

const snapshot=(page:Page)=>page.evaluate(()=>{const s=(window as any).prototype.state;return {direct:s.controlledBodyId,focus:s.explorationControl?.commandFocusId,aim:s.explorationControl?.aim,orders:s.explorationControl?.moveOrders||{},stats:s.stats,units:s.units.map((u:any)=>({id:u.id,pos:u.pos,direct:u.direct,defense:u.commandDefense,ai:u.companionCombat,skills:u.skillStates,charges:u.evasion?.charges,blink:u.blink?.charges,attackPending:u.attackPending,chain:u.basicChain}))};});
const errors=new WeakMap<Page,string[]>();test.beforeEach(async({page})=>{const e:string[]=[];errors.set(page,e);page.on('pageerror',x=>e.push(x.message));});test.afterEach(async({page})=>expect(errors.get(page)).toEqual([]));
async function worldBody(page:Page,id:string){await page.waitForTimeout(250);return page.evaluate(id=>{const p=(window as any).prototype,u=p.state.units.find((u:any)=>u.id===id),q=p.project(u.drawPos||u.pos);for(let dy=-80;dy<=10;dy+=4)for(let dx=-28;dx<=28;dx+=4){const hit={x:Math.round(q.x+dx),y:Math.round(q.y+dy)};if([[0,0],[-3,0],[3,0],[0,-3],[0,3],[-6,0],[6,0],[0,-6],[0,6]].every(([x,y])=>p.scene.pick(hit.x+x,hit.y+y).unitId===id&&document.elementFromPoint(hit.x+x,hit.y+y)?.closest('#scene')))return hit;}throw Error('body not pickable');},id);}
async function order(page:Page){await page.keyboard.press('f');const t=await ground(page);await page.mouse.move(t.q.x,t.q.y);await page.waitForTimeout(80);await page.mouse.click(t.q.x,t.q.y);await expect.poll(async()=>Object.keys((await snapshot(page)).orders).length).toBeGreaterThan(0);return (await snapshot(page)).orders[(await snapshot(page)).direct];}
test('B avatars and world bodies switch once, same actor preserves Aim and never attacks',async({page})=>{await begin(page);await page.locator('[data-unit="ranger"]').click();expect((await snapshot(page)).direct).toBe('ranger');await page.keyboard.press('f');const aim=(await snapshot(page)).aim;await page.locator('[data-unit="ranger"]').click();expect((await snapshot(page)).aim).toEqual(aim);await page.keyboard.press('Escape');await page.waitForTimeout(1200);const q=await worldBody(page,'hunter');await page.mouse.click(q.x,q.y);expect((await snapshot(page)).direct).toBe('hunter');expect((await snapshot(page)).stats.basicStagesStarted||0).toBe(0);await expect(page.locator('#command-skills')).toHaveCount(0);await expect(page.locator('#path-aim-button')).toHaveCount(0);await expect(page.locator('#control-status')).toContainText('猎人');});
test('C real skill keys and mobility use current actor resources only',async({page})=>{await begin(page,'ines');await page.evaluate(async()=>{const s=(window as any).prototype.state,{skillState}=await import('/src/core/progression.ts' as string);const p=s.units.find((u:any)=>u.id==='ines');p.skillSlots=['pain','sanctuary',null];skillState(p,'pain').counter=3;skillState(p,'sanctuary').cd=0;});await page.keyboard.press('2');await page.keyboard.press('Space');await page.keyboard.press('e');expect((await snapshot(page)).units[1].skills.pain.counter).toBe(0);await page.keyboard.press('r');await expect.poll(async()=>(await snapshot(page)).stats.skills).toBe(2);await page.keyboard.press('1');expect((await snapshot(page)).units[1].skills.sanctuary.run).toBeDefined();await page.keyboard.press('2');await page.keyboard.down('w');await page.waitForTimeout(100);await page.keyboard.up('w');expect((await snapshot(page)).units[1].skills.sanctuary.run).toBeUndefined();const t=await ground(page);await page.mouse.move(t.q.x,t.q.y);await page.keyboard.press('Shift');await expect.poll(async()=>(await snapshot(page)).stats.evadeUses).toBe(1);expect((await snapshot(page)).units[0].blink).toBe(10);await page.keyboard.press('1');await expect(page.locator('#mobility-name')).toContainText('瞬影');});
test('D F order survives switch and another actor Basic; only successful own W cancels',async({page})=>{await begin(page);await page.keyboard.press('2');const o=await order(page);await page.keyboard.press('1');expect((await snapshot(page)).orders.ranger.id).toBe(o.id);await page.keyboard.press('Space');const t=await ground(page);await page.mouse.click(t.q.x,t.q.y);await expect.poll(async()=>(await snapshot(page)).stats.basicStagesStarted).toBe(1);expect((await snapshot(page)).orders.ranger.id).toBe(o.id);await page.keyboard.press('2');expect((await snapshot(page)).orders.ranger.id).toBe(o.id);await page.keyboard.down('w');await expect.poll(async()=>!!(await snapshot(page)).orders.ranger).toBe(false);await page.keyboard.up('w');});
test('E switching cancels Aim and resumes old order; blocked held W never revives',async({page})=>{await begin(page);await page.keyboard.press('2');const o=await order(page);await page.keyboard.press('f');await page.keyboard.down('w');await page.keyboard.press('1');expect((await snapshot(page)).aim).toBeUndefined();expect((await snapshot(page)).orders.ranger.id).toBe(o.id);await page.keyboard.press('Space');await page.waitForTimeout(150);expect((await snapshot(page)).units[0].direct).toBeUndefined();await page.keyboard.up('w');await page.keyboard.down('w');await expect.poll(async()=>(await snapshot(page)).units[0].direct?.direction.y).toBe(-1);await page.keyboard.up('w');});
test('F real heavy Ability restores offhand AI; switch back removes ordinary AI route',async({page})=>{await begin(page);await danger(page,'hunter');await page.keyboard.press('2');await page.keyboard.press('Space');await expect.poll(async()=>(await snapshot(page)).units[0].ai).toBeDefined();await page.waitForTimeout(900);expect((await snapshot(page)).units[0].defense).toBeUndefined();await page.keyboard.press('1');expect((await snapshot(page)).units[0].ai).toBeUndefined();expect((await snapshot(page)).direct).toBe('hunter');expect((await snapshot(page)).stats.commandDefenseWalks||0).toBe(0);});
test('G committed Basic releases once after switch; old buffered click never replays',async({page})=>{await begin(page);await page.keyboard.press('Space');const t=await ground(page);await page.mouse.click(t.q.x,t.q.y);await expect.poll(async()=>(await snapshot(page)).units[0].attackPending).toBeDefined();await page.keyboard.press('2');await expect.poll(async()=>(await snapshot(page)).units[0].attackPending).toBeUndefined();expect((await snapshot(page)).stats.basicStagesStarted).toBe(1);await page.keyboard.press('1');await page.waitForTimeout(700);expect((await snapshot(page)).stats.basicStagesStarted).toBe(1);expect((await snapshot(page)).units[0].chain.buffer).toBeUndefined();});
test('H natural controls and modal retain one authority and normal time speed',async({page})=>{await begin(page);await page.keyboard.press('Space');await page.keyboard.down('w');await page.waitForTimeout(100);await page.keyboard.press('2');await page.waitForTimeout(100);await page.keyboard.up('w');await page.keyboard.press('1');const t=await ground(page);await page.mouse.click(t.q.x,t.q.y);await page.waitForTimeout(400);await page.locator('[data-action="build"]').first().click();await page.keyboard.press('2');await page.keyboard.press('e');expect((await snapshot(page)).direct).toBe('hunter');await page.keyboard.press('Escape');await page.keyboard.press('2');expect((await snapshot(page)).direct).toBe('ranger');expect((await snapshot(page)).focus).toBeNull();expect(await page.evaluate(()=>(window as any).prototype.state.tacticalFocus)).toBeUndefined();mkdirSync('../work/T035',{recursive:true});await page.screenshot({path:'../work/T035/单一实控试玩.png'});});

// Preserve pre-existing modal timing and Tower controls outside the simplified exploration identity.
test('I summon Aim retains existing slow time while switching alone does not',async({page})=>{await begin(page);await page.evaluate(()=>{(window as any).prototype.state.fragments=40;});await page.keyboard.press('Space');const time=()=>page.evaluate(()=>(window as any).prototype.state.stats.slowTime||0);await page.locator('[data-clone="hunter"]').click();const a=await time();await page.waitForTimeout(500);expect((await time())-a).toBeGreaterThan(0);await page.keyboard.press('Escape');const b=await time();await page.waitForTimeout(500);expect(await time()).toBe(b);});
test('J Tower still accepts absolute original selection 3 and 4',async({page})=>{await page.goto('/');await page.locator('[data-action="carry"]').click();await page.locator('[data-action="start"]').click();await page.locator('[data-action="pause"]').click();await page.evaluate(()=>{const s=(window as any).prototype.state;s.units=s.units.filter((u:any)=>u.team==='ally');for(const u of s.units){u.life='active';u.ready=0;u.shadowResident=false;}});await page.keyboard.press('Space');for(const key of ['3','4']){await page.keyboard.press(key);expect(await page.evaluate(()=>(window as any).prototype.interaction.selectedId)).toBe(await page.evaluate(n=>(window as any).prototype.state.units[Number(n)-1].id,key));}});
