import {expect,test} from 'vitest';
import {createGame,command,step} from '../src/core/engine';
import {beginSkillAim} from '../src/core/skill-intent';
import {skillState} from '../src/core/progression';
import {issueMoveOrder} from '../src/core/move-order';
function fixture(){const s=createGame();command(s,{type:'selectJourney',journey:'exploration'});command(s,{type:'selectExplorationCompanion',id:'ines'});command(s,{type:'carry',gold:0,vitality:0});s.units=s.units.filter(u=>u.team==='ally');s.tiles.forEach(t=>{t.obstacle=false;t.layer=0;});for(const u of s.units){u.ready=0;u.stagger=0;u.attackTimer=100;u.path=[];}const h=s.units[0],p=s.units.find(u=>u.id==='ines')!;h.pos={x:15,y:10};p.pos={x:10,y:10};return {s,h,p};}
test('legacy Focus and Promote reject without changing Direct or Aim',()=>{const {s,p,h}=fixture();command(s,{type:'beginExplorationAim',id:h.id,kind:'path',source:'direct'});const old=s.explorationControl!.aim;expect(command(s,{type:'commandFocus',id:p.id}).ok).toBe(false);expect(command(s,{type:'promoteCommandFocus'}).ok).toBe(false);expect(s.controlledBodyId).toBe(h.id);expect(s.explorationControl!.aim).toBe(old);});
test('valid explicit switch cancels old Aim while same and invalid switch are no-op',()=>{const {s,h,p}=fixture();command(s,{type:'beginExplorationAim',id:h.id,kind:'path',source:'direct'});const old=s.explorationControl!.aim;expect(command(s,{type:'controlBody',id:'missing'}).ok).toBe(false);expect(s.explorationControl!.aim).toBe(old);command(s,{type:'controlBody',id:h.id});expect(s.explorationControl!.aim).toBe(old);command(s,{type:'controlBody',id:p.id});expect(s.explorationControl!.aim).toBeUndefined();expect(s.controlledBodyId).toBe(p.id);expect(s.tacticalFocus).toBeUndefined();});
test('switch preserves both orders and current atomic action/resources',()=>{const {s,h,p}=fixture();issueMoveOrder(s,h,{x:18,y:10},'direct');issueMoveOrder(s,p,{x:10,y:14},'direct');const orders=structuredClone(s.explorationControl!.moveOrders);p.stagger=1;p.attackPending={targetId:'',remaining:.2,facing:'east',basic:true};const pending=p.attackPending;const charges=p.evasion!.charges;command(s,{type:'controlBody',id:p.id});expect(p.attackPending).toBe(pending);expect(p.stagger).toBe(1);expect(p.evasion!.charges).toBe(charges);expect(s.explorationControl!.moveOrders).toEqual(orders);command(s,{type:'controlBody',id:h.id});expect(s.explorationControl!.moveOrders).toEqual(orders);});
test('Direct skill token dies on explicit switch and Command skill source rejects',()=>{const {s,h,p}=fixture();p.skillSlots=['pain',null,null];skillState(p,'pain').counter=3;command(s,{type:'controlBody',id:p.id});expect(beginSkillAim(s,p.id,0,'direct').ok).toBe(true);const token=s.explorationControl!.aim!.skill!.sessionId;command(s,{type:'controlBody',id:h.id});expect(command(s,{type:'confirmSkillAim',sessionId:token}).ok).toBe(false);expect(skillState(p,'pain').counter).toBe(3);expect(beginSkillAim(s,p.id,0,'command').ok).toBe(false);});
test('stale Focus and Defense migrate without giving an invisible action authority',()=>{const {s,h,p}=fixture();s.explorationControl!.commandFocusId=p.id;h.commandDefense={action:'hold',reason:'legacy',nextDecision:0};step(s,.01);expect(s.explorationControl!.commandFocusId).toBeNull();expect(h.commandDefense).toBeUndefined();expect(s.controlledBodyId).toBe(h.id);});
test.each(['downed','dead','rescued','withdrawn','respawning','departed','shadow','clone','enemy'] as const)('invalid explicit %s switch preserves existing Aim and control',kind=>{const {s,h,p}=fixture();command(s,{type:'beginExplorationAim',id:h.id,kind:'path',source:'direct'});if(kind==='shadow')p.shadowResident=true;else if(kind==='clone')p.cloneOf=h.id;else if(kind==='enemy')p.team='enemy';else p.life=kind;const before=structuredClone(s);expect(command(s,{type:'controlBody',id:p.id}).ok).toBe(false);expect(s).toEqual(before);});
test('incoming ordinary AI marker cannot erase an actor-owned order execution route',()=>{const {s,h,p}=fixture();issueMoveOrder(s,p,{x:10,y:14},'direct');const path=p.path,order=s.explorationControl!.moveOrders![p.id];p.ai={...p.ai,moving:true} as any;p.companionCombat={moving:true} as any;command(s,{type:'controlBody',id:p.id});expect(p.path).toBe(path);expect(s.explorationControl!.moveOrders![p.id]).toBe(order);expect(p.companionCombat).toBeUndefined();command(s,{type:'controlBody',id:h.id});expect(s.explorationControl!.moveOrders![p.id]).toBe(order);});
