import {legacyEnemy,hazard} from './legacy-enemy-fixture';
// AR06: legacy charge tests retain the old ranger branch.
vi.mock('../src/core/al-state',async importActual=>({...await importActual<object>(),isAlV2:()=>false}));
// AR05: this frozen historical suite verifies the retained pre-Blue branch.

vi.mock('../src/core/hunter-state',async importActual=>({...await importActual<object>(),isHunterV2:()=>false}));
import {vi,expect,test} from 'vitest';
import {createGame,command,step} from '../src/core/engine';
import {issueMoveOrder} from '../src/core/move-order';
import {advanceCompanionCombat,TACTICAL_WEIGHTS} from '../src/core/companion-combat';
import {focusCandidate,effectiveTacticWeights,maintainPartyTactics,finishPartyTactic} from '../src/core/party-tactics';
import {startIntent} from '../src/core/attack-intent';
function fixture(){const s=createGame();command(s,{type:'selectJourney',journey:'exploration'});command(s,{type:'selectExplorationCompanion',id:'ines'});command(s,{type:'carry',gold:0,vitality:0});s.units=s.units.filter(u=>u.team==='ally');s.tiles.forEach(t=>{t.obstacle=false;t.layer=0;});for(const u of s.units){u.ready=0;u.path=[];u.attackTimer=100;}const h=s.units.find(u=>u.id==='hunter')!,p=s.units.find(u=>u.id==='ines')!;h.pos=h.drawPos={x:15,y:10};p.pos=p.drawPos={x:10,y:10};return {s,h,p};}
const issue=(s:any,issuer:any,recipient:any,kind:string,requestId=1,targetId?:string)=>command(s,{type:'partyTactic',issuerId:issuer.id,recipientId:recipient.id,kind,requestId,expectedControlRevision:s.controlRevision??0,targetId} as any);
test('rally walks the offhand to the live controlled actor without switching or teleporting',()=>{const {s,h,p}=fixture();expect(issue(s,h,p,'rally').ok).toBe(true);expect((s as any).partyTactics?.[p.id]?.kind).toBe('rally');const start={...p.pos};step(s,.05);expect(Math.hypot(p.pos.x-start.x,p.pos.y-start.y)).toBeLessThan(.4);for(let i=0;i<150;i++)step(s,.05);expect(Math.hypot(p.pos.x-h.pos.x,p.pos.y-h.pos.y)).toBeLessThan(2.1);expect(s.controlledBodyId).toBe(h.id);expect((s as any).partyTactics?.[p.id]).toBeUndefined();});
test('cautious and free preserve precise orders; rally replaces only recipient order once',()=>{const {s,h,p}=fixture();issueMoveOrder(s,h,{x:18,y:10},'direct');issueMoveOrder(s,p,{x:10,y:15},'direct');const own=s.explorationControl!.moveOrders![h.id],old=s.explorationControl!.moveOrders![p.id];expect(issue(s,h,p,'cautious').ok).toBe(true);expect(s.explorationControl!.moveOrders![p.id]).toBe(old);expect(issue(s,h,p,'free',2).ok).toBe(true);expect(s.explorationControl!.moveOrders![p.id]).toBe(old);expect(issue(s,h,p,'rally',3).ok).toBe(true);expect(s.explorationControl!.moveOrders![p.id]).toBeUndefined();issueMoveOrder(s,p,{x:10,y:15},'direct');const newer=s.explorationControl!.moveOrders![p.id];issue(s,h,p,'rally',3);expect(s.explorationControl!.moveOrders![p.id]).toBe(newer);expect(s.explorationControl!.moveOrders![h.id]).toBe(own);});
test('invalid focus and stale control session have zero order/tactic side effects',()=>{const {s,h,p}=fixture();issueMoveOrder(s,p,{x:10,y:15},'direct');expect(issue(s,h,p,'focus',1,'missing').ok).toBe(false);const request={type:'partyTactic',issuerId:h.id,recipientId:p.id,kind:'rally',requestId:2,expectedControlRevision:(s as any).controlRevision??0};command(s,{type:'controlBody',id:p.id});command(s,{type:'controlBody',id:h.id});const before=structuredClone(s);expect(command(s,request as any).ok).toBe(false);expect(s.explorationControl!.moveOrders).toEqual(before.explorationControl!.moveOrders);expect((s as any).partyTactics).toEqual((before as any).partyTactics);});
test('pending rally preserves committed basic and cautious clears on receiver invalidation',()=>{const {s,h,p}=fixture();p.attackPending={targetId:'',remaining:.5,facing:'east',basic:true};const attack=p.attackPending;expect(issue(s,h,p,'rally').ok).toBe(true);expect(p.attackPending).toBe(attack);step(s,.02);expect((s as any).partyTactics[p.id].execution).toBe('pending-body');issue(s,h,p,'cautious',2);command(s,{type:'controlBody',id:p.id});expect((s as any).partyTactics[p.id].kind).toBe('cautious');p.life='downed';step(s,.01);expect((s as any).partyTactics[p.id]).toBeUndefined();});

function combat(){const s=createGame();command(s,{type:'selectJourney',journey:'exploration'});command(s,{type:'selectExplorationCompanion',id:'ranger'});command(s,{type:'carry',gold:0,vitality:0});const h=s.units.find(u=>u.id==='hunter')!,p=s.units.find(u=>u.id==='ranger')!,e=legacyEnemy(s);s.units=[h,p,e];s.tiles.forEach(t=>{t.obstacle=false;t.layer=0;});h.pos=h.drawPos={x:15,y:10};p.pos=p.drawPos={x:10,y:10};e.pos=e.drawPos={x:14,y:10};for(const u of s.units){u.path=[];u.destination=null;u.ready=0;u.attackTimer=100;u.skillSlots=[null,null,null];u.weapons.forEach(w=>w.weight=0);u.hp=u.maxHp=10000;}e.encounterRoom=1;e.enemyMotion='engaged';e.pursuitTargetId=h.id;e.enemySense!.home={...e.pos};s.context='explorationBattle';s.exploration!.lastActivity=0;s.exploration!.definition.encounters=[{room:1,name:'combat',tier:'strong',enemyIds:[e.id],center:{x:13,y:10},tacticalRadius:6.5}];return {s,h,p,e};}
test('focus affects the actual committed Basic even with a closer enemy on the same ray',()=>{const {s,h,p,e}=combat();p.pos=p.drawPos={x:11,y:10};p.weapons[0].range=5;const near=structuredClone(e);near.id='near';near.pos=near.drawPos={x:12,y:10};s.units.push(near);e.statuses=near.statuses=[{kind:'stun',remaining:100,power:0}];p.attackTimer=0;expect(issue(s,h,p,'focus',1,e.id).ok).toBe(true);for(let i=0;i<120&&!s.combatEvents?.some(a=>a.sourceId===p.id);i++)step(s,.05);const hits=s.combatEvents?.filter(a=>a.sourceId===p.id&&a.kind==='basic')||[];expect(hits.length).toBeGreaterThan(0);expect(hits[0].targetId).toBe(e.id);expect(s.partyTactics![p.id].targetId).toBe(e.id);});
test('focus remembered route never follows hidden live coordinates; expires without retargeting',()=>{const {s,h,p,e}=combat();issue(s,h,p,'focus',1,e.id);const remembered={...e.pos};e.pos={x:35,y:35};s.time=.2;maintainPartyTactics(s);advanceCompanionCombat(s);expect(s.partyTactics![p.id].lastKnownTarget!.point).toEqual(remembered);expect(p.destination!.x).toBeLessThan(16);s.time=1.6;maintainPartyTactics(s);expect(s.partyTactics![p.id]).toBeUndefined();});
test.each(['dead','return','inactive'] as const)('focus ends on target %s and keeps a subsequent actor-owned route',kind=>{const {s,h,p,e}=combat();issue(s,h,p,'focus',1,e.id);advanceCompanionCombat(s);if(kind==='dead')e.life='dead';if(kind==='return')e.enemyMotion='return';if(kind==='inactive'){e.pursuitTargetId=undefined;e.enemyMotion='route';e.enemySense!.provoked=undefined;}const newer=[{x:12,y:9}];p.path=newer;maintainPartyTactics(s);expect(s.partyTactics![p.id]).toBeUndefined();expect(p.path).toBe(newer);});
test('successful F order clears rally/focus and preserves cautious preference',()=>{const {s,h,p}=fixture();issue(s,h,p,'rally');expect(issueMoveOrder(s,p,{x:10,y:14},'direct').ok).toBe(true);expect(s.partyTactics![p.id]).toBeUndefined();issue(s,h,p,'cautious',2);issueMoveOrder(s,p,{x:10,y:15},'direct');expect(s.partyTactics![p.id].kind).toBe('cautious');});
test('cautious overlays profile weights, still contributes safe attacks, never rewrites tendency',()=>{const {s,h,p,e}=combat();p.aiTendency='aggressive';const before=structuredClone(TACTICAL_WEIGHTS);issue(s,h,p,'cautious');expect(effectiveTacticWeights(s,p,TACTICAL_WEIGHTS.aggressive)).toEqual({risk:2,flank:.7,peel:1.4,separation:.25});p.attackTimer=0;e.statuses=[{kind:'stun',remaining:100,power:0}];for(let i=0;i<200&&!s.combatEvents?.some(a=>a.sourceId===p.id);i++)step(s,.05);expect(s.combatEvents?.some(a=>a.sourceId===p.id)).toBe(true);expect(p.aiTendency).toBe('aggressive');expect(TACTICAL_WEIGHTS).toEqual(before);});
test('rally refuses new autonomous Basic and retains real Ability defense before resuming',()=>{const {s,h,p,e}=combat();p.pos=p.drawPos={x:14.8,y:10};h.pos=h.drawPos={x:28,y:10};p.attackTimer=0;issue(s,h,p,'rally');hazard(s,e,p);advanceCompanionCombat(s);s.time=.95;const charges=p.evasion!.charges;advanceCompanionCombat(s);expect(p.evasion!.charges).toBe(charges-1);expect(p.evasion!.action).toBeDefined();expect(s.partyTactics![p.id].kind).toBe('rally');for(let i=0;i<25;i++)step(s,.05);expect(p.attackPending).toBeUndefined();expect(p.evasion!.action).toBeUndefined();expect(s.partyTactics![p.id]?.kind).toBe('rally');expect(p.destination).toBeDefined();});
test('busy waiting does not burn blocked rally budget; true obstruction terminates with feedback',()=>{const {s,h,p}=fixture();issue(s,h,p,'rally');p.stagger=20;for(let i=0;i<200;i++)step(s,.05);expect(s.partyTactics![p.id].budget).toBe(0);p.stagger=0;s.tiles.forEach(t=>{if(Math.hypot(t.x-h.pos.x,t.y-h.pos.y)<3)t.obstacle=true;});for(let i=0;i<170;i++)step(s,.05);expect(s.partyTactics![p.id]).toBeUndefined();expect(s.log.some(l=>l.includes('集合超时'))).toBe(true);});
test('rally arrival cannot succeed through a wall and the controlled partner can command Hunter',()=>{const {s,h,p}=fixture();command(s,{type:'controlBody',id:p.id});p.pos=p.drawPos={x:13,y:10};h.pos=h.drawPos={x:11.5,y:10};s.tiles=s.tiles.filter(t=>t.x>=10&&t.x<=14&&t.y>=8&&t.y<=12);s.tiles.forEach(t=>{if(t.x===12)t.obstacle=true;});expect(issue(s,p,h,'rally').ok).toBe(true);step(s,.05);expect(s.partyTactics![h.id]?.kind).toBe('rally');expect(s.controlledBodyId).toBe(p.id);});
test('focus candidates use committed manual Basic, not buffers, and never guess a nearest target',()=>{const {s,h,p,e}=combat();expect(focusCandidate(s)).toBeUndefined();h.attackTimer=0;h.pos={x:13,y:10};command(s,{type:'basic',id:h.id,aim:e.pos,requestId:1});expect(focusCandidate(s)).toBe(e.id);h.basicChain!.buffer={id:2,aim:{x:0,y:0},targetId:'buffer-target',source:'player-input',expiresAt:2};expect(focusCandidate(s)).toBe(e.id);s.time=2.1;expect(focusCandidate(s)).toBeUndefined();expect(focusCandidate(s,e.id)).toBe(e.id);});
test.each(['clone','enemy','reserve','downed','shadow'] as const)('invalid %s recipient rejects without changing orders',kind=>{const {s,h,p}=fixture();issueMoveOrder(s,p,{x:10,y:14},'direct');const before=s.explorationControl!.moveOrders![p.id];if(kind==='clone')p.cloneOf=h.id;else if(kind==='enemy')p.team='enemy';else if(kind==='shadow')p.shadowResident=true;else p.life=kind;expect(issue(s,h,p,'rally').ok).toBe(false);expect(s.explorationControl!.moveOrders![p.id]).toBe(before);});
test('high-level task rejects offensive tactics but free/cautious do not interrupt it',()=>{const {s,h,p}=fixture();p.partyTask={kind:'recall',elapsed:0,repath:0};const task=p.partyTask;expect(issue(s,h,p,'rally').ok).toBe(false);expect(issue(s,h,p,'cautious').ok).toBe(true);expect(p.partyTask).toBe(task);});
test('focus timeout cleans its ordinary AI route and never restores an old target',()=>{const {s,h,p,e}=combat();issue(s,h,p,'focus',1,e.id);advanceCompanionCombat(s);expect(p.path.length).toBeGreaterThan(0);e.life='dead';maintainPartyTactics(s);expect(p.path).toEqual([]);expect(p.companionCombat?.targetId).toBeUndefined();});
test('cautious pending status becomes active and cleanup also works outside exploration',()=>{const {s,h,p}=fixture();p.stagger=1;issue(s,h,p,'cautious');p.stagger=0;maintainPartyTactics(s);expect(s.partyTactics![p.id].execution).toBe('active');s.exploration=undefined;maintainPartyTactics(s);expect(s.partyTactics![p.id]).toBeUndefined();});
test('dead focus clears during a committed action without cancelling the action',()=>{const {s,h,p,e}=combat();issue(s,h,p,'focus',1,e.id);p.attackPending={targetId:e.id,remaining:.5,facing:'east',basic:true};const action=p.attackPending;e.life='dead';maintainPartyTactics(s);expect(s.partyTactics![p.id]).toBeUndefined();expect(p.attackPending).toBe(action);});
test('tactic ending during crossing preserves just the current atomic edge',()=>{const {s,h,p}=fixture();issue(s,h,p,'rally');p.path=[{x:11,y:10},{x:12,y:10},{x:13,y:10}];s.partyTactics![p.id].ownedPath=p.path;p.crossing={from:{...p.pos},to:{x:11,y:10},elapsed:.1,switched:false};const crossing=p.crossing;finishPartyTactic(s,p,'cancel');expect(p.crossing).toBe(crossing);expect(p.path).toEqual([{x:11,y:10}]);});
test('navigation budget is bounded while default navigation still finds the detour',async()=>{const {navigate}=await import('../src/core/navigation');const {s,p}=fixture();s.tiles=s.tiles.filter(t=>t.x>=8&&t.x<=18&&t.y>=7&&t.y<=15);s.tiles.forEach(t=>{t.obstacle=t.x===12&&t.y<14;});const budget={remaining:1};expect(navigate(s,p.pos,{x:16,y:10},false,true,.25,budget)).toEqual([]);expect(budget.remaining).toBe(0);expect(navigate(s,p.pos,{x:16,y:10},false,true,.25).length).toBeGreaterThan(0);});

test('an ancient accepted request never replays after hundreds of newer requests',()=>{const {s,h,p}=fixture();for(let i=1;i<270;i++)expect(issue(s,h,p,'free',i).ok).toBe(true);issueMoveOrder(s,p,{x:10,y:15},'direct');const order=s.explorationControl!.moveOrders![p.id];expect(issue(s,h,p,'rally',1).ok).toBe(false);expect(s.explorationControl!.moveOrders![p.id]).toBe(order);});

test('future timestamps from an old run cannot become a fresh focus candidate',()=>{const {s,h,e}=combat();h.lastManualBasic={targetId:e.id,at:10};s.time=0;expect(focusCandidate(s)).toBeUndefined();});

test('blocked rally discards only its obsolete ordinary route and preserves newer routes',async()=>{const {advanceTacticRoute}=await import('../src/core/party-tactics');for(const replace of [false,true]){const {s,h,p}=fixture();issue(s,h,p,'rally');advanceTacticRoute(s,p);expect(p.path.length).toBeGreaterThan(0);const newer=[{x:10,y:12}];if(replace)p.path=newer;s.tiles.forEach(t=>{if(t.x>10)t.obstacle=true;});s.time=.3;advanceTacticRoute(s,p);expect(s.partyTactics![p.id].execution).toBe('blocked');expect(p.path).toEqual(replace?newer:[]);}});
