import {test,expect} from '@playwright/test';
import {walk,snapshot} from './ui01c-browser-helpers';
import {mkdirSync,writeFileSync} from 'node:fs';
const dir='../work/UI-01C-20261010/browser-world';mkdirSync(dir,{recursive:true});test.setTimeout(480000);
for(const [width,height]of [[1920,1080]])test(`ordinary complete native encounters and persistent world ${width}`,async({page})=>{
 const errors:string[]=[],contextErrors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(/Too many active WebGL|CONTEXT_LOST|context lost/i.test(m.text()))contextErrors.push(m.text());});
 await page.setViewportSize({width,height});await page.goto('/');await page.locator('[data-companion=ranger]').click();await page.locator('[data-action=carry]').click();await expect.poll(()=>page.evaluate(()=>['hunter','ranger'].every(id=>(window as any).prototype.scene.unitVisuals.get(id)?.reference?.ready)),{timeout:30000}).toBe(true);
 const initial=await page.evaluate(()=>{const p=(window as any).prototype,s=p.state;return {groups:s.exploration.definition.encounters,enemyCount:s.units.filter((u:any)=>u.team==='enemy').length,families:s.units.filter((u:any)=>u.team==='enemy').map((u:any)=>u.enemyV2?.profile.visual),old:s.units.filter((u:any)=>u.enemyCombat||u.enemySense||u.attackIntent).length,loaded:p.scene.unitVisuals.size};});
 expect(initial.enemyCount).toBeGreaterThan(40);expect(initial.enemyCount).toBeLessThanOrEqual(48);expect(initial.families.every((f:string)=>f==='zombie'||f==='ranged')).toBe(true);expect(initial.old).toBe(0);expect(initial.loaded).toBeLessThan(15);expect(await page.locator('[data-v2]').count()).toBe(0);
 await page.locator('#exploration-objective summary').click();await page.locator('[data-exploration-point=campfire-1]').click();await expect(page.locator('[data-exploration-point=campfire-1]')).toBeDisabled();await page.keyboard.press('AltLeft');const facts:any[]=[];
 for(const tier of ['small','normal','strong']){const g=initial.groups.filter((g:any)=>g.tier===tier).sort((a:any,b:any)=>Math.hypot(a.center.x-6,a.center.y-8)-Math.hypot(b.center.x-6,b.center.y-8))[0];await walk(page,g.center,`${tier}-${width}`);await page.screenshot({path:dir+`/${tier}-${width}.png`});facts.push(await page.evaluate(()=>{const p=(window as any).prototype,s=p.state;return {time:s.time,kills:s.kills,memory:p.scene.renderer.info.memory,loaded:p.scene.unitVisuals.size,views:[...p.scene.unitVisuals.values()].map((a:any)=>({id:a.unit.id,visible:a.group.visible,ready:a.reference?.ready,failed:a.loadFailed,pose:a.reference?.pose})),events:s.units.filter((u:any)=>u.enemyV2).map((u:any)=>({id:u.id,life:u.life,profile:u.enemyV2.profile.id,brain:u.enemyV2.brain,events:u.enemyV2.trace.slice(-20)})),entities:s.enemyRuntime?.entities};}));}
 // Exercise both players and all main controls through real inputs.
 await page.keyboard.press('z');const shot=await page.evaluate(()=>{const p=(window as any).prototype,s=p.state,a=s.units.find((u:any)=>u.id===s.controlledBodyId);return p.project({x:a.pos.x+3,y:a.pos.y});});await page.mouse.move(shot.x,shot.y);await page.mouse.down({button:'right'});await page.waitForTimeout(1600);await page.mouse.up({button:'right'});await page.keyboard.press('Shift');await page.keyboard.press('e');await page.keyboard.press('z');await page.mouse.down({button:'right'});await page.waitForTimeout(200);await page.mouse.up({button:'right'});await page.keyboard.press('f');await page.keyboard.press('Escape');await page.keyboard.down('g');await page.keyboard.press('Escape');await page.keyboard.up('g');
 const end=await page.evaluate(()=>(window as any).prototype.state.exploration.definition.exit);await walk(page,end);await page.waitForTimeout(1200);if(!await page.locator('#exploration-objective details').evaluate((e:HTMLDetailsElement)=>e.open))await page.locator('#exploration-objective summary').click();await expect(page.locator('[data-action=exit-exploration]')).toBeEnabled({timeout:20000});await page.keyboard.press('Space');const before=await snapshot(page);expect(before.kills).toBeGreaterThan(0);
 const enemyBefore=await page.evaluate(()=>(window as any).prototype.state.units.filter((u:any)=>u.enemyV2).map((u:any)=>({id:u.id,hp:u.hp,posture:u.posture,delay:u.postureDelay,life:u.life,ready:u.enemyV2.readyAt,home:u.enemyV2.brain?.home})));
 await page.locator('[data-action=exit-exploration]').click();const outside=await snapshot(page);await expect(page.locator('.exploration-ended')).toBeVisible();await page.screenshot({path:dir+`/outside-${width}.png`});expect(outside.units).toEqual(before.units.map(u=>({...u,hunter:u.hunter&&{...u.hunter,held:false},al:u.al&&{...u.al,held:false,shotHeld:false}})));expect(outside.settled).toBeNull();await page.waitForTimeout(250);expect((await snapshot(page)).time).toBe(outside.time);await page.locator('[data-action=continue-world]').click();await page.keyboard.press('Space');const back=await snapshot(page);
 expect(back.world).toBe(before.world);expect(back.dead).toEqual(before.dead);expect(back.rewards).toEqual(before.rewards);expect(back.resources).toEqual(before.resources);
 const enemyAfter=await page.evaluate(()=>(window as any).prototype.state.units.filter((u:any)=>u.enemyV2).map((u:any)=>({id:u.id,hp:u.hp,posture:u.posture,delay:u.postureDelay,life:u.life,ready:u.enemyV2.readyAt,home:u.enemyV2.brain?.home})));expect(enemyAfter).toEqual(enemyBefore);await page.screenshot({path:dir+`/continued-${width}.png`});
 expect(back.used).toEqual(before.used);expect(back.units.map(u=>u.weapons)).toEqual(before.units.map(u=>u.weapons));await expect(page.locator('[data-exploration-point=campfire-1]')).toBeDisabled();await page.locator('[data-action=restart-world]').click();await page.locator('[data-action=cancel-economic]').click();expect((await snapshot(page)).world).toBe(before.world);await page.locator('[data-action=restart-world]').click();await page.locator('[data-action=confirm-economic]').click();await page.locator('[data-companion=ranger]').click();await page.locator('[data-action=carry]').click();const fresh=await snapshot(page);expect(fresh.world).not.toBe(before.world);expect(fresh.used).not.toContain('campfire-1');writeFileSync(dir+`/lifecycle-${width}.json`,JSON.stringify({method:"real mouse and keyboard; no state, HP, position or command injection",initial,facts,before,outside,back,fresh,enemyBefore,enemyAfter,errors,contextErrors},null,2));expect(errors).toEqual([]);expect(contextErrors).toEqual([]);
});
