import {test,expect} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
import {route} from './ui01c-browser-helpers';
test.setTimeout(60000);
test('internal PPT placement and naturally damaged authoritative bars',async({page})=>{
 await page.setViewportSize({width:1920,height:1080});await page.goto('/?enemies=v2&mode=four');
 await expect.poll(()=>page.evaluate(()=>['hunter','ranger'].every(id=>(window as any).prototype?.scene.unitVisuals.get(id)?.reference?.ready)),{timeout:30000}).toBe(true);
 await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').hp),{timeout:25000}).toBeLessThan(360);await page.keyboard.press('Space');
 const data=await page.evaluate(()=>{
  const rect=(e:Element)=>{const b=e.getBoundingClientRect();return{x:b.x,y:b.y,w:b.width,h:b.height};};const s=(window as any).prototype.state;
  return ['hunter','ranger'].map(id=>{const c=document.querySelector(`[data-body="${id}"]`)!;const u=s.units.find((u:any)=>u.id===id);return{id,cluster:rect(c),bar:rect(c.querySelector('.duo-hp')!),secondary:rect(c.querySelector('.duo-secondary')!),weapons:[...c.querySelectorAll('[data-hand]')].map(rect),passives:[...c.querySelectorAll('[data-passive-level]')].map(rect),item:rect(c.querySelector('[data-reserve-kind]')!),face:id==='ranger'?rect(c.querySelector('.duo-face')!):null,hp:u.hp,maxHp:u.maxHp,gray:u.grayHp,posture:u.posture,maxPosture:u.maxPosture,clips:['.duo-health','.duo-gray','.duo-posture i'].map(sel=>(c.querySelector(sel) as HTMLElement).style.clipPath),text:c.querySelector('.duo-values')!.textContent};});
 });
 for(const d of data){
  expect(d.bar.w).toBeCloseTo(d.cluster.w,1);expect(d.secondary.y).toBeGreaterThanOrEqual(d.bar.y+d.bar.h);expect(d.weapons[0].x).toBe(d.weapons[1].x);expect(d.weapons[1].y).toBeGreaterThanOrEqual(d.weapons[0].y+d.weapons[0].h);expect(d.item.x).toBeGreaterThanOrEqual(d.weapons[0].x+d.weapons[0].w);expect(d.passives).toHaveLength(3);expect(new Set(d.passives.map(p=>p.y)).size).toBe(1);expect(d.passives[0].x).toBeLessThan(d.passives[1].x);expect(d.passives[1].x).toBeLessThan(d.passives[2].x);
  for(const b of [...d.weapons,...d.passives,d.item]){expect(b.x+b.w).toBeLessThanOrEqual(d.cluster.x+d.cluster.w+1);expect(b.y+b.h).toBeLessThanOrEqual(d.cluster.y+d.cluster.h+1);}
  if(d.face){expect(d.face.x+d.face.w).toBeLessThanOrEqual(d.weapons[0].x);expect(d.passives[0].y+d.passives[0].h).toBeLessThanOrEqual(d.weapons[0].y);}
  const ratios=[d.hp/d.maxHp,Math.min(1,(d.hp+d.gray)/d.maxHp),d.posture/d.maxPosture];ratios.forEach((f,i)=>expect(parseFloat(d.clips[i].split(' ')[1])).toBeCloseTo(100-(2.15+Math.max(0,Math.min(1,f))*95.7),3));expect(d.text).toContain(`生命 ${Math.ceil(d.hp)}/${d.maxHp}`);expect(d.text).toContain(`虚血 ${Math.ceil(d.gray)}`);expect(d.text).toContain(`架势 ${Math.ceil(d.posture)}/${d.maxPosture}`);
 }
 const out='../work/UI-01C-20261010/browser';mkdirSync(out,{recursive:true});writeFileSync(out+'/internal-and-damage.json',JSON.stringify(data,null,2));await page.screenshot({path:out+'/real-damage.png'});
});
test('ordinary exploration G focus uses a visible engaged target',async({page})=>{
 test.setTimeout(180000);await page.goto('/');await page.locator('[data-companion=ranger]').click();await page.locator('[data-action=carry]').click();await expect.poll(()=>page.evaluate(()=>['hunter','ranger'].every(id=>(window as any).prototype?.scene.unitVisuals.get(id)?.reference?.ready)),{timeout:30000}).toBe(true);await page.keyboard.press('AltLeft');
 const to=await page.evaluate(()=>(window as any).prototype.state.exploration.definition.encounters.filter((g:any)=>g.tier==='small').sort((a:any,b:any)=>Math.hypot(a.center.x-6,a.center.y-8)-Math.hypot(b.center.x-6,b.center.y-8))[0].center);const way=await route(page,to);let cursor=0;const held=new Set<string>();let target:any;
 const keys=async(next:string[])=>{for(const k of [...held])if(!next.includes(k)){await page.keyboard.up(k);held.delete(k);}for(const k of next)if(!held.has(k)){await page.keyboard.down(k);held.add(k);}};
 for(let n=0;n<1800;n++){
  const d=await page.evaluate(async()=>{const p=(window as any).prototype,s=p.state,h=s.units.find((u:any)=>u.id==='hunter'),{focusTargetLegal}=await import('/src/core/party-tactics.ts' as string);const e=s.units.find((u:any)=>focusTargetLegal(s,u.id)&&p.scene.unitVisuals.get(u.id)?.reference?.ready&&(()=>{const q=p.project(u.drawPos??u.pos);return q.x>40&&q.x<innerWidth-300&&q.y>220&&q.y<innerHeight-230;})());return{pos:h.pos,life:h.life,target:e&&{id:e.id,point:p.project(e.drawPos??e.pos)}};});expect(d.life).toBe('active');if(d.target){target=d.target;break;}
  while(cursor<way.length&&Math.hypot(way[cursor].x-d.pos.x,way[cursor].y-d.pos.y)<.3)cursor++;expect(cursor,'route has not ended before combat target').toBeLessThan(way.length);const goal=way[cursor],dx=goal.x-d.pos.x,dy=goal.y-d.pos.y;await keys([...(Math.abs(dx)>.13?[dx>0?'d':'a']:[]),...(Math.abs(dy)>.13?[dy>0?'s':'w']:[])]);await page.waitForTimeout(Math.min(110,Math.max(16,Math.hypot(dx,dy)*1000/24)));
 }
 await keys([]);expect(target).toBeTruthy();const pick=await page.evaluate((id:string)=>{const p=(window as any).prototype,e=p.state.units.find((u:any)=>u.id===id),q=p.project(e.drawPos??e.pos);const hits:{x:number;y:number}[]=[];for(let dy=-90;dy<=35;dy+=5)for(let dx=-45;dx<=45;dx+=5){const x=q.x+dx,y=q.y+dy;if(document.elementFromPoint(x,y)?.closest('#scene')&&p.scene.pick(x,y).unitId===id)hits.push({x,y});}if(hits.length){const c={x:hits.reduce((a,b)=>a+b.x,0)/hits.length,y:hits.reduce((a,b)=>a+b.y,0)/hits.length};return hits.sort((a,b)=>Math.hypot(a.x-c.x,a.y-c.y)-Math.hypot(b.x-c.x,b.y-c.y))[0];}throw Error('ready target has no actual scene hover '+id);},target.id);await page.mouse.move(pick.x,pick.y);await page.keyboard.down('g');await expect(page.locator('#tactic-wheel')).toBeVisible();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.wheel.targetId)).toBe(target.id);const b=(await page.locator('#tactic-wheel').boundingBox())!;await page.mouse.move(b.x+b.width/2+100,b.y+b.height/2);await page.keyboard.up('g');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.partyTactics?.ranger?.kind)).toBe('focus');
 const out='../work/UI-01C-20261010/browser';mkdirSync(out,{recursive:true});writeFileSync(out+'/ordinary-focus.json',JSON.stringify({method:'real WASD and G, read-only map route/target; no injection',target,tactic:await page.evaluate(()=>(window as any).prototype.state.partyTactics?.ranger)},null,2));await page.screenshot({path:out+'/ordinary-focus.png'});
});
