// UI-01C natural regression; original evidence paths kept intact.
// Existing natural regression adapted only to retired entry/new HUD selectors.
import {test,expect} from '@playwright/test';
test.setTimeout(60000);
test('AR06 real keys drive Al yellow visual, held basic, gun and independent HUD',async({page})=>{await page.goto('/');await page.locator('[data-companion="ranger"]').click();await page.locator('[data-action="carry"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').ready)).toBe(0);await page.keyboard.press('z');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.unitVisuals.get('ranger')?.reference?.ready)).toBe(true);const box=(await page.locator('#scene').boundingBox())!;await page.mouse.move(box.x+box.width*.55,box.y+box.height*.5);await page.mouse.down();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').alCombat.trace.filter((e:any)=>e.kind==='accepted'&&e.stage!==undefined).length),{timeout:15000}).toBeGreaterThan(3);await page.mouse.up();expect(await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').alCombat.trace.filter((e:any)=>e.kind==='accepted'&&e.stage!==undefined).length)).toBeGreaterThan(2);await page.waitForTimeout(1300);await page.mouse.down({button:'right'});await page.waitForTimeout(1400);await page.mouse.up({button:'right'});expect(await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').alCombat.trace.filter((e:any)=>e.kind==='ammo-payment').length)).toBeGreaterThan(0);await expect(page.locator('#action-strip')).toContainText('四发射击');await page.keyboard.press('Shift');await page.keyboard.press('z');expect(await page.evaluate(()=>(window as any).prototype.state.controlledBodyId)).toBe('hunter');await expect(page.locator('#action-strip')).toContainText('方向格挡');});

import {writeFileSync,mkdirSync} from 'node:fs';
test.use({video:'on'});
test('AR06 evidence four native RMB payments reload rocket and two reference actors',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.locator('[data-companion="ranger"]').click();await page.locator('[data-action="carry"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.unitVisuals.get('ranger')?.reference?.ready)).toBe(true);await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').ready)).toBe(0);await page.keyboard.press('z');const box=(await page.locator('#scene').boundingBox())!;await page.mouse.move(box.x+box.width*.58,box.y+box.height*.5);await page.mouse.down({button:'right'});await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').alCombat?.trace.filter((e:any)=>e.kind==='ammo-payment').length??0),{timeout:15000}).toBe(4);await page.mouse.up({button:'right'});await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').alCombat?.ammo),{timeout:15000}).toBe(4);await page.keyboard.press('e');await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='ranger').alCombat.trace.filter((e:any)=>e.kind==='land').length),{timeout:10000}).toBe(1);mkdirSync('../work/UI-01C-20261010/browser-combat',{recursive:true});await page.screenshot({path:'../work/UI-01C-20261010/browser-combat/two-actors.png'});const data=await page.evaluate(()=>{const p=(window as any).prototype,s=p.state;return {trace:s.units.find((u:any)=>u.id==='ranger').alCombat.trace,ready:['hunter','ranger'].map(id=>({id,ready:p.scene.unitVisuals.get(id)?.reference?.ready})),hud:document.querySelector('#action-strip')?.textContent};});writeFileSync('../work/UI-01C-20261010/browser-combat/browser-evidence.json',JSON.stringify(data,null,2));expect(data.ready.every((x:any)=>x.ready)).toBe(true);await page.keyboard.press('z');await expect(page.locator('#action-strip')).toContainText('方向格挡');expect(errors).toEqual([]);
});
