// UI-01C natural regression; original evidence paths kept intact.
import {test,expect} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
const out='../work/UI-01C-20261010/browser-groups';mkdirSync(out,{recursive:true});test.setTimeout(60000);
for(const [mode,count] of [['four',4]] as const)test(`named native enemy group ${mode}`,async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`/?enemies=v2&mode=${mode}`);
 await expect.poll(()=>page.evaluate(()=>{const p=(window as any).prototype;return !!p&&p.state.units.filter((u:any)=>u.enemyV2).every((u:any)=>p.scene.unitVisuals.get(u.id)?.reference?.ready);}),{timeout:30000}).toBe(true);
 expect(await page.evaluate(()=>(window as any).prototype.state.units.filter((u:any)=>u.enemyV2).length)).toBe(count);
 await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.filter((u:any)=>u.enemyV2).some((u:any)=>u.enemyV2.trace.some((r:any)=>r.kind==='event'))),{timeout:20000}).toBe(true);
 if(count>1)await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.filter((u:any)=>u.enemyVisualProfileId==='ranged').some((u:any)=>u.enemyV2.trace.filter((r:any)=>r.kind==='spawn').length>=3)),{timeout:20000}).toBe(true);
 await page.keyboard.press('z');const q=await page.evaluate(()=>{const p=(window as any).prototype,e=p.state.units.find((u:any)=>u.enemyV2&&u.life==='active');return p.project(e.drawPos??e.pos);});await page.mouse.move(q.x,q.y-15);await page.mouse.down({button:'right'});await page.waitForTimeout(1000);await page.mouse.up({button:'right'});await page.keyboard.press('Shift');await page.keyboard.press('e');await page.waitForTimeout(500);await page.keyboard.press('z');await page.mouse.down({button:'right'});await page.waitForTimeout(200);await page.mouse.up({button:'right'});
 await page.keyboard.press('Space');await expect.poll(()=>page.evaluate(async()=>{const {visible}=await import('/src/core/engine.ts' as string),p=(window as any).prototype,s=p.state;return s.units.filter((u:any)=>u.enemyV2&&visible(s,u)).every((u:any)=>p.scene.unitVisuals.get(u.id)?.reference?.ready);}),{timeout:10000}).toBe(true);const result=await page.evaluate(async()=>{const {visible}=await import('/src/core/engine.ts' as string),p=(window as any).prototype,s=p.state;return {time:s.time,generation:s.combatIdentity.generation,units:s.units.map((u:any)=>({id:u.id,life:u.life,hp:u.hp,enemy:!!u.enemyV2,visible:visible(s,u),profile:u.enemyV2?.profile.id,trace:u.enemyV2?.trace,old:!!(u.enemyCombat||u.attackIntent),ready:p.scene.unitVisuals.get(u.id)?.reference?.ready})),entityTrace:s.enemyRuntime?.trace,errors:s.errors};});
 writeFileSync(out+`/${mode}-observed.json`,JSON.stringify(result,null,2));expect(result.units.filter(u=>u.enemy).every(u=>!u.old)).toBe(true);expect(result.units.filter(u=>u.enemy&&u.visible).every(u=>u.ready)).toBe(true);expect(result.units.filter(u=>u.enemy).some(u=>u.trace.some((r:any)=>r.kind==='accepted'))).toBe(true);
 await page.screenshot({path:out+`/${mode}.png`});writeFileSync(out+`/${mode}.json`,JSON.stringify({method:'named development entry, real Z/RMB/Shift/E; read-only observations',count,result,errors},null,2));expect(errors).toEqual([]);
});
