import {test,expect} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
const out='../work/UI-01C-20261010/browser';mkdirSync(out,{recursive:true});
test.setTimeout(90000);
const reference={hero:[34,41,529,163],companion:[3,860,377,220],world:[1648,17,259,117],hotbar:[550,965,866,110],skills:[1665,760,254,273],vitality:[1568,1050,350,30]};
async function enter(page:any,width:number,height:number){await page.setViewportSize({width,height});await page.goto('/');await page.locator('[data-companion=ranger]').click();await page.locator('[data-action=carry]').click();await expect.poll(()=>page.evaluate(()=>['hunter','ranger'].every(id=>(window as any).prototype?.scene.unitVisuals.get(id)?.reference?.ready)),{timeout:30000}).toBe(true);await page.waitForTimeout(800);await page.keyboard.press('Space');}
for(const [width,height]of [[1920,1080],[1440,900],[1280,720]])test(`before capture ${width}`,async({page})=>{
 test.skip(!process.env.UI01C_CAPTURE_BASELINE,'Manual pre-change capture only; published before evidence is immutable.');
 await enter(page,width,height);const boxes=await page.evaluate(()=>['[data-body=hunter]','[data-body=ranger]','#world-status','#quick-reserved','#action-strip'].map(selector=>{const b=document.querySelector(selector)!.getBoundingClientRect();return {selector,x:b.x,y:b.y,w:b.width,h:b.height};}));
 await page.screenshot({path:out+`/before-${width}.png`});writeFileSync(out+`/before-${width}.json`,JSON.stringify(boxes,null,2));
});
test('user portrait remains identity-specific and HUD slots never attack through',async({page})=>{
 await enter(page,1920,1080);await page.keyboard.press('Space');
 const trace=()=>page.evaluate(()=>{const s=(window as any).prototype.state;return s.units.find((u:any)=>u.id==='hunter').hunterCombat.trace.filter((e:any)=>e.kind==='accepted').length;});
 const before=await trace();for(const selector of ['[data-body=hunter] [data-passive-level="1"]','[data-skill-key=Q]','[data-skill-key=E]','[data-skill-key=R]','#quick-reserved [data-slot="1"]']){const b=(await page.locator(selector).boundingBox())!;await page.mouse.click(b.x+b.width/2,b.y+b.height/2);}await page.waitForTimeout(150);expect(await trace()).toBe(before);
 await page.goto('/');await page.locator('[data-companion=ines]').click();await page.locator('[data-action=carry]').click();const img=page.locator('#companion-cluster .duo-face img');await expect(img).not.toHaveAttribute('src','/assets/ui/portraits/al-user.png');await expect.poll(()=>img.evaluate((im:HTMLImageElement)=>im.complete&&im.naturalWidth>0)).toBe(true);await expect(page.locator('#companion-cluster')).toHaveAttribute('data-body','ines');
});
test('paused skill slots remain the same DOM nodes across HUD frames',async({page})=>{
 await enter(page,1440,900);const q=await page.locator('[data-skill-key=Q]').elementHandle();expect(q).not.toBeNull();await page.waitForTimeout(200);expect(await q!.evaluate(e=>e.isConnected)).toBe(true);
});
test('xx preview and isolated main character remain playable',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/xx-preview.html');await expect.poll(()=>page.evaluate(()=>!!(window as any).xxPreview?.visual.ready),{timeout:30000}).toBe(true);await page.screenshot({path:out+'/xx-preview.png'});
 await page.goto('/?xx=1');await page.locator('[data-companion=ranger]').click();await page.locator('[data-action=carry]').click();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.scene.unitVisuals.get('hunter')?.reference?.ready),{timeout:30000}).toBe(true);await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').ready)).toBe(0);
 const b=(await page.locator('#scene').boundingBox())!;await page.mouse.move(b.x+b.width*.55,b.y+b.height*.5);await page.mouse.down();await expect.poll(()=>page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').xxCombat.trace.filter((e:any)=>e.name==='accepted').length),{timeout:15000}).toBeGreaterThan(3);await page.mouse.up();await page.keyboard.press('z');await expect(page.locator('#action-strip')).toHaveAttribute('data-actor','ranger');await page.keyboard.press('z');await expect(page.locator('#hero-cluster header b')).toHaveText(await page.evaluate(()=>(window as any).prototype.state.units.find((u:any)=>u.id==='hunter').name));await page.screenshot({path:out+'/xx-main.png'});expect(errors).toEqual([]);
});
for(const [width,height]of [[1920,1080],[1440,900],[1280,720]])test(`PPT clusters, actual Al portrait and inert slots ${width}`,async({page})=>{
 await enter(page,width,height);
 const hero=page.locator('[data-body=hunter]'),al=page.locator('[data-body=ranger]');
 await expect.soft(hero.locator('.duo-face')).toHaveCount(0);
 const image=al.locator('.duo-face img');await expect.soft(image).toHaveAttribute('src','/assets/ui/portraits/al-user.png');
 await expect.soft(page.locator('#action-strip [data-skill-key]')).toHaveCount(3);
 if(await page.locator('[data-ui-cluster=hero]').count()===0){expect.soft(false,'six PPT clusters absent').toBe(true);return;}
 const layout=await page.evaluate(()=>Object.fromEntries([...document.querySelectorAll('[data-ui-cluster]')].map(e=>{const b=e.getBoundingClientRect();return [(e as HTMLElement).dataset.uiCluster,{x:b.x,y:b.y,w:b.width,h:b.height}];})));
 if(width===1920){for(const [id,[x,y,w,h]]of Object.entries(reference)){const b=layout[id];expect(Math.abs(b.x-x),id+' x').toBeLessThanOrEqual(1920*.012);expect(Math.abs(b.y-y),id+' y').toBeLessThanOrEqual(1080*.012);expect(Math.abs(b.w-w)/w,id+' width').toBeLessThanOrEqual(.08);expect(Math.abs(b.h-h)/h,id+' height').toBeLessThanOrEqual(.08);const area=Math.max(0,Math.min(x+w,b.x+b.w)-Math.max(x,b.x))*Math.max(0,Math.min(y+h,b.y+b.h)-Math.max(y,b.y));expect(area/(w*h+b.w*b.h-area),id+' IoU').toBeGreaterThanOrEqual(.8);}}
 const overlap=(a:any,b:any)=>Math.max(0,Math.min(a.x+a.w,b.x+b.w)-Math.max(a.x,b.x))*Math.max(0,Math.min(a.y+a.h,b.y+b.h)-Math.max(a.y,b.y));
 for(const b of Object.values(layout) as any[]){expect(b.x).toBeGreaterThanOrEqual(-1);expect(b.y).toBeGreaterThanOrEqual(-1);expect(b.x+b.w).toBeLessThanOrEqual(width+1);expect(b.y+b.h).toBeLessThanOrEqual(height+1);}
 for(const a of ['companion','hotbar','skills','vitality'])for(const b of ['companion','hotbar','skills','vitality'])if(a!==b)expect(overlap(layout[a],layout[b]),a+' / '+b).toBe(0);
 const details=await page.evaluate(()=>{const box=(selector:string)=>{const b=document.querySelector(selector)!.getBoundingClientRect();return {x:b.x,y:b.y,w:b.width,h:b.height};};const im=document.querySelector('[data-body=ranger] .duo-face img') as HTMLImageElement;return {q:box('[data-skill-key=Q]'),e:box('[data-skill-key=E]'),r:box('[data-skill-key=R]'),face:box('[data-body=ranger] .duo-face'),alBar:box('[data-body=ranger] .duo-hp'),hotSlots:[...document.querySelectorAll('#quick-reserved [data-slot]')].map(e=>{const b=e.getBoundingClientRect();return{x:b.x,y:b.y,w:b.width,h:b.height};}),portrait:{src:im.currentSrc,width:im.naturalWidth,height:im.naturalHeight,complete:im.complete},center:!!document.elementFromPoint(innerWidth/2,innerHeight/2)?.closest('#scene')};});
 expect(details.q.x).toBeGreaterThan(details.e.x);expect(details.r.x).toBeGreaterThan(details.e.x);expect(details.q.y).toBeLessThan(details.e.y);expect(details.e.y).toBeLessThan(details.r.y);
 expect(details.face.w).toBeGreaterThan(layout.companion.w*.4);expect(details.face.h).toBeCloseTo(details.face.w,1);expect(details.face.y).toBeGreaterThan(details.alBar.y);
 expect(details.portrait.width).toBeGreaterThan(0);expect(details.portrait.complete).toBe(true);expect(details.center).toBe(true);expect(details.hotSlots.length).toBe(10);expect(new Set(details.hotSlots.map(b=>Math.round(b.y))).size).toBe(1);
 const state=()=>page.evaluate(()=>{const s=(window as any).prototype.state;return {time:s.time,controlled:s.controlledBodyId,economy:s.economy.carried,events:s.combatEvents.length,units:s.units.filter((u:any)=>u.team==='ally').map((u:any)=>({id:u.id,hp:u.hp,gray:u.grayHp,posture:u.posture,h:u.hunterCombat,a:u.alCombat}))};});
 const before=await state();for(const key of ['q','r','v','y','Tab','1','2','3','4','5','6','7','8','9','0'])await page.keyboard.press(key);for(const selector of ['[data-body=hunter] [data-passive-level="1"]','[data-skill-key=Q]']){const b=(await page.locator(selector).boundingBox())!;await page.mouse.click(b.x+b.width/2,b.y+b.height/2);}expect(await state()).toEqual(before);
 await page.keyboard.press('Space');await page.keyboard.press('z');await expect(al).toHaveClass(/controlled/);await expect(page.locator('#action-strip')).toHaveAttribute('data-actor','ranger');await expect(page.locator('[data-skill-key=E]')).toContainText('火箭');await expect(image).toHaveAttribute('src','/assets/ui/portraits/al-user.png');await page.keyboard.press('z');await expect(hero).toHaveClass(/controlled/);await page.keyboard.press('Space');
 const bars=await page.evaluate(()=>{const s=(window as any).prototype.state;return s.units.filter((u:any)=>['hunter','ranger'].includes(u.id)).map((u:any)=>{const card=document.querySelector(`[data-body="${u.id}"]`)!;return{id:u.id,hp:u.hp,max:u.maxHp,clip:(card.querySelector('.duo-health') as HTMLElement).style.clipPath,text:card.querySelector('.duo-values')!.textContent};});});for(const b of bars){expect(parseFloat(b.clip.split(' ')[1])).toBeCloseTo(100-(2.15+b.hp/b.max*95.7),3);expect(b.text).toContain(`生命 ${Math.ceil(b.hp)}/${b.max}`);}
 await page.screenshot({path:out+`/game-${width}.png`});writeFileSync(out+`/layout-${width}.json`,JSON.stringify({layout,details,bars},null,2));
});
